### ISSUE TITLE
Empty Open Page

### ISSUE THREAD

**Issue by phanicherukuri** [alex-shpak/hugo-book#1]
Hi, after cloning the theme and running in local, I'm getting an empty open page.

**Comment by alex-shpak** [comment]
Hi!

Theme is designed to not interfere with other templates in website so it renders only `docs` section.
You can set main page to render as `docs` like [this](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/_index.md)
By specifying `type: docs` in front matter
```
---
title: Root Page
type: docs
---
```

**Comment by alex-shpak** [comment]
Please re-open if you still have this problem.
