### ISSUE TITLE
h4 headers look like body

### ISSUE THREAD

**Issue by JensRantil** [alex-shpak/hugo-book#100]
See screenshot taken in Google Chrome Version 78.0.3904.87 (Official Build) (64-bit) on MacOSX:

![image](https://user-images.githubusercontent.com/730342/69061715-01921600-0a1a-11ea-8362-f22d45087bfb.png)

The first line is a `<h4>` header. The second line is body.

**Comment by alex-shpak** [comment]
HI!
I can increase `font-weight` for `h4, h5, h6`, but not sure that it will look nice. Do you think it's a problem?

**Comment by JensRantil** [comment]
Yes, definitely a problem. H5 and h6 are totally fine and stand out so you might not really need to adjust those.

**Comment by alex-shpak** [comment]
I think bolder `h4` will stand out too much
![image](https://user-images.githubusercontent.com/5515443/69188097-2a9acf80-0b1c-11ea-824c-fea0c20d926f.png)

So like this would be better
![image](https://user-images.githubusercontent.com/5515443/69188696-523e6780-0b1d-11ea-8014-bb02618e749a.png)

**Comment by alex-shpak** [comment]
Pushed to master

**Comment by JensRantil** [comment]
Excellent! Thanks!
