### ISSUE TITLE
Hi, I want to build online website tech ducuments for my github project, so which is a better choice, docsy or hugo-book?

### ISSUE THREAD

**Issue by jievince** [alex-shpak/hugo-book#101]

**Comment by alex-shpak** [comment]
Hi!
Hard to not be biased here 😄 

I would say that it's mostly up to your visual preference. Many features are similar between themes.

**Comment by jievince** [comment]
> Hi!
> Hard to not be biased here 😄
> 
> I would say that it's mostly up to your visual preference. Many features are similar between themes.

Oh, I think both theme can satisfy my need for visual preference. I also care about the version control feature, does hugo-book has version control?

**Comment by alex-shpak** [comment]
If you mean showing last commit date and link to edit this page - book has it.
At the bottom of page
![image](https://user-images.githubusercontent.com/5515443/70093368-84bd8980-1620-11ea-8800-b0c3539119bc.png)

**Comment by jievince** [comment]
Sorry for my unclear expression. I need to deploy several version of documents to my web site, and the users can choose which version to use. It should like this:
![image](https://user-images.githubusercontent.com/38901892/70401447-93fe6600-1a6a-11ea-8383-34c49152b5b1.png)
In the picture, v3.0, dev, v2.1 are three version of docs, users can click one of them.
The example web site in the picture is https://pingcap.com/docs/

**Comment by alex-shpak** [comment]
You can use multilang support in get versioning, where one "language" will represent one version.
I guess same comes with docsy.
