### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Nguimjeu** [alex-shpak/hugo-book#102]
Hey are you planning to also provide a `dark` version of the `hugo-book` template?

Thanks for the template by the way :-)

**Comment by alex-shpak** [comment]
Hi!
Check [here](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/assets/_variables.scss)

You can create folder `assets` in your website with `_variables.scss` to override vars. import `plugins/dark` there and you will get some dark mode, it mostly done, except icons are still dark.

Related https://github.com/alex-shpak/hugo-book/issues/59#issuecomment-537938670

**Comment by Nguimjeu** [comment]
Many thanks!
