### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by v-pere** [alex-shpak/hugo-book#103]
Follow "Creating site from scratch" instructions:

> hugo new site mydocs; cd mydocs
> git init
> git submodule add https://github.com/alex-shpak/hugo-book themes/book
> cp -R themes/book/exampleSite/content .
> hugo server --minify --theme book

And get the error:

> Error: ".../themes/book/layouts/partials/docs/languages.html:4:1": parse failed: template: partials/docs/languages.html:4: function "merge" not defined

**Comment by alex-shpak** [comment]
Hi!
Which version of hugo do you use? `$ hugo version`

**Comment by v-pere** [comment]
> Hugo Static Site Generator v0.55.5/extended darwin/amd64 BuildDate: unknown
> Hugo Static Site Generator v0.55.6-A5D4C82D linux/386 BuildDate: 2019-05-18T07:55:31Z

**Comment by alex-shpak** [comment]
I see. 
Merge function was introduced in `0.56` https://github.com/gohugoio/hugo/releases/tag/v0.56.0
So README page is misleading. I will update that.

Would it work for you to update to higher version of hugo? `0.60` was released recently.

**Comment by v-pere** [comment]
Updated hugo to the latest version 0.61. All right.
Thank you!
