### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kazukyakayashi** [alex-shpak/hugo-book#105]
Hello,
I followed the "Creating site from scratch" instructions:

    hugo new site mydocs; cd mydocs
    git init
    git submodule add https://github.com/alex-shpak/hugo-book themes/book
    cp -R themes/book/exampleSite/content .

But I get this error when I launch the Hugo server `hugo server --minify --theme book`

```
Building sites … ERROR 2019/11/30 09:22:03 Failed to read Git log: fatal: your current branch 'master' does not have any commits yet
Built in 135 ms
Error: Error building site: logged 1 error(s)
```

Version : `Hugo Static Site Generator v0.60.1/extended windows/amd64 BuildDate: unknown`

**Comment by alex-shpak** [comment]
Hi!
This error happens if you have `enableGitInfo = true` in `config.toml`, which reads git info. I guess you copied config file as well? By default you don't need any config to start with.
Either disable it or commit something to git repository.

**Comment by kazukyakayashi** [comment]
Hi, 
Thank you, it works once the  `enableGitInfo = true` option switched to `false`

Sorry for the unnecessary inconvenience.

**Comment by jfmatth** [comment]
I vote to set this to False 😄
