### ISSUE TITLE
KaTeX formulas in columns do not render

### ISSUE THREAD

**Issue by VilhelmPrytz** [alex-shpak/hugo-book#106]
As of hugo version `v0.60.0` (including `v0.60.1`, tested), KaTeX formulas put in `{{< columns >}}` do not render at all. I have not tested if other contents have trouble rendering in columns.

This is how the `exampleSite` page `shortcodes/katex` looks in `v0.59.1`
![hugo_v59](https://user-images.githubusercontent.com/15460993/69906756-72e1a980-13c8-11ea-957e-84893a936c76.png)

And this is how the same page looks in `v0.60.0` and `v0.60.1`
![hugo_v60](https://user-images.githubusercontent.com/15460993/69906758-7ecd6b80-13c8-11ea-99cd-b63b46b07ef4.png)

Hope my description of this issue is sufficient.

Cheers

**Comment by alex-shpak** [comment]
Hi!
I would guess that it's due to hugo's change from blackFriday to GoldMark, will need some debugging.

https://gohugo.io/news/0.60.0-relnotes/
```
markup:
  goldmark:
    renderer:
      unsafe: true
```

This might help

**Comment by VilhelmPrytz** [comment]
Hi! Thank you, that did solve the problem :slightly_smiling_face:
