### ISSUE TITLE
function "merge" not defined

### ISSUE THREAD

**Issue by kovasap** [alex-shpak/hugo-book#107]
Running `hugo` on my site gives:

```
Error: "/home/kovas/website/kovasap/themes/hugo-book/layouts/partials/docs/languages.html:4:1": parse failed: template: partials/docs/languages.html:4: function "merge" not defined
```

This happens after 05c3b8fac9bec7cf54fed20d93fac52e1e97ad97.  Seems like a bug with that change?  Any idea what might be causing it?

**Comment by alex-shpak** [comment]
Hi!
`merge` function was introduced in hugo `0.56`, I would recommend to update if you running older version.

**Comment by kovasap** [comment]
Ah, that's probably it; I'm on an older version.  I'll reopen if that's not the case.
