### ISSUE TITLE
Toc in mobile browsers

### ISSUE THREAD

**Issue by archphile** [alex-shpak/hugo-book#11]
Hi and congrats for your really nice theme.

I am preparing a website and I noticed that when using the mobile theme, the table of content disappears.
Is there any way to show it, ex. in the beginning of the document or anywhere else?
Thank you in advance.
Mike

**Comment by alex-shpak** [comment]
Hi! Thank you!

During initial work I spent some time but didn't succeed to make toc work nicely on mobile devices,
If there is demand I can spend some more time.

I guess simplest way is to show it on bottom of content, but that it feels useless, so maybe use `order: x` to swap content and toc places.

**Comment by archphile** [comment]
Many hanks for your reply.
