### ISSUE TITLE
'gaming' search

### ISSUE THREAD

**Issue by jamesb93** [alex-shpak/hugo-book#110]
Hi Alex,

Is there a way to influence how the search finds pages in the site? Does it parse a certain kind of markdown tag? From what I can see it picks up on `<h1>` or `#`.

**Comment by alex-shpak** [comment]
Hi!
You can configure `flexsearch` see https://github.com/nextapps-de/flexsearch
[Here](https://github.com/alex-shpak/hugo-book/blob/master/i18n/en.yaml#L11) config is stored per language.

I checked search results. In example site it looks like `h1` and `#` are picked correct. there are some `h1` in text, and `#` finds nothing. 

You can check [this file](https://themes.gohugo.io/theme/hugo-book/en.search-data.min.3dbf4286529ae0b9a31b660d4bce0eea1e1634fbbcb422b4b7972dff64547ffa.js) to see generated content (Or corresponding file in your site). Search also uses `.Plain` [page variable](https://gohugo.io/variables/page/) to get content with removed tags. So seems in tact.

**Comment by jamesb93** [comment]
Cool, thank you!
