### ISSUE TITLE
markdown outline displaying defect

### ISSUE THREAD

**Issue by outrunJ** [alex-shpak/hugo-book#112]
appreciating "hugo-book" 's jobs, I adopted this theme for my personal knowledge base.

I updated "hugo-book" version a couple days ago, and found markdown's outline on the right does not display or displays without their front titles.
case like this(my site): https://outrunj.github.io/docs/algorithm/

I appreciate some clues to fix it.
thank you。

**Comment by alex-shpak** [comment]
Hi!
I think it happens because of changes in hugo `0.60`
please check https://gohugo.io/getting-started/configuration-markup/ and corresponding setting:
```
[markup.tableOfContents]
  startLevel = 1
```

**Comment by outrunJ** [comment]
> Hi!
> I think it happens because of changes in hugo `0.60`
> please check https://gohugo.io/getting-started/configuration-markup/ and corresponding setting:
> 
> ```
> [markup.tableOfContents]
>   startLevel = 1
> ```

It works! thank you,
It's my fault for not checking it out.
