### ISSUE TITLE
dates for blog posts

### ISSUE THREAD

**Issue by jamesb93** [alex-shpak/hugo-book#113]
Hi Alex,

How come my website's blog post's date is displaying some arbitrary time at the top? Where does it pull the date information from? Is there perhaps a way to hide dates in blog posts?

https://www.hudhack.space/posts/version-control/

**Comment by alex-shpak** [comment]
HI!
I will update template to hide date if there is no date specified.

**Comment by alex-shpak** [comment]
Pushed to master.

**Comment by alex-shpak** [comment]
Closing issue, write here if you still have that problem, I will re-open.

**Comment by jamesb93** [comment]
Thanks Alex, sorry for the delayed response but it works now.

**Comment by try-agaaain** [comment]
I have an opposite requirement where I'd like the date to be displayed by default below any post, even if I don't specify a date. Are there any configurations that can meet this requirement?
