### ISSUE TITLE
Page "weight" doesn't appear to work

### ISSUE THREAD

**Issue by VilhelmPrytz** [alex-shpak/hugo-book#114]
Previously, I have been able to specify the weight of a document in order to sort them (within the left-menu of the project). Since a while ago (I'm unsure when, I believe it was after the `0.60` update) this has stopped working.

See this example.

```markdown
---
title: Test
weight: 1
---
``` 

The menu ignores the weight, they are not ordered after weight in the menu.

Is this related to the theme or is this a change within Hugo that has caused this?

**Comment by alex-shpak** [comment]
Hi!
It is indeed was working before `0.60`, I will check.

**Comment by alex-shpak** [comment]
Hi again!
I tested weight on [exampleSite](https://github.com/alex-shpak/hugo-book/tree/master/exampleSite) and seems like it is working as expected. Both on section and page.

**Comment by VilhelmPrytz** [comment]
Ah, yes, I got it solved now. Before version `0.60` or `0.61` (can't remember for sure) I would have several pages within a folder with the weight of the first one set as `0`. This, however, seems to have broken.

Once I set the first page to `weight: 1` and everything else to 2, 3, 4 ... and so on, it works. Before I would have the first one set as `weight: 0` and everything else to 1, 2, 3 ... and so on.

Not too sure what caused this. Anyways, maybe this should be mentioned somewhere? Perhaps it's not at all related to your (excellent) theme and it's just something that changed with the new release of Hugo?

Hugo version:

```
Hugo Static Site Generator v0.61.0/extended linux/amd64 BuildDate: unknown
```

**Comment by alex-shpak** [comment]
Heh, I never tried to set `weight` to 0, I usually use 10, 20, 30 to be able to insert page between later without rewriting all other weights.
I think no need to write something extra, sorting by weight is feature coming entirely from hugo.

**Comment by VilhelmPrytz** [comment]
Fair enough, thanks for letting me know!
