### ISSUE TITLE
Support for inline math expressions

### ISSUE THREAD

**Issue by p-gw** [alex-shpak/hugo-book#117]
Thank you for this great theme. 

Since Katex shortcodes are already implemented I wondered whether inline math expressions are supported as well. I already tried the basic inline syntax using `$$` (e.g. *some text* `$$x = 1$$` *some more text*), but it gets rendered as a block.

It is suggested [here](https://vincenttam.gitlab.io/post/2019-04-29-improved-integration-of-hugo-and-katex/#solution) to add `markup: mmark` to the front matter or to save the `*.md` files as `*.mmark`. When doing so the inline math expressions do get rendered correctly with `$$` but the table of contents in the right column  vanishes. 

Is there a way to both get inline math as well as keep the table of contents when using hugo-book?

**Comment by alex-shpak** [comment]
Hi!
Unfortunately, I think `mmark` rendered doesn't support ToC listing.
Also it is about to be removed from Hugo https://gohugo.io/content-management/formats/

**Comment by BetFab** [comment]
Hi, 
I faced this issue too and solved it by modifying the katex shortcode by : 
```html {hl_lines=["6-16"]}
{{ if not (.Page.Scratch.Get "katex") }}
<!-- Include katext only first time -->
<link rel="stylesheet" 
...
  onload="
      renderMathInElement(
          document.body,
          {
              delimiters: [
                  {left: '$$', right: '$$', display: true},
                  {left: '\\[', right: '\\]', display: true},
                  {left: '$', right: '$', display: false},
                  {left: '\\(', right: '\\)', display: false}
              ]
          }
      );"></script>
{{ .Page.Scratch.Set "katex" true }}
{{ end }}

<p class="katex{{ with .Get "class" }} {{ . }}{{ end }}">
  $$ {{ .Inner }} $$
</p>
```
it just changes the call of auto-rendering from Katex like in [the KaTex repo](https://github.com/KaTeX/KaTeX/blob/master/contrib/auto-render/index.html)

Then I created another shortcode (based of the katex one) for inline math that uses span & the $.$ syntax : 
```html
...
<span class="katex{{ with .Get "class" }} {{ . }}{{ end }}">
  ${{ .Inner }}$
</span>
```
Finally I can call this shortcode to generate inline math in a post like for example
 `a permutation {{< katex_inline >}}\pi(x){{< /katex_inline >}} ` and it works fine. 

It may not be optimal but it can be a start.

**Comment by alex-shpak** [comment]
I updated `KaTeX` shortcode so that it accepts `display` param. So:
`{{< katex >}}\pi(x){{< /katex >}}` will produce `\( ... \)` wrap for inline text and
`{{< katex display >}}\pi(x){{< /katex >}}` will procude `\[ ... \]` wrap for display mode.

**Comment by alex-shpak** [comment]
This will work for now, but it have high chance to mess with markdown. For example if you put inline shortcode in the middle of heading (like `## heading <shortcode> rest of it`) it will break markdown layout.

**Comment by p-gw** [comment]
Thank you @BetFab for the modification and @alex-shpak for the implementation! This will work just fine for my use case.

**Comment by alex-shpak** [comment]
👍 I will close this issue then, write here if you want me to reopen.

**Comment by taxilian** [comment]
Just to add a note for the next person looking for a solution here: as of [v0.132.0](https://github.com/gohugoio/hugo/releases/tag/v0.132.0) hugo can now do katex rendering on the server side automatically – no special `hugo-book` configuration needed. see https://gohugo.io/render-hooks/passthrough/

In `hugo.toml` add:
```toml
[markup]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
```

Then create a `layouts/_default/_markup/render-passthrough.html` file with this:

```
{{ if eq .Type "block" }}
  {{ $opts := dict "displayMode" true }}
  <span class="katex-display">{{ transform.ToMath .Inner $opts }}</span>
{{ else }}
  {{ transform.ToMath .Inner }}
{{ end }}
```

You need katex CSS but the rendering will happen during build. It's nice to have this option because it's compatible with github's markdown, so if you have anything you want to render on github and also in a hugo site this works.

It's still a little bit experimental, but it took a long time for me to track all of that down, so I thought I'd share it on one of the places I first found when I was looking.
