### ISSUE TITLE
I have two questions; search Korean and first page

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#118]
Hi Alex,

I am Ryan, live in Korea. I found your blog and I feel wonderful blog. I tried to port and tested. However, from the first time, I have some challenges. 

Firstly, I would like to show my blog post whenever I visit and refresh the web site. I do not know how to fix the  _index.md file. 

Secondly, I am Korean thus, I need to search in Korean on the search form. How I do fix it?

**Comment by alex-shpak** [comment]
Hi Ryan!
Unfortunately there is no simple way to render list of posts as home page in theme.
As option if you have reverse proxy in front of site you can rewrite `/` to `/posts/`. Alternatively override `layouts/home.html` template to render posts.
Also to note, theme is more documentation oriented, so it might lack some blogging features.

As for search, there is settings for languages [here](https://github.com/alex-shpak/hugo-book/tree/master/i18n), tho I don't speak korean, so I need help to figure out settings for [FlexSearch](https://github.com/nextapps-de/flexsearch)

**Comment by alex-shpak** [comment]
Maybe same settings will work for korean as for chinese.
https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean

**Comment by alex-shpak** [comment]
I added `ko` language code with same settings as chinese.
Try to set your site language to `ko` in `config.toml|yaml`

```toml
defaultContentLanguage = 'ko'

[languages]
[languages.ko]
  languageName = 'Korean'
  contentDir = 'content'
  weight = 1
```

**Comment by noweaver** [comment]
Alex, thank you for your kindness. 

But I would like to solve the first issue which is my front page, https://noweaver.github.io 
I want to show my blog(https://noweaver.github.io/posts) whenever I visite my site. 

Could you show me in detail? I am a rookie. :<

**Comment by alex-shpak** [comment]
Try this:

 - Remove this file: https://github.com/noweaver/noweaver/blob/master/content/_index.md
 - Create file https://github.com/noweaver/noweaver/blob/master/layouts/home.html
    Path is `/layouts/html.home` in your repository.

With content:
```tpl
{{ define "main" }}
{{ with .Site.GetPage "section" "posts" }}
  {{ $paginator := .Paginate (where .Pages "Params.hidden" "ne" true) }}
  {{ range sort .Paginator.Pages }}
  <article class="markdown book-post">
    <h2>
      <a href="{{ .RelPermalink }}">{{ .Title }}</a>
    </h2>
    {{ partial "docs/post-meta" . }}
    <p>
      {{- .Summary -}}
      {{ if .Truncated }}
        <a href="{{ .RelPermalink }}">...</a>
      {{ end }}
    </p>
  </article>
  {{ end }}

  {{ template "_internal/pagination.html" . }}
{{ end }}
{{ end }}

{{ define "toc" }}
  {{ partial "docs/taxonomy" . }}
{{ end }}
```

I'm not 100% sure that it will help. You also might need to update it from time to time, when something changes in theme.

**Comment by noweaver** [comment]
Thank you for your kindness again.

I solved it perfectly from your help!

**Comment by alex-shpak** [comment]
Glad to help!
Just keep in mind that if related partials would change you might need to fix `home.html` file.
