### ISSUE TITLE
Tags, Categories Links in the Blog posts ignore websites root directory

### ISSUE THREAD

**Issue by gshamov** [alex-shpak/hugo-book#122]
Hi,

First I must say the Book theme is great, easy to use, many thanks Alex for developing it!

A small thing (may well be I am not doing something correctly, because I am new to Hugo). I have my site's baseURL as something like http://mysite.ca/doc . Then, I enable BookSection='*' to actually see the blog posts. 

It all works; the tags and categories (which are links) are correctly linking on the right-hand side TOC to /doc/tags/something and /doc/categories . This is because I have ./doc root for the website. 

However, the same tags and categories links on the actual blog posts seem to ignore the "/doc" root and go direct to the nonexisting /tags/something and /categories/something. 

Thanks! 

Grigory Shamov

**Comment by alex-shpak** [comment]
Hi! Thanks!
It is likely a bug, I will take a look.

**Comment by alex-shpak** [comment]
Fix is pushed to master

**Comment by gshamov** [comment]
Thank you very much!
