### ISSUE TITLE
Question: add image beside title

### ISSUE THREAD

**Issue by pmatula** [alex-shpak/hugo-book#123]
I want to ask, is it possible to add an (small) image beside the title? I didn't find any configuration possibility.

**Comment by alex-shpak** [comment]
Hi!
I guess you are looking for this

https://github.com/alex-shpak/hugo-book/pull/71
https://github.com/alex-shpak/hugo-book#site-configuration (Look at `BookLogo`)

**Comment by pmatula** [comment]
Exactly. I conveniently overlooked it. Thanks! :-)
