### ISSUE TITLE
Building with any version after 0.59, breaks URL formatting

### ISSUE THREAD

**Issue by atrahhdis** [alex-shpak/hugo-book#124]
Hi and many thanks for this really nice theme. 

I am experiencing some issues when trying to build a website with latest theme and  hugo>.0.59.

This is a part of my page with 0.59:

https://i.imgur.com/thEOqOa.png

and this is with 0.62:

https://i.imgur.com/2ZCHoYG.png

This is the source of the page:

```
*Download this text in e-book format: [epub](https://mahasivipassana.com/downloads/epub/Practical Insight Meditation_ Basic Practice - Mahasi Sayadaw.epub) | [azw3 (kindle)](https://mahasivipassana.com/downloads/azw3/Practical Insight Meditation_ Basic Practice - Mahasi Sayadaw.azw3) | [mobi (kindle old format)](https://mahasivipassana.com/downloads/mobi/Practical Insight Meditation_ Basic Practice - Mahasi Sayadaw.mobi) | [md (source)](https://mahasivipassana.com/downloads/md/Practical Insight Meditation_ Basic Practice - Mahasi Sayadaw.md)*
<br/>
<sub> ***e-book version:*** *2.4 - 2019-12-29*</sub>
```

Greetings,
M.

**Comment by alex-shpak** [comment]
Hi!
In hugo version `0.60.0` they changed markdown renderer to [Goldmark](https://github.com/yuin/goldmark/) and it seems like it doesn't like spaces in your URL.

Try replacing spaces with `%20` which is url-encode value of space. Like this:
`[epub](https://mahasivipassana.com/downloads/epub/Practical%20Insight%20Meditation_%20Basic%20Practice%20-%20Mahasi%20Sayadaw.epub)`

**Comment by atrahhdis** [comment]
Ooooh!

Many thanks for your quick reply. 

I will try it ASAP.

**Comment by atrahhdis** [comment]
I tested it and it works. 

BTW it seems that Goldmark breaks A LOT of my previous markdown texts for various reasons.

Thanks again.

**Comment by atrahhdis** [comment]
Just to make my previous post clearer, I needed to correct a lot, but most of them were mistakes that most probably were auto-corrected in previous versions. It seems that Goldmark is much less tolerant in formatting.

An example: I had links like this one before without any trouble:

`[word] (url)`

With Goldmark I had to remove the extra space and make it:

`[word](url)`
