### ISSUE TITLE
What is the problem with search functions?

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#125]
Dear Alex, 

Thanks for my last issue. Now, I would like to solve the problem of the Search form.
I want to search for my article written Korean in the Search form.

My confit.toml file is below as;
```
[languages.ko]
  languageName = 'Korean'
  contentDir = 'content'
  weight = 1
```
As far as I know, this configuration is for supporting multi-language. I don't know why this configuration file is relevant to Search.

Plus, as you guided, my ko.yaml of i18n is below as;
```
- id: Search
  translation: 검색

- id: Edit this page
  translation: 편집

- id: Last modified by
  translation: 마지막 수정일자

- id: bookSearchConfig
  translation: |
    {
      encode: false,
      tokenize: function(str) {
        return str.replace(/[\x00-\x7F]/g, '').split('');
      }
    }
```
Plus, I have an article, /posts/05-14-Hugo-Blog-Installation.md, written Korean.

However, I still don't know how to touch and fix the configuration. 
Give light to beginners.

my blog: https://noweaver.github.io/
my repository of blog: https://github.com/noweaver/noweaver.github.io

In my blog, https://noweaver.github.io/, You can check the Korean Character in the Search form after copy and paste, Sorry

**Comment by alex-shpak** [comment]
Hi!
Did you set `defaultContentLanguage: ko`?

`defaultContentLanguage` param is used to pick up translations (and search config is implemented as one of them)
I can see that in your blog it is still loading `en` configuration.

You can also remove `en` language:
https://github.com/noweaver/noweaver/blob/master/config.toml#L25-L28

Here is hugo docs for reference
https://gohugo.io/content-management/multilingual/

**Comment by noweaver** [comment]
Alex!
You Genius!
