### ISSUE TITLE
The post doesn't come out.

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#126]
He Alex,

Continuously I keep testing it. But this time, it doesn't publish an article. The total number of post in posts directory is three, only two have been published. Why is that?

**Comment by alex-shpak** [comment]
Hi!
That post is dated `2020-01-17`, which is in future. Hugo's behaviour is not to render that post until date. See docs: https://gohugo.io/content-management/front-matter/#front-matter-variables
Params: `date`, `publishDate` and `expiryDate`

Also you can build future posts with `--buildFuture` flag

**Comment by noweaver** [comment]
Thank you. I noticed yesterday.

**Comment by alex-shpak** [comment]
Can be closed? :)
