### ISSUE TITLE
Firefox only prints first page of longer posts

### ISSUE THREAD

**Issue by sjml** [alex-shpak/hugo-book#127]
I've taken my own stab at trying to fix this, and continuing to investigate, but I can't quite pin down what's going wrong. 

Right now if you print a long-ish page from Firefox, only the first page will be printed. (You can see the problem just by generating a PDF of the page; no need to actually use paper.) This is apparently a long-standing issue with FF, but other sites have found ways around it. It seems to lie in the usage of CSS on tall elements. 

[This answer in the Mozilla forums](https://support.mozilla.org/en-US/questions/1198054#answer-1059906) points to a few possibilities, as do the responses to [this StackOverflow question](https://stackoverflow.com/questions/4609007/firefox-printing-only-1st-page). The simple ones from SO don't seem to do the trick, and I'm poking around hugo-book's CSS and DOM to see if any of the points from the Mozilla forum apply, but kind of stumped right now. 

Logging this here in case you're able to pinpoint it faster than I am, but I'm going to continue looking around.

**Comment by alex-shpak** [comment]
Hi!
Seems like `display: flexbox` on `<main>` is causing this.
Here is some discussion.https://stackoverflow.com/questions/45414152/css-flex-box-not-printing-all-pages-on-firefox

**Comment by sjml** [comment]
Yup, that seems to be the trick. Overriding it on `@media print` isn't straightforward since it's using the `flex` class. Unless we override *that* on print, but that seems overly broad. Maybe `<main>` needs to have `display: flex` set directly instead of using the `flex` class?

**Comment by alex-shpak** [comment]
Eh, I will need to think about it.
Right now `flexbox` is used to show ToC on top of page when printing, by reversing order of containers for print... so that would stop to work if we enforce `display: block`

**Comment by sjml** [comment]
Ah, right, my bad. (Not using ToC in my site, so didn't notice.) I'll poke around and see if there's some more subtle solution, too, but glad it's on your radar.

**Comment by sjml** [comment]
Closed by #129.
