### ISSUE TITLE
The link of both categories and tag in the front-page is broken

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#130]
https://noweaver.github.io/

The categories and tags of the right side are the right links by clicking with mouse hover.

https://noweaver.github.io/tags/2019/

But on the front page, the link is broken.

https://noweaver.github.io/tags/2019/**Page%28**/tags/2019**%29**

**Comment by alex-shpak** [comment]
👋 
Seems like regression bug, I pushed changes to master.
