### ISSUE TITLE
Keyboard shortcut for focusing the search field

### ISSUE THREAD

**Issue by skoskav** [alex-shpak/hugo-book#134]
Would there be interest in allowing a keyboard shortcut to give focus to the search field? For instance, in GitHub this can be achieved by pressing `/` or `s`.

If yes, is it okay if I started working on this?

**Comment by alex-shpak** [comment]
Hi! Could be a nice touch.

Conventions I'm keeping for JS:
- No NPM/Node modules
- Site should work if JS is disabled.

I think you can add it to `assets/search.js`
