### ISSUE TITLE
question about table of contents on the right

### ISSUE THREAD

**Issue by rhuang** [alex-shpak/hugo-book#138]
I pulled the latest code on the theme from the submodule and the table of contents on the right is a bit different than the demo page in the smaller resolutions:

Demo;
<img width="777" alt="Screen Shot 2020-01-23 at 9 07 58 PM" src="https://user-images.githubusercontent.com/1022385/73045881-a0752d00-3e24-11ea-8008-359a1a70f34e.png">

Mine:
<img width="755" alt="Screen Shot 2020-01-23 at 9 07 55 PM" src="https://user-images.githubusercontent.com/1022385/73045882-a0752d00-3e24-11ea-93df-4b40c5c28ccb.png">

I can see the styling is a bit different. I've set `BookToC: true` and don't have any overrides in the individual pages. Can you help me understand why?

I also noticed when I take the v5 commit (https://github.com/alex-shpak/hugo-book/commit/995c1e695cb5d6f30f0b15fe040693aab052bbf0), the table of contents on the right doesn't trigger.

<img width="1103" alt="Screen Shot 2020-01-23 at 9 20 08 PM" src="https://user-images.githubusercontent.com/1022385/73046285-4a08ee00-3e26-11ea-9ced-3b062f045a33.png">

**Comment by alex-shpak** [comment]
Hi!
Yesterday I pushed some changes to ToC behaviour to master, soon `v6` will be released.
In `v5` there is no support for ToC in mobile view, `v6` will bring it.

It was not yet deployed at examples site.

This is how it supposed to look on mobile in latest revisions.
![image](https://user-images.githubusercontent.com/5515443/73068586-de696400-3eab-11ea-90ef-2ca4e9f24d04.png)

**Comment by rhuang** [comment]
Cool. The demo site's ToC in mobile view is the "slide" version, I'm not sure what version that is.
It looks like v5 as well as the latest code on `master` both have the ToC version in your screenshot.

Just want to point out in the latest code on `master` that sometimes there is horizontal scrolling in the mobile resolutions:

<img width="532" alt="Screen Shot 2020-01-25 at 3 24 51 PM" src="https://user-images.githubusercontent.com/1022385/73128631-0bd71000-3f87-11ea-9e1e-dfcc013836c3.png">

**Comment by alex-shpak** [comment]
Hi!
https://themes.gohugo.io/theme/hugo-book/ now picked latest master commit, so they are aligned.
About scroll bar - I will check, might be regression after [this](https://github.com/alex-shpak/hugo-book/commit/ba5d38ad4427bcda21a4cc57689464ed58d8b9a0#diff-a933843e1880482a58ba7e91b7daf11aR34)

**Comment by alex-shpak** [comment]
Hi again!
Minimum body width used to be `320px`, but after css rewrite became `400px`, so I lowered it back. Note that scrollbar will start to appear lower that `320px` anyway.

**Comment by rhuang** [comment]
Thanks Alex, looks great!

I will close this issue now.
