### ISSUE TITLE
adding toc on rmarkdown documents

### ISSUE THREAD

**Issue by emmandecena** [alex-shpak/hugo-book#139]
Hi,

I cannot seem to show the table of contents on my rmarkdown generated document. 
I tried adding `bookToC: true` , `booktoc: true` or `toc: true` to the front matter of my rmarkdown document but still the toc does not show on the rendered html.

**Comment by alex-shpak** [comment]
Hi!
Parameter `BookToC` in site and page params is `true` by default, perhaps your toc is limited by markup config, by default hugo starts to render headings from second level in toc.

Try this in your site config:
```toml
[markup.tableOfContents]
  startLevel = 1
  endLevel = 6
```

Ref: https://gohugo.io/getting-started/configuration-markup/#table-of-contents

If that doesn't help compare your settings and content to `exampleSite`, ToC works there.

**Comment by emmandecena** [comment]
I was able to show the toc by putting the following code on my Rmarkdown front matter:
`output:
  blogdown::html_page:
    toc: true`

However, I would like the toc to be on the right side, just like your template. How do I extract this toc and put it on the template? See attached image. Thank you.
![Screen Shot 2020-01-29 at 8 47 20 PM](https://user-images.githubusercontent.com/14914909/73337234-c8f3a000-42d8-11ea-87ef-09abf78f0c72.jpg)

**Comment by alex-shpak** [comment]
Hi!
Did you try suggestions I had in previous comment?
Maybe you can create example site to reproduce issue, so I can have a look at it.

**Comment by alex-shpak** [comment]
Can be related: https://github.com/rstudio/blogdown/issues/58#issuecomment-299232908

**Comment by alex-shpak** [comment]
Perhaps you need to switch output format from `rmd` to `md` for that. Unfortunately I don't have experience with blogdown.

**Comment by emmandecena** [comment]
I figured there might not yet be a feature to extract the toc from and `rmd` file. Will try to address this issue on the blogdown page. Thank you!
