### ISSUE TITLE
Could you solve the tag problem in Korean?

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#140]
I would like to solve and improve your theme one by one with you.

Firstly, I would like to improve the problem. This problem is that the Korean tag is not shown on the blog post page. However, the right-side tags are showing correctly Korean tags.

As far as you know, I am a rookie of the static blog and I am not a web programmer.

**Comment by alex-shpak** [comment]
Hi!

As I mentioned there https://github.com/alex-shpak/hugo-book/issues/132#issuecomment-577410198 this looks like hugo issue, there is trick to solve it with checking both `urlize` and original tag name in pages but that is bad solution I think.

I suggest to open discussion on Hugo's forum: https://discourse.gohugo.io/ or issues https://github.com/gohugoio/hugo. Unfortunately I didn't have time yet to take care of it.

**Comment by alex-shpak** [comment]
Related: https://github.com/gohugoio/hugo/issues/5687

**Comment by noweaver** [comment]
Alex, always thank you for your care and kindness.

I read your guide, however, I do not know exactly how I fix my blog. I am not a programmer.

But, if you give me the guide one more, I gonna try to fix it and then I will give you the feadback.

**Comment by alex-shpak** [comment]
Well, hugo recently fixed it, in 0.65
I will prepare update in theme.

https://gohugo.io/news/0.65.0-relnotes/
look for `GetTerms`

**Comment by alex-shpak** [comment]
☝️ Fix is pushed to master

**Comment by noweaver** [comment]
Thank you for your efforts.
