### ISSUE TITLE
How do I make tag count and category count?

### ISSUE THREAD

**Issue by noweaver** [alex-shpak/hugo-book#141]
I want to show an article's count number on categories and tags of the right-side.

How do I do that?

**Comment by alex-shpak** [comment]
HI! This snippet in `taxonomy.html` would do
```tpl
{{ range .Pages }}
  <li class="flex justify-between">
    <a href="{{ .RelPermalink }}">{{ .Title }}</a>
    <span>{{ len .Pages }}</span>
  </li>
{{ end }}
```

![image](https://user-images.githubusercontent.com/5515443/74191500-06024f80-4c54-11ea-96f8-950bfbce7bf0.png)

**Comment by alex-shpak** [comment]
Pushed to master

**Comment by alex-shpak** [comment]
Feel free to re-open if you still need assistance.
