### ISSUE TITLE
Help needed with Katex

### ISSUE THREAD

**Issue by pantelis** [alex-shpak/hugo-book#142]
Hi all, I do face an important issue as I am using the template for a course with lots of math. I have created an inject body.htm and added in there the katex cdn script imports with delimiter options. In some equations though I am not able to get the right rendering.

This equation is not rendered:
`$$  \mathbf{s}_t = f(\mathbf{s}_{t-1}, \mathbf{x}_t ; \theta) $$`

This equation is rendered correctly though
`$$ \mathbf{s}_t = f(\mathbf{s}^{t-1}, \mathbf{x}_t ; \theta) $$`

Notice that the only change is a single symbol on the right hand side. 

When I use the shortcut, the 2nd equation is rendered correctly although the font is too big for a page that is full of math. 

`{{< katex >}}
\mathbf{s}_t = f(\mathbf{s}_{t-1}, \mathbf{x}_t ; \theta) 
{{< /katex >}}`

I am including below the layouts/partials/docs/inject/body.html

```
<!DOCTYPE html> 

<link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/katex.min.css"
  integrity="sha384-BdGj8xC2eZkQaxoQ8nSLefg4AV4/AwB3Fj+8SUSo7pnKP6Eoy18liIKTPn9oBYNG"
  crossorigin="anonymous">

<script defer
  src="https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/katex.min.js"
  integrity="sha384-JiKN5O8x9Hhs/UE5cT5AAJqieYlOZbGT3CHws/y97o3ty4R7/O5poG9F3JoiOYw1"
  crossorigin="anonymous"></script>

<script defer
  src="https://cdn.jsdelivr.net/npm/katex@0.11.0/dist/contrib/auto-render.min.js"
  integrity="sha384-kWPLUVMOks5AQFrykwIup5lo0m3iMkkHrD0uJ4H5cjeGihAutqP0yW0J6dpFiVkI"
  crossorigin="anonymous" onload="renderMathInElement(document.body);">
</script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    renderMathInElement(document.body, {
      delimiters: [
          {left: "$$", right: "$$", display: true},
          {left: "$", right: "$", display: false}
      ]
    });
  });
</script>

<!-- <script type="text/javascript">
  window.MathJax = {
    showProcessingMessages: false,
    messageStyle: 'none',
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']]
    }
  };
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script> -->
</html>
```

I have tried both katex and Mathjax and I am getting the exact same behavior. Can anyone help me understand what is may be going wrong? I am new to hugo so if there is another solution that will allow me to use the $$ and $ delimiters, I would appreciate any pointers. 

Thank you

**Comment by alex-shpak** [comment]
Hi!
I tried it with `{{ katext }}` shortcode, looks like this for me
![image](https://user-images.githubusercontent.com/5515443/73921977-a2c99380-48c8-11ea-9508-db321b1d365a.png)

Seems to be correct. So maybe check generated html text, maybe `^` symbol gets escaped, or something similar.

How does it look for you?

P.S. I agree that formula text size should be smaller in inline mode, I will check.

**Comment by pantelis** [comment]
Hi Alex,

the part that is between $$ delimiters ( $$\mathbf{s}_t = f(\mathbf{s}_{t-1}, \mathbf{x}_t ; \theta)$$) is the first line below. It simply does not parse but its parsing perfectly in the katex.org site. The html code treats the underscores as **emphasis instead of math subscripts.** 

`<p>$$ \mathbf{s}<em>t = f(\mathbf{s}</em>{t-1}, \mathbf{x}_t ; \theta) $$</p>`

This equation, $$\mathbf{s}_t = f(\mathbf{s}^{t-1}, \mathbf{x}_t ; \theta)$$ which as you notice involves a superscript at the right hand side is also parsed as

`<p>$$ \mathbf{s}<em>t = f(\mathbf{s}</em>{t-1}, \mathbf{x}_t ; \theta) $$</p>` but shows up OK. 

Everything that is using the shortcut is parsed fine. I cant use the shortcut notation as its extremely verbose for a page with full of math as compared to delimiters such as $$. 

![Screen Shot 2020-02-06 at 3 56 22 PM](https://user-images.githubusercontent.com/508740/73981612-8f3a1f00-4900-11ea-9e75-9dd5af28ec64.png)

So the question is what the shortcut is doing that the inject body.html code above doesnt. Also is there any way that we accommodate the $$ $$ delimiters in the shortcut as they are valid katex options. 

Thank you

**Comment by alex-shpak** [comment]
Well, `_text_` a is markdown form for emphasis. And content of `{{ katex }}` shortcode is not processed by markdown rendered, I think this is the difference.

Try to escape `_` with `\_`.

**Comment by alex-shpak** [comment]
For delimiters: The `katext` shorcode supports two modes: inline and display. Because of that inserting delimiters is delegated to the shortcode. It's possible to add logic to cut excess delimiters I guess, not sure that it worth it.

**Comment by pantelis** [comment]
Thank you - the escaping of the underscore works.
