### ISSUE TITLE
Markdown link does not persist columns

### ISSUE THREAD

**Issue by qeef** [alex-shpak/hugo-book#143]
The best is example. The following does not work:
```
{{< columns >}}
[link 1][l1]
<--->
[second link][l2]
{{< /columns >}}

[l1]: whatever-for-1
[l2]: whatever-for-2
```

**Comment by alex-shpak** [comment]
Hi!
Unfortunately this is how it works. Shortcode's markdown content rendered separatelyso it is not populating footnotes to page itself.

**Comment by qeef** [comment]
Ok, thanks for info.
