### ISSUE TITLE
Organizing the left side navigation without using the leaf bundle menu?

### ISSUE THREAD

**Issue by desertmonkey** [alex-shpak/hugo-book#146]
Hi, quick question about the Book theme. Is there a way to have a mix of files and subfolders within a given folder and have their order arranged by the weights of the files? Right now, if I have a mix of files and subfolders, the subfolders always appear at the top of the left side navigation. 

For example, my local file system looks like this:

```
├── content
    ├── folder1
        ├── _index.md (weight 440)
    ├── file1.md (weight 400)
    ├── file2.md (weight 430)
    ├── folder2
        ├── _index.md (weight 410)
```

I would expect/hope the TOC to look like this:

```
    ├── file1.md (weight 400)
    ├── folder2
        ├── _index.md (weight 410)
    ├── file2.md (weight 430)
    ├── folder1
        ├── _index.md (weight 440)
```

But in reality, it looks like this:

```
    ├── folder2
        ├── _index.md (weight 410)
    ├── folder1
        ├── _index.md (weight 440)
    ├── file1.md (weight 400)
    ├── file2.md (weight 430) (edited) 
```

We'd rather not use bundles, since they're very labor intensive. Thanks!

**Comment by alex-shpak** [comment]
HI!
It should work as you expect 🤔 

It used to render sections and then pages before `v4` check maybe you have older version of theme? (Note that there was breaking changes)

**Comment by desertmonkey** [comment]
Good to know it should work! We were using an older version and are upgrading now. But we've made some customizations so maybe we need to see what we tweaked. Would the changes have been made in the [menu-filetree.html](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html) file?

**Comment by alex-shpak** [comment]
Yes, [this  PR](https://github.com/alex-shpak/hugo-book/pull/70) changed it.
Tho, between v5 and v6 there was big amount of template changes, so watch your step :)

If you do not have too many changes I would suggest reapply them over `v6`. And in general to use special `inject` templates for customisation.

**Comment by desertmonkey** [comment]
OK, great thank you so much @alex-shpak! We are in the midst of updating, so we should be pulling in v6, but we cherry picked the content. But we'll see about refactoring using inject templates. Thanks for the tip! 

And if you're curious as to how we're using your template, check out our [doc site](https://docs.cumulusnetworks.com/cumulus-linux/) when you have a minute.

**Comment by alex-shpak** [comment]
Heh, looks nice! I would not recognise it 😄.
I'm afraid at that level of changes just `inject` templates would not make it.

Also worth noting:
I see you use hugo `0.55` https://github.com/CumulusNetworks/docs/blob/master/amplify.yml#L7
There was significant changes in markdown rendering at hugo `0.60` if you going to upgrade hugo as well.

Nice to see that theme is used!

**Comment by desertmonkey** [comment]
Thank you! It's still your work underneath! Our designer had his way with skinning it to fit into our overall site. 

We've got a branch with the latest Hugo 0.64 and are working out the kinks there. We're weaving in your updates as well there. Should be live in the next few days. Pity the inject templates won't work, but we dug our own grave here! :) 

Thanks again.

**Comment by alex-shpak** [comment]
Hi!
I'm doing a bit of cleanup, I will close this issue. If you need some assistance write here, I will reopen.
