### ISSUE TITLE
"mobile-header" breaking build

### ISSUE THREAD

**Issue by vgzr** [alex-shpak/hugo-book#147]
I'm not sure why, but every time I try to build my site, I get an error "error calling partial: partial "docs/mobile-header" not found ". It appears to be related to the below code-snippet from the Layouts > Events > _baseof.html_ file. I'm honestly not sure what its intended to be referencing, so I have no idea what to change it to to fix the problem... 

     <div class="book-posts">
      {{ partial "docs/mobile-header" . }}
      {{ template "main" . }}
      {{ partial "docs/inject/footer" . }}
    </div>
  </main>

I rolled back to v5, which worked at first, but now my build isn't working again...

Thanks for your help, and hard work! I really love this theme and hope I can get my build working again.

**Comment by alex-shpak** [comment]
Hi!
There were changes between `v5` and `v6` in `baseof` template (and some others). `mobile-header.html` is now renamed to ` header.html`

Check here: https://github.com/alex-shpak/hugo-book/blob/master/layouts/_default/baseof.html
New there are more templates for customization

**Comment by vgzr** [comment]
Thank you so much!
