### ISSUE TITLE
Collapsing options in menu file

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#149]
Thanks for this awesome theme, almost zero configuration and I can use it to create websites without hijacking any existing md files. Exactly what I've been looking for 🥳

I hardcode the menu in `menu/index.md` using `BookMenuBundle: /menu` setting.
I read that if I use the file structure I can use `bookCollapseSection`, is there anyway I can achieve the same behavior in the menu file?

**Comment by alex-shpak** [comment]
Hi! Thank you!

Yes, unfortunately I didn't find satisfactory way collapsing menu rendered from markdown file without adding JS. And I want as many as possible features in theme to work without JavaScript.
You can try some tricks with `<details></details>` in menu file, but it doesn't give good result for my taste.

I can suggest to switch to file-tree menu and manage pages with `weight` and `BookHidden`.

Related #51

**Comment by undergroundwires** [comment]
Thanks for the quick response. I went with the file-tree menu. In my opinion choosing to not have JS is the right decision when it comes to the trade-off, minimalism is what makes this theme unique and beauty 👌

**Comment by undergroundwires** [comment]
I'm closing the issue as the decision is made.
