### ISSUE TITLE
Use this without theme

### ISSUE THREAD

**Issue by pjebs** [alex-shpak/hugo-book#15]
Is there anyway to use this theme for a particular "section" only and have a different theme for the rest of the site?

It would be awesome if instructions were added to readme despite it being an unorthodox case.

**Comment by alex-shpak** [comment]
Hi!
Unfortunately there is no way in hugo to apply multiple themes.
Though, Book theme is designed to render `docs` and `posts` sections only, leaving user to render other pages, so your case sounds possible to do.

Hugo theme file structure is the same as in root of project. So if you copy one theme into `~/my-hugo-project` and another into `~/my-hugo-project/themes/name` it supposed to work, maybe with minor tweaks.

Steps would be something like this:
- Create new hugo project
- add **Theme-1** to `themes/theme-1` 
- copy `static`, `assets`, `layouts` from **Theme-2** into project root
- run site with **Theme-1**

In this case `Theme 2` will have higher priority in rendering
But then it will be up to you to manually update **Theme 2** sometimes

It's up to you to decide to use Book theme as **Theme 1** or **Theme 2*, depending on complexity of other theme.

I hope it makes sense or helps you.

P.S. I'm not sure that is good idea to put it into README, but it will be searchable from now.

**Comment by alex-shpak** [comment]
Feel free to reopen if you need some more assistance.
Closing for now.

**Comment by pjebs** [comment]
thanks
