### ISSUE TITLE
Dynamic switching of dark & default theme

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#151]
The dark theme looks awesome. I'm thinking of a checkbox switch that'll allow switching to that for longer readings and vice versa.

Would you consider having the possibility to switch between two themes on the fly? If that's not the case, would you recommend a way to customize the theme to be able to do it?

**Comment by alex-shpak** [comment]
Hi!
I will need to think on solution.

Now there is single `css` file generated based on variables. So there is only one of themes generated on build. Making it switchable will require few things:
1. Duplicate css into multiple files with light and dark mode.
2. Make some JS script to flip styles on load and save state in `localStorage`.

Alternatively duplicate styles and have extra class that applies dark theme at body level. That will increase size of css tho.
I will take some time to think about it.

**Comment by undergroundwires** [comment]
Duplicating the files and switching CSS would probably a bit slower with faster startup (less initial data). But I believe the data size difference or the speed would be too significant either away.

An inspiration is [here](https://github.com/zzossig/hugo-theme-zzo/blob/d7e012c02d8999c3bf6f4091800419ea797d866c/layouts/partials/head/scripts.html#L443. Live example (https://zzodocs.netlify.com/docs/gettingstarted/quickstart/)[here)] I see it flips the class at (body level)[https://github.com/zzossig/hugo-theme-zzo/blob/d7e012c02d8999c3bf6f4091800419ea797d866c/layouts/partials/head/scripts.html#L504]. 

One more nice to have thing is a callback for extensibility.  So `hugo-book` calls a JS function `onThemeChange(themeName)` if not null when the theme changes, so I can update other stuff such as comments section on the page with that callback.

**Comment by alex-shpak** [comment]
Hi there!
I thought about it, I would like to keep css as it is in theme for now, without switching on fly. It adds extra complexity which I want to avoid in maintaining this theme.

**Comment by Calinou** [comment]
We could use the [`@media (prefers-color-scheme: dark)` CSS media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to enable a dark theme automatically. The code can be made non-repetitive by using CSS custom properties.

**Comment by Dorson** [comment]
Coded a flexible solution for the Dark Mode. You are welcome to copy, port, adopt.

Try demo in here:
https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Works with basic CSS variables + short JavaScript functions.

Can be used inside existing CSS style file. Can be used to define multiple color themes in one CSS file as variable groups. No user logins or profiles required.

Will save our eyesight at night :-)

**Have fun using my code !**

**Comment by undergroundwires** [comment]
@Dorson I checked your solution and I see that it utilizes CSS properties . However hugo-book uses SCSS variables which makes overriding them harder after they are compiled.

An option is to refactor those SCSS variables into `:root` CSS properties to allow runtime switching, then we could easily implement dark theme switching and could use ` @media (prefers-color-scheme: dark)` as @Calinou mentioned.

I wonder what you think about swapping SCSS variables to custom properties @alex-shpak ? 

It'll allow theme users to:
- Implement a theme toggle easily (those who want JS)
- Implement `@media (prefers-color-scheme: dark)` (no JS) to respect browser/user preference

**Comment by Dorson** [comment]
> * @media screen and  (prefers-color-scheme: dark)

This is the more safe route, because it will only work on the mobile so far, that is where the brightness issue is the most irritating one.

If unsure, use light gray colors for that, if the user is in the bright environment with that setting on. The users who are able to activate the prefers-color-scheme: dark , are also the users who are reducing the brightness of their screen at night anyway.

I think those users prefer darker themes too. 

This stops being useful in the bright sunlight. Did try. Had to pump up the screen brightness, that is why the light gray / pastel colors might be a bit more universal for the dark mode users.


> SCSS VS pure CSS variables

The CSS variables are good for dynamic changes, without re-loads, logins, file loads, etc.

Alternatively people use different CSS files for different devices, color themes. This works well for ages, but it's not dynamic to the click actions.

The CSS variables are the way to go for dynamic changes on-click, or time event. Or when we want to avoid any server side processing.


> :root element class

It's actually the html tag, but with higher hierarchy. Also forces reset fallback if 
 activated with a class **:root.CSS-class** , it overwrites all the the lower hierarchy rules. The :root also makes the CSS variables accessible to all children elements. A bit like a global variable rule.

```
If we had the same variables **to be activated dynamically** for one of those:

root , html.dark-color-class , body.color-class , :root.reset-color-class

the :root.reset-color-class has higher hierarchy in this case, **if there is a dynamic change** and re-painting of the DOM, without page reload. That is why we like to define the re-set defaults in there, in case all else fails. the :root element is good for the reset option to the default variable values.
```

**Comment by ikingye** [comment]
Looking forward to this *FEATURE*.

**Comment by alex-shpak** [comment]
So after some though.
I mostly use `sass` for nesting css rules, I really like that. Probably we can use sass and css vars. They are now have okay browser coverage. But then it must be either all variables in css or in sass. Not mix of them!

I seems to me `@media` query is okay solution. Plus optional theme param to turn on and off automatic switch.
There are few places where sass color functions are used, that will need to be refactored, otherwise I think it is not hard to change to css vars.

well, there is always way to add `custom.scss` styles and `@media` query and just override styles on specific elements to be dark. But I think that will be messy.

**Comment by alex-shpak** [comment]
Well, it has landed for testing.
New param `BookTheme: auto|dark|light`

Other vars will need to be also moved to CSS vars.

**Comment by ikingye** [comment]
Maybe, it will be nice if you can add a dark-mode-checkbox.

like this: https://golang.design/under-the-hood/

implement on:
https://github.com/golang-design/under-the-hood/blob/320971abd63c787b5934eb56a77c31f89947464d/website/themes/book/layouts/partials/zh-cn/search.html
https://github.com/golang-design/under-the-hood/blob/003bcae865542fe6569c4b9b8d8d64eae7f09d40/website/themes/book/static/dark.js

**Comment by halfrost** [comment]
@ikingye I also implement this toggle, https://books.halfrost.com/leetcode/

![](https://user-images.githubusercontent.com/10825609/93083279-f43eca00-f6c4-11ea-875a-96c4fdb8ad3a.png)

**Comment by alex-shpak** [comment]
Hi!
I want to avoid adding extra JS for this feature, so I would leave switch implementation to site owners.

**Comment by bphenriques** [comment]
> Well, it has landed for testing.
> New param `BookTheme: auto|dark|light`
> 
> Other vars will need to be also moved to CSS vars.

With this migration, how can I override the variables? I am attempting to override either through `_variables.scss` or `_custom.scss` but not succeding:
```
body {
    --body-background: #38474f;
    --color-link: #84b2ff;
    --color-visited-link: #84b2ff;
}
```

**Comment by alex-shpak** [comment]
Hi!
Example that you pasted shoudl work.
Put that content in `assets/_custom.scss`

**Comment by bphenriques** [comment]
> Hi!
> Example that you pasted should work.
> Put that content in `assets/_custom.scss`

It does! Thank you for that and for the theme!

**Comment by michaeltlombardi** [comment]
@alex-shpak assuming I'm able to get a (relatively) simple implementation working, would it be acceptable to submit a PR with docs on how to extend `hugo-book` for toggleable light/dark mode (i.e. not incorporate that functionality to this project, just be able to point people at a doc page for resolving this so you can close this issue and just point to that)?

**Comment by alex-shpak** [comment]
Not a problem :) also people should be able to find this thread in search engines.

**Comment by jpritikin** [comment]
I'm confused. I tried `BookTheme = 'light'` but the site still renders as dark on my mobile phone. I'm using hugo-book 4ef38f3bbf5d

**Comment by jpritikin** [comment]
> I'm confused. I tried BookTheme = 'light' but the site still renders as dark on my mobile phone.

I didn't have hugo-extended installed so the SCSS was not getting regenerated. Solved now.

**Comment by MaximilianKohler** [comment]
How do I get a button like [this](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)? I did this https://github.com/alex-shpak/hugo-book/issues/151#issuecomment-698603280 but it only changed the dark color.

**Comment by alex-shpak** [comment]
Hi!
There s only very simple included with theme. There is no UI css framework or something similar in theme to keep everything light.
So you might need to add one for more complex buttons.

**Comment by RoySRC** [comment]
If anyone's still looking, I'm using this to toggle theme:
```js
function __switchTheme() {
    const root = document.documentElement;
    const isDark = getComputedStyle(root).getPropertyValue('--body-background').trim() === '#343a40';

    if (isDark) {
        // Switch to light theme
        root.style.setProperty('--gray-100', '#f8f9fa');
        root.style.setProperty('--gray-200', '#e9ecef');
        root.style.setProperty('--gray-500', '#adb5bd');
        root.style.setProperty('--color-link', '#0055bb');
        root.style.setProperty('--color-visited-link', '#8440f1');
        root.style.setProperty('--body-background', 'white');
        root.style.setProperty('--body-font-color', 'black');
        root.style.setProperty('--icon-filter', 'none');
        localStorage.setItem('theme', 'light');
    } else {
        // Switch back to dark theme
        root.style.setProperty('--gray-100', 'rgba(255, 255, 255, 0.1)');
        root.style.setProperty('--gray-200', 'rgba(255, 255, 255, 0.2)');
        root.style.setProperty('--gray-500', 'rgba(255, 255, 255, 0.5)');
        root.style.setProperty('--color-link', '#84b2ff');
        root.style.setProperty('--color-visited-link', '#b88dff');
        root.style.setProperty('--body-background', '#343a40');
        root.style.setProperty('--body-font-color', '#e9ecef');
        root.style.setProperty('--icon-filter', 'brightness(0) invert(1)');
        localStorage.setItem('theme', 'dark');
    }
}

// Apply the theme from local storage on document load
document.addEventListener('DOMContentLoaded', () => {
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme) {
        const root = document.documentElement;
        if (savedTheme === 'light') {
            root.style.setProperty('--gray-100', '#f8f9fa');
            root.style.setProperty('--gray-200', '#e9ecef');
            root.style.setProperty('--gray-500', '#adb5bd');
            root.style.setProperty('--color-link', '#0055bb');
            root.style.setProperty('--color-visited-link', '#8440f1');
            root.style.setProperty('--body-background', 'white');
            root.style.setProperty('--body-font-color', 'black');
            root.style.setProperty('--icon-filter', 'none');
        } else if (savedTheme === 'dark') {
            root.style.setProperty('--gray-100', 'rgba(255, 255, 255, 0.1)');
            root.style.setProperty('--gray-200', 'rgba(255, 255, 255, 0.2)');
            root.style.setProperty('--gray-500', 'rgba(255, 255, 255, 0.5)');
            root.style.setProperty('--color-link', '#84b2ff');
            root.style.setProperty('--color-visited-link', '#b88dff');
            root.style.setProperty('--body-background', '#343a40');
            root.style.setProperty('--body-font-color', '#e9ecef');
            root.style.setProperty('--icon-filter', 'brightness(0) invert(1)');
        }
    }
});
```
