### ISSUE TITLE
Tabs do not work inside columns

### ISSUE THREAD

**Issue by ashleyvega** [alex-shpak/hugo-book#153]
Tabs do not work when inside columns. Specifically, no tab body appears for any tab. The tab titles are visible, and it's possible to switch between tabs, but with no effect.

## Example document
```markdown
---
weight: 99
title: This is a layout test doc
---

# Doc Title

{{< columns >}}
This is content for col 1
<--->
This is content for col 2 - tabs inside a column:
{{< tabs "noneworkingtabs" >}}
{{< tab "Thing1" >}}This information on Thing1 does not appear.{{< /tab >}}
{{< tab "Thing2" >}}This information on Thing2 does not appear.{{< /tab >}}
{{< /tabs >}}
More content for col 2
{{< /columns >}}

Back to one wide col. Here are some tabs outside columns which work fine:

{{< tabs "workingtabs" >}}
{{< tab "Thing3" >}}This information on Thing3 is fine.{{< /tab >}}
{{< tab "Thing4" >}}This information on Thing4 is fine.{{< /tab >}}
{{< /tabs >}}

end of doc
```

## Versions used for testing
* hugo `v0.65.3-211BA42A linux/amd64 BuildDate: 2020-02-23T09:59:37Z`
* hugo-book `v6-17-g5d7f257` from 2020-02-23

**Comment by alex-shpak** [comment]
Hi! Thanks for report!
I pushed fix to `master`, there were some extra spaces generated in `tabs` html

**Comment by ashleyvega** [comment]
@alex-shpak Many thanks for the super-fast fix :+1:
