### ISSUE TITLE
Collapsing the menu on mobile is too hard

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#154]
![image](https://user-images.githubusercontent.com/15555035/75374202-1b21e400-58cc-11ea-9c07-10cfcca197cc.png)

**Comment by alex-shpak** [comment]
Hi!
I added transparent overlay over content that would hide menu on click.

**Comment by alex-shpak** [comment]
Hi again!
Did it work for you? :)

**Comment by undergroundwires** [comment]
Thanks @alex-shpak, it works pretty good. I tested on Firefox + Chrome on Windows & Linux & Android. It looked as expected everywhere except android Firefox, there I got a gray overlay while touching, it disappears after I stop touching (when the menu disappears). Maybe `outline: none;` is needed. I can test it with that property later on and come back. For now I'm closing the issue. Thanks again!
