### ISSUE TITLE
Indicators for sections in file tree menu

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#155]
I believe it's a big UX improvement that increases the usability as one could easily get a quick picture of the depth of the content.

It'd be achieved with three states: section (1), page (2) and a collapsed section (3). Here's an example from [haxe](https://haxe.org/manual/introduction-about-this-document.html)

![image](https://user-images.githubusercontent.com/15555035/75299638-dcd9e580-5835-11ea-92f6-1dfe378fe141.png)

Or even more minimal example from Microsoft Docs:

![image](https://user-images.githubusercontent.com/15555035/75303200-4ced6900-5840-11ea-9acc-7383c8c91200.png)

It surely wouldn't look as clean as it is now but it's a trade-off I'd make for the reading experience.

You think it should be an optional feature of `hugo-book`? Or how would you recommend extending the theme to achieve that?

**Comment by alex-shpak** [comment]
Hi again!
I had some thought about icon when I was working on collapsable menu. And at that time I decided to keep it as it is for theme slogan: "As simple as plain book"

I feel like icons on left might be an overkill, but indicator that section can be expanded might be good. Maybe a dot or triangle on right side of menu 🤔

**Comment by alex-shpak** [comment]
![image](https://user-images.githubusercontent.com/5515443/75492487-2a7e5b80-59b8-11ea-961c-141ff83d4f2f.png)
Like that perhaps

**Comment by undergroundwires** [comment]
@alex-shpak thanks for maintaining and supporting this and considering having this feature natively in the theme.

I loved the simplicity of the theme and I believe many do and that's why are here :) Picture you've shown is the most simplistic implementation that looks perfectly clear without any bloat.

I'd love to see  ➡️ (state 3) when a section is collapsed (`bookCollapseSection: true`) but has more than single page content in it. It enhances the reading experience with more information about the content at the first sight.

⬇️ (state 1) is nice to have as indenting already makes it clear that the menu items are under that section, however it'd probably go along pretty good with ➡️ cosmetically.

**Comment by alex-shpak** [comment]
I added state 3 indicator on collapsed sections. It hard to track parent section to change icon because menu is generated statically, so no state 1. But I think its okay enough. 🤷‍♂
![image](https://user-images.githubusercontent.com/5515443/75614496-9b00b600-5b39-11ea-8cf9-9a9a3852d013.png)

**Comment by undergroundwires** [comment]
I also think it's OK enough 👍🏿 Really huge thanks for it! I loved how clean the commit is 😲, I've been expecting much more lines :)

I just tested it and it showed the bullet on every single menu item in `file-tree` 😞, but then I realized that I have been brute-forcing `bookCollapseSection` on every single page. I now only set it on pages that includes pages and it looks pretty neat 👌

Thanks again and very cool that you decided to have it natively 💗

Closing the issue now.

**Comment by undergroundwires** [comment]
I know that now it's about different tastes, but when I compared on the right vs on the left I personally thought it looks better on the left as they are aligned. It gives a little bit chaotic look when they're not symmetrical. It may vary from person to person but I'd prefer to have them on the left. I did it now with some css override. You decide what to keep as default.

Here's a picture of the site I'm building for comparison:

![image](https://user-images.githubusercontent.com/15555035/75616085-c3de7680-5b4c-11ea-85d7-7887b5600ff0.png)

**Comment by alex-shpak** [comment]
Yeah, it might need tweaking. It kinda depends on how many collapsed items you have, in your case there are a lot so it looks better on left. Maybe on right image icons should be aligned and pushed to right edge.
Or they should be outside of menu block to not break text alignment
This is what I want to avoid
```
Menu item 1
▸  Menu Item 2
Menu item 3
```

So maybe it should be like
```
   Menu item 1
▸  Menu Item 2
   Menu item 3
```

**Comment by alex-shpak** [comment]
> I just tested it and it showed the bullet on every single menu item in file-tree 😞

I pushed change to skip collapsed icon for leaf pages (even if `bookCollapseSection` is set for regular page) to address that.

**Comment by undergroundwires** [comment]
> I pushed change to skip collapsed icon for leaf pages (even if `bookCollapseSection` is set for regular page) to address that.

Cool! 

Sass uses the bullet on right and aligns them as well. It think it's also a good option: https://sass-lang.com/documentation/syntax

> So maybe it should be like: (good alignment)

I put pulled left each bulleted item, and then moved menu to the right with same margin to achieve it:

⚠️ I'm a shit CSS-writer. Codes below are probably ugly hacks.

```scss
.book-menu {
    $arrow-margin: 1rem;
    // Mark with "▸"
    a {
        &.collapsed {
            &::before {
                content: "▸";
                margin-left: -$arrow-margin;
                margin-right:0.3rem;
            }
            // Override the default
            &::after { content: ""; margin-left: 0; }
        }
    }
    // Fix alignment
    ul {
        margin-left:  $arrow-margin;
        ul {
            margin-left:0; // Only affect parrent
        }
```

I also played with some SCSS to be able to write a query like: `If I'm a menu item with "active" class on, find all UL's above me, then for each parent UL, check its first child with ".collapsed" class and then overwrite "▸" with "▾"`. I wasn't succesful enough to achieve state 1 with only css but I got it working with JS + CSS:

```scss
    .open-section {
        &::before {
            content: "▾" !important;
        }
    }
```

```js
    window.onload = markOpenSections;
    function markOpenSections() {
        const styleName = 'open-section';
        const activeElement = document.getElementsByClassName('active','collapsed')[0];
        styleParents(activeElement);

        function styleParents(element) {
            const isOpen = element.classList.contains('collapsed');
            if(isOpen) {
                element.classList.add(styleName);
            }
            const closestList = element.closest('ul');
            if(!closestList) {
                return;
            }
            const nextMenu = closestList.parentElement;
            if(!nextMenu) {
                return;
            }
            const nextItem = nextMenu.children[0];
            if(!nextItem) {
                return;
            }
            styleParents(nextItem);
        }
    };
```
