### ISSUE TITLE
Scrollbar for table of contents is in middle of the page

### ISSUE THREAD

**Issue by ivywong** [alex-shpak/hugo-book#156]
This might be an edge case, but when I have a really long page with many headings, the table of contents will look kind of ugly because the scrollbar is in the middle of the screen, not the edge. Is it possible (or even a good idea) to change the TOC to expand to the edge, maybe by increasing padding? I don't want the text to run all the way to the right edge, just the scrollbar.

Or should I just attempt the browser hacks as mentioned in #83?

![Screenshot_20200226_001715](https://user-images.githubusercontent.com/2830112/75325496-cb8cdb00-582d-11ea-8a63-755813b7dd8e.png)

**Comment by alex-shpak** [comment]
Hi!
Indeed this is not looking great, I didn't find elegant solution for that.
Even if we move scrollbar to right - it would be double scrollbar on page.

You can try `scrollbars` plugin: https://github.com/alex-shpak/hugo-book#plugins
This will override scrollbar styles for `webkit` and `firefox` browsers and will make it visible only on hover.

**Comment by alex-shpak** [comment]
Unfortunately in current state of scrollbar customization is not much I can do. I will close this issue, and will keep scrollbars in mind if opportunity appears.
