### ISSUE TITLE
can we use utterances as book-comments?

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#158]
https://utteranc.es/

**Comment by alex-shpak** [comment]
Hi! Yes, you will need to overwrite one template.
In your site (not in theme folder) create `layouts/partials/docs/comments.html` and put utteranc code there.

**Comment by ikingye** [comment]
> Hi! Yes, you will need to overwrite one template.
> In your site (not in theme folder) create `layouts/partials/docs/comments.html` and put utteranc code there.

LGTM. 

can I create layouts/partials/docs/header.html (or footer.html)
and put [github-corner](https://github.com/tholman/github-corners) in it ?

**Comment by alex-shpak** [comment]
I think `https://github.com/alex-shpak/hugo-book#partials` would be good place for it.
https://github.com/alex-shpak/hugo-book#partials

**Comment by ikingye** [comment]
> I think `layouts/partials/docs/inject/body.html` would be good place for it.
> https://github.com/alex-shpak/hugo-book#partials

work like a charm, thanks.

**Comment by alex-shpak** [comment]
Great! I will close then. 👍
