### ISSUE TITLE
Ability to more clearly show "Last modified by" 

### ISSUE THREAD

**Issue by VilhelmPrytz** [alex-shpak/hugo-book#161]
![Footer](https://user-images.githubusercontent.com/15460993/75616490-f63ea280-5b51-11ea-87cc-1167397b8167.png)

I might be missing something here, but the only way I can find who was the last person to edit a specific page (i.e. with the `enableGitInfo` enabled) is to hover over the date ("February 29, 2020" in the picture above). Is there any way to configure the theme to more visibly display who edited the page, and if not, is this something that could be implemented?

Cheers

**Comment by alex-shpak** [comment]
Well, I didn't put it into link to save some space in mobile view.
Simple trick would be to inject extra line into footer with `layouts/docs/inject/footer.html` and 
```
{{ with .GitInfo }}
<div class="flex justify-end">
  {{ i18n "Last modified by" }} {{ .AuthorName }}
</div>
{{ end }}
```

![image](https://user-images.githubusercontent.com/5515443/75616909-9cd97200-5b57-11ea-8f78-3f179ffc8cf0.png)
Tho looks a bit ugly for my taste 🤔 

I'm open for changing it if we can find some clean way.

**Comment by VilhelmPrytz** [comment]
Hmm, I created the file `layouts/docs/inject/footer.html` in my project but the "Last modified" does not show up? Is there anything else I have to add?

**Comment by VilhelmPrytz** [comment]
Oh, I got it. I had to create the file as `layouts/partials/docs/inject/footer.html` and not `layouts/docs/inject/footer.html`. I agree that it looks a little bit of, perhaps a little bit smaller and/or italic? (just suggestions)

**Comment by alex-shpak** [comment]
Ah, my bad, I wrote path wrong. You can apply styles you want directly in partial or in `assets/_custom.scss`. I don't have vision right now how to fit it nicely 🤔

**Comment by alex-shpak** [comment]
Hi!
I gave it some thought, I would like to keep date as it is I think, it is small and simple now. So you will have to customize it for your needs, unfortunately.
