### ISSUE TITLE
Subpath of baseURL should not exist in link of markdown

### ISSUE THREAD

**Issue by luckywinds** [alex-shpak/hugo-book#166]
eg：`baseURL: http://x.x.x.x/me`

image：`![alt](/me/images/hello_world.png)`

but, should：`![alt](/images/hello_world.png)`

no `/me`.

**Comment by alex-shpak** [comment]
Hi!
Well, this is how markdown works, theme does not decide this behavior.
Basically markdown rendered doesn't transform URL and puts it into `<img src...>` as is.

The most compatible way would be to use URLs relative to page if you keep image near page, or use absolute path if you keep images in `/static`. This will help code editors to render pictures correctly.

**Comment by alex-shpak** [comment]
https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks
Related, might be useful

**Comment by luckywinds** [comment]
done，3q

**Comment by try-agaaain** [comment]
How to position image links correctly?
I have a directory of files like this:
.
├── _index.md
└── docs
         ├── _index.md
         ├── about.md
         └── images
                 └── test_image.png
And the image `test_image.png` was used in `about.md` through `![image](./images/test_image.png)`, but hugo did not correctly obtain the position of the image. It positioned the image position as:
http://127.0.0.1:1313/docs/about/images/test_image.png
And the actual position of the image is:
http://127.0.0.1:1313/docs/images/test_image.png

I can use `![image](../images/test_image.png)` to let hugo get the correct image position, but in this case the image cannot be displayed normally when I edit it locally. Is there any way to make `![image Does ](./images/test_image.png)` take effect?

**Comment by try-agaaain** [comment]
I found that the method for generating image links is set in `layouts/_default/_markup/render-image.html`, so I manually adjusted the original image link:

```html
<img src="{{ .Destination | safeURL }}" alt="{{ .Text }}" {{ with .Title }}title="{{ . }}"{{ end }}/>
```
to:
```html
<img src="../{{ .Destination | safeURL }}" alt="{{ .Text }}" {{ with .Title }}title="{{ . }}"{{ end }}/>
```

This indeed solved the issue for me, but I'm not sure if this is the correct way to make the modification.
