### ISSUE TITLE
Katex $ shortcut

### ISSUE THREAD

**Issue by dsevero** [alex-shpak/hugo-book#168]
I noticed that 

```
$$
<latex code>
$$
```

works fine in hugo book, but inline `$ <latex code> $` does not. Is there any way to enable this?

**Comment by alex-shpak** [comment]
Hi!
KaTex uses default set of symbols: https://katex.org/docs/autorender.html
Which are
```
[
  {left: "$$", right: "$$", display: true},
  {left: "\\(", right: "\\)", display: false},
  {left: "\\[", right: "\\]", display: true}
]
```

I'm not big math typesetting user so I decided to keep default settings.

**Comment by alex-shpak** [comment]
I hope that answered your question. Poke me here if you want this issue re-opened.

**Comment by dsevero** [comment]
It did. Thanks.
