### ISSUE TITLE
Nesting `tabs` shortcodes doesn't work

### ISSUE THREAD

**Issue by julienduchesne** [alex-shpak/hugo-book#169]
The top-level selector works but the lower ones don't

After investigating, it seems like markdownify puts the `<input>` into a `<p>` block. Therefore, the input is not right beside the content `<div>` anymore.

It would be nice to allow two levels of selectors. For some advanced use cases with lots of options, it gets messy

**Comment by alex-shpak** [comment]
Hi!
Thank you for PR, I didn't have time yet to check it more deeply, but my bling guess would be that some whitespaces/newlines are involved. So it might be solved by adding `{{-` `-}}` around and in tabs.

I will take a look.

**Comment by alex-shpak** [comment]
For example similar case:
https://github.com/alex-shpak/hugo-book/issues/153
https://github.com/alex-shpak/hugo-book/commit/08519158f49bb97c6f758cf8886e25b7f9aec433#diff-5dc43ccec39279a468a19cb397b020b8L6-R14

**Comment by julienduchesne** [comment]
Hhmm, the example I added in my PR works regardless of my fix so it's not very convenient to test your theory :stuck_out_tongue: . I'll go over my documentation page and try to find the real issue and I'll update or close this. 

Thanks for checking!

**Comment by julienduchesne** [comment]
I actually changed the content of my tabs since I last opened my PR and I'm not able to reproduce it anymore :man_shrugging:. I'll open a new issue if I find an actual bug.

Great theme btw, I use it everywhere :+1: :heart:

**Comment by alex-shpak** [comment]
> Great theme btw, I use it everywhere 👍 ❤️
Thank you!

I quite sure it is whitespaces 😄 Having extra whitespaces makes markdown to generate `<p>` tags, which breaks CSS
