### ISSUE TITLE
Documentation on posts/ directory

### ISSUE THREAD

**Issue by jallbrit** [alex-shpak/hugo-book#17]
it is not clear in the documentation that the posts/ directory must be named as such (as opposed to post/). This was not apparent when installing and led to multiple errors.

**Comment by alex-shpak** [comment]
On another hand documentation states `posts` as example
https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages

🤔

**Comment by alex-shpak** [comment]
After checking around other themes, I found both `posts` and `post` layouts,
I would keep `posts` for now for backward compatibility and will add note to README as you suggested.

**Comment by jallbrit** [comment]
Awesome, thank you!
