### ISSUE TITLE
[Feature] Breadcrumbs

### ISSUE THREAD

**Issue by julienduchesne** [alex-shpak/hugo-book#170]
I have a lot of nested pages in my doc and I think it would benefit from having breadcrumbs. A bit like what's in bootstrap: https://getbootstrap.com/docs/4.0/components/breadcrumb/

Is that something you would be open to?

If so, I can get working on a PR

Let me know what you think!

**Comment by alex-shpak** [comment]
Hi!
I considered to add breadcumbs, but didn't find good place or visual for them.

Simple hack:
`partials/docs/inject/content-before.html`
```
<div class="markdown">
  {{- template "crumb" .Page -}}
</div>

{{ define "crumb" }}
  {{- with .Parent }}
    {{- template "crumb" . }} / 
  {{- end }}
  <a href="{{ .RelPermalink }}">{{ partial "docs/title" . }}</a>
{{ end }}
```

Will give you
![image](https://user-images.githubusercontent.com/5515443/76143188-937b6880-6075-11ea-98c5-153a31aed879.png)

**Comment by alex-shpak** [comment]
Not sure if it should be on theme core 🤔

**Comment by julienduchesne** [comment]
Works for me either way. Thanks a lot for the `content-before` snippet. I modified it a bit to not show up in the first page and also to not show flat sections:
```
{{- if .Parent }}
    <div class="markdown">
        {{- template "crumb" .Page -}}
    </div>
{{- end }}

{{ define "crumb" }}
    {{- if .Parent }}
        {{- template "crumb" .Parent }}
        {{- if not .Params.BookFlatSection -}}&nbsp;/&nbsp;{{- end -}}
    {{- end }}
    {{- if not .Params.BookFlatSection -}}
        <a href="{{ .RelPermalink }}">{{ partial "docs/title" . }}</a>
    {{- end -}}
{{ end }}
```

**Comment by alex-shpak** [comment]
If breadcrumbs would go to theme core these things have to be thought through. Some people might prefer to show flat sections 🤔 

Maybe it's better to check `{{- if not .Content -}}&nbsp;/&nbsp;{{- end -}}` to skip crumb if page is empty.

**Comment by julienduchesne** [comment]
Yes, you're right. I noticed that after I posted it, I edited it

**Comment by alex-shpak** [comment]
I will close this issue. I didn't find place where to put breadcrumbs.
