### ISSUE TITLE
[Feature] Different page title and navigation title

### ISSUE THREAD

**Issue by julienduchesne** [alex-shpak/hugo-book#171]
Currently, the page title is the one used in the navigation and in the search. However, I have multiple leaf pages with the same name.

For example, my page names are `us-east-1` because that's what I want to show up in the sidebar. If I use the searchbar, all results are named `us-east-1`. The page titles are `us-east-1` as well. I would really like to be able to specify a search result name and a page title different from the sidebar title

**Comment by alex-shpak** [comment]
Hi!
There is `.LinkTitle` page param, maybe we can make use of it 🤔 
https://gohugo.io/variables/page/

**Comment by alex-shpak** [comment]
Hi! will something like this solve your problem?
https://github.com/alex-shpak/hugo-book/issues/236#issuecomment-654264245

Displaying parent section name in search results.
