### ISSUE TITLE
Ability to go back to home on 404

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#172]
Do you think it might be a good idea to have an option to go back to home on 404 so that the user can reach the content easily without playing with the address bar of the web browser?

Now we see only `404 Not Found`

Can we maybe
1. render `brand.html` that redirects us back to home ? 
2. or just a simple go to home button?
3. or clickable URL of the webpage?
4. if none at all, can we have an injectable after 404 error text so we can add what we want optionally?

I always see overriding the theme as last option and would like to see what you think about having a native feature.

Cheers & thumps up for the awesome work.

**Comment by alex-shpak** [comment]
Yep, I think `404.html` template needs some love, I didn't touch it since the beginning.
Probably to add site title and link to home page.

**Comment by alex-shpak** [comment]
Closed via #178
