### ISSUE TITLE
Prioritize .Description frontmatter on description meta

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#176]
`description` meta renders the page title. It sounds like a fallback but it should render `description` frontmatter data first.

Prioritization suggestion: (inspired from how [hugo](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html) does it):

`.Description > .Summary > .Site.Params.description > partial "docs/title" .`

**Comment by alex-shpak** [comment]
Closed via #177
