### ISSUE TITLE
Make tags more visible in search results

### ISSUE THREAD

**Issue by yeniklas** [alex-shpak/hugo-book#179]
In the current search results there is no way to tell if a result is a tag or a page.

It would be nice if it could be visualized somehow that results are referring to tags, maybe with a gray suffix telling us what kind of resource the result is pointing to.

This becomes a problem especially if you have tags and pages with the same name.

**Comment by alex-shpak** [comment]
Hi!
Perhaps taxonomy pages should not be visible at all in search. They went to search index unintentionally.

**Comment by yeniklas** [comment]
Well I'm fine with that solution as well, I'll try it out.

**Comment by alex-shpak** [comment]
Closing then 👍
