### ISSUE TITLE
Fonts not found?

### ISSUE THREAD

**Issue by alecsatin** [alex-shpak/hugo-book#18]
Am trying out the theme on linux/firefox and am having a font issue.  Is there anyway to make sure that Oxygen is used?  Or is there any way to specify a different font?

Sorry if this is too simple to fix.  Any help appreciated.  

Otherwise the theme seems excellent.

**Comment by alex-shpak** [comment]
HI!
I checked in Firefox 63.0.1 on MacOS, Oxygen font is rendered. Though, I see some difference in how Chrome and Firefox rendering bold text.

Maybe you can share screenshot and console output from your website, for easier debugging?

**Comment by alecsatin** [comment]
After testing this afternoon, it seemed like the problem was on my development machine.  All seems to be working now, and this can be closed.
Will continue working with the book theme, and hope to get a site up with it soon.  Thank you for your prompt reply, and wish you well.
