### ISSUE TITLE
Adding Font Awesome

### ISSUE THREAD

**Issue by niklas-fischer** [alex-shpak/hugo-book#180]
Since I have not found anything in the previous issues: Is there a chance that you add Font Awesome for integrating icos?

**Comment by alex-shpak** [comment]
Hi!
I try to keep theme slim, so I would suggest you to add icons via `assets/_custom.scss` in your site.

**Comment by niklas-fischer** [comment]
Hi!
All right, thanks for your effort!

**Comment by orsinium** [comment]
For posterity: create `layouts/partials/docs/inject/head.html`:

```html
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
  integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
```
