### ISSUE TITLE
Align the post overview with the posts

### ISSUE THREAD

**Issue by niklas-fischer** [alex-shpak/hugo-book#181]
Is there a way that the formatting of the blog under 'posts' is formatted the same as when you open one of the posts?

This is the overview:
![Overview](https://user-images.githubusercontent.com/62063364/76422091-f1c18780-63a4-11ea-9109-a1736959a915.png)

This is inside of a post:
![Inside Post](https://user-images.githubusercontent.com/62063364/76422145-0867de80-63a5-11ea-8f1a-d561f8e27acf.png)

Can you adjust this?

Kind regards

**Comment by alex-shpak** [comment]
Hi!
Well, I intentionally made them differ. Thinking is that single page has `h1` as heading/title but in list of posts they has `h2`, implying that title of list page itself should be `h1`, it is just hidden.

And I think having so many `h1` heading didn't looks great 🤔
You think it's better for list of posts to have `h1`?

**Comment by niklas-fischer** [comment]
Hi!
Yes, I think it is a good idea to set everything to `h1`. It's simpler and looks identical everywhere :)

But what bothers me more is the different formatting in terms of links and lists. 
In the overview these are not shown at all, only if you click directly into the post. Also, the text in the overview is written directly after each other, which doesn't look nice either. 

I sort of have this image in my head for the overview:

![bild](https://user-images.githubusercontent.com/62063364/76513295-61437f80-6456-11ea-9ed0-6e43540f7b59.jpg)

**Comment by alex-shpak** [comment]
Unfortunately summary works like that. It is plain text by default. you can set `<!--more-->` comment in document to set where to cut markdown in document.

See:
https://discourse.gohugo.io/t/markdown-content-renders-as-regular-text-in-summary/1396
https://gohugo.io/content-management/summaries/

**Comment by alex-shpak** [comment]
I set titles to `h1` for posts list. I actually don't like the result. I think title is too big.
![image](https://user-images.githubusercontent.com/5515443/76647886-eebdc700-655d-11ea-971e-65b49a8a8b24.png)

**Comment by niklas-fischer** [comment]
> 
> 
> Unfortunately summary works like that. It is plain text by default. you can set `<!--more-->` comment in document to set where to cut markdown in document.
> 
> See:
> https://discourse.gohugo.io/t/markdown-content-renders-as-regular-text-in-summary/1396
> https://gohugo.io/content-management/summaries/

I tried `<!--more-->` , that's amazing! Thank you! :D Solves my problem. 
I see what you mean with `h1`. Just letting it at the old setting is also good :)

**Comment by alex-shpak** [comment]
Great, I think I will keep post titles as it is :) 
I will close issue, poke me here if you want it reopened.
