### ISSUE TITLE
How to add extra menu item without creating markdown file in File tree menu mode?

### ISSUE THREAD

**Issue by Zeqiang-Lai** [alex-shpak/hugo-book#182]
<img width="1066" alt="截屏2020-03-20下午8 17 23" src="https://user-images.githubusercontent.com/26198430/77162949-1249ba00-6ae8-11ea-9e46-a4a4905a2f0c.png">

how to add menu items like Blog, Github and Hugo themes in the screenshot above?

**Comment by alex-shpak** [comment]
Hi!
These links are coming from hugo menus.
https://gohugo.io/content-management/menus/

See it in `exampleSite`
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yaml#L37
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/posts/_index.md

**Comment by Zeqiang-Lai** [comment]
Solved, Thanks!
