### ISSUE TITLE
Theme demo broken in v0.68.1

### ISSUE THREAD

**Issue by onedrawingperday** [alex-shpak/hugo-book#183]
Hello @alex-shpak 

Your theme's demo is broken in v0.68.1 because you generated the theme resources with the recent Hugo versions that featured a commit that was reverted.

You need to regenerate and re-commit your theme's resources with v0.68.1

The demo will be fixed in the next scheduled update of the repository.

Once you update the resources feel free to close this issue.

If you want to read the background of this issue see: https://github.com/gohugoio/hugoThemes/issues/822

**Comment by alex-shpak** [comment]
Resources are regenerated, thanks for heads up!
