### ISSUE TITLE
I use new site but have runtime error.

### ISSUE THREAD

**Issue by wizarot** [alex-shpak/hugo-book#185]
Hugo Static Site Generator v0.64.1/extended darwin/amd64 BuildDate: unknown
hugo-book v7

I try to create a new site. 

→ hugo server  --theme book

Building sites … ERROR 2020/03/28 17:56:33 render of "page" failed: execute of template failed: template: posts/single.html:6:5: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/will/go_productions/src/hugo_books/themes/book/layouts/partials/docs/post-meta.html:7:21": execute of template failed: template: partials/docs/post-meta.html:7:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
ERROR 2020/03/28 17:56:33 render of "section" failed: execute of template failed: template: posts/list.html:8:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/will/go_productions/src/hugo_books/themes/book/layouts/partials/docs/post-meta.html:7:21": execute of template failed: template: partials/docs/post-meta.html:7:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
ERROR 2020/03/28 17:56:33 render of "page" failed: execute of template failed: template: posts/single.html:6:5: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/will/go_productions/src/hugo_books/themes/book/layouts/partials/docs/post-meta.html:7:21": execute of template failed: template: partials/docs/post-meta.html:7:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
ERROR 2020/03/28 17:56:33 render of "taxonomy" failed: execute of template failed: template: taxonomy/taxonomy.html:8:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/will/go_productions/src/hugo_books/themes/book/layouts/partials/docs/post-meta.html:7:21": execute of template failed: template: partials/docs/post-meta.html:7:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
Built in 357 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:6:5: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/will/go_productions/src/hugo_books/themes/book/layouts/partials/docs/post-meta.html:7:21": execute of template failed: template: partials/docs/post-meta.html:7:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState

→ hugo -v
INFO 2020/03/28 17:57:22 No translation bundle found for default language "en"
INFO 2020/03/28 17:57:22 Translation func for language en not found, use default.
INFO 2020/03/28 17:57:22 i18n not initialized; if you need string translations, check that you have a bundle in /i18n that matches the site language or the default language.
INFO 2020/03/28 17:57:22 Using config file:
Building sites … INFO 2020/03/28 17:57:22 syncing static files to /Users/will/go_productions/src/hugo_books/public/
Total in 8 ms
Error: Error building site: "/Users/will/go_productions/src/hugo_books/content/_index.md:8:1": failed to extract shortcode: template for shortcode "columns" not found

**Comment by alex-shpak** [comment]
Hi!
`GetTerms` was added in hugo is `0.65`, which become minimum required version for the latest version of theme. So please upgrade Hugo.

**Comment by wizarot** [comment]
Thank you ! I update hugo to 0.68.3 , it work.
