### ISSUE TITLE
BookSection does not work when building in Windows 10

### ISSUE THREAD

**Issue by kaipyroami** [alex-shpak/hugo-book#186]
I m using Hugo 0.68.0 on windows 10 and the BookSection flag does not work. 
On Manjaro I can get the site to build properly.

**Comment by alex-shpak** [comment]
HI!
Can you please elaborate on what is not working. Doe it throw error or doesn't render menu.
If possible please include hugo log or screenshot.

My guess would be that it is somehow related to path `/` vs `\`

**Comment by kaipyroami** [comment]
![image](https://user-images.githubusercontent.com/378223/77856038-59e7da00-71a9-11ea-9ada-8e91ab90ac78.png)

**Comment by kaipyroami** [comment]
So instead of the "docs" folder being the root it defaults to the "content" folder. Thus including all other folders.

**Comment by alex-shpak** [comment]
From screenshot it seems like `docs` section is rendered correct, but `title` resolution is not working properly. I will take a look.

**Comment by kaipyroami** [comment]
The entire content folder instead of only the docs folder will render. Similar to if the BookSection config flag is commented out. 

On *nix the BookSection flag will function correctly.

**Comment by elv1s42** [comment]
Hi, 
Looks like I'm having the same issue using Hugo on Win10 with `hugo-book` v7 release

**Comment by alex-shpak** [comment]
I tried to run it on windows. It renders `docs` section correct. Title is wrong then.
![image](https://user-images.githubusercontent.com/5515443/78072692-d6440e00-739f-11ea-8a51-54e53b9bf4db.png)

Compare it to https://themes.gohugo.io/theme/hugo-book/

**Comment by alex-shpak** [comment]
Fix is pushed to master

**Comment by elv1s42** [comment]
Thank you @alex-shpak!
I've tested the fix and can confirm it's working fine for me

**Comment by kaipyroami** [comment]
@alex-shpak Fixed on mine too! Thank you!
