### ISSUE TITLE
multilanguage link isnt correct after upgrading the theme

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#187]
after i upgrade the theme,  the website  no longer links to corresponding language pages.

**Comment by longlu** [comment]
not sure whether i did anything wrong,  I simply downloaded the themes file and replace the old theme folder.

**Comment by longlu** [comment]
and I use different domain for different languages

**Comment by longlu** [comment]
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: unknown

i can reproduce it on the provided example  site by adding base url under 'contentDir =' for each language   in the config file 
baseURL = "https://a.com"
baseURL = "https://b.com"
baseURL = "https://c.com",
this does not happen with previous version of hugo book

**Comment by longlu** [comment]
for example the homepage  doesnt link to other languages now  when multidomain is enabled this way.

**Comment by longlu** [comment]
Configure Multilingual Multihost

**Comment by alex-shpak** [comment]
Hm, for multi-domain it's possible that 
https://github.com/alex-shpak/hugo-book/commit/a33bb33f189a565c848819181b1b87e66d020c58#diff-3653f22966cbc47435b587a58cb142e1L21-R21

This changed behaviour. `.Permalink` -> `.RelPermalink`. I will check around.

**Comment by alex-shpak** [comment]
Reverted back to `.Permalink`, pushed to master.

**Comment by alex-shpak** [comment]
Hi! Is issue solved? Can be closed?

**Comment by longlu** [comment]
Yes , sovled! thanks a lot!
