### ISSUE TITLE
does the theme have hreflang tag to let search engine know it's multilingual

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#188]
https://regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/

`{{ if .IsTranslated }}
	{{ range .Translations }}
	<link rel="alternate" hreflang="{{ .Language.Lang }}" href="{{ .Permalink }}" title="{{ .Language.LanguageName }}">
	{{ end }}
{{ end }}
{{ if .IsTranslated }}
	<nav class="LangNav">
	{{ range .Translations }}
		<a href="{{ .Permalink }}">{{ .Language.LanguageName }}</a>
	{{ end}}
	</nav>
{{ end }}`

**Comment by longlu** [comment]
https://support.google.com/webmasters/answer/189077?hl=en

**Comment by alex-shpak** [comment]
I added `hreflang` link into html head block.
```tpl
{{- range .Translations }}
<link rel="alternate" hreflang="{{ .Language.Lang }}" href="{{ .Permalink }}" title="{{ partial "docs/title" . }}">
{{ end -}}
```

**Comment by alex-shpak** [comment]
Hi! Is issue solved? Can be closed?
