### ISSUE TITLE
how to center image or table?

### ISSUE THREAD

**Issue by noticebo** [alex-shpak/hugo-book#189]
Hi, how to center image or table on Hugo? thanks.

**Comment by alex-shpak** [comment]
Hi!
There is not default way in markdown to center image or table, but you can use some tricks.
For example
```
<div class="flex justify-center">

| Head | Head |
| ---- | ---- |
| Cell | Cell |

</div>
```

And for image you can do the same, or use [`figure`](https://gohugo.io/content-management/shortcodes/#figure) shortcode from hugo and add classes there.

Note: I can't guarantee that `justify-center` class would not change name.

**Comment by alex-shpak** [comment]
Hope that answered your question! Closing issue for now. Write here if you want it re-opened.

**Comment by IronicBadger** [comment]
Hi,

Sorry to revive a closed issue but the above code `<div class="flex justify-center">` does nothing for me and the table remains left aligned as is default behaviour.

Thanks for any help in advance you can offer,
IB

**Comment by alex-shpak** [comment]
Hi!
Here an example
```
<div class="flex justify-center">

| head | head |
| ---- | ---- |
| body | body |

</div>
```

Worked for me with an `exampleSite`
![image](https://user-images.githubusercontent.com/5515443/89425734-a637bd80-d739-11ea-90f7-6544c82eedcb.png)

**Comment by bubbleguuum** [comment]
That's not working for me: it remains aligned left.
Apparently, and based on Googling, centering anything with markdown is the most complicated thing is world.

Nothing to exceptional on the page:

```
---
title: Introduction
type: docs
bookToC: false
---

<div class="flex justify-center">

| head | head |
| ---- | ---- |
| body | body |

</div>
```

**Comment by mahmoudksherif** [comment]
not working for images as well

**Comment by alex-shpak** [comment]
Hi!
I tried existing solution with `justify-center` and worked for me as expected.
Please check that you don't have CSS customization that could interfere.
