### ISSUE TITLE
Unable to build the site using the theme

### ISSUE THREAD

**Issue by SanjanaB** [alex-shpak/hugo-book#19]
I am using yarn package manager to install hugo. I have installed the following hugo version
```Hugo Static Site Generator v0.53-8FC339DC2529FF77E494A1C12CD1FF9FBCB880A4 darwin/amd64 BuildDate: 2018-12-24T08:24:44Z```

However when I try to build the site, getting the following error
```ERROR 2019/01/25 11:52:51 error: failed to transform resource: TOCSS: failed to transform "book.scss" (text/x-scss): this feature is not available in your current Hugo version```

Kindly assist in this regard.

**Comment by ksinica** [comment]
You need to install "extended" Hugo version for SCSS support. Assuming you have Go installed, just run:

```go get -v -u --tags extended github.com/gohugoio/hugo```

**Comment by alex-shpak** [comment]
Hi!
Yes, or download one [here](https://github.com/gohugoio/hugo/releases)

Looks like many users falls to problem with extended version of hugo, which ships embedded SASS support. I guess I should consider providing compiled CSS instead.

**Comment by SanjanaB** [comment]
Thanks, Closing the issue.

**Comment by amthe** [comment]
Can't build it either:
`hugo server -t book
ERROR 2019/04/11 10:13:47 Failed to add template "partials/docs/shared.html" in path "partials/docs/shared.html": template: partials/docs/shared.html:17: unexpected "=" in operand
ERROR 2019/04/11 10:13:47 partials/docs/shared.html : template: partials/docs/shared.html:17: unexpected "=" in operand
Building sites … ERROR 2019/04/11 10:13:47 Error while rendering "page" in "posts/": template: posts/single.html:2:4: executing "posts/single.html" at <partial "docs/shared...>: error calling partial: template: "partials/docs/shared.html" is an incomplete or empty template
ERROR 2019/04/11 10:13:47 Error while rendering "page" in "docs/": template: docs/single.html:2:4: executing "docs/single.html" at <partial "docs/shared...>: error calling partial: template: "partials/docs/shared.html" is an incomplete or empty template
ERROR 2019/04/11 10:13:47 Error while rendering "section" in "": template: docs/list.html:2:4: executing "docs/list.html" at <partial "docs/shared...>: error calling partial: template: "partials/docs/shared.html" is an incomplete or empty template
ERROR 2019/04/11 10:13:47 Error while rendering "home" in "": template: docs/list.html:2:4: executing "docs/list.html" at <partial "docs/shared...>: error calling partial: template: "partials/docs/shared.html" is an incomplete or empty template
ERROR 2019/04/11 10:13:47 Error while rendering "section" in "": template: posts/list.html:2:4: executing "posts/list.html" at <partial "docs/shared...>: error calling partial: template: "partials/docs/shared.html" is an incomplete or empty template
ERROR 2019/04/11 10:13:47 Error while rendering "404" in "": template: 404.html:2:4: executing "404.html" at <partial "docs/shared...>: error calling partial: template: "partials/docs/shared.html" is an incomplete or empty template
Total in 14 ms
Error: Error building site: logged 8 error(s)
`

`
hugo version
Hugo Static Site Generator v0.47.1/extended linux/amd64 BuildDate: 2018-09-25T03:41:10Z
`

**Comment by alex-shpak** [comment]
I see. Variable override that I added recently requires Hugo [0.48](https://github.com/gohugoio/hugo/releases/tag/v0.48)
I will update docs and theme declaration.
