### ISSUE TITLE
Adding icon for menu.after entry

### ISSUE THREAD

**Issue by racng** [alex-shpak/hugo-book#190]
Hi, I am new to html and hugo. I was trying to add a Font Awesome icon to menu.after items. I downloaded github svg file to `static/svg/github.svg` of the theme. Then, I edited the site `config.toml` by adding the `pre` attribute to display the icon as svg image for the "Github" menu.after entry.

``` 
[[menu.after]]
  name = "Github"
  pre = "<img src='svg/github.svg' style='height: 15px; width: 25px;'>"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 10
```

The github icon shows properly when I am on the Introduction page:
![image](https://user-images.githubusercontent.com/20281248/78411248-ea685500-75c3-11ea-8cd6-a73550cdc13c.png)

But then it disappears from the menu when I click on any other page:
![image](https://user-images.githubusercontent.com/20281248/78411290-0ec43180-75c4-11ea-910c-a29a187ca84c.png)

Why does the menu behave this way?

**Comment by alex-shpak** [comment]
Hi!
So, in this snippet `<img src='svg/github.svg' style='height: 15px; width: 25px;'>` url is relative to page address. Try to put absolute path instead `/svg/github.svg`.

For example on page with url `http://example.com/docs/page/`  image url `svg/github.svg` will produce `http://example.com/docs/page/svg/github.svg`. But for absolute path `/svg/github.svg` it should become `http://example.com/svg/github.svg`

Note that it only would work if baseURL doesn't contain path segments.

**Comment by racng** [comment]
Thank you!
In another post regarding Font Awesome #180 , you suggested adding icons to `assets/_custom.css`.
What are the steps for doing that? 
Do I move `font-awesome/scss/*` and `font-awesome/webfonts/*` to `assets/plugins/`?
and add the following to `assets/_customs.scss`?
```
@import "plugins/font-awesome/scss/brands";
@import "plugins/font-awesome/scss/fontawesome";
@import "plugins/font-awesome/scss/regular";
@import "plugins/font-awesome/scss/solid";
```
Would the existing theme's `assets/_variables.scss` conflict with font-awesome's `asset/plugins/font-awesome/scss/_variables.scss`?
Would this enable icons in markdown content files as well?
I don't know the differences between js, css, or scss, but why is scss preferred?

**Comment by alex-shpak** [comment]
SASS(scss) helps maintaining and templating css, and use variables before css variables times.
In this specific case SASS is not required. You can put `font-awesome` into `static` folder and add
`<link ....` as described in documentation into `layouts/partials/docs/inject/head.html`

**Comment by alex-shpak** [comment]
So:
1. Download and unzip font-awesome
2. Move `css` and `webfonts` folders into `static/font-awesome` folder.
3. Add `layouts/partials/docs/inject/head.html` with
```
  <link href="/font-awesome/css/fontawesome.css" rel="stylesheet">
  <link href="/font-awesome/css/brands.css" rel="stylesheet">
  <link href="/font-awesome/css/solid.css" rel="stylesheet">
``` 

Should be enough. I didn't test it tho.
This should enable `<i...>` tags everywhere in website, including markdown

**Comment by alex-shpak** [comment]
I will close issue, hope it helped, poke me here if you want it re-opened.
