### ISSUE TITLE
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss): resource "scss/book.scss_50fc8c04e12a2f59027287995557ceff" not found in file cache

### ISSUE THREAD

**Issue by SophoWang** [alex-shpak/hugo-book#191]
hi, I encounter a error, when I start hugo use `hugo server --minify --theme book`

I just use hugo create a new site, and download hugo-book unzip it in theme directory.

but when a run `hugo server --minify --theme book`, I can not successful.

output is:
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss): resource "scss/book.scss_50fc8c04e12a2f59027287995557ceff" not found in file cache

can you help me, thanks!

**Comment by alex-shpak** [comment]
Hi!
To start with something make sure that you are using hugo extended version (that has sass support)

Also please post your hugo version and OS.

**Comment by SophoWang** [comment]
You are right!
Use hugo extended version, It appears to work well.
Thanks!

```sh
Hugo v0.68.3

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

**Comment by axet** [comment]
I had same issue. Maybe it is worth mentioning in docs!

**Comment by alex-shpak** [comment]
Hi! It is mentioned in requirements :) 
https://github.com/alex-shpak/hugo-book#requirements
