### ISSUE TITLE
head partial

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#192]
I added a script  like this in < script data-ad-client="ca-pub-xxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script >
head.html

it seems that the code wont show up in the webpage.
can that be added ?

**Comment by longlu** [comment]
I copied the layouts/partials/docs/inject/head.html  to main folder and follow the same folder struture,

**Comment by alex-shpak** [comment]
Hi!

If you have exactly `< script` in content (with space) that might be an issue. Also check text output of page, for example with curl to see what content is printed.

**Comment by alex-shpak** [comment]
Hi! Is you issue solved?

**Comment by longlu** [comment]
Thanks,  it solved,  the folder name i entered wasn't correct
