### ISSUE TITLE
add external links to menu

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#194]
I chose  "File tree menu (default)", and if I want to add external links as menu,
does this work?  
https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu

**Comment by longlu** [comment]
[[languages.en.menu.main]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 110

[[languages.en.menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    url = "https://xxxx.com/xxxxx/"
    weight = 100


i added this to config file, the menu doesnt show up

**Comment by alex-shpak** [comment]
Hi!
There are two menus available: `before` and `after` filetree menu. Try to set one of those.

https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L41

**Comment by alex-shpak** [comment]
Hi! Is you issue solved?

**Comment by longlu** [comment]
it can be added, 
by default , menu external link is opened in new tab.
what i want is the opposite

so i added   'hrefTargetBlank = false
[[languages.en.menu.before]]
    name = ""
    url = "https://"
    hrefTargetBlank = false
    weight = 
 it seems that there's no effect

**Comment by longlu** [comment]
i just found this:
https://agrimprasad.com/post/hugo-goldmark-markdown/
https://gohugo.io/getting-started/configuration-markup/#goldmark

**Comment by longlu** [comment]
it seems hugo doesn't allow easily customizing this for each link now.

**Comment by longlu** [comment]
for this external menu link,
themes/book/layouts/partials/docs/menu-hugo.html
i need to remove "_blank"  in menu-hugo.html ?

**Comment by longlu** [comment]
i copied that to layout, and changed blank to _self, then it's solved  for the menu link.

I'll test with external links in the  posts in the future.   I remember is it is customizable for each link in posts.

**Comment by alex-shpak** [comment]
Default behaviour of generated link in menu is to open in current tab for local URLs and open new tab for external URLs. I think it's sane default.
Param `hrefTargetBlank` works only for markdown content. So yes, you will need to customize `menu-hugo.html` and remove `target=_blank`

**Comment by ikingye** [comment]
How can I use `<hr />`  befere `menu.after`

**Comment by ikingye** [comment]
> it can be added,
> by default , menu external link is opened in new tab.
> what i want is the opposite
> 
> so i added 'hrefTargetBlank = false
> [[languages.en.menu.before]]
> name = ""
> url = "https://"
> hrefTargetBlank = false
> weight =
> it seems that there's no effect

You can add `menu-before.html` to `layouts/partials/docs/inject/`
```
<hr />
<ul>
  <li><a href="https://xxx">xxx</a></li>
</ul>
```
