### ISSUE TITLE
plugin _numbered, toc limit to 9

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#196]
<img src="https://user-images.githubusercontent.com/29562589/79196215-36d45000-7e62-11ea-99e5-7cb179e52feb.png" width="20%" height="20%">

ps: 
can toc be like this:
1. test1
  1.1 a
  1.2 b
  1.3 c
  1.4 d

**Comment by alex-shpak** [comment]
Hehe. The first number in `1x` is getting out of component view. Will take a look.
For P.S. that plugin is kinda set of CSS hacks, not sure that I want to change it.

also I think if there is nesting padding in list it's better to keep plan number:
```
1. xxx
   1. xxx
   2. yyy
```
vs
```
1. xxx
1.1 xxx
1.2 yyy
```

Tho, probably doable with more CSS hacks :)

**Comment by alex-shpak** [comment]
Pushed some refactoring to master.
![image](https://user-images.githubusercontent.com/5515443/79915581-7e8d4580-8427-11ea-86f6-a694aa898fd0.png)

**Comment by alex-shpak** [comment]
Can be closed?
