### ISSUE TITLE
Hugo 0.69.0 breaks collapsed menu expansion for current page

### ISSUE THREAD

**Issue by mterhar** [alex-shpak/hugo-book#197]
In my example, I have a heirarchy of pages where the 3rd tier is "bookCollapseSection" and with hugo version 0.68.3, when viewing the section header for the collapsed menu, it expands. 

After updating to 0.69.0, the subsections don't expand unless the user navigates to one of those child pages. 

This change looks like the only one related to ancestors: https://github.com/gohugoio/hugo/commit/4a39564efe7b02a685598ae9dbae95e2326c0230

**Comment by alex-shpak** [comment]
Hi!
Eh, seems like that indeed affected menu. Probably extra check needed like `{{ if or $ancestor (not $collapsed) (eq .CurrentPage .Section) }}`. I will take a look

**Comment by alex-shpak** [comment]
Pushed change to master. From now it is a hack. 😭
