### ISSUE TITLE
about homepage

### ISSUE THREAD

**Issue by u200915986** [alex-shpak/hugo-book#2]
sir, I like your theme very, and forked it, but where is the homepage,why the homepage is readme?
thanks!

**Comment by u200915986** [comment]
where could I change my homepage url? thanks!

**Comment by u200915986** [comment]
could you build a sample site? I am newer in hugo, I do not know how to do it . even I spent 5 hours on it

**Comment by u200915986** [comment]
or could share the sourse code https://themes.gohugo.io/theme/hugo-book/

**Comment by alex-shpak** [comment]
Please re-open if you still have this problem
