### ISSUE TITLE
plugin _numbered, can "main body" set startLevel = 2

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#201]
![image](https://user-images.githubusercontent.com/29562589/79426121-46d06900-7ff5-11ea-8e8d-d5bedcfc5c92.png)

The toc can set startLevel = 2, which is good.
But main body can't do that.

I think one article generally has only one Head 1 (Level 1).

**Comment by alex-shpak** [comment]
Hi! After refactor you can copy-paste `_numbered.scss`  to your site `assets/plugins` folder and change `$startLevel: 1;` to the same value as `markup` param. I didn't find way to pick that number from hugo config.

**Comment by alex-shpak** [comment]
Can be closed?
