### ISSUE TITLE
how to folded the titles of the menu tree and then unfolded them

### ISSUE THREAD

**Issue by noticebo** [alex-shpak/hugo-book#203]
Hi,

I am looking for the method to make the leafs of the menu tree in the left side of website folded and then unfolded them after clicking.

For example, I have below menu tree:

- [node1]
  - [leaf1]
  - [leaf2]
- [node2]
 - [leaf3]
 - [leaf4]

I would like to make leaf1, leaf2, leaf3 and leaf4 hidden and after I click node1, leaf1 and leaf2 will show. then if I click node2, leaf1 and leaf2 hidden while leaf3 and leaf4 shown.

thanks

**Comment by alex-shpak** [comment]
Hi!
For filetree style menu you can set `bookCollapseSection: true` in frontmatter of `node1` and `node2` pages.
In case of leaf bundle menu I would recommend to switch to filetree menu 😄 

https://github.com/alex-shpak/hugo-book#page-configuration

**Comment by noticebo** [comment]
hi,

I have set **bookCollapseSection: true** but it seems doesn't work.

my directories organized as below:

- docs
   - ml
      - lr.md
      - _index.md
   - dl
      - lr.md
      - _index.md

I have set _index.md like:

---
bookCollapseSection: true
weight: 10
---

however, it doesn;t  work :(

**Comment by noticebo** [comment]
besides, what's the difference between file-tree and leaf-tree

**Comment by alex-shpak** [comment]
File-tree menu is generated form file structure, leaf-bundle menu is using markdown file to generate side menu.

This supposed to work 🤔 
Try to compare your site settings to example site: https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml
And here is collapsed section: https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/docs/example/collapsed/_index.md
Works in example: https://themes.gohugo.io//theme/hugo-book/docs/example/collapsed/

Also maybe share your OS and version of hugo

**Comment by noticebo** [comment]
Hi alex,

I checked your said example and found that 3rd level and 4th level are not hidden. I am finding a solution that 3rd level and 4th level will be hidden until Collapsed is clicked. The reason why I seek for this is that when there are many articles in the node, the length of side menu will become very long. I found that someone has implemented this like: https://chaoskey.gitee.io/notes/tags/hugo/
Do our theme support this?

thanks.

BTW, my os is win10, and Hugo Static Site Generator v0.67.1/extended windows/amd64

**Comment by alex-shpak** [comment]
Hm, I don't follow, sorry.

It works for me on chrome/macos on example site, I also tested it on Windows 10 with hugo 0.67 extended, seems fine. Maybe you have some customisation which breaks expanding?

![image](https://user-images.githubusercontent.com/5515443/79956984-34d14900-8481-11ea-9919-91992dcf636e.png)
![image](https://user-images.githubusercontent.com/5515443/79957001-3a2e9380-8481-11ea-8b95-541b6991bdc7.png)

**Comment by noticebo** [comment]
hi alex, thanks for your reply.

Could you please upload your configuration file relating to collapse function?

**Comment by alex-shpak** [comment]
It is uploaded.
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/docs/example/collapsed/_index.md

https://github.com/alex-shpak/hugo-book/tree/master/exampleSite is the source code of https://themes.gohugo.io/theme/hugo-book/

**Comment by noticebo** [comment]
thanks man.

I know how to configure it now.


besides, i would like to know how to make the font of 'Collapsed' bold?

![image](https://user-images.githubusercontent.com/62462953/79983805-d769e600-84da-11ea-849c-9bf190683aa4.png)

**Comment by alex-shpak** [comment]
For that you will need to add a bit of custom CSS
Create file in your site (not in theme) `assets/_custom.scss` with content
```
.book-menu > nav > ul > li > a
  font-weight: bolder;
}
```

That will make first level of links bolder.

**Comment by noticebo** [comment]
hi,

I tried to do like what you suggested, but got the below error. is there something I mistaken?

Building sites … Total in 735 ms
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss): SCSS processing failed: file "D:/blog/assets/_custom.scss", line 1, col 1: Invalid CSS after ".": expected 1 selector or at-rule, was ".book-menu > nav > "


thanks

**Comment by alex-shpak** [comment]
There was missed `{` in snipped. Fixed below:
```
.book-menu > nav > ul > li > a {
  font-weight: bolder;
}
```

**Comment by ikingye** [comment]
900 and 600 seem no difference
```
.book-menu>nav>ul>li>a {
    font-weight: 900;
}

.book-menu>nav>ul>li>ul>li>a {
    font-weight: 600;
}
```

**Comment by alex-shpak** [comment]
Right now available font weights are: 300, 400 and 700.
Tho, your snipped works as intended for me, on macOS, chrome
![image](https://user-images.githubusercontent.com/5515443/80531474-0250b000-899b-11ea-935f-f7dd3c07c442.png)

**Comment by EricLi23** [comment]
> Hi alex,
> 
> I checked your said example and found that 3rd level and 4th level are not hidden. I am finding a solution that 3rd level and 4th level will be hidden until Collapsed is clicked. The reason why I seek for this is that when there are many articles in the node, the length of side menu will become very long. I found that someone has implemented this like: https://chaoskey.gitee.io/notes/tags/hugo/ Do our theme support this?
> 
> thanks.
> 
> BTW, my os is win10, and Hugo Static Site Generator v0.67.1/extended windows/amd64

I meet same problem today. can you share the method how to collapse the menu?
