### ISSUE TITLE
How to customize Mermaid JS

### ISSUE THREAD

**Issue by aseltmann** [alex-shpak/hugo-book#204]
I would like to customize the appearance of my mermaid charts using the [mermaidAPI](https://mermaid-js.github.io/mermaid/#/mermaidAPI). I found the following files dealing with mermaid:  `layouts/shortcodes/mermaid.html` and `static/mermaid.min.js`. I guess `assets` is also a directory which plays a role here. Following the mermaidAPI documentation I would have to edit the initialization call:

```js
mermaid.initialize({
  flowchart:{
    htmlLabels: false
  }
});
```

or I would have to do it in some `<script>`-Tag:

```html
<script>
  var config = {
    startOnLoad:true,
    flowchart:{
      useMaxWidth:true,
      htmlLabels:true,
      curve:'cardinal',
    },

    securityLevel:'loose',
  };
  mermaid.initialize(config);
</script>
```

What would be the advised option for hugo book?

**Comment by R0quef0rt** [comment]
I'm interested in this as well. My understanding is that you would want to create a theme:

https://github.com/mermaid-js/mermaid/tree/master/src/themes

But I don't know how to choose a theme from Book's mermaid shortcode. I don't think it's supported at this time.

**Comment by alex-shpak** [comment]
Hi!
Right now there is no option to customize mermaid settings. It's a bit tricky to do, I will need to think about elegant solution.

**Comment by btshft** [comment]
Hi!

I also encountered the need to change mermaid's config. I managed to solve it as follows:
1. Edit theme's layouts/shortcodes/mermaid.html

```
{{ if not (.Page.Scratch.Get "mermaid") }}
<!-- Include mermaid only first time -->
<script src="{{ "mermaid.min.js" | relURL }}"></script>
<script>

var initMermaid = function(config) {
  config = config || { useMaxWidth:true };
  mermaid.initialize(config || {});
}

{{ with .Get "configUrl" }}
  {{ $url := .}}
  {{ if $url }}
    {{ $config := getJSON $url }}
    initMermaid({{ $config  }});
  {{ else }}
    initMermaid();
  {{ end }}
{{ end }}
</script>
{{ .Page.Scratch.Set "mermaid" true }}
{{ end }}

<p class="mermaid{{ with .Get "class" }} {{ . }}{{ end }}">
  {{- .Inner -}}
</p>
```

2. Edit my site's docs page (for example):
```
{{< mermaid configUrl="data/mermaid/mermaid.json" >}}
graph LR
    id1{This is the text in the box}
{{< /mermaid >}}
```

3. Add mermaid.json to site's data/mermaid dir with following content (for example)
```
{
    "theme": "forest"
}
```

I unfortunately have very little experience with Hugo. Therefore, I can’t say how good this solution is, but it works. Maybe someone will come in handy 😃

**Comment by alex-shpak** [comment]
Changes has been pushed to master.
You can customize mermaid config object with `assets/mermaid.json` file.
