### ISSUE TITLE
[Feature] Add {{ expand }} default state

### ISSUE THREAD

**Issue by sboishtyan** [alex-shpak/hugo-book#205]
What do you think about the default state to expand? I want to show the expanded block because when it in the collapsed state it easy to miss something important.

**Comment by alex-shpak** [comment]
HI!
I'm thinking to rewrite `expand` shortcode with html5's `details`/`summary` tag. Which has `open` attribute, so stay tuned :)

**Comment by alex-shpak** [comment]
Details shortcode added.
