### ISSUE TITLE
请问需要怎么使用？我对代码这块不懂？

### ISSUE THREAD

**Issue by chenxuejian** [alex-shpak/hugo-book#206]
xuejian in ~/Adolf-blog λ hugo server --minify --theme book

Building sites … ERROR 2020/04/22 16:17:50 render of "taxonomy" failed: execute of template failed: template: taxonomy/taxonomy.html:7:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/xuejian/Adolf-blog/themes/book/layouts/partials/docs/post-meta.html:6:21": execute of template failed: template: partials/docs/post-meta.html:6:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
ERROR 2020/04/22 16:17:50 render of "taxonomy" failed: execute of template failed: template: taxonomy/taxonomy.html:7:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/xuejian/Adolf-blog/themes/book/layouts/partials/docs/post-meta.html:6:21": execute of template failed: template: partials/docs/post-meta.html:6:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
ERROR 2020/04/22 16:17:50 render of "taxonomy" failed: execute of template failed: template: taxonomy/taxonomy.html:7:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/xuejian/Adolf-blog/themes/book/layouts/partials/docs/post-meta.html:6:21": execute of template failed: template: partials/docs/post-meta.html:6:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
ERROR 2020/04/22 16:17:50 render of "taxonomy" failed: execute of template failed: template: taxonomy/taxonomy.html:7:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/xuejian/Adolf-blog/themes/book/layouts/partials/docs/post-meta.html:6:21": execute of template failed: template: partials/docs/post-meta.html:6:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState
Built in 170 ms
Error: Error building site: failed to render pages: render of "taxonomy" failed: execute of template failed: template: taxonomy/taxonomy.html:7:7: executing "main" at <partial "docs/post-meta" .>: error calling partial: "/Users/xuejian/Adolf-blog/themes/book/layouts/partials/docs/post-meta.html:6:21": execute of template failed: template: partials/docs/post-meta.html:6:21: executing "partials/docs/post-meta.html" at <$.GetTerms>: can't evaluate field GetTerms in type *hugolib.pageState

**Comment by alex-shpak** [comment]
Hi,
Seems like error is about `.GetTerms` function, which was added in hugo `0.65`, which is required minimum version. Please check your version.

**Comment by chenxuejian** [comment]
Normal after upgrading hugo version ，ths
