### ISSUE TITLE
Columns broken since 0.69

### ISSUE THREAD

**Issue by VilhelmPrytz** [alex-shpak/hugo-book#207]
[This](https://github.com/VilhelmPrytz/utbildningsmaterial/blob/master/content/docs/fysik-1a/elektricitet.md#str%C3%B6m) section is rendered like the screenshot below.

![image](https://user-images.githubusercontent.com/15460993/80144795-6fd19a80-85af-11ea-93a1-91a167c93f9c.png)

The section above it ([this one](https://github.com/VilhelmPrytz/utbildningsmaterial/blob/master/content/docs/fysik-1a/elektricitet.md#elementarladdning)) is rendered normally which leads me to believe something is not right with the columns.

Have columns broken?

Rendered on Hugo `0.69.1` with hugo-book theme commit 7b18b077eef940111cb13d20ba2151ff6c36633b

**Comment by alex-shpak** [comment]
Hi!
Yes, seems like. There was recent change trying to fix that: https://github.com/alex-shpak/hugo-book/commit/e4e43bd9b12a3e37f0d3c2760ea7f867ba8273a7

But seems like I didn't cover all cases.
For some reason `shortcode` eats `\` in `\(` and `\)`, not sure why.

I will take your markdown for test-case.

**Comment by alex-shpak** [comment]
I pushed some change, please test.

**Comment by VilhelmPrytz** [comment]
Seems to work fine!
