### ISSUE TITLE
Posts name cut after dot

### ISSUE THREAD

**Issue by niklas-fischer** [alex-shpak/hugo-book#208]
Hi! 
I noticed that when creating a new post with` hugo new posts/1.x.md` the new title of the created document is "1", not "1.x". Unfortunately I don't understand the syntax to change it in the archetypes by myself. Is this a bug or intended behaviour?

**Comment by alex-shpak** [comment]
Hi!
In archetype `{{ replace .Name "-" " " | title }}` `.Name` trims file name.

Try this:
```
---
title: "{{ replace .File "-" " " | title }}"
date: {{ .Date }}
---
```

**Comment by niklas-fischer** [comment]
You're awesome! It worked :-)
Thank you very much!
