### ISSUE TITLE
The site-name link point to localhost:1313

### ISSUE THREAD

**Issue by sitexa** [alex-shpak/hugo-book#21]
when upload to server, the site-name link point to "localhost:1313". 
can anybody help? thanks.

**Comment by alex-shpak** [comment]
Hi!
Make sure that you set base url like [here](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yml#L3)
Or via cli `hugo --baseURL="http://xxx"`

**Comment by alex-shpak** [comment]
Feel free to reopen if you need some more assistance.
Closing for now.
