### ISSUE TITLE
Katex not working

### ISSUE THREAD

**Issue by SimZhou** [alex-shpak/hugo-book#210]
Hi, I tried your examplesite and the Katex page appears like this:

![katex](http://s1.ax1x.com/2020/04/26/J6Mpm6.png)

The tex fomula is not working.
And I checked the elements, it appears the page is not loading katex js and css dependencies.

What should I do?

**Comment by alex-shpak** [comment]
Hi!
To start with, please make sure https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L11-L14
is set in your settings.

**Comment by alex-shpak** [comment]
Hi! is your issue solved?

**Comment by SimZhou** [comment]
> Hi! is your issue solved?

Hi, yes it is solved as long as I changed the config file as you said. Thanks a lot!
