### ISSUE TITLE
Why is the margin subtly different?

### ISSUE THREAD

**Issue by okapixel** [alex-shpak/hugo-book#211]
When the width of the container exceeds 1280px, the margins are automatically added to the left and right. However, this margin varies from page to page. (e.g., the top page and the Buttons page)
It's odd because the position of the menu moves subtly when you move the page. It would be nice if you could adjust it.

**Comment by alex-shpak** [comment]
Hi!
If you are in Windows - it's likely that appearance of scrollbars is affecting page size. Not much I can do about it :(

Otherwise please share your OS/Browser so I can check.

**Comment by okapixel** [comment]
Thanks for the quick reply! That's right, I'm using Windows. We also confirmed the impact of the presence of scroll bars. Thank you!

**Comment by okapixel** [comment]
I added the following code in _custom.sccs.
```
@media screen and (min-width: $container-max-width) {
    .container {
        margin-left: calc(50vw - #{$container-max-width} / 2);
    }
}
```
Does this code have the potential to cause any problems?

**Comment by alex-shpak** [comment]
Should be ok.
