### ISSUE TITLE
"bookCollapseSection: true" not work if one's name include others

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#212]
There are two directorys, which are `a` and `aa`. 
Both are setting `bookCollapseSection: true`.

When I click `aa`, the `a` will unfold too.

**Comment by alex-shpak** [comment]
Related: https://github.com/gohugoio/hugo/commit/8d5766d417d6564a1aa1cbe8f9a29ab9bba22371

**Comment by alex-shpak** [comment]
Fix pushed with adjusted behaviour for latest Hugo version. You will need minimum hugo `0.69.2`
