### ISSUE TITLE
Problems with editing menu bar on the left side

### ISSUE THREAD

**Issue by ajdintrejic** [alex-shpak/hugo-book#213]
This is my first Hugo page and I have read the documentation on menus but I'm still confused by how to edit it. 
I have added another folder to the /docs doler
![image](https://user-images.githubusercontent.com/41389717/80486876-280a9480-895c-11ea-96dd-5dff9b0af8b2.png)
I have added the line to menu/index.md
![image](https://user-images.githubusercontent.com/41389717/80487092-8afc2b80-895c-11ea-8766-007036372e34.png)
Here is an example file
![image](https://user-images.githubusercontent.com/41389717/80487029-70c24d80-895c-11ea-8568-c410df52d1de.png)
This is how it's rendered:
![image](https://user-images.githubusercontent.com/41389717/80487072-82a3f080-895c-11ea-95b8-7b5e50e24789.png)

Now this is what is confusing me:
Am I supposed to be editing the menu/index.md file?
Why is there no heading for /write-ups-big-menu, or why are they rendered at the root of menu?
Does weight only affect the order of the menu elements in the same level or does it also do something else?

**Comment by ajdintrejic** [comment]
So I realized to add the "folder heading" I have to add _index.md to the folder, 
![image](https://user-images.githubusercontent.com/41389717/80492524-70c64b80-8964-11ea-8f2f-dd05f4c0f6c8.png)
Now it renders correctly, but I still have no idea what is that menu/index.md file used for. It doesn't contain my new "Write Up section"
![image](https://user-images.githubusercontent.com/41389717/80492956-019d2700-8965-11ea-960e-3a6d1e4a57ed.png)

**Comment by alex-shpak** [comment]
Hi!
There are two kinds of menu: ([Ref](https://github.com/alex-shpak/hugo-book#menu))
- Filetree menu
- Leaf bundle menu

File-tree is built from directory structure. It is default option. Then leaf bundle menu is using markdown file (`content/docs/menu/index.md`) to render menu instead, this let user write own menu, or even use shortcodes. But file-tree menu is recommended.

With file-tree you can remove `content/docs/menu/` folder, it is in example site just for... example :)

**Comment by ajdintrejic** [comment]
I've read your documentation on menus but I have no idea I read it so poorly, read it once more after you replied and I understand now thanks, and thanks for developing this theme and keeping it simple.
