### ISSUE TITLE
Header with link, click it on toc, how to jump to the header instead of link

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#214]
I set the header with link.
When I click it on toc, I expect to jump to the header.
But now It jumps to the link.

```
## [header](http://link)
```

**Comment by alex-shpak** [comment]
Hi!
This is how it is generated by Hugo. Theme doesn't have control over it, so not much we can do...

**Comment by ikingye** [comment]
get

**Comment by alex-shpak** [comment]
I will close this one, we can reopen in case of changes from hugo side.
