### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by kharazi** [alex-shpak/hugo-book#215]
Is it possible to support Right To Left language in this theme?

**Comment by alex-shpak** [comment]
Hi!
I think most things should work. But there is no config param right now. You can achieve by setting `direction: rtl` in `_custom.scss`.

We can add some configuration param, it probably should live in `i18n` folder.

![image](https://user-images.githubusercontent.com/5515443/81334176-f1442500-90a5-11ea-80f6-e6a2debf550c.png)
I can see right now that collapsed menu icon is off, other seems fine.

**Comment by alex-shpak** [comment]
Added support for `languageDirection` in lang config from hugo, you can give it a try.

References:
https://gohugo.io/content-management/multilingual/
https://github.com/gohugoio/hugo/issues/6550

**Comment by kharazi** [comment]
@alex-shpak 
Awesome! I handled it before with custom CSS.
There are few mobile view bugs when I configured language direction:
- Nav menu will open completely white
- Nav menu must open from right

**Comment by alex-shpak** [comment]
I pushed fix for that, seems like search progressbar also needs fix.

**Comment by kharazi** [comment]
I disabled search :- D
thanks for your great effort on this awesome theme

**Comment by alex-shpak** [comment]
Thank you!
I also fixed search spinner. Closing then.
