### ISSUE TITLE
404 layout error with Home.RelPermalink

### ISSUE THREAD

**Issue by dimensi0n** [alex-shpak/hugo-book#218]
I got this error when I try to build [my site](https://github.com/open-incubator/wiki) :

```
Error: Error building site: render of "404" failed: "/home/erwan/Documents/wiki/themes/book/layouts/404.html:26:27": execute of template failed: template: 404.html:26:27: executing "404.html" at <.Site.Home.RelPermalink>: error calling RelPermalink: runtime error: invalid memory address or nil pointer dereference
```

It disappears on my local repository when I add the -D flag, it is strange.

**Comment by alex-shpak** [comment]
Hi!
Check that your home page file `content/_index.md` doesn't have date field in future.

**Comment by alex-shpak** [comment]
Oh, you actually have `draft: true` in frontmatter.
That makes your home page absent without rendering drafts.

**Comment by dimensi0n** [comment]
Thanks it worked 🙏🏻
