### ISSUE TITLE
Menu on the left doesnot highlight the link if on the current Page

### ISSUE THREAD

**Issue by SanjanaB** [alex-shpak/hugo-book#22]
When I am on a page by clicking on the link on the menu, the clicked link is not shown highlighted. This happens if the `BookMenuBundle` option is set. The .Content is rendered within `menu-bundle.html` partial, which gives no control to style the clicked link. Kindly assist.

**Comment by alex-shpak** [comment]
Hi!

I made temporary solution in last [commit](https://github.com/alex-shpak/hugo-book/commit/fa58475a37b0cd4cd72ccb1aa09a92976c1adb80)
It works for now, but I will likely change that implementation later.

Solution injects style with attribute selector in each page.

**Comment by SanjanaB** [comment]
Hi!
This fix doesnot work for nested sections. Looks like the default function parameters are also toggled. https://gohugo.io/functions/default/

**Comment by alex-shpak** [comment]
Ah, sleepy me yesterday. Fixed order in `default`

About nested menu
![image](https://user-images.githubusercontent.com/5515443/52638139-87a08f80-2ed1-11e9-8756-185db30c03f3.png)
It worked with setup like this
```
- [**Introduction**]({{< ref "/" >}})
- [Examples]({{< ref "/docs/examples.md" >}})
    - [With Table of contents]({{< ref "/docs/with-toc.md" >}})
    - [Without Table of Contents]({{< ref "/docs/without-toc.md" >}})
        - [Without Table 1]({{< ref "/docs/server.md" >}})
            - [Without Table 2]({{< ref "/docs/client.md" >}})  
```

Maybe you can share your menu example with me?

**Comment by SanjanaB** [comment]
Hi!
We use relative ref links

```

**Comment by alex-shpak** [comment]
Update pushed
```
nav ul a[href$="{{- .RelPermalink -}}"] {
```
