### ISSUE TITLE
BookEditPath should not point to 'content' folder

### ISSUE THREAD

**Issue by yevgen-nykytenko** [alex-shpak/hugo-book#220]
Readme.md line 166 says BookEditPath should point to content folder:  
like this BookEditPath = 'edit/master/exampleSite/content'.

However footer.html partial is also requires .Site.Params.contentDir variable to be set at 
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/footer.html#L18

So if to set *BookEditPath* and omit *.Site.Params.contentDir* there will be duplicated slash in a resultant edit url.

**Comment by alex-shpak** [comment]
Hi!
Documentation was outdated, fixed.
