### ISSUE TITLE
Book menu will not collapse when using BookMenuBundle

### ISSUE THREAD

**Issue by kaipyroami** [alex-shpak/hugo-book#221]
Book menu will not collapse when using BookMenuBundle. When BookMenuBundle is enabled the menu collapses as expected.

**Comment by alex-shpak** [comment]
Hi! Unfortunately collapsing Bundle menus is not supported, I didn't find a way to do it.
I suggest to switch to file-tree option, I think I'm gonna deprecate bundle menu in some future and replace with hugo native menu.

**Comment by kaipyroami** [comment]
That's fine. My issue with the file-tree method is that it always capitalizes the first character of the file name and separates letters. For example in my case "BMW i3" becomes "B M W I3". Is there any work around to make file-trees literal for instance "BMW-i3" or similar?

**Comment by alex-shpak** [comment]
Try to add frontmatter with title. By default menu tries to humanize names of files, but if you set specific title in document:
```
---
title: BMW
---
```
theme will use that.

**Comment by kaipyroami** [comment]
Beautiful!!! That works!

Thank you, much appreciated.
