### ISSUE TITLE
Page banner

### ISSUE THREAD

**Issue by geoffreymbrown** [alex-shpak/hugo-book#222]
I'd like to add a banner above the book site.   I commonly do this for classes to provide branding (the school) and links to the department, etc.

 I've tried using the

layouts/partials/docs/inject/head.html

but, this content is rendered on top of the menu.   I'm guessing this isn't the right path to achieve what I want.

**Comment by alex-shpak** [comment]
Hi!
`layouts/partials/docs/inject/head.html` in injectet into html's `<head>` block, try `layouts/partials/docs/inject/content-before.html`.

I can suggest to also try `BookLogo` param, to add logo before site title, and put your links into `before` menu. `before` menu is rendered above main menu.

https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L59
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L40

**Comment by geoffreymbrown** [comment]
Thanks !   I did try all of those, but none really did what I wanted --
something spanning the whole window.   Each of them adds stuff either to
the menus or the content.
Geoffrey

**Comment by alex-shpak** [comment]
Well 🤔  there is no inject block that would take entire width of page right now, because it interferes with fixed position of left and right menus.

**Comment by alex-shpak** [comment]
Can you perhaps draw a sketch picture of what you are trying to achieve? So I can get better understanding.

**Comment by geoffreymbrown** [comment]
This is from an earlier project so the links and overall layout don't match the book model, but the idea of having a top area for branding, links, etc. is what I'm after.  BTW, I wasn't looking for you to change your system, just to see if there was a natural way to do this.  I have enjoyed using the hugo-book theme for a course, but did miss the ability to provide a top area.

![Screenshot from 2020-05-19 17-42-29](https://user-images.githubusercontent.com/1752914/82381624-8a553300-99f8-11ea-9acf-e968357ea8b7.png)

**Comment by alex-shpak** [comment]
Now unfortunately there is no block to take all width. I initially designed layout without top panel just to look a bit more unique :)

**Comment by geoffreymbrown** [comment]
Thanks for taking a look.   It's not a deal breaker.    I looked at the
code a bit and I can probably patch things with some effort if I decide
it's important.

Geoffrey

**Comment by alex-shpak** [comment]
Okay, I will close then :) Feel free to open new issue if you need help.

P.S. With some recent changes in master branch you can now make sticky header/footer, tho still not full width.

**Comment by geoffreymbrown** [comment]
Just to follow up, I did finally get around to getting something to work.    I modified baseof.html by adding  

`<header>
    {{ partial "navbar.html" . }}
  </header>`

before main.    I then added some styling to the _custom.scss.  The following carve out some space for the navbar.   I'm sure there are less hacky ways to create the needed margins for the navbar, but I'm barely a novice when it comes to css.

`
.book-menu nav {
    margin-top: 130px;
}

.book-toc nav {
    margin-top: 130px;
}
`
and styling for the navbar itself -- obviously this is specfic to the project

`
/* The navigation bar */
.navbar {
    overflow: hidden;
    background: linear-gradient(#990000,#e60000);
    border-bottom: 3px solid #2e3436;
    font-family: "Verdana", Arial, sans-serif;
    color: white;
    //background-color: #333;
    position: sticky; /* Set the navbar to fixed position */
    top: 0; /* Position the navbar at the top of the page */
    width: 100%; /* Full width */
  }
  
  /* Links inside the navbar */
  .navbar a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
  
  /* Change background on mouse-over */
  .navbar a:hover {
    background: #ddd;
    color: black;
  }
`

**Comment by andrewfn** [comment]
Thank you so much for raising and solving this issue!
I found I had to do one more thing to prevent the book-menu having a white background which overlaid the top bar:
`
.book-menu {
  --body-background: transparent;
}
`
This changes the value of the body-background variable which is set in :root to white.
