### ISSUE TITLE
Missing Nav. Icons on Mobile

### ISSUE THREAD

**Issue by stockphrase** [alex-shpak/hugo-book#223]
- I built a site with this theme which looks great on a screen, but on a phone there are missing navigation icons for the menu/toc. Is this a bug or am I missing something here?

- Also noticing that the search box doesn't do anything if a term is entered.

![Book-theme](https://user-images.githubusercontent.com/2568776/82394775-ea0f0680-9a17-11ea-945d-62c879e1a6b4.png)

**Comment by alex-shpak** [comment]
Hi!
Icons work for me on demo site in mobile view
https://themes.gohugo.io/theme/hugo-book/

Perhaps check your `baseURL` for site. If it is opensource please send a link, so I can check.

**Comment by stockphrase** [comment]
I seem to have fixed the icon issue. Not certain what the problem was. I pulled in the theme again and re-uploaded it to the server. I icons magically appeared. Apologies for the trouble.

**Comment by alex-shpak** [comment]
Good 👍 Then I close the issue.
