### ISSUE TITLE
highlights and hints do not work inside tabs

### ISSUE THREAD

**Issue by tobtoht** [alex-shpak/hugo-book#224]
```
{{< tabs >}}
{{< tab "1" >}}
# Some markdown
{{< hint info >}}
Some hint
{{< /hint >}}
{{< /tab >}}
{{< tab "2" >}}
# More markdown
{{< /tab >}}
{{< /tabs>}}
```

Result: hint blockquote and its content are missing from output.

Hugo Version: v0.71.0
hugo-book version: d198d96 (current master)

**Comment by alex-shpak** [comment]
Hi!
![image](https://user-images.githubusercontent.com/5515443/82816329-400dff00-9e9b-11ea-8c75-4a554eef3149.png)
It worked for me, please check that you have `unsafe=true` in config
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L14

**Comment by tobtoht** [comment]
Thanks, it is working now.

I figured out what happened:
The exampleSite `config.toml` is not copied when the instructions in the readme are followed:
`cp -R themes/book/exampleSite/content .`
So, I didn't have the `unsafe=true` flag.
