### ISSUE TITLE
can't evaluate field LanguageDirection in type *langs.Language

### ISSUE THREAD

**Issue by cells800** [alex-shpak/hugo-book#226]
Just download and try the book theme.
Followed theses instructions.
=====
hugo new site mydocs; cd mydocs
git init
git submodule add https://github.com/alex-shpak/hugo-book themes/book
cp -R themes/book/exampleSite/content .
hugo server --minify --theme book
====
and got this error
=====
execute of template failed: template: posts/single.html:2:51: executing "posts/single.html" at <.Site.Language.LanguageDirection>: can't evaluate field LanguageDirection in type *langs.Language
====

Thanks,
Simon

**Comment by alex-shpak** [comment]
Hi!
It is likely that you are using too old version of hugo.
https://github.com/alex-shpak/hugo-book#requirements

Minimum required version is 0.68.
