### ISSUE TITLE
function "warnf" not defined on Netlify

### ISSUE THREAD

**Issue by DirtyF** [alex-shpak/hugo-book#227]
Hey, 

Thanks for this nice theme, I don't get why I can compile it locally, and in Forestry.io preview environment but not on Netlify, I get the following error

```
Error: "/opt/build/repo/themes/book/layouts/_default/_markup/render-image.html:15:1": parse failed: template: _default/_markup/render-image.html:15: function "warnf" not defined
```

Hugo: 0.71.1
Go: 1.14.3

Any insight welcome, thanks.

**Comment by DirtyF** [comment]
This looks related to https://discourse.gohugo.io/t/using-errorf-or-warnf-within-a-render-hook/25814

**Comment by alex-shpak** [comment]
Hi!
That's a new one 🤔 It doesn't reproduce for me on macos, hugo `0.71.1`.
Tho, `warnf` function was added in Hugo `v0.62.0`, maybe you can re-check version?

**Comment by DirtyF** [comment]
yeah it compiles fine on macOS, but it fails to build on Netlify

**Comment by Stephen8787** [comment]
Hed
