### ISSUE TITLE
hugo server --theme hugo-book or hugo server -D gives this and shows no pages:

### ISSUE THREAD

**Issue by chevybeef** [alex-shpak/hugo-book#23]
Building sites … WARN 2019/02/13 12:41:18 Found no layout for "taxonomyTerm", language "en", output format "HTML": create a template below /layouts with one of these filenames: categories/terms.en.html.html, categories/list.en.html.html, categories/terms.html.html, categories/list.html.html, categories/terms.en.html, categories/list.en.html, categories/terms.html, categories/list.html, taxonomy/terms.en.html.html, taxonomy/list.en.html.html, taxonomy/terms.html.html, taxonomy/list.html.html, taxonomy/terms.en.html, taxonomy/list.en.html, taxonomy/terms.html, taxonomy/list.html, _default/terms.en.html.html, _default/list.en.html.html, _default/terms.html.html, _default/list.html.html, _default/terms.en.html, _default/list.en.html, _default/terms.html, _default/list.html
WARN 2019/02/13 12:41:18 Found no layout for "taxonomyTerm", language "en", output format "HTML": create a template below /layouts with one of these filenames: tags/terms.en.html.html, tags/list.en.html.html, tags/terms.html.html, tags/list.html.html, tags/terms.en.html, tags/list.en.html, tags/terms.html, tags/list.html, taxonomy/terms.en.html.html, taxonomy/list.en.html.html, taxonomy/terms.html.html, taxonomy/list.html.html, taxonomy/terms.en.html, taxonomy/list.en.html, taxonomy/terms.html, taxonomy/list.html, _default/terms.en.html.html, _default/list.en.html.html, _default/terms.html.html, _default/list.html.html, _default/terms.en.html, _default/list.en.html, _default/terms.html, _default/list.html
WARN 2019/02/13 12:41:18 Found no layout for "home", language "en", output format "HTML": create a template below /layouts with one of these filenames: index.en.html.html, home.en.html.html, list.en.html.html, index.html.html, home.html.html, list.html.html, index.en.html, home.en.html, list.en.html, index.html, home.html, list.html, _default/index.en.html.html, _default/home.en.html.html, _default/list.en.html.html, _default/index.html.html, _default/home.html.html, _default/list.html.html, _default/index.en.html, _default/home.en.html, _default/list.en.html, _default/index.html, _default/home.html, _default/list.html

**Comment by alex-shpak** [comment]
Hi!

Theme is intended for documentation so it doesn't render taxonomy, you can disable it in config like [here](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yml#L6)

About no pages,
Intentionally theme renders only `docs` section or `docs` page type, put your documents into `docs` or mark type like [here](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/_index.md)

In general you can use [exampleSite](https://github.com/alex-shpak/hugo-book/tree/master/exampleSite) as reference

**Comment by cbluth** [comment]
@chevybeef 
i got it to work by doing this:
` cd /path/to/hugo/directory`
`<git clone hugo-book theme into themes>`
`rsync -avPz themes/book/exampleSite/content/ ./content/`
`mkdir resources`
`rsync -avPz themes/book/exampleSite/resources/ ./resources/`
`hugo server --theme book`

then it worked for me

**Comment by alex-shpak** [comment]
@chevybeef Feel free to reopen if you still have this issue.
Closing for now
