### ISSUE TITLE
Allow interacting with menus without changing the page

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#231]
Everyone has been loving the theme so far. So great job again :) I've been getting some feedback and many brought up "being able to expand & collapse other menu sections without opening them".

Let me show you some examples: 
- hugo's own [documentation page](https://gohugo.io/templates/menu-templates/)
- microsoft docs [documentation pages](https://docs.microsoft.com/en-us/powershell/scripting/overview)
- aws has different way (need to click on arrow instead of the name), [see](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-tutorials.html)

AWS has content in grouping pages (expandable) but that might be probably hard to implement. If we'd take the easiest approach I see that both Hugo and Microsoft docs that implement it this way: Sections **does not have content** for those pages. So those section titles are not really pages but just groups stuff.

From UX perspective it's a big improvement when reading content in multiple sections, and almost becoming the de-facto way of menu handling in websites with sectioning.

I wonder how to implement similar 🤔

In hugo documentation I see that you need to define them all in site [configuration file](#https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu). I think it's a pretty ugly way of doing it & which does not currently work with hugo-book.

How about using empty `_index.md` pages only that has some frontmatter that somehow indicates that the page is just a grouper for the content in directory in `file-tree` menu? Then we'll know that it's a dead page and can allow expanding collapsing for those pages.

@alex-shpak, would  you consider having this functionality natively in the theme?

How should we implement this? Maybe CSS with invisible radio boxes?

**Comment by alex-shpak** [comment]
Hi! Thank you!

At time of making side menu I didn't find good way to expand menus without switching page. But I think it would be nice to have, maybe worth trying to implement it again.

Currently you can also declare menu in hugo way, via `menu` in config, not all features are there yet but eventually it is intended to replace bundle menu (which is controlled by markdown file).

Usual rule here is that menu should work fine without JS, maybe radios and unique ID might work, Just CSS probably would not, because there is no place to properly store state. Also there will be changes to menu generation, now pages that are hidden are not rendered into HTML.

About `_index.md`. Now menu renders empty pages not clickable, https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html#L40
Adding `frontmatter` param should do, we have actually one already `BookCollapseSection` :)

**Comment by undergroundwires** [comment]
Hi @alex-shpak, really thanks for giving a green light considering it as a nice to have 😊. As I hear from users (one of them being a professional UX guy) this is the only big UX improvement missing in the theme. In my humble opinion, the feature completes the perfection and makes a difference as it's not supported by many other themes.

Looking at the code + property `BookCollapseSection` it feels like we have the tools needed to go further with this.

I'm probably not the right guy to try to implement this & would appreciate help/contribution.

**Comment by alex-shpak** [comment]
It should be working without javascript, so finding solution might be tricky. But feel free to try! I don't have out-of-the-box solution right now.

**Comment by undergroundwires** [comment]
I will take a look at it when I have time (not promising for any timeline). I'm not good at CSS but will try my best. Meanwhile if there's someone else interested & capable in the community please feel free to take a look at it.

**Comment by alex-shpak** [comment]
Horray!
Some solution is pushed to master.

There might be futher chages. I think to start keeping links to pages without content, and link to them anyway, to make things simpler. Because empty page is created by hugo anyway.

**Comment by undergroundwires** [comment]
Hi, sorry for coming back late, I had no time for fun stuff lately 😊

I've started using it and it works like charm. Just a minor feedback.

I think it'd be nice to not change the color of the "contentless" on hover to give them a different (more dead) feeling than pages with content. What do you think?

Happy new year and have a nice Christmas and thanks again for maintaining this, and implementing all necessary major features to make it a great theme. I see that it's becoming one of the most popular themes and I'm sure community appreciate  your efforts a lot!

**Comment by undergroundwires** [comment]
Hi, sorry for coming back late, I had no time for fun stuff lately 😊

I've started using it and it works like charm. Just a minor feedback.

I think it'd be nice to not change the color of the "contentless" on hover to give them a different (more dead) feeling than pages with content. What do you think?

Happy new year and have a nice Christmas and thanks again for maintaining this, and implementing all necessary major features to make it a great theme. I see that it's becoming one of the most popular themes and I'm sure community appreciate  your efforts a lot!

**Comment by undergroundwires** [comment]
Hi @alex-shpak , sorry for coming back late, I had no time for fun stuff lately 😊

I've started using it and it works like charm. Just a minor feedback.

I think it'd be nice to not change the color of the "contentless" on hover to give them a different (more dead) feeling than pages with content. What do you think?

Happy new year and have a nice Christmas and thanks again for maintaining this, and implementing all necessary major features to make it a great theme. I see that it's becoming one of the most popular themes and I'm sure community appreciate  your efforts a lot!
