### ISSUE TITLE
question: html/css only version?

### ISSUE THREAD

**Issue by nvictor** [alex-shpak/hugo-book#232]
Hey,

I really love this theme and would love to apply the styling to a project outside of Hugo. Is there a way to generate a HTML/CSS only version of this theme?

Thanks

**Comment by alex-shpak** [comment]
Hi! Thank you!
There is no specific tool for that I'm afraid. You can try to generate `exampleSite` locally and just grab HTML layout and generated `book.min.----.css` files. And then adapt to your needs.

**Comment by nvictor** [comment]
Thank you so much!!
