### ISSUE TITLE
[Feature] Scrollspy-esque follower for the BookToC right sidebar?

### ISSUE THREAD

**Issue by jamesb93** [alex-shpak/hugo-book#235]
How hard would it be to implement a Scollspy-esque follower for the BookToC right sidebar?

An example is here: http://www.benhackbarth.com/audioGuide/docs_v1.37.html ...

although it could be way simpler and just have a dot or highlight animation to show you where in the structure you are currently.

**Comment by alex-shpak** [comment]
Hi! Should be not hard to do,
I googled some library: https://github.com/cferdinandi/gumshoe (Props to creator!)

In your site source code create `layouts/partials/docs/inject/body.html` with content.

```
<script src="https://cdn.jsdelivr.net/gh/cferdinandi/gumshoe@5/dist/gumshoe.polyfills.min.js"></script>
<script>new Gumshoe('.book-toc a', { nested: true });</script>
<style>
.book-toc li.active > a {
    font-weight: bold;
}
</style>
```

You can adjust styles like you want. Also styles can be put to `_custom.scss` if you like.

![image](https://user-images.githubusercontent.com/5515443/85070370-f83a7900-b1b5-11ea-842c-04764bda0aee.png)

**Comment by jamesb93** [comment]
Wow, have to say that the support for this theme is unbelievable. I really appreciate your hard work and quick responses. The theme is helping me arrange my PhD into a web based format so making it look as good as it can be is paramount to me. Thanks!
