### ISSUE TITLE
Display parents in search results

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#236]
Show parents of a page in search results (each clickable) to be able to separate have more context about two pages having same or similar names.

I'd guess that we need to add parent tree in index in `search-data.js` in this case and then render it. We can then render each parent as clickable breadcrumb items. 

#230 has a screenshot attached to illustrate it.

I can try to implement this & create a PR, waiting for your feedback @alex-shpak .

**Comment by alex-shpak** [comment]
I did some experiment. Looks okay I think.
![image](https://user-images.githubusercontent.com/5515443/86602789-77e08a00-bfa3-11ea-80c2-3890908453fe.png)

**Comment by undergroundwires** [comment]
Looks awesome, baked in the theme in a nice & subtle way. 👏🏿 Is it breadcrumb? Can we see all of the the hierarchical or only one level above or only the top level? I'd vote for rendering all levels. And a just nice to have thing is to make them clickable 😊 I hope I'm not asking for too much. Thanks!

**Comment by alex-shpak** [comment]
Well, adding more levels would probably bring some complexity. Titles might get long and then entire breadcrumb would take very large space. So it must be cut or wrapped.

I made some immitation:
![image](https://user-images.githubusercontent.com/5515443/86636903-23560280-bfd5-11ea-8754-fd9f896863b7.png)

I think it doesn't look very clean 🤔

**Comment by undergroundwires** [comment]
I tested it and it works as expected & looks good. 🎉

Can I ask you have did you write hugo code in `search-data.js` to get all parents in hierarchical way? It'd be an awesome reference code.

**Comment by undergroundwires** [comment]
I tested it and it works as expected & looks good. 🎉

Can I ask you have did you write hugo code in `search-data.js` to get all parents in hierarchical way? It'd be an awesome reference code and very helpful 😳

**Comment by undergroundwires** [comment]
> Well, adding more levels would probably bring some complexity. Titles might get long and then entire breadcrumb would take very large space. So it must be cut or wrapped.

I agree that it does not look very good when cutting. However I'd still like to keep them without cutting as without context it's really like gambling when you click on a title. As a user, with just one parent you simply do not know where you're going, maybe it's a very content-specific situation for me but here's the illustration:

I might be the exception here but I'd like to have some kind of modularity instead of overriding two JS scripts.. I agree on you that having a function on `window` feels like a hack.

One idea that comes to my mind is intercepting default functions. But I cannot do it as `search.js` as well as others run in an anonymous function context. And intercepting is pretty much against open-closed principle.

So the question is how we can have JS part of the library more modular & extensible..

I guess a good way to open up book JS parts for extensions would be having `book` as global namespace, search as a module in it and having a method like `registerRenderFunction()`. Then we will not need any more `window` registration and have cleaner way to extend & make JS API:s accessible.

So instead of:

```js
(function () {
  const input = document.querySelector('#book-search-input');
  const results = document.querySelector('#book-search-results');
  // .. rest of the script ...
})();
```

Having this:

```js
book = book || {}; // Allows having more modules in book namespace
book.search = book.search || { // Allows reloading script more than once, dunno why
	const input = document.querySelector('#book-search-input');
        const results = document.querySelector('#book-search-results');
	// Rest of the script...

	return { 
		registerRenderFunction: registerRenderFunction // we export public APIs we want to expose
	}
}
```

You've been great at building & maintaining `hugo-book`. I'm pretty sure you will do the right decision, decision is yours to make 👍🏿 Have a great weekend!

**Comment by alex-shpak** [comment]
I usually try to link commit to issue, here is the change: https://github.com/alex-shpak/hugo-book/commit/f416a71bf8bb77e7af9ade9eea7fe3b662962290

As usual I will take some time to think through :) 
Some options come to mind:
 - There are `inject` templates, maybe add inject template into script. that will allow override some parts of logic
 - There is fresh-brand-new JS bundler built-in in Hugo 0.74, maybe we can figure something out of it.
