### ISSUE TITLE
Shortcode Error - HAHAHUGOSHORTCODE ... HBHB Not Found in menu/_index.md

### ISSUE THREAD

**Issue by webjoe** [alex-shpak/hugo-book#237]
When starting the preview server, I get WARNINGS like this for each link in my content/menu/index.md file:

`Building sites … WARN 2020/06/22 15:27:47 Page 'HAHAHUGOSHORTCODE-s0-HBHB' not found in 'menu/_index.md'
WARN 2020/06/22 15:27:47 Page 'HAHAHUGOSHORTCODE-s1-HBHB' not found in 'menu/_index.md'
WARN 2020/06/22 15:27:47 Page 'HAHAHUGOSHORTCODE-s2-HBHB' not found in 'menu/_index.md'
WARN 2020/06/22 15:27:47 Page 'HAHAHUGOSHORTCODE-s3-HBHB' not found in 'menu/_index.md'
WARN 2020/06/22 15:27:47 Page 'HAHAHUGOSHORTCODE-s4-HBHB' not found in 'menu/_index.md'`

It's laughing at me.... I don't know where this error is coming from.  Did I add "HAHA" somewhere by accident? 

I looked in both`/content/menu/_index.md` and `/themes/book/layouts/shortcodes/*` and couldn't find anything that relates to that warning. 

Since it's a warning, everything works fine, but I'm trying to figure out how to resolve this!

**Comment by alex-shpak** [comment]
Haha!

Hi! It's likely due to enabled `BookProtableLinks` param combined with `[{{ relref '' }}]()` link in `menu/_index.md`, so get rid of one of them :)

**Comment by webjoe** [comment]
That did the trick.  Thanks for this!
