### ISSUE TITLE
Error: Error building site: TOCSS: failed to transform "book.scss"

### ISSUE THREAD

**Issue by jo-m** [alex-shpak/hugo-book#240]
First, thank you for this awesome  minimal theme! I use it on my blog (not as book, though ;).

On recent 05c6336, hugo 0.73.0.

I executed the sample setup from the README:

```
hugo new site mydocs; cd mydocs
git init
git submodule add https://github.com/alex-shpak/hugo-book themes/book
cp -R themes/book/exampleSite/content .

hugo server --minify --theme book
```

As a result, I get

```
Building sites … WARN 2020/07/04 12:15:48 Expand shortcode is deprecated. Use 'details' instead.
Built in 72 ms
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss): resource "scss/book.scss_50fc8c04e12a2f59027287995557ceff" not found in file cache
```

**Comment by jo-m** [comment]
Nevermind, the problem was that I was not using the extended version.

**Comment by ciacicode** [comment]
Extended version of what?
I am facing the same issue, using AWS amplify. I have a feeling I need to do something different with the build script, and with the same error, I ended up here...
