### ISSUE TITLE
Expanded menu item is not collapsible 

### ISSUE THREAD

**Issue by yevgen-nykytenko** [alex-shpak/hugo-book#241]
Hi!
If to click on "[Collapsed"](https://themes.gohugo.io//theme/hugo-book/docs/example/collapsed) menu item that is in expanded state already it won't collapse to its initial collapsed state (so that child items is not displayed). 
Is this achievable? 
Thanks.

**Comment by alex-shpak** [comment]
Hi!
Right now there is no way to achieve it. Menu is statically generated, so it expanded by navigating to another page. This might change in future.

**Comment by undergroundwires** [comment]
Can be solved by #231

**Comment by alex-shpak** [comment]
Closing in favor of #231, to keep one issue on topic.
