### ISSUE TITLE
Allow specifying what pages to appear in search results (or not)

### ISSUE THREAD

**Issue by undergroundwires** [alex-shpak/hugo-book#242]
There are some pages I wouldn't want to appear in searches. Maybe we can introduce something like `BookSearchable = true (default)` frontmatter on pages so we can exclude stuff from the search by setting it to `false`?

**Comment by alex-shpak** [comment]
Hm, I'm not sure then should `BookHidden` pages go to search index or not. Probably some users don't want page in left menu but want it to appear in search 🤔  But then adding extra param for skipping indexing will create extra dimension in settings.

**Comment by undergroundwires** [comment]
I actually want both worlds:

- I want pages to appear on the left menu but not to appear in search for some pages.
- And for other pages (like privacy policy page), I don't want it to appear in the menu but want it to be searchable. I can live with not having them searchable if you decide not to index them but happier with having it searchable 😀

My opinion is that the safest bet is to go with different flags.

**Comment by alex-shpak** [comment]
New param `bookSearchExclude` 🎉
