### ISSUE TITLE
Japanese language code is wrong

### ISSUE THREAD

**Issue by astropenguin** [alex-shpak/hugo-book#243]
Hi @alex-shpak, thank you for creating such a nice theme!

I found that the Japanese language code should be `ja`, not `jp` (cf. https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).
So I would like to propose to (1) rename `i18n/jp.yaml` to `i18n/ja.yaml` or (2) copy `i18n/jp.yaml` to `i18n/ja.yaml`.
Because this may affect user's config files, I think that the second proposal would be nice to coexist two i18n configs for a while.

**Comment by alex-shpak** [comment]
Hi! Yes, best option would be to copy file to `ja.yaml` (Same happened with `zh` code). Will do.

**Comment by astropenguin** [comment]
Hi @alex-shpak, thank you for the update!
