### ISSUE TITLE
How to use translation by filename

### ISSUE THREAD

**Issue by Nagidal** [alex-shpak/hugo-book#244]
This is a bit related to issue #99 
I have tried to set up a minimal example site with two language files:

    content/_index.en.md
    content/_index.de.md

I have defined a default language (en) and a languages block in config.yaml. Hugo server starts, but it when I try to switch the language, it doesn't find the German index page.

Is this a hugo bug?

**Comment by alex-shpak** [comment]
Hi! From your description all sounds correct.
Can you please attach your language config and output of hugo command?

**Comment by Nagidal** [comment]
Thanks for bringing the hugo command up. Looks like I had too much trust in hugo. I used `hugo server -D --bind=192.168.2.135 --disableFastRender` because I have been working with hugo remotely through an ssh session. It seems that while Hugo generates multilingual content, all the links to the non-standard language pages point to `localhost:1313/...` and only the standard language content is bound to the IP I specified. I think this is a bug in Hugo server itself and has nothing to do with your awesome theme here. 

When I ran hugo server locally, it looked multilingual content could be previewed normally. I have not have enough time to thoroughly verify and confirm this, but once I do it I will post it on hugo as a bug report. I think here we can close this issue here.

**Comment by alex-shpak** [comment]
Good that it works 👍 
Check `baseURL` param, `--bind=` param just specifies what interface to bind, but `baseURL` is what used to generate links, you also can set it per language.

**Comment by Nagidal** [comment]
Thank you for the pointer to the --baseURL parameter of `hugo server` When I change my server start to `hugo server -D --disableFastRender --bind 192.168.2.135 --baseURL http://192.168.2.135` it works nicely. I get all the translations. Wonderful.
