### ISSUE TITLE
Tabs and Details won't allow in-line icons

### ISSUE THREAD

**Issue by stockphrase** [alex-shpak/hugo-book#245]
I'm using some fontawesome icons on the site I've built, but they don't work inside the "tabs" and "details" shortcodes. The icon is given a line and then the text appears beneath it.

Is it possible to add this functionality? Otherwise icons can't be used as intended.

**Comment by alex-shpak** [comment]
Hi!
There is some magic around shotcodes markdown rendering. Can you please include markdown snippet  you try, so I can reproduce it?

**Comment by stockphrase** [comment]
It is a bit involved. 

- My shortcode:

```
<!-- Load fontawesome only once per page -->
{{ if not (.Page.Scratch.Get "fontawesomeLoaded") }}
  {{ .Page.Scratch.Set "fontawesomeLoaded" true }}
  <script defer src="/css/all.js"></script>
{{ end }}
<i class="fas {{ range $element := .Params }} fa-{{ $element }} {{ end }}"></i>

```
- Minimal working example:

```
---
weight: 1
bookFlatSection: true
bookToc: true
bookHidden: true
title: "Test"
---

Outside of the tabs environment, this works as expected:

{{< fa question-circle  >}} *Question of the Day*: Something you love/hate? 


But inside tabs environment, this breaks the line:

{{< tabs "Week-One" >}}
{{< tab "9.14" >}}

### Course orientation

{{< fa question-circle  >}} *Question of the Day*: Something you love/hate? 


{{< /tab >}}
```

- Image of problem:

![book-issue](https://user-images.githubusercontent.com/2568776/87609835-a829d600-c6d1-11ea-941c-8808dbe33b38.png)

**Comment by alex-shpak** [comment]
I tried it and this is what I got
![image](https://user-images.githubusercontent.com/5515443/87768941-2fd02b80-c81d-11ea-9acf-590ba166576e.png)

Which version of hugo you use?
Also something to check: make sure you don't have extra whitespaces inside `fa` shortcode, they will be interpreted by markdown renderer as new lines

e.g. if you have double new line at the end of `shortcodes/fa.html` file.

**Comment by stockphrase** [comment]
Alex, you genius! I had two blank lines at the end of the shortcode. Removing them fixed the issue! Thank you so much.

**Comment by stockphrase** [comment]
Ugh. One last issue. While removing the extra lines in the shortcode fixed the issue above, I'm having a related problem. Using the icon in an ordered list within the tabs environment breaks the list.

So, this works as expected:
- {{< fa question-circle  >}} This is a test.

But this doesn't:

{{< tabs "Week-One" >}}
{{< tab "9.14" >}}

### Course orientation

- Item one
- Item two
- {{< fa question-circle  >}} This is a test.

{{< /tab >}}

![Screenshot from 2020-07-18 12-54-43](https://user-images.githubusercontent.com/2568776/87857593-eef81580-c8f5-11ea-9cbc-b35f809ca671.png)

**Comment by alex-shpak** [comment]
Well, might be new lines again :) 
Try this, in your shortcode
```
{{- if not (.Page.Scratch.Get "fontawesomeLoaded") -}}
  {{- .Page.Scratch.Set "fontawesomeLoaded" true -}}
  <script defer src="/css/all.js"></script>
{{- end -}}
```

add `-`es in `{{...}}` tags, like `{{- -}}` that will remove leading/trailing whitespaces.

**Comment by alex-shpak** [comment]
I hope it helped, I will close this issue. Write me here if you want it re-opened.
