### ISSUE TITLE
Search feature fails with FlexSearch 404 error

### ISSUE THREAD

**Issue by johnclary** [alex-shpak/hugo-book#246]
Thanks for this excellent theme!

It seems that the search functionality is broken. I can repeat this on your demo site, as well as my own. When I click into the search box, the loading gif starts spinning, but the search itself is unresponsive.

It appears that the problem is that flexsearch.min.js is not found. Maybe a problem with the [`relUrl`](https://github.com/alex-shpak/hugo-book/blob/f416a71bf8bb77e7af9ade9eea7fe3b662962290/assets/search.js#L49)?

Here's the error msg:

GET https://pydoc-markdown.readthedocs.io/flexsearch.min.js net::ERR_ABORTED 404
loadScript @ en.search.min.ac0d2ece0f0d28f23400e605a9e47f9eeb5989acf7a509606db5695be8b2babe.js:10
init @ en.search.min.ac0d2ece0f0d28f23400e605a9e47f9eeb5989acf7a509606db5695be8b2babe.js:6
en.search.min.ac0d2ece0f0d28f23400e605a9e47f9eeb5989acf7a509606db5695be8b2babe.js:10 GET https://pydoc-markdown.readthedocs.io/en.search-data.min.e736b506f763fa8bc0981e3d0983630a64506164945f8613e91aa1a85e1fec3d.js net::ERR_ABORTED 40

**Comment by alex-shpak** [comment]
Hi!
Theme uses [hugo pipes](https://gohugo.io/hugo-pipes/) to process JS and CSS files, and generated link is dependent on `baseURL` param.
 
Make sure that you set `baseURL` in toml/yaml or flag when generating site.
in your case `baseURL: https://pydoc-markdown.readthedocs.io/en/latest/`

**Comment by alex-shpak** [comment]
So I guess this option is off somewhere
https://pydoc-markdown.readthedocs.io/en/latest/docs/renderers/hugo.html#baseurl

**Comment by NiklasRosenstein** [comment]
Hey @alex-shpak , setting the `baseURL` to `https://pydoc-markdown.readthedocs.io/en/latest/` fixes the search. But I think this will break again when specific versions of the documentation are published under another URL (e.g. `/en/v3.2.0`). 😞

**Comment by NiklasRosenstein** [comment]
Here's an example of the problem when I set the `baseURL`: https://pydoc-markdown.readthedocs.io/en/develop/

When you click on one of the menu entries, it will take you to the page on `/en/latest` instead. Also the search `*.js` files are loaded from `/en/latest` instead of `/en/develop`.

**Comment by alex-shpak** [comment]
Well, from your description sounds like `baseURL` is still set to `https://pydoc-markdown.readthedocs.io/en/latest/` and site is deployed to `https://pydoc-markdown.readthedocs.io/en/develop/` 🤔 

I think it is not something I can't fix in theme, `baseURL` is hugo param which tells theme how to create permanent links.
For example for version `v3.2.0` you will need to set corresponding `baseURL` using scripting or something.

**Comment by alex-shpak** [comment]
Basically if `baseURL` is `https://pydoc-markdown.readthedocs.io/en/develop/` generated link to `js` files would be `/en/develop/name.js`

**Comment by NiklasRosenstein** [comment]
I see your point -- what I was trying to say is that I can see this as a common use case to have multiple versions of a documentation. Requiring that the `baseURL` is adjusted respectively requires either some form of `sed` or explicit support for this scenario from downstream tooling. If the theme would support the case when `baseURL` is simply not set, that would make it a bit easier. 

I don't know too much about Hugo or how it generates links. I suppose if it doesn't support relative links to the JS files then it won't work without `baseURL`. 😄

**Comment by alex-shpak** [comment]
Well, this is how hugo built. ¯\_(ツ)_/¯ 
You can read docs about `absURL` and `relURL` here https://gohugo.io/functions/relurl/
So I think setting proper `baseURL` is the only good option.

**Comment by alex-shpak** [comment]
Hi!
Did you solve your issue? Can it be closed?

**Comment by NiklasRosenstein** [comment]
Hey, I managed to solve the issue by generating the base URL dynamically. Thanks!

**Comment by alex-shpak** [comment]
Cool, I will close then.
