### ISSUE TITLE
implement shortcode in Rmd

### ISSUE THREAD

**Issue by matteodelucchi** [alex-shpak/hugo-book#247]
For a certain project, I have to use R markdown files instead of Markdown.
To profit of the great shortcodes implemented in this theme, I followed the guidelines from [blogdowns Shortcode tutorial](https://bookdown.org/yihui/blogdown/content.html#shortcode). However, it seems that they are not compatible in that way.
How can I use the shortcodes from the hugo-book theme within .Rmd files?

**Comment by alex-shpak** [comment]
Hi!
Unfortunately I don't have experience with blogdown/rstudio.

What error you get? or what is output?

**Comment by matteodelucchi** [comment]
I don't get an error per se. It just displays the plain html code of the shortcode snippet when I look at the .html compiled version of the .Rmd file.

**Comment by alex-shpak** [comment]
Hm, well, try do use `tweet` shortcode as in docs, if it works we might try to find difference, if `tweet` shortcode gives same result maybe you need to look at blogdown params.

**Comment by alex-shpak** [comment]
Hi! Can be closed?

**Comment by matteodelucchi** [comment]
Close for the moment. I'll reopen the issue in case of experiencing the error again. Working currently on an other project.
