### ISSUE TITLE
.GitInfo not showing current commit

### ISSUE THREAD

**Issue by ChristopherBarrington** [alex-shpak/hugo-book#255]
I have made a new site using RStudio>File>New project and specified `alex-shpak/hugo-book` as the theme in the dialogue. The only change I made to the default config was to set `baseURL='/'`. Then I go to the site directory, `git init` and commit some changes.

At the footer of the webpage I would like to present a commit ID so that a user can reference the version of the webpage they are looking at. So I copy `footer.html` from the theme layouts into `layouts/partials/docs/footer.html` and add the following code within the `<div class="flex flex-wrap justify-between">`:

```
<!-- add the GitHub commit ID and author -->
{{ if .GitInfo }}
  <div><hr>{{ .GitInfo }}</div>
{{ end }}
```

(I only want use `.AbbreviatedHash` and `.AuthorName` in the final version)

But when the page is rendered with the new footer, it only shows the initial commit. Any commits that I have made since the first are not shown. The following is the output in the web page:

```
{af0b2376d63f72873b4b12c4a88affe7b452017d af0b237 initialised repo Christopher Barrington 2020-07-23 09:58:45 +0100 BST 2020-07-23 09:58:45 +0100 BST}
```

and the commits in the repo:

```
$ git log
commit 3685bf2ed41f57e03aba962a1f36184a5dfb19d7 (HEAD -> master)
Author: Christopher Barrington
Date:   Thu Jul 23 09:59:35 2020 +0100

    added footer layout

commit af0b2376d63f72873b4b12c4a88affe7b452017d
Author: Christopher Barrington
Date:   Thu Jul 23 09:58:45 2020 +0100

    initialised repo
```

I thought the `.AbbreviatedHash` would be `3685bf2` not `af0b237` as is listed in the `.GitInfo`?

Have I misunderstood something or failed to configure something? Thanks for your help - is this the right place to ask for this help? Sorry if not!

Chris

**Comment by alex-shpak** [comment]
Hi!
`.GitInfo` is information about commit when that specific markdown file is last changed. It's not head commit of branch.

**Comment by ChristopherBarrington** [comment]
my misunderstanding. and thanks for the fastest response ever!
