### ISSUE TITLE
[Feature] Inject content before/after the table of contents

### ISSUE THREAD

**Issue by NotWoods** [alex-shpak/hugo-book#257]
Similar to menu-before/menu-after.html, it would be nice to have some way to inject HTML before/after the table of contents on the right sidebar. I poked around a little and it seems this would require some CSS changes, as the current CSS relies on the HTML structure of Hugo's .TableOfContents

**Comment by alex-shpak** [comment]
Hi! yes, due to `.TableOfContents` and DOM structure generated by hugo there is no ToC inject partials now. Also ToC is not always displayed (based on page type or params), so I decided to not add them.

**Comment by alex-shpak** [comment]
I can try to look at it i you think this is necessary feature.

**Comment by NotWoods** [comment]
I'd like this feature as most of my pages show the TOC, and there's more space available there than the left sidebar.

**Comment by undergroundwires** [comment]
+1 for this
