### ISSUE TITLE
Broken anchors when using headings in nav menu

### ISSUE THREAD

**Issue by R0quef0rt** [alex-shpak/hugo-book#259]
Hugo version: 0.73.0
Book version: v8

Hello,

After upgrading to v8 of your theme, I've found that anchors in the nav menu are rendered on a second line. This is what it looks like with default CSS settings:

https://imgur.com/a/FdSXh75

Is this by design?

If so, is there any way to change it, such that the anchor is rendered at the end of a line, like it is everywhere else? We really think it looks ugly with the anchor on a second line.

Thanks for any help you can provide. Keep up the good work.

**Comment by alex-shpak** [comment]
Hi!
I guess you are using bundle menu? (as markdown file). Well, I kinda forgot about it when was adding link anchors.
I would suggest to change to file-tree menu, or native hugo menu. I plan to deprecate bundle (markdown) menu some day.

**Comment by alex-shpak** [comment]
You can customize partial that renders anchors and remove anchors, as an option.
Here: https://github.com/alex-shpak/hugo-book/blob/master/layouts/_default/_markup/render-heading.html

**Comment by R0quef0rt** [comment]
Thanks. The custom partial worked for me.

It's too bad you'll be deprecating the leaf bundle menu some day. We really like having the option to hand-tailor the nav menu via standard markdown, instead of Hugo-specific stuff. It makes it more declarative, and portable.

Anyway, thanks for the quick response.

**Comment by alex-shpak** [comment]
Well, it will stay for some time. Issue is that it is yet another thing to support and features like folding in menu are not working in markdown menu.
