### ISSUE TITLE
Please allow relative links

### ISSUE THREAD

**Issue by cbluth** [alex-shpak/hugo-book#26]
I would like to serve this site from a non-root directory (kind of like `example.com/hugo-book/`), but when I do, it has formatting issues:

![image](https://user-images.githubusercontent.com/6709636/53079096-fdba7d00-34f5-11e9-9cfc-926ccac31a91.png)

compared to this:

![image](https://user-images.githubusercontent.com/6709636/53079116-057a2180-34f6-11e9-9c15-1b239ab61ea9.png)

**Comment by alex-shpak** [comment]
Hi!

Can you please share some details of your config/setup?
It works for me in [exampleSite](https://github.com/alex-shpak/hugo-book/tree/master/exampleSite), with `hugo server --themesDir ... --baseURL=http://0.0.0.0:1313/example/`

**Comment by cbluth** [comment]
admittedly, i am a hugo newb, and most likely i probably have done something wrong.

My setup uses ipfs `dnslink`, and i have pointed it to cloudflares ipfs public gateway, you can read more about it here: 
- https://developers.cloudflare.com/distributed-web/ipfs-gateway/connecting-website/
- https://blog.cloudflare.com/distributed-web-gateway/

Anyways, my website is located here:
- https://cobin.io/ (this link will only work properly when my laptop is open, until i move the content to a more permanent host)
^ and this seems to be formatting properly.


but, the same content is available here:
- https://cloudflare-ipfs.com/ipns/cobin.io (this link will only work properly when my laptop is open, until i move the content to a more permanent host)
- https://ipfs.io/ipns/cobin.io (this link will only work properly when my laptop is open, until i move the content to a more permanent host)

^ and these two are not formatted properly

I will include some screenshots in case you try the links when i am not using my laptop.

![image](https://user-images.githubusercontent.com/6709636/53235126-5ffbb500-3691-11e9-8338-dac4b3850be9.png)


![image](https://user-images.githubusercontent.com/6709636/53235138-668a2c80-3691-11e9-92d4-0b39b828e265.png)

**Comment by alex-shpak** [comment]
Well, theme supports relative link, few tips to help you with debugging:

1. Make sure to use latest commit of theme.
2. Use `relUrl`, `RelPermalink` everywhere
3. Your `baseURL` parameter in config or CLI param should be `https://cloudflare-ipfs.com/ipns/` or similar. (at least include `/ipns/` in the end)
4. Check which urls are wrong in HTML code, for debugging

**Comment by alex-shpak** [comment]
Hi! I hope you solved problem. Will close this for now.
Feel free to re-open if you need some assist.
