### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by EloFran** [alex-shpak/hugo-book#262]
when I try to install it in both vercel and netfily I get this error:

`Error: Error building site: "/vercel/1cefbe94/content/_index.md:8:1": failed to extract shortcode: template for shortcode "columns" not found`

**Comment by alex-shpak** [comment]
Hi!
This might happen if hugo didn't find theme, please make sure that:
 - theme is in correct folder
 - theme name is not misspelled

**Comment by EloFran** [comment]
thx the first,
I have installed your theme locally and it works correctly there, on the other hand if I upload it to git and try to put it online with vercel or netlify that is when it returns that error.
I don't mind starting from scratch, could you tell me in github that it is tested on vercel or netlify working?
Thank you

**Comment by alex-shpak** [comment]
Not sure about Vercel, but it should work on `Netlify`.
https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

**Comment by alex-shpak** [comment]
Hi! Can issue be closed?
