### ISSUE TITLE
questions about the ServiceWorker implementation and errors in lighthouse audit

### ISSUE THREAD

**Issue by ghost** [alex-shpak/hugo-book#263]
I've been trying (unsuccessfully) to fix some issues shown by [Lighthouse](https://developers.google.com/web/tools/lighthouse/) when I've enabled Service Workers in this theme.

I also observed the following line in [sw.js](https://github.com/alex-shpak/hugo-book/blob/master/assets/sw.js#L3)

```{{ if eq .Site.Params.BookServiceWorker "precache" }}```

If I understand this correctly, this means that the site pages will be cached as soon as the website loads if the value of `BookServiceWorker` is `precache` rather than `true`. Still, even if I set this value to `precache`, I still can't get rid of the following error. Any ideas about what's wrong?

```start_url does not respond with a 200 when offline. The start_url did respond, but not via a service worker.```

![notes-before](https://user-images.githubusercontent.com/67443683/89833782-4436e800-db7f-11ea-9acc-af3579bcb2b9.png)

**Comment by alex-shpak** [comment]
Hi!
I will need to debug it, with `precache` setting it is likely showing `start_url` error because service worker is not waiting for cache. [here](https://github.com/alex-shpak/hugo-book/blob/master/assets/sw.js#L11)
