### ISSUE TITLE
Render site strangely on Netlify

### ISSUE THREAD

**Issue by sodacorsair** [alex-shpak/hugo-book#267]
Hi, I deployed [a test site](https://adoring-knuth-2331cb.netlify.app/docs/example/) on Netlify, where all deployment settings are default except in Environment Variables set HUGO_VERSION as v0.74.3.
You could see a strange phenomenon when you switch pages within the site I deployed, the text seems to become sort of larger and then recover, whereas it runs normally in local server. 
It's strange that your demo in Hugo official site which also runs on Netlify don't experience the change of text size when loading page, did I miss something?

**Comment by alex-shpak** [comment]
Hi!
So, likely font change happens because of https://github.com/alex-shpak/hugo-book/blob/master/assets/_fonts.scss#L6
`font-display: swap;`, this makes fonts to fallback before new fonts loaded via network, in ideal case on second load fonts should be cached and not swap.

Not sure for your specific case, things that come to mind:
1. Cache headers or etags.
2. ServiceWorker.

**Comment by sodacorsair** [comment]
I download code and deploy on Netlify again to make sure there's no other modifications, still no change happens.
However I observed that after shutting down local server for about half an hour the local deployed site becomes visited slowly and reproduced same phenomenon, I guess in local enviroment it already exists this problem but covered by fast loading speed.
So there's anything that change cache, I have tried asset optimizations in Netlify but none of that worked.
This is [the deployed repository](https://github.com/sodacorsair/blog.of.sodacorsair).

**Comment by alex-shpak** [comment]
Try to disable ServiceWorked and see if it helps.

**Comment by sodacorsair** [comment]
Not worked... Thanks anyway.

**Comment by alex-shpak** [comment]
I think it actually worked, you need to delete existing service-worker in your browser.

**Comment by sodacorsair** [comment]
Unregister service worker and worked, bravo. I assumed that service worker stores the initial website static assets and intercepts subsequent requests for server which just returns initial cache and causes the font swap, is it right?

**Comment by alex-shpak** [comment]
This service worked is implemented as network-first, so it provides cache when there is no network. Not sure why it affected fonts like this, some debugging is needed. It is still experimental feature, so probably better to turn it off for now.
