### ISSUE TITLE
Feature Req: support "info" headings on post tags?

### ISSUE THREAD

**Issue by sgoley** [alex-shpak/hugo-book#269]
Feature description:
Is it possible to use an `_index.md` document to "sticky" a description or heading for a particular tag?

Background:
Hugo has support for a "tags" functionality on all documents. 
Those tags become available at "baseurl"/tags. Example: `Localhost:1234/tags/`
The directory equivalent is `projectdir/content/tags/`. My intuition is that I would be able to place an `_index.md` at the location: `projectdir/content/tags/<tagname>` in order to add a header section, description etc. This did not work. Interested in understanding what it would take to support functionality like this because I'd like to explain or add meta information about some particular tags.

2nd Note:
I did see that if I place an `index.md` at `projectdir/content/tags/<tagname>`, the dynamically built tag "index" is completely replaced and no longer functions. (Naturally)

**Comment by alex-shpak** [comment]
Hi!
I don't think it is possible in hugo out of the box. Taxonomy pages are special kind and they are not rendered from markdown files.

You can probably hack templates to make it work, but not naturally.
- Create bundle page
- Create md file per tag
- Using hugo function find that bundle and desired markdown file
- Render it inside of taxonomy template

I didn't try to make that worl, just speculation.

**Comment by alex-shpak** [comment]
Closing this issue, poke me if you want it re-opened.
