### ISSUE TITLE
Responsivness issues in mobile view

### ISSUE THREAD

**Issue by caseneuve** [alex-shpak/hugo-book#27]
Hi,

I am really fond of your theme and try to build a site with it. 

I found that text doesn't scale properly on my phone (720x1280 screen) with vertical view. It only works with horizontal view (screenshots attached). I can't make it smaller manually (although it works with bigger displays -- I checked the behavior on 1080x2160 screen where text didn't scale automatically but could be rescaled manually to fit the screen).

Is it "fixable"?

![720x1280 vertical](https://user-images.githubusercontent.com/25939958/53337208-131e1580-3901-11e9-84cf-3de11beb7de8.png)

![720x1280 horizontal](https://user-images.githubusercontent.com/25939958/53337247-2630e580-3901-11e9-965f-d3c19b51bdef.png)

**Comment by alex-shpak** [comment]
Hi!

Which device and android version you use for test?
I targeted minimum screen width as [400px](https://github.com/alex-shpak/hugo-book/blob/master/assets/book.scss#L13), also there is required meta tag [here](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/html-head.html#L2)

Do you, by chance, set font/view scaling in android?

**Comment by alex-shpak** [comment]
From screenshot looks like it's header getting out of screen, right?
Blocks of code are scrollable horizontally, and this is intentional

**Comment by caseneuve** [comment]
The smaller one is Huawei ALE-L21, Android 6.0, bigger is Huawei RNE-L21, Android 8.0.0.

I made another screenshot where the problem is more obvious. Look for example on phrase "arma sorori" or "vetuere aliis, modo":

![hugobookvert2](https://user-images.githubusercontent.com/25939958/53338821-f71c7300-3904-11e9-8646-d9eea12533ab.png)

So it's header and body text which don't scale.

I don't recall setting any font/view scaling in my devices.

**Comment by caseneuve** [comment]
Update: the issue concerns Firefox browser, on Chrome I can scale down manually.

**Comment by caseneuve** [comment]
To have proper rendering in Firefox I have to enable scaling fonts to system fonts in the browser settings and set the system font size to "small".

**Comment by alex-shpak** [comment]
I see, I will try to reproduce.

**Comment by bubbleguuum** [comment]
Same issue on Samsung devices with Samsung Internet as browser: the page is truncated a bit to the right and you can pinch to zoom out and see the full page fitting exactly screen width.

**Comment by alex-shpak** [comment]
I have a suggestion, it might be due to pixel ratio. For example, right now minimal width is set to `400px`, screen of test device is `720px` with pixel ratio `2`, which will make effective rendering into `360px`

This is how it looks on `360px`
![image](https://user-images.githubusercontent.com/5515443/54746514-a0851a80-4bcc-11e9-9ad4-46181c398cd4.png)

Quite similar. I will try to confirm this.

**Comment by bubbleguuum** [comment]
Yes it looks exactly like this on my Samsung S9.

**Comment by alex-shpak** [comment]
I pushed an updated to set min width to `320px`, should be enough for most of devices

**Comment by caseneuve** [comment]
@alex-shpak It seems to solve the problem in all my devices, both in Chrome and Firefox, thanks.

**Comment by alex-shpak** [comment]
👍 I will close then, feel free to re-open if it pops up again.
