### ISSUE TITLE
order of posts in left sidebar menu

### ISSUE THREAD

**Issue by ChristopherBarrington** [alex-shpak/hugo-book#270]
Is it possible to change the order of posts in the left sidebar so that they are reverse chronologically ordered? At the moment I use `weight` to order the sections as I want and the posts are ordered newest at the top within each section. I would like to change that so that the newest post (by the `date` in the front matter) is at the bottom of the section list.

I have tried to find the solution and came across the help [on gohugo.io](https://gohugo.io/templates/lists#reverse-order) but I cannot understand how/where to make these changes with respect to my site using `hugo-book`.

Thank you very much,

Chris

**Comment by alex-shpak** [comment]
Hi!
It is supposed to be like that out of the box 🤔  Theme is using default hugo's ordering https://gohugo.io/templates/lists/#default-weight--date--linktitle--filepath

I created 3 pages, `3rd` has latest date
![image](https://user-images.githubusercontent.com/5515443/92312826-f9b15b80-efc4-11ea-8a25-815b546691d2.png)

Anyway, [here](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html#L17) is where loop over pages happens.

**Comment by ChristopherBarrington** [comment]
Thank you. I was not clear in my original post. What I wanted to achieve was the most recent post at the bottom of the list. So in your example, '1st' would be at the top and '3rd' at the bottom. 

Using the link you provided I can copy the partial into layouts and change the line to:

```
{{ range (where .Section.Pages "Params.bookhidden" "ne" true).Reverse }}
```

to get what I wanted but it seems as though this could be an option in a configuration file somewhere rather than a new partial for such a small change.

Thanks again!

**Comment by alex-shpak** [comment]
Yep, that should work.
