### ISSUE TITLE
Error: Error building Site

### ISSUE THREAD

**Issue by phillipgibson** [alex-shpak/hugo-book#271]
Just started off trying to use Hugo and this theme. Seems pretty straight forward but when I run the command hugo server --minify --theme book  I get the following error:

$ hugo server --minify --theme book
Built in 18 ms
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss): resource "scss/book.scss_50fc8c04e12a2f59027287995557ceff" not found in file cache

**Comment by alex-shpak** [comment]
Hi!
Please make sure that you use Hugo extended version. `sass` transformation is not available in regular version.

Otherwise, to make it work with regular versiob you need to copy these:
https://github.com/alex-shpak/hugo-book/tree/master/exampleSite/resources/_gen/assets/scss
to your site.

**Comment by alex-shpak** [comment]
Closing this issue, write here if you need further asistance.
