### ISSUE TITLE
Would it be possible to skip interval page?

### ISSUE THREAD

**Issue by peilingjiang** [alex-shpak/hugo-book#272]
The menu collapse feature is really helpful, however, for most of the cases, I just need it to help organize and clean the side bar, while don't really need an extra page for the section. Would it be possible to enhance this feature so that user will be sent to the first item in the section directly? Or, the section name will only be a trigger to fold and unfold the section, instead of a link to any page? Thanks.

**Comment by alex-shpak** [comment]
Hi!
There is discussion here: https://github.com/alex-shpak/hugo-book/issues/231

Can't say now if we will find way to collapse menus without JS and changing page.
Skipping to first page if collapsed page is empty should be not hard to do.

**Comment by alex-shpak** [comment]
Some improvement was pushed to master, we can continue discussion in #231.
Closing this one.
