### ISSUE TITLE
App logo not overwritten

### ISSUE THREAD

**Issue by peilingjiang** [alex-shpak/hugo-book#273]
As shown in the screenshot, the favicon is replaced by the custom `favicon.png` image in `static`, while the Chrome app logo is still the default one.

<img width="401" alt="book_screenshot" src="https://user-images.githubusercontent.com/25191575/93031440-d3a93e00-f5f8-11ea-95df-d0f8a42cbed2.png">

**Comment by alex-shpak** [comment]
Hi!
If you canged `favicon.svg` after enabling service-worker - service-worker will cache old favicon. 
https://github.com/alex-shpak/hugo-book/blob/master/assets/manifest.json#L11

You need to uninstall service-worker in browser and visit page again. New visitors shuold get new icon.

**Comment by peilingjiang** [comment]
Thanks for the clarification!
