### ISSUE TITLE
Nav to pre page and next page

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#274]
like this

![image](https://user-images.githubusercontent.com/29562589/93079321-84c5dc00-f6be-11ea-95ec-c3f6ee705819.png)
https://golang.design/under-the-hood/zh-cn/part1basic/ch02life/cmd/

implement on:
https://github.com/golang-design/under-the-hood/blob/8db0a5aec71a2b5740cff46d5cee150b2032afd3/website/themes/book/layouts/partials/zh-cn/inject/footer.html

**Comment by alex-shpak** [comment]
Hi!
There is ongoing discussion #165 and branch `feature/prev-next` for similar functionality

**Comment by alex-shpak** [comment]
I will close this one in favour of #165.
