### ISSUE TITLE
Question: How do i add sliders into this layout? 

### ISSUE THREAD

**Issue by mindyhuynhx3** [alex-shpak/hugo-book#275]
i found this shortcode that allows you to insert slides of images from a folder. For some reason the pictures just aren't showing up. any help would be greatly appreciated.

https://github.com/tbiering/hugo-slider-shortcode

**Comment by alex-shpak** [comment]
Hi!
Do you have deployed site where I can check for errors? Or example source code.

**Comment by mindyhuynhx3** [comment]
Hi Alex, Thanks for your response! i found the issue. I was trying to put the images in a different folder than their "/static/" folder. I thought that changing the code to point to a different folder would be enough. I really did need to have it in /static/ folder.

thank you so much for your response!
