### ISSUE TITLE
Page auto-scaling on a big screen

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#277]
When I open the page on a big screen, the page will automatically stretch, instead of leaving gaps on both sides.

![image](https://user-images.githubusercontent.com/29562589/95651000-a5e0e780-0b19-11eb-8f5e-2edecf3cc056.png)

**Comment by alex-shpak** [comment]
Hi! Should be possible with tweaking scss vars. What do you expect to happen to content? Strech readable area, or leave gaps between menu and content?

Tho, I belive the current behaviour is good :)

**Comment by ikingye** [comment]
Actually, I expect to strech readable area.

**Comment by alex-shpak** [comment]
Hi!
To do so in `assets/_variables.scss` set `$container-max-width: 100%` or other desirable value.
