### ISSUE TITLE
Change color of Warnings

### ISSUE THREAD

**Issue by YeetKuneDo** [alex-shpak/hugo-book#279]
I'm trying to change the color of the yellow warning box to green, and I've identified that code for the color settings exists in
 \resources\_gen\assets\scss\book.scss_50fc8c04e12a2f59027287995557ceff.content and in \assets\_defaults.scss, but changing those values doesn't seem to make the color change when the site rebuilds. Where do I find the code necessary to make that change?

**Comment by alex-shpak** [comment]
Hi!

It should work. You need to change those https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L25-L29.
You can do it without forking by creating `assets/_variables.scss` in your site.

**Comment by YeetKuneDo** [comment]
I tried that. It did not work.

**Comment by alex-shpak** [comment]
Hi!
Don't change or overwrite `_defaults.scss`

Put this to `_varaibles.scss`
```
$hint-colors: (
  info: #6bf,
  warning: #6c0,
  danger: #f66,
);
```

Note removed `!default`

**Comment by alex-shpak** [comment]
I will close the issue, write here if you want it re-opened.
