### ISSUE TITLE
Put footer after comments

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#280]
Now `inject/footer.html` is on top of `comments.html`.
How to put footer after comments (at the very bottom)?

**Comment by alex-shpak** [comment]
Hi!
Well, there are few ways:

- Change `layouts/partials/docs/comments.html` and add content after comments
  ```html
  <!-- This partial can be replaced to support other commenting engines -->
  {{ template "_internal/disqus.html" . }}
  <div>Other footer</div>
  ```

- Change `listof` and `single` layouts https://github.com/alex-shpak/hugo-book/tree/master/layouts/_default and re-define comments block
  ```html
  {{ define "comments" }}
    {{ if and .Content (default true (default .Site.Params.BookComments .Params.BookComments)) }}
    <div class="book-comments">
      {{- partial "docs/comments" . -}}
    </div>
    {{ end }}
    <div>Other footer</div>
  {{ end }}
  ```
