### ISSUE TITLE
Inserting an empty line in menu in file tree mode

### ISSUE THREAD

**Issue by BruceBoDing** [alex-shpak/hugo-book#282]
Hi Alex, thanks for this amazing theme. I like it a lot. 
I've seen that in Leaf bundle menu mode, you could use a `<br />` to add an empty line in the menu. 
But how could I add empty lines while in file tree mode? (I use file tree mode because I need collapse section, so the question would also be will you add the bookCollapseSection function to leaf bundle menu mode in the future? )
Thanks!

**Comment by alex-shpak** [comment]
Hi! Thanks.

Unfortunately there is no similar feature. Probably the closest thing to adding spaces is a flat section, like `Shortcodes` section here https://themes.gohugo.io/theme/hugo-book/

You perhaps can customize menu and add param to insert space in template, if you really want. [Here](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html)

P.S. I think to remove the leaf menu in some future, it is far behind in features and many features are hard to implement over markdown menu.

**Comment by BruceBoDing** [comment]
Thank you so much Alex! I'll give it a try.
