### ISSUE TITLE
search is broken if not served on root

### ISSUE THREAD

**Issue by colinbrownec** [alex-shpak/hugo-book#283]
I am trying to use the hugo-book theme and host the final documentation in a subdirectory of the root domain.

However when this is done the scripts needed for the search box fail to load when the search box is clicked.
This behavior is also seen on the gohugo.io website preview of this theme at https://themes.gohugo.io/theme/hugo-book/

I think the behavior comes from the [`loadScript`](https://github.com/alex-shpak/hugo-book/blob/master/assets/search.js#L49) functions being given absolute URLs.

On the theme preview page you can see this results in 404s for both
- https://themes.gohugo.io/flexsearch.min.js
- https://themes.gohugo.io/en.search-data.min.fa36e324a0e5d0afc0130e940a7bab346aaa53bfaa20a68f746242a6c2532c96.js

when instead the URLs should be
- https://themes.gohugo.io/theme/hugo-book/flexsearch.min.js
- https://themes.gohugo.io/theme/hugo-book/en.search-data.min.fa36e324a0e5d0afc0130e940a7bab346aaa53bfaa20a68f746242a6c2532c96.js

I believe the URLs are absolute files because the URLs are generated as relative URLs, but relative to the `assets/search.js` file.
If I think about it, I am not sure how this is expected to work as relative URLs because the `search.js` file can be loaded from any page of the documentation.

---

I have tried adding javascript before the call to `loadScript` that dynamically constructs the URLs based off the generated URL for the `favicon.png`. This will correctly load the javascript files, but then the same problem exists for links inside the generated `en.search-data.min.[hash].js` file.

---

I have also tried different settings for the Hugo options of  `baseURL` as well as the `relativeURLs` & `uglyURLs` but have not found any success.

---

I apologize if I am missing something as I am new to Hugo, but do you have any tips on how to fix this or a workaround?

**Comment by alex-shpak** [comment]
Hi!
https://themes.gohugo.io/ doesn't set `baseURL` properly, that's why search doesn't work there.
But on regular case `baseURL` should make URLs correct. Do you have your site source published somewhere, so I can take a look?

When I try on [exampleSite](https://github.com/alex-shpak/hugo-book/tree/master/exampleSite) with `--baseURL=http://localhost/path` it works as expected.

**Comment by alex-shpak** [comment]
Hi! Closing this issue for now. Comment if you want it reopened.
