### ISSUE TITLE
book-brand not ending with trailing /

### ISSUE THREAD

**Issue by peterfarrant** [alex-shpak/hugo-book#284]
We use Azure blob storage to serve out the website content
The issue I am having at the moment is that this requires the trailing / on all the urls to work - and being 'dumb' storage does not allow any rewrite rules I could easily use on a full webserver

if I go to http://example.com/subsite/  it maintains the trailing / except when I click on the logo 'book-brand' and then it returns me to http://example.com/subsite   - no trailing space
(note my base URL includes the trailing /)

I found the relevant partial brand.html but could not see how to ensure this always has a trailing space
```
  <a href="{{ .Site.BaseURL | relLangURL }} ">
```
For a subsite I could amend to 
```  
<a href="{{ .Site.BaseURL | relLangURL }}/ ">
```
and that works fine for a subsite returning the link as '/subsite/'
but then it goes wrong for the root and returns '//'

Is there an easy way to adjust this to append a trailing / if there is not one ?
(apologies if I am asking in the wrong place - please point me to where I should be

**Comment by alex-shpak** [comment]
Hi!
Seems like `relLangURL` is eating trailing `/`. You can try few options:
1. In case if you have single host (domain) do `<a href="{{ .Site.BaseURL | absLangURL }}">`, that will make URL absolute and will keep `/`
2. Alternative: `<a href="{{ (printf "%s/" .Site.BaseURL) | relLangURL }}">` but that looks like a hack, and probably not guaranteed to work later.

**Comment by peterfarrant** [comment]
Thaks for a very prompt response - I will see how that works

**Comment by peterfarrant** [comment]
Seems to work great thanks
