### ISSUE TITLE
[Feature] Image thumbnails for posts?

### ISSUE THREAD

**Issue by MelonKony** [alex-shpak/hugo-book#286]
I was wondering if it might be possible to support simple image thumbnails in the posts list? I've found Book to be an incredible theme and really versatile, but I'd really appreciate an option to enable image content in posts as thumbnails, like in other themes.

**Comment by alex-shpak** [comment]
Hi!
It is possible with some template editing.

You can update `post-meta.html` template and add something like snippet below in the end of the file.
```tpl
{{ with .Params.image }}
  <img src={{ . | relURL }} />
{{ end }}
```

And add frontematter
```md
---
image: /path.png
---
```

I will need to think if I want to add it to theme.

**Comment by MelonKony** [comment]
Thanks a lot! This works great.

I think it could be a useful addition, since it allows for different types of blogs to accompany the documentation side of the main theme.

**Comment by alex-shpak** [comment]
Added to theme.
