### ISSUE TITLE
Failed to get translated string for language "art-x-gb" and ID "Search": %!s(<nil>)

### ISSUE THREAD

**Issue by peterfarrant** [alex-shpak/hugo-book#287]
The above message appears 7 times when I upgraded to hugo 78.1 extended and using book theme in the output from running the website interactively

It re-occurs each time I change page
No other changes made to the website

I switch the hugo.exe back to 75.1 and the issue stops
It seems to occur certainly from 76.1
Not had chance to try all versions between 75.1 and 76.1 yet

Is this a theme specific item or hugo ? I have logged it with you first - let me know if I need to report to hugo instead

**Comment by alex-shpak** [comment]
Hi!
From log message it sounds like you render site with lang code `art-x-gb`and it can't find `Search` translation
https://github.com/alex-shpak/hugo-book/blob/master/i18n/en.yaml#L1

**Comment by peterfarrant** [comment]
Alex
I don't think I made the steps clear enough 
No I don't have an art-x-gb language - I use en and gb (for UK English instead of American) I have a 'local' i18n folder with  gb.yaml file
I have done a global search in all my content for art-x-gb and it finds no results.

I make no change to the website - just use the hugo.exe 0.76.1 instead of 0.75.1 and it complains about this 
Just switch back the exe to 0.75.1 and it is OK again

**Comment by peterfarrant** [comment]
The problem starts with v 0.76.0 the first release after 75.1 that is OK

**Comment by alex-shpak** [comment]
Hm, never seen that before. This might be related: https://github.com/gohugoio/hugo/issues/7838

I tried `exampleSite` on hugo v0.78.2/extended, search is working for `en` lang.
Do you have source of your website published somewhere so I can take a look?

**Comment by peterfarrant** [comment]
All in a company repo with other stuff at the moment, but I have spun off a sample section into my repo and the issue reproduces there
See the readme of how I run it - this is due to having multiple portals in the full solution 
https://github.com/peterfarrant/doctest.git

**Comment by alex-shpak** [comment]
Okay, I think I don't have control over language resolution. Just to try something, change `gb` to `en-gb`.

**Comment by peterfarrant** [comment]
Alex,

Sorry for my ignorance as a newbie to hugo - do you mean in the config file language section change gb: -> en-gb

**Comment by alex-shpak** [comment]
NP, both things:
1. rename locale file to `en-gb` 
2. change config
  ```
defaultContentLanguage: en

languages:
  en:
    languageName: English (US)
    weight: 1
  en-gb:
    languageName: English (GB)
    weight: 2
  ```

I think `gb` is not a valid locale.

**Comment by alex-shpak** [comment]
Closed by accident :)

**Comment by peterfarrant** [comment]
Alex,
I can now run 0.78.2 hugo.exe with out the messages
BUT I seem to lose all my English GB content
When switching to English GB the URL changes
http://localhost:1313/en-gb/
but has no content

**Comment by peterfarrant** [comment]
Just thought - I need to change all my files to be index.en-gb.md .... instead of index.gb.md

**Comment by alex-shpak** [comment]
Yes, everyhing needs rename.
I prefer to split languages into directories, like in [exampleSite](https://github.com/alex-shpak/hugo-book/tree/master/exampleSite)

**Comment by peterfarrant** [comment]
Yes that sorts it - happy to close issue and many thanks for you time on this

On the split directories:
I had started with that - but found it makes it harder to keep the multiple languages in step because when you edit one language you have to go up to the top level in your files manager, back down to the folder you are in to open the other language to make the same edit. 
If they live in the same folder you just click on the one below and edit

I'm still confused with the images naming/location - particularly if I try BookPortableLinks ... but I am straying off issue

**Comment by alex-shpak** [comment]
Something to understand links better:
If you have page `content/docs/level1/level2.md` generated page url will be `host:/docs/level1/level2` that means if you relatively reference image it will get absolute URL of `host:/docs/level1/level2/image.png`, eg. it must be located in subfolder of `level2`

Usually solution is to use directory structure
```
level1
  level2
    _index.md
    image.png
```

Then the image is part of resources of the page.

As for portable links, `BookPortableLinks` tries to use relative URLs in markdown text and verify that such page or image exists. Benefit is that with relative links in markdown you can navigate them in github or text editor.

**Comment by peterfarrant** [comment]
Spoke too soon - having renames all .gb.md files to en-gb.md they start to appear but I get 
`Start building sites …
Built in 366 ms
Error: Error building site: render of "404" failed: "C:\Code\Documentation\hugo\themes\book\layouts\404.html:26:27": execute of template failed: template: 404.html:26:27: executing "404.html" at <.Site.Home.RelPermalink>: error calling RelPermalink: runtime error: invalid memory address or nil pointer dereference`

**Comment by alex-shpak** [comment]
Judging from the error, check that you have translated home page for all languages.

**Comment by peterfarrant** [comment]
You are correct - I tested my bulk rename on one file and then ran for all and that one had a double gb in it - sorted and running fine

**Comment by peterfarrant** [comment]
So with BookPortableLink do all images have to be relative - you can't use and from the static dir ?

**Comment by peterfarrant** [comment]
Thanks for your assistance on this, happy it is working fine now
