### ISSUE TITLE
Hint shortcode does not seem to obey theme override --hint-color-info

### ISSUE THREAD

**Issue by peterfarrant** [alex-shpak/hugo-book#288]
In _default.scss there is  on line 25
`$hint-colors: (
  info: #6bf,
  warning: #ff9100,
  danger: #f66,
) !default;`

In each theme there is the options for 
`--hint-color-info: #6bf;
  --hint-color-warning: #ff9100;
  --hint-color-danger: #f66;`

It appears that these --hint colors are ignored and what is set by $hint-color is used
Am I correct or am I doing something wrong

**Comment by alex-shpak** [comment]
👋 

`--hint-color` css vars is an unfinished part of migration from SASS vars to CSS vars. I didn't find good way to adjust hint background with it. For now `$hint-colors` has to be used.

**Comment by peterfarrant** [comment]
I tried using the $hint-colors but could only work for me in the _default.scss, they did not appear to work if I put into the assets/themes/my-theme-name.css file so I could not have different colors for different themes

Is that the way it is ?

**Comment by alex-shpak** [comment]
I tihnk it should work in `themes` folder, e.g
```
:root {
  @include theme-light;
}

$hint-colors: (
  info: #000,
  warning: #000,
  danger: #000,
);
```

note that there is no `!default` suffix in var declaration.

**Comment by peterfarrant** [comment]
I had tried to put them in the wrong part - below the :root as you showed in your example and they work now
