### ISSUE TITLE
Is it possible to link nested docs?

### ISSUE THREAD

**Issue by celicoo** [alex-shpak/hugo-book#29]
Hey, I'm trying to organize the dir structure of my project to follow the menu hierarchy:

```
---
headless: true
---

- [**About**]({{< relref "/docs/about/index.md" >}})
    - [Features]({{< relref "/docs/about/features.md" >}})
    ...
```

But this causes the following error:

```
Source changed "/Users/celicoo/go/src/github.com/celicoo/docli/docs/content/menu/index.md": CREATE
ERROR 2019/02/28 09:07:03 [en] REF_NOT_FOUND: Ref "/docs/about/features.md": "/Users/celicoo/go/src/github.com/celicoo/docli/docs/content/menu/index.md:6:18": page not found
```

Isn't this supported?

**Comment by alex-shpak** [comment]
Hi!
Well, from error it looks like `features.md` file does not exists, hugo requires it to be present in order to use `relref`

**Comment by celicoo** [comment]
Hey @alex-shpak, thank you for the fast reply.

It's present in the folder:

<img width="1440" alt="screen shot 2019-02-28 at 09 40 12" src="https://user-images.githubusercontent.com/7903844/53567085-e7876f00-3b3c-11e9-92c2-9df7a9d418d2.png">

**Comment by alex-shpak** [comment]
Is by chance page is `draft`? Then it also can't be referenced

**Comment by celicoo** [comment]
@alex-shpak not really, the page is completely empty.

I've just pushed the latest state, you can check it out [here](https://github.com/celicoo/docli/tree/feature/docs/docs)

Thank you very much for your help btw.

**Comment by alex-shpak** [comment]
Looks like you have `Leaf bundle` in `docs/about` folder, which hides all pages in it.
https://gohugo.io/content-management/page-bundles/

Rename `index.md` to `_index.md`

**Comment by alex-shpak** [comment]
You also can add [this line](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yml#L6) to get rid of warnings

**Comment by celicoo** [comment]
Oh man, you are already in my heart! HAHAHA

That's my first time using Hugo. I've spent one-hour last night trying to figure this out.

Thank you very much! You've just gained my eternal ⭐️.

**Comment by alex-shpak** [comment]
Happy to help :)
