### ISSUE TITLE
Shortcode fails inside tab environment

### ISSUE THREAD

**Issue by stockphrase** [alex-shpak/hugo-book#293]
I have a shortcode that fails if it is in the tabs environment of this theme. The shortcode embeds audio:

```
<audio controls style="width: 50%; margin-bottom: 10px">
    {{ with .Get "ogg" }}<source src="{{ . }}" type="audio/ogg">{{ end }}
    {{ with .Get "mp3" }}<source src="{{ . }}" type="audio/mpeg">{{ end }}
    {{ with .Get "wav" }}<source src="{{ . }}" type="audio/wav">{{ end }}
    Your browser does not support the audio element.
</audio>
```
I call it with:
```
{{< audio mp3="/sound.mp3" >}}
```
But this fails inside the tab environment. Any reason why this happens? It works outside of the tab environment as expected.  Thank you.

**Comment by alex-shpak** [comment]
Hi!
Is there any error?
There are sometimes issues with shortcodes nested in other shortcodes. Try to add whitespaces or new lines around inner shortcodes.

Related https://github.com/alex-shpak/hugo-book/issues/216

**Comment by stockphrase** [comment]
No error, just shows some of the text of the shortcode in the generated page. Should I put &nbsp; in the html? I experimented with that and some blank lines, but nothing seemed to work out.

**Comment by stockphrase** [comment]
I fiddled with it some more an made *some* progress. Just to visualize what is happening here:
Code outside and inside the detail environment:
![screen1](https://user-images.githubusercontent.com/2568776/99976663-bcfa3280-2d71-11eb-8f21-976dd1c777c6.png)

Result:
![screen1](https://user-images.githubusercontent.com/2568776/99976673-bff52300-2d71-11eb-8281-b1879303f926.png)

The one inside the detail environment is greyed out and not playable.

**Comment by alex-shpak** [comment]
From description it is sounds like mentioned problem with whitespaces in nested shortcodes. Now we need to find what triggers it.
If you have it published somewhere I can try and take a look, try also to compare html output of working vs non-working case to see if any html tags gets swallowed.

**Comment by stockphrase** [comment]
The repo for the site is: https://github.com/stockphrase/no-silo

The page and section where I am experimenting is: /courses/writing-3/wr3-syllabus/#schedule-of-readings-and-assignments (See Week 1 tab).

Appreciate your help!

**Comment by alex-shpak** [comment]
Great! 👍
