### ISSUE TITLE
Issue with images when site in sub folder

### ISSUE THREAD

**Issue by peterfarrant** [alex-shpak/hugo-book#294]
I have a site in a subfolder as it is part of a bigger document setup. 

The site behaves correctly in terms of links to the documents, but it appears wrong when referencing images 
I have broken this down to a one page test site available on github at https://github.com/peterfarrant/doctest.git

because my site baseurl is  example.com/client

when I refer to images I have to say /client/imagename.png in the link
I would have expected to just say /imagename.png

**Comment by alex-shpak** [comment]
Hi!

It is common issue with markdown, where markdown renderer is not aware of baseURL/context.
It is recomended to keep images inside of page bundle e.g. for page `documents` create `documents/_index.md` and `documents/image.png`, then you can reference image in relative wa, e.g. `![client root us](root.en-us.png)`

Alternative is to use hugo functions to get `relURL` 
Read more here: https://gohugo.io/content-management/page-resources/

**Comment by peterfarrant** [comment]
Thanks for the info

**Comment by yogendra-yatnalkar** [comment]
Hi @alex-shpak, @peterfarrant, I use MarkText editor to write markdown files and I save images as: 

if markdown filename is: one.md 
Then there will be a folder: **one** at same location having image **1.png**. 

MarkText displays image as: ![](one/1.png)

but for hugo-book, I need to convert everything to: ![](1.png)

Is there a way to handle images using the earlier way ?
