### ISSUE TITLE
Issue with images in multilingual setup

### ISSUE THREAD

**Issue by peterfarrant** [alex-shpak/hugo-book#295]
I am having difficulty understanding multilingual images
From the documentation I was expecting to have an image in one language and that would be used in each language unless I explicitly provided a localised version and the behaviour is different if using images from staticdir or put locally with the md files

(note I am using the by filename method not by directory as it makes it much easier to make a quick edit in each language version than having them in separate folders - and there is nothing to indicate this should not work the same way)

my sample site is available at https://github.com/peterfarrant/doctest.git

I was expecting to have an image link like so in each of my language.md files
'''
![image link](/imagename.png)
'''
And then provide in static dir an image called **imagename.en-us.png**    (my default language)
An if I wanted a language specific version to provide a **imagename.en-gb.png**

This is not what I see and I am confused how I should make this work
It appears for images in staticdir in each language.md file 

Please can you assist

**Comment by alex-shpak** [comment]
Hi!

I don't think that multilang for images would work in `static` dir in hugo, but only in `content`.
I will need to do some tests, I will come back to you.

You can try posting this question on hugo forum, as it is hugo specific rather than theme specific.

**Comment by alex-shpak** [comment]
Hi!
Sorry, took some time.

So, markdown generator is pretty simple, and doesn't operate on content lang level.
It more-less will get URL to image you set in markdown and add relative location to it.

So in each lang you need to reference correct image, alternatively you can introduce simple shortcode that will decide which file to use.

**Comment by peterfarrant** [comment]
thanks for the update
