### ISSUE TITLE
TOCSS fails to transform book.scss

### ISSUE THREAD

**Issue by ChristopherBarrington** [alex-shpak/hugo-book#297]
Hi,

I get the following error when building my website:

```
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss): SCSS processing failed: file "/path/to/page/root/themes/book/assets/themes/_light.scss", line 2, col 12: no mixin named theme-light
```

I am using:

```
Hugo Static Site Generator v0.79.0-1415EFDC/extended linux/amd64 BuildDate: 2020-11-27T09:16:17Z
```

The webpage has built on previous versions of hugo-book but not the current version that I added with `git submodule add` as in the readme.

Any advice/pointers would be great. Thank you.

**Comment by vaab** [comment]
Hi, I'm new to hugo, and got confronted to the same issue. 
Managed to find that: https://gohugo.io/troubleshooting/faq/#i-get-tocss--this-feature-is-not-available-in-your-current-hugo-version
So in short, you should install hugo extended version.

**Comment by alex-shpak** [comment]
Hi @ChristopherBarrington!

Is it possible that you have some customization in `assets/book.scss` 
themes were added recently, so perhaps there is a conflict.

Do you have sources published so I can take a look?

**Comment by ChristopherBarrington** [comment]
Hi @alex-shpak 

Thanks! This was the problem - I had added some new theme elements in the assets directory of my project. I had copied the _defaults.scss file from the theme into my project and added some elements.

For example, in my project I added another `hint` tag called `note` and gave it a colour in `$hint-colors` but to make that work I had to copy the whole _defaults.scss (which then the original caused problem). Is there a better/correct way to expand scss files to achieve that?

**Comment by peterfarrant** [comment]
Christopher 
I have expanded hint options with note and tip 
Minimal changes and not copying the whole _default.scss 
See the example I created to ask Alex another question on his excellent theme (https://github.com/peterfarrant/doctest.git)

hint shortcode now also has an image in them by adjusting the hint.hml from the theme into my local  layouts\shortcodes folder. You can see the minimal changes in the assets folder

**Comment by ChristopherBarrington** [comment]
Thank you all, this is great!
