### ISSUE TITLE
enableGitInfo: true The parameter is invalid and does not work.

### ISSUE THREAD

**Issue by hijulian** [alex-shpak/hugo-book#30]
enableGitInfo: false The parameter is invalid. It is closed but still displayed.

**Comment by alex-shpak** [comment]
Hi!
Can you please extend question? 
If I understand you correct:
`enableGitInfo` is a hugo parameter which used in conjuction with `BookEditPath` and `BookRepo` parameters oh theme
you need to disable [both](https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/git-footer.html#L1) to hide it completely.

**Comment by hijulian** [comment]
This is my configuration
```
enableGitInfo: flase
  #BookRepo: https://github.com/alex-shpak/hugo-book
  #BookEditPath: edit/master/exampleSite/content
```
But, still displayed on the website page

![image](https://user-images.githubusercontent.com/6925683/54190872-b66d4e00-44ef-11e9-8226-4eb378c1b5d7.png)

**Comment by hijulian** [comment]
This is my configuration
```
enableGitInfo: false
  #BookRepo: https://github.com/alex-shpak/hugo-book
  #BookEditPath: edit/master/exampleSite/content
```
But, still displayed on the website page

![image](https://user-images.githubusercontent.com/6925683/54190872-b66d4e00-44ef-11e9-8226-4eb378c1b5d7.png)

**Comment by hijulian** [comment]
Locahost:1313 View is normal
This problem occurs after the deployment is successful.

**Comment by alex-shpak** [comment]
I tried to reproduce this and it works as expected for me.
If your website is public maybe I can take a look.

Are you sure you deployed latest generated files and it's not browser cache?

**Comment by hijulian** [comment]
my website: ppages.tk

![image](https://user-images.githubusercontent.com/6925683/54247578-79976a80-4574-11e9-8b08-3911372012bf.png)

**Comment by alex-shpak** [comment]
I tried all cases with these variables,
behaviour that you see on https://ppages.tk corresponds to:
```yml
enableGitInfo: true
#BookRepo: https://github.com/alex-shpak/hugo-book
#BookEditPath: edit/master/exampleSite/content
```

I'm can suggest that you didn't get clean upload after disabling `enableGitInfo`

**Comment by hijulian** [comment]
I found the reason.
Since I am using netlify deployment, and the deployment file netlify.toml has the parameter HUGO_ENABLEGITINFO = "true", change HUGO_ENABLEGITINFO = "true" in netlify.toml to HUGO_ENABLEGITINFO = "false".

Https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

```
[build]
Publish = "public"
Command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
Command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[context.deploy-preview]
Command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
Command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.54.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
```

**Comment by alex-shpak** [comment]
👍 I will close this issue then.
Feel free to reopen if you need some more assistance
