### ISSUE TITLE
Store on route, not /docs/. /Docs/ is blank. 

### ISSUE THREAD

**Issue by markdevjapan** [alex-shpak/hugo-book#301]
This page is blank: [https://themes.gohugo.io//theme/hugo-book/docs/](https://themes.gohugo.io//theme/hugo-book/docs/)

I also don't want `docs` in in the URL. How do I remove this? 

Say I have a book coding with chapters:

```
- How to code/
- - writing styles/
- - - the best styles.html
- - - the easiest styles.html
- How to get the best IDE/
- python/
```

I want my site to be: 

`mysite.com/how-to-code/writings-styles/ best-styles.html`

not

`mysite.com/docs/how-to-code/writings-styles/ best-styles.html`

**Comment by MelonKony** [comment]
Move `how-to-code` out of `docs` (into `content`), then in your site config put `BookSection = '*'`.

This will render all sections of your site in the menu, including your seperate `content` folders.

The easiest way to configure your menu from here on is by hiding any pages you don't want rendered with `bookHidden: true` in the header. If you don't want every post in the blog to render, for example, put `bookHidden: true` in the `index.md` of your posts folder. Do this case-by-case, and you'll be able to maintain multiple sections of your site in the same menu.

Hopefully this works for you.

**Comment by alex-shpak** [comment]
Hi!
Yes, previous comment is correct, in order to render all pages in `content` in menu you need to set `BookSection = '*'`.
But also as placing pages in sections tells hugo which template to use, so pages in `docs` use `docs` template.

for pages outside of `docs` you can specify section manually by setting `type` in frontmatter.
```
---
type: docs
---
```

**Comment by alex-shpak** [comment]
I hope your problem is solved, I will close this issue for now. Write here if you want it re-opened.
