### ISSUE TITLE
[Feature] About Collapsed

### ISSUE THREAD

**Issue by halfrost** [alex-shpak/hugo-book#306]
1. When `BookSection` enable in the config.toml, collapsed menu will show. While `BookMenuBundle` enable, collapsed menu disappeared. Could `BookMenuBundle` support collapsed menu?
2. Whatever collapsed menu is unfolded or folded, the right arrow keeps pointing down. Shouldn't the arrow point up when it be unfolded? like this:
![image](https://user-images.githubusercontent.com/10825609/105933449-61a63280-6089-11eb-9ae8-ec322c79c6c4.png)

**Comment by alex-shpak** [comment]
Hi!
In bundle mode theme just renders a markdown page as side menu. So you are limited to what you can do in markdown file, unfortunatelly. I would suggest to migrate to automatically generated menu which has more features.
At some point I likely will deprecate menu bundle mode.

As for icons I think it doesn't worth extra css complexity, I try to keep it simple.

**Comment by halfrost** [comment]
OK, I get it. Thanks for your reply.
