### ISSUE TITLE
Alter link color 

### ISSUE THREAD

**Issue by stockphrase** [alex-shpak/hugo-book#309]
Is the recommended way of changing the hyperlink colors to put an /assets folder in root containing an altered **$color-link:** value in the **_defaults.scss**?

This doesn't seem to change the coloration as I would expect.

**Comment by alex-shpak** [comment]
Hi!
In latest version SCSS vars were canged to CSS vars https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L32

In order to overwrite those you can add something like this in `_variables.scss` or `_custom.scss` files
```
body {
    --color-link: red;
}
```

**Comment by alex-shpak** [comment]
As an alternative you can create your own theme
https://github.com/alex-shpak/hugo-book/tree/master/assets/themes
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yaml#L50

**Comment by alex-shpak** [comment]
Hi!
I hope your issue is solved. I'm closing it, write here if you want to re-open.
