### ISSUE TITLE
Tables are not formatted nicely

### ISSUE THREAD

**Issue by jordibares** [alex-shpak/hugo-book#31]
Could you please review the formatting of tables so they look nice? at the moment the table frame is not rendered at all so it looks awful.

Name | Surname
------|-----------
Jordi | Bares
Pedro | Almodovar

thanks in advance

**Comment by alex-shpak** [comment]
![image](https://user-images.githubusercontent.com/5515443/54945462-26d78e80-4f36-11e9-86d2-a859cdf8d46b.png)
Like this?
