### ISSUE TITLE
How can I add content/_index.md to the search?

### ISSUE THREAD

**Issue by jasikpark** [alex-shpak/hugo-book#311]
https://jasikpark.github.io/topgrade-docs/ is not included when I search for "install", only the /docs and /pages pages are found.
<img width="1680" alt="Screen Shot 2021-02-17 at 7 12 59 PM" src="https://user-images.githubusercontent.com/10626596/108289547-35477880-7154-11eb-8786-9f91ce8eb165.png">

**Comment by alex-shpak** [comment]
Hi!
Well, right now there is no such option. Search index is built by going through sections, and home page is out of sections. Changing this will require some refactoring.
