### ISSUE TITLE
i want mathjax support also, what's the best place put this code for hugo-book?

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#315]
--> 
this has been tested to work for this theme:

https://github.com/kaushalmodi/hugo-bare-min-theme/blob/master/layouts/partials/mathjax.html

he put a mathjax.html there.

**Comment by longlu** [comment]
or will you consider adding this  html file to the them to support mathjax too?

**Comment by alex-shpak** [comment]
Hi!
As I try to keep things small, I would avoid adding one more math-expr library,

but you can check how it is done for katex
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/katex.html

TL;DR, logic inside that shortcode includes library and config once, on first use.
I think should work also with mathjax

**Comment by alex-shpak** [comment]
Hi! did yo manage to copy solution for MathJax?
I don't think I'm gonna add second tex library into theme, but you can create your own shortcode.

**Comment by longlu** [comment]
I'm haven't begun to try that, I'm trying to figure out how katex can work for inline formula.

I'll try that eventually when i have enough time
