### ISSUE TITLE
Searching By Tag

### ISSUE THREAD

**Issue by juansc** [alex-shpak/hugo-book#316]
Hugo newbie here. I would like to be able to search by tags. I display the tags by overriding the partials and I see them on the page, but they do not show up in my search results.

**Comment by alex-shpak** [comment]
Hi!
Sorry for late reply.

By default tag pages are not part of search index, as in default layout in theme they have no content.
You can override logic here: https://github.com/alex-shpak/hugo-book/blob/master/assets/search-data.js#L19

As you can see by default it picks `page` and `section` kinds

**Comment by juansc** [comment]
Thanks!
