### ISSUE TITLE
Collapsed menu - am I stupid?

### ISSUE THREAD

**Issue by KristofferBroberg** [alex-shpak/hugo-book#318]
For a not so technical person as myself, the documentation about how to achieve collapsed sections in the menu could use some improvement. But, it might just be me :)

I've spent...way too long trying to get it to work. Now I resorted back to where I started. A clean slate:

/content
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/folder1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/folder2
index.md

Each folder contains multiple pages, but no index.md at this point. So, how do I go about getting the collapsed menu for the pages inside?

Love this theme, by the way!

**Comment by alex-shpak** [comment]
Hi!

This is how hugo works, to set frontmatter (read metadata) of section (e.g. `folder1`, `folder2`) you need to create `_index.md` file with it. Tho, you can keep that `_index.md` file without content

**Comment by KristofferBroberg** [comment]
Yes. Got it working. Thank you!
