### ISSUE TITLE
Left menu foldable

### ISSUE THREAD

**Issue by jordibares** [alex-shpak/hugo-book#32]
Could we have foldable left menues? when you build a big structure it is rather exhausting to have so much visual noise.

Thanks in advance

**Comment by bubbleguuum** [comment]
+1 for this.

**Comment by alex-shpak** [comment]
This requires some nice solution.
Now I try to keep theme functional without JS enabled.

I will check what I can do.

**Comment by vhbelvadi** [comment]
I managed to achieve this with some jQuery (not sure if it's the best solution). Posting here if anyone is interested/wishes to improve:

In site-level (not theme-level) partial menu-bundle.html replace `{{ .Content }}` with

` {{ .Content | replaceRE "<ul>" "<ul class=\"listing\">" | replaceRE "<li>" "<li class=\"entries\">" | safeHTML }}`

Put this in the injected footer:

```
$(document).ready(function() {
    $('.book-menu ul li.entries').click(function(e) {
      $('.book-menu ul li ul.listing').slideUp();
      $(this).children('.book-menu ul li ul.listing').slideDown();
    });
});
```

**Comment by jordibares** [comment]
Thanks, will check

**Comment by ktibi** [comment]
@vhbelvadi Hi,

I want to try your solution but I don't understand where I need to add the part of menu-bundle.html.

@alex-shpak  Any news for that ?
