### ISSUE TITLE
The BookLogo isn't shown on top of sidebar nor anywhere in the front page. Am I missing anything?

### ISSUE THREAD

**Issue by mc-gulu** [alex-shpak/hugo-book#320]
How should I process to check if the setting is recognized correctly?

Thanks!

**Comment by alex-shpak** [comment]
Hi!
Is your website opensource?

Probably path to custom logo is not correct. custom logo must be placed in `static` folder, and param value is the name of the file.

**Comment by mc-gulu** [comment]
It works now. I forgot how I fixed it 🤣 

https://sensiblecontract.org/

**Comment by alex-shpak** [comment]
Cool 👍
