### ISSUE TITLE
Katex support align block problem

### ISSUE THREAD

**Issue by qrzbing** [alex-shpak/hugo-book#321]
By default, katex supports `\begin{align}...\end{align}`, but when I want to write formula below will not display correctly:

``` latex
{{< katex display >}}
\begin{align}
\textrm{Precision}&=\frac{\textrm{TP}}{\textrm{TP+FP}} \\
\textrm{Recall}&=\frac{\textrm{TP}}{\textrm{TP+FN}} \\
\textrm{F1}&=\frac{\textrm{2} \times \textrm{Precision} \times \textrm{Recall}}{\textrm{Precision+Recall}}
\end{align}
{{< /katex >}}
```

It will show like this:

![MommyTalk1616749679656](https://user-images.githubusercontent.com/23500397/112608913-ddd4b080-8e55-11eb-9911-a67919def898.png)

But after compile, it seems to cause some errors:

![Snipaste_2021-03-26_17-13-54](https://user-images.githubusercontent.com/23500397/112609595-ac101980-8e56-11eb-840a-308fc389533a.png)

After reading #106 and for comparison, I write another fomular:

``` latex
{{< katex display >}}
x=\begin{cases}
    a&\text{if } b\\
    c&\text{if } d
\end{cases}
{{< /katex >}}
```

It displays correctly. I'm not sure where cause this problem.

**Comment by alex-shpak** [comment]
Hi!
From I can see in katex logs.

```
 with  ParseError: KaTeX parse error: No such environment: align at position 9: x=\begin{̲a̲l̲i̲g̲n̲}̲
```

Katex library doesn't recognize `align` directive

**Comment by alex-shpak** [comment]
Try `aligned` instead
Related: https://github.com/KaTeX/KaTeX/issues/1007

**Comment by alex-shpak** [comment]
Will close issue, write here if you still need assist.
