### ISSUE TITLE
Add customization for width of menu, main, and ToC.

### ISSUE THREAD

**Issue by Phosp** [alex-shpak/hugo-book#322]
# Add customization for width of menu, main, and ToC.

I need to way in increase the amount of screen used by the main section of my pages. Another solution would be to allow an object to pop out as an overlay when clicked. This is getting to the point that we may have to change to another theme due to user complaints. A front matter entry would be great for page specific changes and a configuration file change for global defaults.

### **Imbedded Video**
HTML 5 allows the video command which I have used for a Hugo Shortcode. A width of 100% only uses the middle of the screen.
``` HTML
<video width="{{.Get `width`}}" height="{{.Get `height`}}" controls="controls">
    <source src="{{.Get `src`}}" type="video/mp4" />
```
### **PDF Viewer**
There are times there is makes more sense to link to PDF files instead of reproducing the information. I use the following shortcode to load the PDF on screen in these cases to prevent my users from having to download the file. I want them to come back for the latest version. A width of 100% is lessened by the margins on the PDF document. They can zoom in but a wider section would be preferable. 
``` HTML
<iframe src={{.Get "src"}} width={{.Get "width"}} height={{.Get "height"}}></iframe>
```
### **Tables**
A table with several columns will not fit on the screen forcing me to disable the Table of Contents or lower the font size with CSS. This is even worse when the table has a URL that limits word wrapping. I often only need a few percentage. We also have some software developer users who use our site on monitors that are rotated 90 degrees in portrait mode with makes the middle section even less. I load some reference data with Hugo from data files and I need more screen space.

``` CSS
tr td a {font-size: 8px;}
```
or
```CSS
tr td {font-size: 8px;}
```

### Complex Diagram Images
Our documentation contains some diagrams that are unreadable when scaled down to the middle section of the page. 

### Mermaid
Mermaid diagram pie charts often have the labels hang off the right side of the section due to a lack of space..

**Comment by alex-shpak** [comment]
Hi!
You can control column sizes using SASS variables. Check here: 
https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L16-L17
https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L20-L21

You can override those in this file:
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/assets/_variables.scss

As for displaying content on hover, in `_custom.scss` you can put what custom CSS you need
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/assets/_custom.scss

It is hard to give advice how to achieve it if I can't see source code. Tho, I try to keep theme generic and customizable, so it fits different users.
