### ISSUE TITLE
BaseURL For Correctly Building Site To Local Disk

### ISSUE THREAD

**Issue by 12thankyou** [alex-shpak/hugo-book#324]
Hello, I am new to Hugo and I am having difficulty with correctly building a site using the Book theme. I am getting the typical issue where the index.html in the public directory is not displaying in Chrome using the Book theme.

My version of Hugo is: 0.82.0, extended

Do you have any recommendations for the best baseURL to use in the config.toml file?

Thank you!

**Comment by 12thankyou** [comment]
Issue resolved.

Thank you for the great Hugo theme!

**Comment by alex-shpak** [comment]
Good. Sorry for not responding earlier.
