### ISSUE TITLE
Search feature broken in the demo at https://themes.gohugo.io/theme/hugo-book/ 

### ISSUE THREAD

**Issue by altosaar** [alex-shpak/hugo-book#326]
When I search for something the spinner just continues indefinitely (in Chrome, on MacOS).

Thanks!

**Comment by alex-shpak** [comment]
Hi!
Unfortunatelly this is a limitation of demo website, as `baseURL` is proccessed differently.
Reference: https://github.com/alex-shpak/hugo-book/issues/193#issuecomment-609428484

When generating site with `hugo` cli it should work as expected.

**Comment by altosaar** [comment]
Fantastic, thank you so much @alex-shpak !!
