### ISSUE TITLE
有大佬知道搜索功能如何改为中文吗？

### ISSUE THREAD

**Issue by webPorter** [alex-shpak/hugo-book#327]

**Comment by yuuuuu422** [comment]
可以在config.toml中加上
```
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[languages.ru]
  languageName = 'Russian'
  contentDir = 'content.ru'
  weight = 2

[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content.zh'
  weight = 3
```
选择语言为中文即可，然后把content文件夹改为content.zh。
或者可以直接在`i18n`中把`en.yaml`中的`- id: bookSearchConfig`改为`zh.yaml`中的那一行，但我发现这样会导致搜索英文失败，好像目前中英文搜索只能二选一。

**Comment by webPorter** [comment]
解决了，用的第二种方法，感谢

**Comment by halfrost** [comment]
> 解决了，用的第二种方法，感谢

@webPorter 那你用第二种方法，就抛弃了英文搜索咯？？

**Comment by alex-shpak** [comment]
`defaultContentLanguage = 'zh'`

**Comment by webPorter** [comment]
感谢

**Comment by pp-tt** [comment]
[和你遇到了同样的问题，可以参考我写的这个解决方案，解决中英混合搜索](https://pp-tt.github.io/solution/problems/hugo-%E4%B8%BB%E9%A2%98-hugo-book-%E4%B8%AD%E8%8B%B1%E6%96%87%E6%90%9C%E7%B4%A2%E9%85%8D%E7%BD%AE/)

**Comment by peter-liu** [comment]
刚刚搞定 ，可以参考[解决方法](https://doc.toast.pub/articles/docs/hugo/hugo-book-multilang-search/)

![image](https://doc.toast.pub/articles/docs/hugo/hugo-book-multilang-search/hugo_book_multilan_search.gif)


没有去研究flexsearch，所以未明白其处理机制下的办法，所以可以先用着。问题也反馈给官方了，后续修复之后可以先用这个撑着。

**Comment by peter-liu** [comment]
> 刚刚搞定 ，可以参考[解决方法](https://doc.toast.pub/articles/docs/hugo/hugo-book-multilang-search/)
> 
> ![image](https://camo.githubusercontent.com/c38f140f45d02c58be3d1f052951c95142f36b76db357bdc61dfe1e24bb230fe/68747470733a2f2f646f632e746f6173742e7075622f61727469636c65732f646f63732f6875676f2f6875676f2d626f6f6b2d6d756c74696c616e672d7365617263682f6875676f5f626f6f6b5f6d756c74696c616e5f7365617263682e676966) [ ](https://camo.githubusercontent.com/c38f140f45d02c58be3d1f052951c95142f36b76db357bdc61dfe1e24bb230fe/68747470733a2f2f646f632e746f6173742e7075622f61727469636c65732f646f63732f6875676f2f6875676f2d626f6f6b2d6d756c74696c616e672d7365617263682f6875676f5f626f6f6b5f6d756c74696c616e5f7365617263682e676966) ![image](https://camo.githubusercontent.com/c38f140f45d02c58be3d1f052951c95142f36b76db357bdc61dfe1e24bb230fe/68747470733a2f2f646f632e746f6173742e7075622f61727469636c65732f646f63732f6875676f2f6875676f2d626f6f6b2d6d756c74696c616e672d7365617263682f6875676f5f626f6f6b5f6d756c74696c616e5f7365617263682e676966) [ ](https://camo.githubusercontent.com/c38f140f45d02c58be3d1f052951c95142f36b76db357bdc61dfe1e24bb230fe/68747470733a2f2f646f632e746f6173742e7075622f61727469636c65732f646f63732f6875676f2f6875676f2d626f6f6b2d6d756c74696c616e672d7365617263682f6875676f5f626f6f6b5f6d756c74696c616e5f7365617263682e676966)
> 
> 没有去研究flexsearch，所以未明白其处理机制下的办法，所以可以先用着。问题也反馈给官方了，后续修复之后可以先用这个撑着。

不太行， 忽略吧
