### ISSUE TITLE
Localhost site and public build site have different appearance/behavior

### ISSUE THREAD

**Issue by 12thankyou** [alex-shpak/hugo-book#328]
Using the example site for this theme, I notice the localhost site (using only hugo server) has slightly different appearance/behavior compared to the public build site (hugo --minify).

For example, when clicking on "columns" then "katex", the menu shifts slightly to the left and back again. Also, clicking on other buttons in the menu causes the text to move slightly. 

I am using Chrome browser, but I see similar artifacts when using Edge, Firefox, and Explorer. However, I see less of this issue using Firefox.

Is this is a simple css fix? Or any thoughts on the cause of this issue? Does anyone else experience this?

BTW, my config is the following:

baseURL = "/"
relativeURLs = true
uglyURLs = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "book"

And in order to display the css, I removed the integrity portion from line 20 of the "html-head.html" file:

<link rel="stylesheet" href="{{ $styles.RelPermalink }}" integrity="">

Thank you for any input you may have on this issue.

**Comment by alex-shpak** [comment]
Hi!
In case of KaTeX you either seeing some intermidiate state, while KaTeX is rendering, or perhaps content goes out of page vertically and creates scrollbar on right. Hard to tell without seeing it.

But either way I would say it is 'normal', not something we can fix.
