### ISSUE TITLE
Does the directory only support level 2 and level 3 titles?

### ISSUE THREAD

**Issue by yuuuuu422** [alex-shpak/hugo-book#329]
I see in the example that the first level title will also generate a directory, but I failed. If I write some long summary articles, I may have a higher demand for the directory. Is there a solution?
![image](https://user-images.githubusercontent.com/59158328/115001500-46073700-9ed6-11eb-9179-156bf86b6452.png)

**Comment by alex-shpak** [comment]
Hi!
Do you refer to side menu or table of contents? I'm not reading you clear.

**Comment by yuuuuu422** [comment]
sorry,I refer to side menu

**Comment by yuuuuu422** [comment]
Sorry, I found that `StartLevel` can be used to solve the problem, thank you  for your reply! I like this theme very much and  I will close this issues.
