### ISSUE TITLE
Feature request : Integration of  Go Playground into the theme 

### ISSUE THREAD

**Issue by kanthi** [alex-shpak/hugo-book#330]
MDBOOK (rustlang) has integration of rust playground such that you can . For example we can run the code on the page itself and get results with out leaving the page in the following link.
https://doc.rust-lang.org/book/ch03-03-how-functions-work.html

Will it be possible to update your goplay to have similar feature

Regards

**Comment by alex-shpak** [comment]
Hi!
Well, somehing like that could be done with shorcodes, will require library to plug in, tho.
Maybe if someone know nice light library for embedding go playground?

**Comment by alex-shpak** [comment]
Hi again!
After some thought, it will be not nice to only make single programming language playground, and it will be hard to maintain set of playgrounds when more people will request more languages.
So I don't think I'm gonna add this to theme, unless there will be some generic external playground that supports multiple languages.

But you still can implement it yourself via shortcode in your website.
