### ISSUE TITLE
search not working when public pages are hosted via IPFS

### ISSUE THREAD

**Issue by DealerJohn** [alex-shpak/hugo-book#333]
Alex,
When I use the local server, search is working perfect. When I move the public pages to IPFS and use that site then search does do nothing.
John

**Comment by alex-shpak** [comment]
Hi!
Well, I would guess that site path that was used to generate site is not same as during browsing.
Do you have hosted IPFS site publicly so that I can take a look?

**Comment by DealerJohn** [comment]
Hi,

https://gateway.pinata.cloud/ipfs/QmdRu9SWq2vqELBD39BNLggjMxbXZ4KRchVF91hbyd2KhM/ <https://gateway.pinata.cloud/ipfs/QmdRu9SWq2vqELBD39BNLggjMxbXZ4KRchVF91hbyd2KhM/>

Here you can have a look. Our site is
- created with Hugo-Book and of course generated with Hugo
- the “public” folder is uploaded to pinata.cloud and pinned/hosted on IPFS

The site is not yet live, but we registered a domain name and will create a dnslink to the IPFS hash
once we go live.

John
-----
John L. Lardee
Bilderdijkstraat 19G
1052NA  Amsterdam

**Comment by alex-shpak** [comment]
As far as I can see it tries to load `https://gateway.pinata.cloud/flexsearch.min.js`, when it should be loading `https://gateway.pinata.cloud/ipfs/QmdRu9SWq2vqELBD39BNLggjMxbXZ4KRchVF91hbyd2KhM/flexsearch.min.js`

what `--baseURL=` you use when generating static files?

**Comment by DealerJohn** [comment]
I do not use this flag when I generate the site… 
But when I look at it, I can only use the official domain name… because when I generate the site with Hugo, I do not know the IPFS hash
yet...

-----
John L. Lardee
Bilderdijkstraat 19G
1052NA  Amsterdam

**Comment by alex-shpak** [comment]
Well, without knowing path is not possible to generate links for resources.
I see you changed links in menu to use relative links, but as scrips are generated once you can't do same for search.

Will work when you have your domain.

**Comment by DealerJohn** [comment]
Thx,
I have another site that is live with a domain name and there it worked with the flag —baseURL added.
John
-----
John L. Lardee
Bilderdijkstraat 19G
1052NA  Amsterdam

**Comment by DealerJohn** [comment]
One last point:
- Can I see the search terms highlighted on the page?
John
-----
John L. Lardee
Bilderdijkstraat 19G
1052NA  Amsterdam

**Comment by alex-shpak** [comment]
No, such feature is not in place at the moment.
