### ISSUE TITLE
Code block color and mermaid color

### ISSUE THREAD

**Issue by zrcoder** [alex-shpak/hugo-book#334]
Code block background is too dark in light theme, and mermaid is too light in dark theme.

**Comment by zrcoder** [comment]
Code block background is too dark in light theme, and mermaid is too light in dark theme.

**Comment by alex-shpak** [comment]
Hi!
You can adjust color to your liking using theming.

For code block coloring use `markup.highlight.style` gohugo param
Ref: https://gohugo.io/getting-started/configuration-markup#highlight

And for mermaid you can overwrite `mermaid.json` config
https://github.com/alex-shpak/hugo-book/blob/master/assets/mermaid.json

**Comment by zrcoder** [comment]
> Hi!
> You can adjust color to your liking using theming.
> 
> For code block coloring use `markup.highlight.style` gohugo param
> Ref: https://gohugo.io/getting-started/configuration-markup#highlight
> 
> And for mermaid you can overwrite `mermaid.json` config
> https://github.com/alex-shpak/hugo-book/blob/master/assets/mermaid.json

Thanks a lot!
