### ISSUE TITLE
Help with anchors on headings

### ISSUE THREAD

**Issue by ChristopherBarrington** [alex-shpak/hugo-book#339]
How do I get the anchor link s next to headings in my site? I use the template to write reports for collaborators so the anchor links would be really helpful to add. 

I have been trying for ages and just cannot seem to get them to work - I'm sure it's something obvious I am doing wrong. If I use your exampleSite the rendered page works. So there must be something in my config that I just cannot see.

If you have any intuition as to what it may be, that would be great. If you can spare some time, I have added an example to [this DropBox link](https://www.dropbox.com/s/uaemk0t0cnv3wb4/example_site.tar?dl=0). The site attached renders as expected but the anchor links at the end of the headings do not show.

I found render-heading.html that you reference in one of the other issues and reading the file I can see how it renders the anchor, but I cannot get my site to render the headings using that partial.

Thank you

**Comment by alex-shpak** [comment]
Hi! Well, to start simple, make sure that you have Hugo version at least 0.71

**Comment by ChristopherBarrington** [comment]
Simple is good! Yes:

```
> hugo version
Hugo Static Site Generator v0.79.0-1415EFDC/extended linux/amd64 BuildDate: 2020-11-27T09:16:17Z
```

**Comment by ChristopherBarrington** [comment]
I found this:

```
markup:
  defaultMarkdownHandler: blackfriday
```

in my config file. I'm not sure why it is there though ... :/

If I remove it, then I get the anchors - great! But I don't really know why?

**Comment by raspopov** [comment]
"[Blackfriday was Hugo’s default Markdown rendering engine, now replaced with Goldmark](https://gohugo.io/getting-started/configuration-markup#blackfriday)".

**Comment by alex-shpak** [comment]
Yep, markdown hooks are working only with goldmark in hugo.

**Comment by ChristopherBarrington** [comment]
Thank you, I will play around a bit more with the hooks.
