### ISSUE TITLE
Two copies of tables of content inside every page.

### ISSUE THREAD

**Issue by raspopov** [alex-shpak/hugo-book#346]
One copy used for small screen (mobile) and another for normal (desktop).
The first is always hidden and second is shown and vice versa.
Is it possible to have only one flexible table of content?

There are even two injects in toc.html so it easily can be used for some large dynamic blocks except toc itself and it'll be pretty expensive...

**Comment by alex-shpak** [comment]
Hi! At the time of creating templates that was easier way to deal with mobile view, without adding a lot of complexity to CSS.
Tho, if perhormance of `inject` template is concern you can use `cachedPartial` per page, that will render template only once per page.

**Comment by raspopov** [comment]
In fact I injected a scripted `<iframe>` in the right side of page, its looks so easily to be done in that way and... got a strange behavior till I found **two** `iframe`s in the single page... 😣

**Comment by alex-shpak** [comment]
Well, I don't have much to say. We can try to reshake DOM to make single appearance of TOC, but it makes CSS very complicated.

**Comment by raspopov** [comment]
Probably it can be done in the same way as a left menu.
