### ISSUE TITLE
menu-before formating

### ISSUE THREAD

**Issue by Amsee-Daniel** [alex-shpak/hugo-book#347]
Hay,
I Managed to Put a static Link into the Side menu, by adding a <a href /a> in "menu-before.html".
It looks exactly the same as the other menu Entries except for hovering and when activated.

The Color Change, when hovering over it, i can achieve with simple CSS. But the Blue Color when activated, i can't find a solution for.

maybe someone here can help.

Thanks in advance.

**Comment by alex-shpak** [comment]
Hi!
Dues to static nature of hugo, where pages are pre-generated, that could be hard to achieve.

Theme uses URL comparsion to detect if page is current and add `active` class.
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html#L28
