### ISSUE TITLE
Fusejs supports more language search

### ISSUE THREAD

**Issue by volfclub** [alex-shpak/hugo-book#348]
Fusejs supports more language search, such as Japanese, Chinese, Korean, etc. And it's very friendly with Hugo.

https://github.com/krisk/Fuse

onweru/compose@c725994

zzossig/hugo-theme-zzo#28

https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

I think adding fusejs as an alternative can better search.

**Comment by ayushnix** [comment]
Maybe it was just me but I failed to understand how fusejs is supposed to work and how it calculates its scores and the right settings for `location`, `distance`, and `threshold` to get meaningful search results because by default, the search results were atrocious.

**Comment by alex-shpak** [comment]
Hi!
I looked at Fuse, doesn't seems like it provides more than current used library and documentation is lacking. Could you please elaborate how Japanese, Chinese, Korean lang support in it is better?

**Comment by volfclub** [comment]
> Hi!
> I looked at Fuse, doesn't seems like it provides more than current used library and documentation is lacking. Could you please elaborate how Japanese, Chinese, Korean langadge support in it is better?

https://github.com/alex-shpak/hugo-book/issues/351

After reading this, I learned that you are using flexsearch, which seems to be friendly to cjk.

I am looking for some hugo documentation topics: some use Algolia, which is difficult to configure; some use Lunr, which is very bad for cjk; and some use fuse, which has good support for cjk (many are from  lunr changed to fuse).

In fact, I clicked the demo link （ https://themes.gohugo.io/theme/hugo-book/ ） in github about and found that the search didn't work at all. I was very confused about it.  It is recommended that you update the link or add a demo URL that supports search in the readme.

You can **ignore** my suggestion to add fuse, thank you for your reply.

**Comment by alex-shpak** [comment]
Unfortunately they way themes are built at https://themes.gohugo.io/theme/hugo-book/ they brake relative links for pipelined resources. That's why search is not working there. ¯\\_(ツ)_/¯
