### ISSUE TITLE
Error: Error building site: template: __bd79e2c7beb3b2743763ee42ab922d26:54: function "display" not defined

### ISSUE THREAD

**Issue by sitexa** [alex-shpak/hugo-book#35]
```
git submodule add ...

hugo server --theme book

```
then:

`Error: Error building site: template: __bd79e2c7beb3b2743763ee42ab922d26:54: function "display" not defined`

**Comment by alex-shpak** [comment]
Hi!

I didn't manage to reproduce this.
My steps:
```sh
mkdir tmp; cd tmp
git init
hugo new site .
git submodule add https://github.com/alex-shpak/hugo-book themes/book
hugo server --theme book
```

Worked as expected
Please check you version of hugo, at least 0.43 required.

As alternative you might create repo with reproduced behaviour
