### ISSUE TITLE
[Bug] Broken search

### ISSUE THREAD

**Issue by benmezger** [alex-shpak/hugo-book#351]
For some reason, the search feature is broken (unsure if this only applies to my use case). When searching for something, seems that `window.bookSearchIndex` is undefined. Any ideia why this happens?

See https://seds.nl -> search for something and look at the console for errors.

```
Uncaught (in promise) ReferenceError: FlexSearch is not defined
    c http://localhost:1313/en.search.min.dca4699b43d82216d4432e68bc422c1aaecfff4a03bd5d5dae1dd1c6f5d76ee8.js:1
    promise callback*c http://localhost:1313/en.search.min.dca4699b43d82216d4432e68bc422c1aaecfff4a03bd5d5dae1dd1c6f5d76ee8.js:1
    EventListener.handleEvent* http://localhost:1313/en.search.min.dca4699b43d82216d4432e68bc422c1aaecfff4a03bd5d5dae1dd1c6f5d76ee8.js:1
    <anonymous> http://localhost:1313/en.search.min.dca4699b43d82216d4432e68bc422c1aaecfff4a03bd5d5dae1dd1c6f5d76ee8.js:1
```

Seems that it relates to the following line:
https://github.com/alex-shpak/hugo-book/blob/9b2e21f87068d6b34d1e8f7cd42e8cc6e66c1f34/assets/search.js#L62

**Comment by volfclub** [comment]
I tried searching the sample webpage, but it keeps loading and nothing happens. https://themes.gohugo.io/theme/hugo-book/

![图片](https://user-images.githubusercontent.com/47265026/120924054-57b1d180-c704-11eb-9906-727f363f7f45.png)

**Comment by benmezger** [comment]
> I tried searching the sample webpage, but it keeps loading and nothing happens. https://themes.gohugo.io/theme/hugo-book/


Seems like the error is a little bit different than the error I have. Odd.

**Comment by alex-shpak** [comment]
Hi!
Search in demo site is broken due to way themes website handles absolute URLs.
There is one on netlify that is configured properly http://hugo-book-demo.netlify.app/

On https://seds.nl I'm not sure how you configured website, but flexsearch (flexsearch.min.js) library is not loading.
Do you have some customization in `html-head` template?

**Comment by alex-shpak** [comment]
I would guess: https://github.com/benmezger/blog/blob/main/layouts/partials/docs/html-head.html
there was recent change in that file in theme. So please grab a new one.

I see that only change you have is custom css
https://github.com/benmezger/blog/blob/main/layouts/partials/docs/html-head.html#L40-L43

You don't have to do that as there is already mechanism for adding custom css.
add file `assets/_custom.scss`

https://github.com/alex-shpak/hugo-book#extra-customisation

**Comment by benmezger** [comment]
> You don't have to do that as there is already mechanism for adding custom css.

You are right, I don't remember why I decided to copy `html-head` to my layouts. I've made the changes you suggested and the search works fine now. The` html-head` was definitely out of date. 

Thanks for the help and for the theme!
