### ISSUE TITLE
hugo server refresh No change

### ISSUE THREAD

**Issue by vicevolf** [alex-shpak/hugo-book#352]
When using the hugo server to preview locally, if you modify the .md files in the content folder to refresh, there is no change in the preview webpage; if you modify the config file, the preview webpage has changes.

![图片](https://user-images.githubusercontent.com/47265026/121769936-f8870d80-cb98-11eb-9dba-72a4b65ca756.png)

**Comment by alex-shpak** [comment]
Hi!
I think it is better to ask on hugo forum: https://discourse.gohugo.io/

For me auto-rebuild works as expected om MacOS. Perhaps it is might be due to your OS or permissions.

**Comment by volfclub** [comment]
> Hi!
> I think it is better to ask on hugo forum: https://discourse.gohugo.io/
> 
> For me auto-rebuild works as expected om MacOS. Perhaps it is might be due to your OS or permissions.
> To clarify: such feature is controlled fully by hugo binary and not by theme.

It's a little strange, I also have other hugo themes locally, they are refreshed normally.  

Should I provide more information to help?  Or should I find another computer for testing?

Thank you very much for your reply, and I will also ask questions to the hugo community.

**Comment by volfclub** [comment]
Could this have something to do with git?  I put it in the old folder that already has git, and then forced the installation of hugo.

**Comment by volfclub** [comment]
> 
> 
> Hi!
> I think it is better to ask on hugo forum: https://discourse.gohugo.io/
> 
> For me auto-rebuild works as expected om MacOS. Perhaps it is might be due to your OS or permissions.
> To clarify: such feature is controlled fully by hugo binary and not by theme.

I submitted a bug, possibly with i18n.  https://github.com/gohugoio/hugo/issues/8688

**Comment by volfclub** [comment]
Try to fix this problem https://github.com/alex-shpak/hugo-book/pull/358
