### ISSUE TITLE
How to selectively pick some blog posts and display them as menu item?

### ISSUE THREAD

**Issue by kostrahb** [alex-shpak/hugo-book#353]
Hi, the title is pretty self-explanatory, but to get context. I am creating my blog with Hugo and your absolutely great theme. So far, I really like blog posts because they have the date I set in the file rendered and generate a nice, sorted, and paginated overview at `/posts` so I write most of the pages as blog posts. As I want some of the posts available in menu, I have quite logically used the menu bundle as you describe in the documentation:

```
[params]
  BookMenuBundle = '/menu'
```
with content like this:

```
---
headless: true
---

- **Korespondence**
- [Toustový chleba]({{< relref "/posts/penam" >}})
- [Rádio D-Dur]({{< relref "/posts/ddur" >}})
- [Kvantový byt]({{< relref "/posts/kvantovy_byt" >}})

- **Pohádky**
- [Dědek Yag]({{< relref "/posts/dedek_yag" >}})
- [Informatická]({{< relref "/posts/informaticka" >}})
- [Kvantová]({{< relref "/posts/kvantova" >}})

- **Ostatní**
- [Kontakt]({{< relref "/docs/contact" >}})

<br />

- [**Blog**]({{< relref "/posts" >}})
```

Unfortunately, the content is growing and this approach ceases to suit me because it is manual and I want to categorize the posts and other sites a little bit more independently on the directory structure (with those perks like collapsed sections, etc.). I am therefore thinking about switching back to the file tree menu and making some custom "virtual" menu items from `/posts` directory.

Is something like this possible? Or at least is there a possibility to imitate section collapsing using menu bundle?

**Comment by kostrahb** [comment]
Other things I take in when considering this change are that the menu bundle seems to be deprecated: `WARN 2021/06/15 08:57:04 Bundle menu mode is deprecated and will be removed`

And I have also seen something that seems like effort to allow building menu the exact way I want - in this [file](https://raw.githubusercontent.com/alex-shpak/hugo-book/master/exampleSite/content/posts/creating-a-new-theme.md) there is configuration section:
```
menu:
  main:
    parent: tutorials
```
but it is not rendered anywhere yet (As of today, on branch master). What is the current status with this feature?

**Comment by alex-shpak** [comment]
Hi!
There is no way to make collapsible menu with bundle mode, as it is just a rendered markdown file. It was an alternative to filetree menu when theme was created, but then filetree menu greatly improved and surpassed `bundle` menu in most ways, therefore I'm planning to remove it at all.

There is no menu called `main` in theme, but there are `before` and `after`, which are rendedred before and after left menu.
The are made to look pretty similar to filetree menu.

See: https://raw.githubusercontent.com/alex-shpak/hugo-book/master/exampleSite/content/posts/_index.md
The `Blog` menu item in example site is added via hugo menu.

The collapsing and highlight of current page is not implemented in such menus, but perhaps possible to add, not sure how much work is it.
