### ISSUE TITLE
Warning - Page not found

### ISSUE THREAD

**Issue by jehoshua7** [alex-shpak/hugo-book#355]
Installed the theme as

`git submodule add https://github.com/alex-shpak/hugo-book.git themes/hugo-book`

then ..

`hugo server --source=exampleSite --themesDir=../..`

and the following warning messages ..

> Start building sites … 
hugo v0.84.0-2C4689F7B linux/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio
WARN 2021/06/19 15:12:36 Page '/overview/configuration/' not found in 'posts/migrate-from-jekyll.md'
WARN 2021/06/19 15:12:36 Page '/layout/templates/' not found in 'posts/migrate-from-jekyll.md'
WARN 2021/06/19 15:12:36 Page '/doc/shortcodes/' not found in 'posts/migrate-from-jekyll.md'
WARN 2021/06/19 15:12:36 Page '/layout/variables' not found in 'posts/goisforlovers.md'
WARN 2021/06/19 15:12:36 Page '/layout/functions' not found in 'posts/goisforlovers.md'
WARN 2021/06/19 15:12:36 Page '/content/front-matter' not found in 'posts/goisforlovers.md'
WARN 2021/06/19 15:12:36 Expand shortcode is deprecated. Use 'details' instead.

                   | EN | RU | ZH  
-------------------+----+----+-----
  Pages            | 57 |  7 |  7  
  Paginator pages  |  0 |  0 |  0  
  Non-page files   |  0 |  0 |  0  
  Static files     | 78 | 78 | 78  
  Processed images |  0 |  0 |  0  
  Aliases          | 12 |  2 |  2  
  Sitemaps         |  2 |  1 |  1  
  Cleaned          |  0 |  0 |  0  

Built in 198 ms
Watching for changes in /home/********/Hugo/mysite/themes/hugo-book/{archetypes,assets,exampleSite,i18n,layouts,static}
Watching for config changes in exampleSite/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

**Comment by alex-shpak** [comment]
Hi!
Warnings are printed by `BookPortableLinks` configuration feature, that helps to find links that lead nowhere.

You can disable that param, or just ignore those varnings, as those posts are just example content.

**Comment by jehoshua7** [comment]
@alex-shpak -  Thanks for advising about that. I'm a newbie to Hugo, and will ignore the warning messages. Thanks  :)
