### ISSUE TITLE
How can I search mixed language text?

### ISSUE THREAD

**Issue by yeonns** [alex-shpak/hugo-book#357]
Hello.

My markdown page contains "Korean" and "English" text like below
```md
### 코드code
```
So, I want to search text with mixed language like "코드code", but I think it only supports one language per file/directory.
Is there any way searching with mixed language?

**Comment by alex-shpak** [comment]
Hi!
For searching [flexsearch](https://github.com/nextapps-de/flexsearch) library is used.
I never tried to make mixed search settings for it, but you can give it a shot.

There is param in i18m called `bookSearchConfig`, where you can specify flexsearch indexing settings.
https://github.com/alex-shpak/hugo-book/blob/master/i18n/zh.yaml#L13

Current settings are taken from their docs
https://github.com/nextapps-de/flexsearch#cjk-word-break-chinese-japanese-korean

**Comment by alex-shpak** [comment]
Related issues in flexsearch repo
https://github.com/nextapps-de/flexsearch/issues/207
https://github.com/nextapps-de/flexsearch/issues/73

**Comment by yeonns** [comment]
Hi!
I will try editing ```bookSearchConfig```.
Thank you 👍

**Comment by yeonns** [comment]
Hi!
I could search mixed language(Korean & English) with below ```bookSearchConfig```
It was simpler than I thought. 
```
- id: bookSearchConfig
  translation: |
    {
      split: " "
    }
```

I think It is little strange because I do not need any custom tokenize function, and just use split function. 😢

**Comment by alex-shpak** [comment]
Cool 👍

**Comment by marshall-999** [comment]
it is not work now.
