### ISSUE TITLE
Katex not working as expected 

### ISSUE THREAD

**Issue by vuvgaG** [alex-shpak/hugo-book#359]
![image](https://user-images.githubusercontent.com/75189112/123919037-68104180-d97c-11eb-86ea-6d1d7f2dd4b2.png)
![image](https://user-images.githubusercontent.com/75189112/123919082-765e5d80-d97c-11eb-8037-2769fdc2c921.png)

**Comment by alex-shpak** [comment]
Hi!
Yes, it is a sideeffect of adding KaTeX library.
See:
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/katex.html#L1-L7
https://katex.org/docs/autorender.html

When Katex library is added to page it is by default goes and finds all formulas.
Also it makes easier to write inline formulas, so I left it as it is.

Is it an issue?

**Comment by vuvgaG-dukgu3-wysnox** [comment]
> Hi!
> 
> Yes, it is a sideeffect of adding KaTeX library.
> 
> 
> 
> See:
> 
> https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/katex.html#L1-L7
> 
> https://katex.org/docs/autorender.html
> 
> 
> 
> When Katex library is added to page it is by default goes and finds all formulas.
> 
> Also it makes easier to write inline formulas, so I left it as it is.
> 
> 
> 
> Is it an issue?

No its fine. Just un expected

**Comment by vuvgaG-dukgu3-wysnox** [comment]
Hey, why is inline mode not working.
![image](https://user-images.githubusercontent.com/75189112/124687751-70f99980-decd-11eb-9076-36e93443ef2d.png)

**Comment by alex-shpak** [comment]
Hi!
Often similar issues are comnig from HTML sanitizing, check that you have unsafe HTML allowed for markdown.

https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yaml#L12-L15

**Comment by alex-shpak** [comment]
Hi! Did you fix your issue?

**Comment by alex-shpak** [comment]
Hi! if you add `< katex display >` in the beginning of page, `$$` I tihnk should work on entire page.
