### ISSUE TITLE
Font size not changing on Netlify server

### ISSUE THREAD

**Issue by soniajoseph** [alex-shpak/hugo-book#367]
Hi there, I'm changing the font size under themes/book/assets/_variables.scss as follows:

`$font-size-base: 20px;
`

The font size changes on my local server, but not on my Netlify build. Any idea why? Do I need to change the font in a different location, or change my build specifications, or something else?

Here is my netlify.toml in case this is relevant:

```
[build]
publish = "public"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.85.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.85.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.85.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.85.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

```

**Comment by alex-shpak** [comment]
Hi!
I don't have much experience with Netlify, tho I would expect this to work.
Just to try, move `themes/book/assets/_variables.scss` to `assets/_variables.scss`

**Comment by soniajoseph** [comment]
It worked! Tysm!!

**Comment by alex-shpak** [comment]
👍  Great! I will close issue then
