### ISSUE TITLE
nested shortcode required?

### ISSUE THREAD

**Issue by lzachmann** [alex-shpak/hugo-book#368]
Hi Alex, this is nothing urgent, but I was wondering if you had thoughts about how to use the katex shortcode inside of the tab shortcode. Even with `markup.goldmark.renderer.unsafe=true` I am still getting partial rendering of the desired result. I can link to the reproducible example if need be, but figured I'd start here in case it's an easy fix. 

Here's the complete page markdown:
```
# Counts

Counts of things are modeled using the Poisson or negative binomial distributions. The latter is typically required with the data are [overdispersed](https://en.wikipedia.org/wiki/Overdispersion). Underdispersed data can be modeled using the generalized Poisson distribution. We also support zero-inflated version of each.

## Poisson
Discrete random variables that occur randomly over time or space.

{{< tabs "poisson" >}}
{{< tab "Math" >}}

# Likelihood

{{< katex display >}}
y \sim \text{Poisson}(\lambda)
{{< /katex >}}

where {{< katex >}}\lambda{{< /katex >}} is the mean.

{{< /tab >}}

{{< tab "Code" >}}

# JAGS code

    y[n] ~ dpois(mu[n])

{{< /tab >}}

```

And here's what it looks like in the browser. The "code" tab looks great. It's the first "math" tab that is not rendering the inline tex stuff correctly. Specifically, the `\lambda` term is not rendering as math....

<img width="826" alt="Screen Shot 2021-08-09 at 3 57 03 PM" src="https://user-images.githubusercontent.com/7574887/128779774-b414c18e-bb87-4e9e-a3ba-109b02650aef.png">
<img width="826" alt="Screen Shot 2021-08-09 at 3 57 12 PM" src="https://user-images.githubusercontent.com/7574887/128779788-2fe8b6e4-3820-4171-a89f-bb93ec6caadd.png">

**Comment by alex-shpak** [comment]
Hi!
It is most likely rendering with `markdownify` that introduces unwanted paragraphs or whitespaces in output. I will need to look into it.

**Comment by alex-shpak** [comment]
Seems like passing content through multiple `markdownify` introduces new `<p>` block and strips escaping for KaTeX block

**Comment by lzachmann** [comment]
That's helpful, thanks! Is there any easy fix for this behavior, or is it a dead end? If it's a dead end I can close the issue and find some other way to present this material without using the tabs shortcode....

**Comment by alex-shpak** [comment]
Hard to tell now, but I don't have quick fix for this, unfortunately. Issue happens due to double `markdownify` on shortcode content, which strips escaping from katext separators`\( \)`
