### ISSUE TITLE
Google Analytics for hugo-book

### ISSUE THREAD

**Issue by DealerJohn** [alex-shpak/hugo-book#369]
Hi,
I try to add Google Analytics to my site but it is not functioning.
I did it in the following way:
config.toml looks like this:
1 googleAnalytics = "G-1234567890"
2 baseURL = "https://xxxxxxx.eu/"
3 languageCode = "en-us"
4 title = "srsrsrsrsr"
5 relativeURLS = true
6 BookTheme = 'light'

**Comment by alex-shpak** [comment]
Hi!
Can you see if there any error in your browser? This theme uses built-in template in hugo.
Also if you can plis refer to source or deployed site, otherwise it is hard to troubleshoot.

**Comment by michaeltlombardi** [comment]
@alex-shpak I noticed today that my sites using hugo-book also don't seem to be functioning with the Google Analytics.

I see this error in the chrome console:

```
The FetchEvent for "https://www.google-analytics.com/analytics.js" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

For all of my sites, but to illustrate the example, for [flagrant.garden](https://flagrant.garden) the source for which is [here](https://github.com/FlagrantGarden/site).

**Comment by alex-shpak** [comment]
Hi!
I've looked at the site, apart from adblock bloking GA didn't show something wrong for me 🤔 
Tho, not sure how GA will react to not valid SSL certificate, maybe check that.

**Comment by michaeltlombardi** [comment]
> Tho, not sure how GA will react to not valid SSL certificate, maybe check that.
😣 oh no! Chrome is telling me the cert is fine, that's weird.

**Comment by alex-shpak** [comment]
Now it is valid, I used to get `*.flagrant.garden` cert when visiting https://flagrant.garden/
Tho, right now it looks fine, including GA.

**Comment by michaeltlombardi** [comment]
Aha, I figured it out - I think it's because the theme is using the v3 analytics and I had set up v4:

https://github.com/alex-shpak/hugo-book/blob/d6087bd32df82e51d7631b094d1a3aa46903c1c8/layouts/partials/docs/html-head.html#L34

[Hugo docs](https://gohugo.io/templates/internal/#use-the-google-analytics-template) imply this should be `google_analytics` instead of `google_analytics_async` - possibly a good candidate for minor PR like:

```
{{ if hasPrefix .Site.GoogleAnalytics "UA-" }}
{{ template "_internal/google_analytics_async.html" . }}
{{ else if hasPrefix .Site.GoogleAnalytics "G- }}
{{ template "_internal/google_analytics.html" . }}
{{ else }}
{{ end }}
```

**Comment by alex-shpak** [comment]
Hi! Good analisys.
When I'm looking at hugo source https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html

They already have logic to switch v3/v4 in non async template.
So maybe just change to that 🤔
