### ISSUE TITLE
Hugo Book + Bootstrap

### ISSUE THREAD

**Issue by jordibares** [alex-shpak/hugo-book#37]
I am keen in adding some more graphical tools to the content and found Bootstrap 4.3 could be great, I followed the installation notes and injected these 3 lines using the head injection mechanism.

Created a head.html on my website's layout/partials/docs/inject/head.html

```
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
```

And when i run the website the widgets I use work as desired, only problem is that the fonts and general proportions of the page amongst other things seem to be broken now.

My questions are;

1) Is this the correct approach?
2) Can I do this without breaking your design?
3) Does this mean the normalize.min.css is not useless? How do I correct the new design to make it look like yours?

Thanks for the help, I hope I can contribute in the near future.
jb

**Comment by alex-shpak** [comment]
🤔I think it would be hard to add bootstrap to this setup. I'm quite sure it would not work with compiled bootstrap version.

What you can try is to use SASS and import only part of bootstrap files, for example `_buttons.scss`, `_forms.scss`, see [here](https://github.com/twbs/bootstrap/tree/master/scss)
I haven't tried this myself.

Then answers:
 1. Yes, approach is correct!
 2. Requires some trying, I think it will be hard to do.
 3. Bootstrap uses `normalize.min.css` as well as book theme to reset some browser inconsistencies or bugs. it's very useful in that matter.

**Comment by jordibares** [comment]
Thank you Alex, will keep digging.

**Comment by alex-shpak** [comment]
I thought to introduce [Basscss](https://basscss.com/), but didn't make my mind yet.
