### ISSUE TITLE
Weird formatting on iPhone 6 / some mobile scresns

### ISSUE THREAD

**Issue by soniajoseph** [alex-shpak/hugo-book#371]
Hey there, thanks for all your help so far, and the great theme! 

When I access my site on mobile, it looks like this: 

![4DDC856A-10B8-4AA1-A4CB-FAD4FA5C355C](https://user-images.githubusercontent.com/29527088/130336663-ae700924-341c-4d80-b350-9db59cff8afa.png)

When I zoom out manually, it looks normal. 

How to fix? Thank you!

**Comment by alex-shpak** [comment]
Hi!
This might happen if minimun body width is bigger than viewport. By default minmum width is 320px, but IPhone 6 should have 375px.

Do you have by chance UI scaling?
