### ISSUE TITLE
Style is completely messed because of `margin-inline-start` style - Adding PostCSS "Autoprefixer" plugin can solve it

### ISSUE THREAD

**Issue by fzyzcjy** [alex-shpak/hugo-book#372]
Hi thanks for the template! I see style is completely messed because of `margin-inline-start` style - it is not implemented in this mobile phone. Adding PostCSS "Autoprefixer" plugin can solve it, by automatically prefixing with suitable vendor prefixs

![image](https://user-images.githubusercontent.com/5236035/131219864-af4a24de-db38-4e8c-8c22-a3262dd9d327.png)

**Comment by alex-shpak** [comment]
Hi! What browser is that?
Unfortunatelly adding PostCSS will require to install it n addition to hugo binary, this is something that I try to avoid 🤔

**Comment by fzyzcjy** [comment]
A browser in an old android phone.
Hmm that is a problem...

**Comment by chrillek** [comment]
It might be possible to use a `@supports`:

```
@supports(margin-inline-start: -16em) {
  .book-menu {
    margin-inline-start: ...
  } 
}
@supports not(margin-inline-start: -16em) {
  .book-menu {
   ... something else ...
 }
}

Alternatively, include the prefixed versions in the style itself. 
The main reason for using this over `margin-left` is that it accounts for rtl scripts. OTH, it is only available since 2018 and has been in Safari only since April 2021. So it might be a bit recent for some use-cases?

**Comment by alex-shpak** [comment]
Well, quite a lot of time passed, and it has pretty good support now, probably doesn't worth to play around it. `marging-inline` is very useful for supporting RTL pages
https://caniuse.com/css-logical-props
