### ISSUE TITLE
context for search

### ISSUE THREAD

**Issue by alustig3** [alex-shpak/hugo-book#377]
It would be great is if the search results provided some surrounding words to the search term, to give some context to the results. This would aid in giving the user more information so they can select the correct option from a list of results. A couple of words on either side of the search term should be sufficient. Something like this: https://github.com/alex-shpak/hugo-book/issues/236#issuecomment-654440277 but instead of breadcrumb, have surrounding words.

I think for example, the search used by https://pmarsceill.github.io/just-the-docs/ does this very well.
<img width="1078" alt="CleanShot 2021-08-31 at 09 54 46@2x" src="https://user-images.githubusercontent.com/8128628/131516602-76e752ed-7c72-45d5-9708-79948becbb29.png">

hugo book has been a great tool for me. Thank you building it and sharing your work!

**Comment by alex-shpak** [comment]
Hi!
It is nice feature, but there is a lot to it. It will extend complexity and not sure if flexsearch library can give location of token.
I don't feel like it worth adding right now. 🤔

**Comment by alex-shpak** [comment]
I think this feature will be too complicated for minimalist theme :) Closing.
