### ISSUE TITLE
Site parameter to permit menu order by name

### ISSUE THREAD

**Issue by chrillek** [alex-shpak/hugo-book#378]
Currently, menu entries can be ordered by weight (in the frontmatter) or date (equally in the frontmatter, if weight is not present). It would be nice if one could have a site parameter that allowed alphabetical (by Title) ordering, too. 

Rationale: If I want alphabetical ordering, I can achieve it by adding weights to the frontmatter. However, this potentially requires changing several files when a new one is added. _Not_ using weights automatically orders menu entries by date – that is fine for blogs, not so much for books (I think). And I can't get rid of the date in front matter because structured data relies on it. So, something like `bookMenuOrder: alpha` would be cool.

**Comment by alex-shpak** [comment]
Hi!
I will need to take a look what can be done, I'm not keen on adding lots of params, I would rather move template out and let theme user overwrite them.

For now you can change template. In your site (not in theme) create file `layouts/partials/docs/menu-hugo.html
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-hugo.html

copy that file and change
```
{{ if . }}
  {{ template "book-menu-hugo" .ByName }}
{{ end }}
```

**Comment by chrillek** [comment]
Right, I’ll follow that route.
