### ISSUE TITLE
Title cut off below logo

### ISSUE THREAD

**Issue by kovasap** [alex-shpak/hugo-book#379]
I'm having an issue after updating to the latest version of hugo and this theme where my title is cut off (it gets positioned to the right of the logo, as opposed to below it):

![image](https://user-images.githubusercontent.com/8763010/132255601-b07631cd-02da-489f-bc68-0c535d1cbbb9.png)

It should look like this (image taken before upgrade):

![image](https://user-images.githubusercontent.com/8763010/132255640-189fad2e-b5e2-4bf4-8b21-ac4e72bd73cf.png)

Any ideas on how to fix this?

**Comment by alex-shpak** [comment]
Hi!
It changed recently as logo got vertically aligned with title using flexbox.
Pretty sure it can be fixed with custom CSS. Is your site public? So I can take a look.

**Comment by kovasap** [comment]
Yes, it's at https://kovasap.github.io/.  Thanks!

**Comment by alex-shpak** [comment]
Create a file in your website source, `assets/custom.scss`
and put 
```
.book-brand a {
  flex-wrap: wrap;
}
```

That should do

**Comment by kovasap** [comment]
That works perfectly, thanks!!
