### ISSUE TITLE
Suggestion: make hotkey for search focus configurable

### ISSUE THREAD

**Issue by michaeltlombardi** [alex-shpak/hugo-book#385]
Hi! While working on a project I noticed something unexpected, which is that attempting to type the `s` key while in a text input failed; it turns out, this fails because of the search implementation, which binds `s` as the hotkey to focus the search bar:

https://github.com/alex-shpak/hugo-book/blob/62004506e2fa0980777de5b1de045d5101d01f6c/layouts/partials/docs/search.html#L3

https://github.com/alex-shpak/hugo-book/blob/9b2e21f87068d6b34d1e8f7cd42e8cc6e66c1f34/assets/search.js#L32-L53

I don't think _most_ people using this theme are doing any forms, but being able to override this from merely pressing `s` would be extremely useful. As is, I _think_ I can get away with overwriting the partial for search locally _but_ I'm hesitant to do so because I want to keep using this theme as close to vanilla as I can, merely extending it instead of clobbering components.

**Comment by alex-shpak** [comment]
Hi!
I understand your problem, I will need to look into it. I try to not add more config parameters to not end up with bloated config. But maybe we can make it work with partials or something similar.

**Comment by alex-shpak** [comment]
I think perhaps move focus part into standalone script, like menu reset https://github.com/alex-shpak/hugo-book/blob/master/assets/menu-reset.js

Then you can override it and keep empty in your site.

**Comment by michaeltlombardi** [comment]
I think that would work phenomenally well.

**Comment by alex-shpak** [comment]
Hi!
I came up with another solution: https://github.com/alex-shpak/hugo-book/commit/2e693816ae3e4976a6bb15e5b23f3422b936f000

Should prevent focusing search field if current focus has value (i.e. it is input field)
Should work out of the box for you.

**Comment by fr4nzap** [comment]
This is not working for me. I have a web component with a textarea that gets defocused when typing `s`, making it completely unusable short of manually editing the search JS. Would it be possible to add a configuration to disable the hotkey?
