### ISSUE TITLE
Introduce shortcodes

### ISSUE THREAD

**Issue by alex-shpak** [alex-shpak/hugo-book#39]
I think to introduce some shortcodes for documentation.
If you have some ideas please post here.

What I have now in mind:
 - [x] Expandable panels
 - [x] Multiple columns
 - [x] Tabs
 - [x] Button shorcode
 - [x] Mermaid chart

**Comment by jordibares** [comment]
Hi Alex, sounds great.

I would say that tabs, accordions, buttons, notices, margins and a few others would be very handy for a book.

**Comment by alex-shpak** [comment]
Some shortcodes are coming
https://github.com/alex-shpak/hugo-book/tree/feature/shortcodes

![shortcodes](https://user-images.githubusercontent.com/5515443/58250204-29e9d200-7d61-11e9-91ba-02dead9c5880.png)

**Comment by alex-shpak** [comment]
Can't make my mind, maybe somebody has opinion.

I came with two syntaxes for columns view.
Less verbose, but reserves `---` separator in markdown
```tpl
{{< columns >}}
# Left Content
Lorem markdownum insigne.
---
# Mid Content
Lorem markdownum insigne.
---
# Right Content
Lorem markdownum insigne.
{{< /columns >}}
```

More verbose but more clear, with child shortcode.
```tpl
{{< columns >}}

{{< column >}}
# Left Content
Lorem markdownum insigne. 
{{< /column >}}

{{< column >}}
# Mid Content
Lorem markdownum insigne. 
{{< /column >}}

{{< column >}}
# Right Content
Lorem markdownum insigne. 
{{< /column >}}

{{< /columns >}}
```

I like first one, but afraid of magic.
