### ISSUE TITLE
Hide menu and ToC?

### ISSUE THREAD

**Issue by lbern0th** [alex-shpak/hugo-book#391]
Moin,

I am wondering if it is possible to hide the menu just like the ToC.
My usecase is that I want to create an entry (doc) on my site that is only reachable through the provided link (mysite.com/example). It is kind of a sub-site for an event which has nothing to do with the rest of my website so i would like to hide the menu on that specific entry.

Is there any way this can be done with the book theme?

Thanks in advance,
Louis

**Comment by alex-shpak** [comment]
Hi!
There is no such config, but you can create special type of page, that hides menu.

For example this is `post` type
https://github.com/alex-shpak/hugo-book/tree/master/layouts/posts

and to set type you can use `type: post` in frontmatter in that specific file

**Comment by alex-shpak** [comment]
You can copy this:
https://github.com/alex-shpak/hugo-book/blob/master/layouts/_default/baseof.html

and overwrite
https://github.com/alex-shpak/hugo-book/blob/master/layouts/_default/baseof.html#L49-L51

with some empty placeholder

**Comment by lbern0th** [comment]
Awesome, that worked out just as I imagined! Thank you.

I just deleted the lines 49–51 and the lines 11–15 which worked out just fine.
