### ISSUE TITLE
Wrong favicon type

### ISSUE THREAD

**Issue by raspopov** [alex-shpak/hugo-book#393]
In the file: `layouts\partials\docs\html-head.html` line 13:
```
<link rel="icon" href="{{ "favicon.png" | relURL }}" type="image/x-icon">
```
has wrong `type` attribute, it must be either `image/png` or file type must be `.ico` correspondingly.

P.S. Also in the other themes I noticed a favicon stuff placed in the separate `layouts\partials\favicon.html` file.

**Comment by alex-shpak** [comment]
Hi!
Does it case some issue apart from warning? I remember I was trying to make it quite compatible without using `ico` file, tho, I already don't remember what was the issue.

Tho, we can move havicon template into own partial, not a big deal

**Comment by raspopov** [comment]
You can use this  https://realfavicongenerator.net/favicon_checker to feel the complexity and misfortune of the fate of modern website favicon. 😔 I start thinking about auto-generating the missed favicon sizes by Hugo in the some sort of partial template. Recommended sizes are 16x16, and 32x32 for legacy Windows, 120x120 for Android, 180x180 for Apple etc...

**Comment by alex-shpak** [comment]
In [69886cc](https://github.com/alex-shpak/hugo-book/commit/69886cc74ba638fa4c0b8062c3b0ab172d4b0103) favicon was moved to separate shortcode to be able to customize, should be good enough
