### ISSUE TITLE
.File.Dir and .File.Path on zero object

### ISSUE THREAD

**Issue by vhbelvadi** [alex-shpak/hugo-book#40]
The terminal throws a pair of errors:

`.File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}`

and

`.File.Path on zero object. Wrap it in if or with: {{ with .File }}{{ .Path }}{{ end }}`

The former is probably from shared.html; about the latter I'm not quite sure. How would I resolve this?

**Comment by alex-shpak** [comment]
I wan't able to reproduce this.

If your project is public, please share link so I can take a look. 
Otherwise maybe share `config.yml|toml` file and structure of content dir.

**Comment by vhbelvadi** [comment]
It’s not public, unfortunately. But I discussed this in the Hugo forums too and here’s a post with steps to reproduce it: https://discourse.gohugo.io/t/error-what-to-replace-file-dir-with-in-hugo-book/18118/10

Turns out the error just might be on Hugo’s end.

**Comment by alex-shpak** [comment]
I guess we can close this? Warning will go away in hugo `0.55.3`

**Comment by vhbelvadi** [comment]
Absolutely. This is effectively solved pending the Hugo `0.55.2` update.
