### ISSUE TITLE
Using File-tree menu

### ISSUE THREAD

**Issue by mojomaayan** [alex-shpak/hugo-book#400]
Thanks for the simple and wonderful theme! I have some trouble using the File Tree menu structure, which I do not think is explained clearly. 

Suppose I have three folders under docs/ - A, B and C. Further there are files A1.md, A2.md and A3.md under A, and similarly for B and C. In the menu, I want only A, B and C to be displayed, but with a button for uncollapsing and showing the individual files. This is similar to 'Collapsed' in the example site (https://hugo-book-demo.netlify.app/docs/example/table-of-contents/) - no page on its own, but displays the pages inside when uncollapsed. 

Also, there could be titles in the menu for groupings, which do not have links, like 'Shortcodes' in the Example site. How do we create these for the File Tree Menu structure?

**Comment by alex-shpak** [comment]
Hi!

As menu is created from file tree, menu needs to read matedata from somewhere, so when you see menu item which is not page it is still technically a page, just with no content. Both goes for collapsible menus and menu items without link.


For collapsible item you need to add pages for `A`, `B` and `C` with `A/_index.md` file without content, but just with frontmatter
```
---
bookCollapseSection: true
---
```

Same goes for `Shortcodes` menu item, it is this page https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/docs/shortcodes/_index.md

with `bookFlatSection: true`

**Comment by NHAS** [comment]
Im going to be a huge pain and ping this closed issue. 
If the documentation could be a little more clear or just caveat that the default is to have everything on one page that'd be super awesome!
