### ISSUE TITLE
Show Git date without link to repository

### ISSUE THREAD

**Issue by jhm-ciberman** [alex-shpak/hugo-book#401]
In my company, we are developing a closed source project we want to document. We would like if posible to leave the documentation repository as private, but the problem is that hugo-book only shows the date of a page only if a `BookRepo` param has been provided. 
Also, the target audience of our software is not a technical audience, so it doesn't even know what git is, so they wouldn't benefit from having a link to a specific commit. 

![image](https://user-images.githubusercontent.com/7988351/146873803-bd33a481-8443-482f-976c-d82c93ccdf54.png)

It is posible to show the date (from git) without having to make the repository public? 
Also, when you hover over the date, it shows who the author of the page is. It is possible to remove the author's name? My boss is very concerned about privacy. 

By the way, amazing theme and great work. I love it. ❤

**Comment by eyllanesc** [comment]
One possible is to override layouts/partials/docs/footer.html and change the following lines: 

https://github.com/alex-shpak/hugo-book/blob/2f60f0919f80a8ad745ef47953f638392af6d37f/layouts/partials/docs/footer.html#L3-L12

**Comment by alex-shpak** [comment]
Hi!
Yes, I think it is good solution, you can format footer of page to your liking.

**Comment by jhm-ciberman** [comment]
Thank you! I did that and it looks perfect! Here is the code in case someone wants to copy paste it: 

**layouts/partials/docs/footer.html**
```html
<div class="flex flex-wrap justify-between">

    {{ if .GitInfo }}
      <div>
        {{- $date := partial "docs/date" (dict "Date" .GitInfo.AuthorDate.Local "Format" .Site.Params.BookDateFormat) -}}
        {{- $commitPath := default "commit" .Site.Params.BookCommitPath -}}
        <span class="flex align-center">
          <img src="{{ "svg/calendar.svg" | relURL }}" class="book-icon" alt="Calendar" />
          <span>Última actualización {{ $date }}</span>
        </span>
      </div>
    {{ end }}
    
    </div>
    
{{ $script := resources.Get "clipboard.js" | resources.Minify }}
{{ with $script.Content }}
    <script>{{ . | safeJS }}</script>
{{ end }}
```

I think the only problem is the date shows in english, not in spanish (the language configured in my toml file). But I think it's not a big problem.

![image](https://user-images.githubusercontent.com/7988351/147361711-166ac395-1718-4999-a037-9833ddef4831.png)

I close the issue. Thank you!
