### ISSUE TITLE
add outdatedInfoWarning

### ISSUE THREAD

**Issue by ikingye** [alex-shpak/hugo-book#402]
Like this:
![image](https://user-images.githubusercontent.com/29562589/147073464-703137bc-e639-4ed8-88e5-72fe0d3030ba.png)

```
  # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [params.outdatedInfoWarning]
    enable = false
    hint = 30               # Display hint if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示提醒
    warn = 180              # Display warning if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示警告
```
https://github.com/olOwOlo/hugo-theme-even/blob/564697987de962672112b910422682eb6f9c26ba/exampleSite/config.toml

**Comment by alex-shpak** [comment]
Hi!
You can try to add `layouts/partials/docs/inject/content-before.html` template to add it to your pages. not sure if it worth to add to default tempaltes.

**Comment by ikingye** [comment]
> 

How can I use hints in content-before.html
```
{{<hint info>}}
outdatedInfoWarning hints
{{</hint>}}
```

**Comment by alex-shpak** [comment]
Hm, I would expect later example to work, I can check.

**Comment by ikingye** [comment]
@alex-shpak Can I get the Article-Update-Time from `layouts/partials/docs/inject/content-before.html` using JavaScript more easily?
