### ISSUE TITLE
Possibility to disable the Blog section

### ISSUE THREAD

**Issue by MexHigh** [alex-shpak/hugo-book#403]
Is it possible to disable the Blog section or at least not display it in the sidebar? Thanks in advance for the help.

**Comment by alex-shpak** [comment]
Hi!
Blog record added to menu in blog page metadata
https://raw.githubusercontent.com/alex-shpak/hugo-book/master/exampleSite/content/posts/_index.md

Remove this portion
```
menu:
  after:
    name: blog
    weight: 5
```

and it will be removed from menu

**Comment by MexHigh** [comment]
Thank you, I probably overlooked it
