### ISSUE TITLE
Customize homepage?

### ISSUE THREAD

**Issue by fzyzcjy** [alex-shpak/hugo-book#405]
Hi thanks for the template! I want to customize the homepage and show all articles in it. Can I do that?

**Comment by alex-shpak** [comment]
Hi!
well, there are multiple ways depending on how much custom it needs to be.

If it is just list of pages in markdown, you can write custom shortcode that will print pages, there is one similar:
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/section.html
https://hugo-book-demo.netlify.app/docs/shortcodes/section/

For more customization you can create custom page type or customise `home.html` 
https://gohugo.io/templates/homepage/
https://gohugo.io/templates/lookup-order/

**Comment by fzyzcjy** [comment]
Thanks!
