### ISSUE TITLE
Link to homepage in menu

### ISSUE THREAD

**Issue by kerwitz** [alex-shpak/hugo-book#406]
When using the BookMenuBundle I can simply add a link to the homepage in whatever section I'd like. How would I achieve that with the directory menu? 

I.e. I have the following structure:

```
/
    _index.md
    /docs
        /introduction
            _index.md
            usage.md
```

As per my config that would show up like this using the generated menu:
```
Introduction
 - Usage
```

When I really want this:
```
Introduction
 - Home
 - Usage
```

I fail to see how I can have a link to my _index.md in a nested section of the menu, if at all possible. If not, what would you suggest? Resorting to using a partial and two separate files?

**Comment by alex-shpak** [comment]
Hi!
There is no way to do that at the moment,

As alternative you can add page to `before` menu to point to home. that will make structure like this
```
Home
Introduction
 - Usage
```

Well, for my use cases I just click on site title, that is linked to home

**Comment by alex-shpak** [comment]
See https://github.com/alex-shpak/hugo-book/pull/440
Should do the trick
