### ISSUE TITLE
Footer appearing on the side

### ISSUE THREAD

**Issue by mojomaayan** [alex-shpak/hugo-book#407]
Hi,

In [my site](https://padips.in/docs/jee_main/jee_main_math/2013/), I added the following line in partials/docs/inject/footer.html

`<p class="footer text-center">Copyright (c) {{ now.Format "2006"}} Padips Inc. </p>`

However the footer is rendered to the right of the screen and not at the bottom as expected. Is this a known issue?

**Comment by alex-shpak** [comment]
Hi!
As it looks to me, it happens on one page,
I suspect that HTML or shortcode inside of markdwn is not valid, which makes it to add extra tag at footer level.

Please carefully inspect content of  `<article class="markdown">` html tag, seems like there is some inclosed tag there

**Comment by alex-shpak** [comment]
This place looks suspicious
```
</div>
<a id='showanswer1'></a>
```

**Comment by mojomaayan** [comment]
Thanks, the issue can be closed, I have debugged it from my end!
