### ISSUE TITLE
Hugo does not preserve capitalization of multilingual codes and hreflang 

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#408]
https://github.com/gohugoio/hugo/issues/7808

this seems true also with hugo book theme ,

**Comment by longlu** [comment]
it has hreflang but it does not seems to preserve capitalization

**Comment by alex-shpak** [comment]
Hi!
Yes, unfortunatelly it is nothing I can fix in theme.

**Comment by alex-shpak** [comment]
Perhaps fix mentioned in comments can be applied, with settings LangCode for every languadge, will think.
