### ISSUE TITLE
Setting the site language in site parameters

### ISSUE THREAD

**Issue by chrillek** [alex-shpak/hugo-book#410]
Apparently, the theme uses `.Site.Language.Lang` to set the `lang` attribute of the `html` element. According to Hugo's documentation, this is the "language of the current locale". Now my locale is most definitely German, but the language is still "en". OTH, I've set the parameter `languageCode` in my config.toml to the value I'd like the `lang` attribute to have.

Wouldn't it be better to take the `lang` attribute's value from the site config file instead of from some environment?

**Comment by alex-shpak** [comment]
Hi!
I don't think I understand the problem.

https://www.w3schools.com/tags/ref_language_codes.asp
attribute `lang` declares languadge of html page.

Is your problem that you have `en` language by default but content is written in `de`? then you can set default language in hugo by `defaultContentLanguage`

**Comment by chrillek** [comment]
The template 'baseof.html' uses this line at its very top:
`<html lang="{{ .Site.Language.Lang }}" dir="{{ .Site.Language.LanguageDirection | default "ltr" }}">`
which references `.Site.Language.Lang`. This is, as I said before, somehow the "language of the current locale" (Hugo documentation). I'd rather have some kind of user-configurable site parameter here, like `languageCode`, so the line would look like this:
`<html lang="{{ .Site.LanguageCode}}" dir="{{ .Site.Language.LanguageDirection | default "ltr" }}">`
(not sure about the capitalization here). Using `defaultContentLanguage` in the site parameters would be another option, if that[ were working as it should](https://github.com/gohugoio/hugo/issues/7344)..

**Comment by alex-shpak** [comment]
Sorry, I struggle to understand the problem.
```
.Site.Language.Lang
the language code of the current locale (e.g., en).
```
from documentation is referencfing current locale in hugo during page generation, basically the languadge of page.

Tho, there is existing problem with `defaultContentLanguage`, that it has to be lowercase. But I don't think it is serious problem and you can just use `defaultContentLanguage`

**Comment by chrillek** [comment]
First, in my case, the current locale is de_DE.UTF-8, the site is written in en_US. And `Site.Language.Lang` seems to be 'en' regardless of the locale (which is nearly ok, but I'd need it to be 'en_US'). At least the HTML generated by Hugo has `lang="en"` in the `html` element.

Yes, forcing `defaultContentLanguage` to all lowercase _is_ a problem because then the regional code (like the US in en_US) is lowercase, too – which is invalid. This is discussed in the Hugo issue I linked to above. 

I'm suggesting a site parameter that hugo-book uses in the `lang` attribute of the `html` element _as is_, without lowercasing or otherwise changing it.

**Comment by alex-shpak** [comment]
By 'the current locale' you mean your computer locale? browser locale?
I understand what happens with lowercased languadge code, but what problem does it cause? Some SEO optimisation issue?

If it is just html validator warning, I would rather wait for fix from hugo team.

**Comment by alex-shpak** [comment]
Perhaps this can be a solution https://github.com/gohugoio/hugo/issues/7808#issuecomment-706458824

**Comment by chrillek** [comment]
This still puts `lang="en-us"` in the `html` element, _not_ `lang="en_US"`. For _that_ to happen, the _default/baseof.html template would have to use `languageCode`, I guess.

**Comment by alex-shpak** [comment]
Literally this line
https://github.com/alex-shpak/hugo-book/commit/3a65df3a76e20ae3f9926aaa69ffc14a86fff055#diff-ec6e7cb6e89cbe10d49085811bd67ad23df375247295fc387da90f5fdc56de7fR2
