### ISSUE TITLE
Can I create a new section that parallell parallell with 'docs' directly?

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#411]
Can I create a new section that parallell with 'docs' directly?  and with new menus for the section

**Comment by longlu** [comment]
I tried that the page could work, but, but the side menus are from 'docs' section

**Comment by alex-shpak** [comment]
Hi!
Can you please sketch and example? not sure what you are trying to achieve

**Comment by longlu** [comment]
BookSection = '*'

yes , the default is docs, 

sometimes there are much content in the side menu.

it'd be great it allow creating multiple booksections, which has different side menus
