### ISSUE TITLE
[FEAT] GitLab IDE: Different BookRepo for edit this page link

### ISSUE THREAD

**Issue by alwinw** [alex-shpak/hugo-book#414]
Great template! I'm using this on GitLab pages, and I'm hoping to change the `Edit this page` link to use the GitLab IDE instead of the normal edit file webpage for a richer user experience.

- <https://gitlab.com/group/repo/-/blob/main/content/get-started/page.md>: Example page
- <https://gitlab.com/group/repo/-/edit/main/content/get-started/page.md>: Edit example page
- <https://gitlab.com/-/ide/project/group/repo/edit/main/-/content/get-started/page.md>: Edit example page in web IDE

I understand that I can set `BookEditPath: edit/main` to get functionality edit a single page, but is there a way I can add `-/ide/project` between `gitlab.com` and `group/repo` for web IDE functionality? Ideally, without changing `BookRepo: https://gitlab.com/group/repo` as I'm using this for the last modified and edit this page links.

If this is a new piece of functionality required, I'd be happy to try work on it myself and open a PR if you can please give me some guidance on what the new configuration parameter should be called.

Thanks!

**Comment by alex-shpak** [comment]
Hi!
Well, as a hack, `BookRepo` variable is only used to generate edit URL to the page.
so you can try setting `BookRepo: https://gitlab.com/-ide/....`

**Comment by alwinw** [comment]
I've given it a go, but (apologies if it wasn't clear before) it changes the last modified link as well. Changing `BookRepo` to include `gitlab.com/-ide/...` also changes the last modified link to `https://gitlab.com/-/ide/project/group/repo/commit/hash` which doesn't resolve correctly.

**Comment by alex-shpak** [comment]
Ah, I forgot about that one,
well, footer layout will need to be changed to achieve that.

perhaps we can have templatable value 🤔 
like `https://domain.com/blahlblah/{{ .Page }}` or something similar

**Comment by alex-shpak** [comment]
Unfortunately that will be a backward incompatible change, so need to be careful here.

**Comment by MAHDTech** [comment]
What about the creation of a new variable, and then any of this special config could be applied in that case.

Then default it to have the same behavior as now for backwards compatibility.

```yaml
BookEditType: default

BookEditType: gitlab

BookEditType: gitlab-ide

BookEditType: github

BookEditType: bitbucket

...
```

**Comment by alex-shpak** [comment]
Hi! I moved link generation into `docs/links/edit.html` and `docs/links/commit.html` partials so that users can re-define them and adjust to needed hosting platform
