### ISSUE TITLE
Rename branch master to main

### ISSUE THREAD

**Issue by deining** [alex-shpak/hugo-book#417]
**[Theme demo](https://hugo-book-demo.netlify.app/) at Netlify:**

All links `Edit this page` are broken, this is a regression introduced with #325.

There are two remedies:

* revert #325 
* rename branch `master` of this repo to `main`.

I would advocate for the second choice given. Users that have a local clone can update it by running the following commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head orig
```

**Comment by alex-shpak** [comment]
Hi!
Yeah, perhaps it is time.
I'm not a big fan of renaming for renaming :)
