### ISSUE TITLE
Add parameter for BookCollapseSectionLevel

### ISSUE THREAD

**Issue by egonelbre** [alex-shpak/hugo-book#418]
For larger number of content it would be nice to specify a level where to automatically collapse pages, rather than specifying `bookCollapseSection: true` them individually to each item.

_Note: I can try figure out an implementation, if it's seems suitable._

**Comment by alex-shpak** [comment]
Hi!
It was discussed before, can't find that issue now.
But, my conclusion was that thoose parameters will be too specific, and I try to avoid adding many configuration parameters in theme, less paramteres will help be maintaning it.

`BookCollapseSectionLevel` then will become `BookCollapseSectionLevelFrom` and `BookCollapseSectionLevelToo` and so on, as some users want to collaps top 3, other bottom 3, etc.

So I think it's better to keep it as it is.

**Comment by alex-shpak** [comment]
ah, here it is https://github.com/alex-shpak/hugo-book/pull/340

**Comment by egonelbre** [comment]
Understandable, I definitely love the minimalist approach in hugo-book and wouldn't want to compromise it. I'll close the issue.

I was able to write custom menu-filetree that handles it, so it's not an hinderance for me.
