### ISSUE TITLE
Allow creating links to external sites from markdown files

### ISSUE THREAD

**Issue by egonelbre** [alex-shpak/hugo-book#419]
Currently the only ways to extend the file-tree menu is by changing either the config.toml or modifying the menu before or after partials.

It would be nice to be able to specify menu items as files e.g. could be located `content/resources/download-pdf.md`:

```
---
title: "Download PDF"
weight: 10
link: "https://www.example.com/documentation.pdf"
---
```

There might be a better name than `link`... maybe `canonicalURL`, `externalLink` or something like it?

This could be handled similarly how sections without content are. This could also potentially help with situation like https://github.com/alex-shpak/hugo-book/issues/406.

*Note: I can try figure out an implementation, if the idea seems suitable.*

**Comment by alex-shpak** [comment]
Hi!
Can be useful, I will think about implementation.

**Comment by alex-shpak** [comment]
Perhaps parameter `BookHref` or something similar.

**Comment by egonelbre** [comment]
Yes `bookHref` sounds good too.

**Comment by egonelbre** [comment]
I would guess it's a new tab, unless it's the same domain. And maybe there are a few different cases.
