### ISSUE TITLE
Manual dark/light theme switch button

### ISSUE THREAD

**Issue by pwittchen** [alex-shpak/hugo-book#420]
Hi,

Thanks for the great theme!

This issue is related to #151. I know that this theme has dark and light version and it's possible to set it to "auto" depending on the user system/browser configuration. I would like to have theme switch button on the website where user can switch theme to dark or light manually. Are you planning to add feature like that to the theme? Or alternatively, can you give me some hints how to create it by myself? Unfortunately, I'm not very experienced with hugo themes and front-end right now.

Regards,
Piotr

**Comment by alex-shpak** [comment]
Hi!
There are sme suggestions in issue #151 you mentioned, how to implement it, though, I don't think I will add switch button to theme.

https://github.com/alex-shpak/hugo-book/issues/151#issuecomment-692144866

**Comment by pwittchen** [comment]
Ok, thanks for the reply.
