### ISSUE TITLE
Feature Request: Multiple Book Sections

### ISSUE THREAD

**Issue by michaeltlombardi** [alex-shpak/hugo-book#423]
As a hugo site developer/maintainer using `hugo-book` as a module, I would like to be able to define 2+ folders in `content` as book sections _without_ having the book section behavior applied to _all_ of my folders (for example, `content/foo` and `content/bar` but not `content/baz`) so that I can host multiple discrete sections without having to update metadata for all other files.

## Example Use Case

In my [flagrant.garden][1] site ([source][2]), I would like to treat the [`games`][3] and [`horticulturists`][4] folders as book sections in terms of navigation and display _without_ treating posts or any other files/folders as such.

## Suggested Implementation

Update the [`docs/menu-filetree.html`][5] partial to handle when `$bookSection` is a string or array of strings and loop over calling the `book-section-children` template if needed and ensure all other references to `$bookSection` pages are updated to handle arrays as well as single entries.

This should make the update backwards compatible (i.e. not require theme users to update their config to always specify an array, even of just one section) without having to add a new configuration variable and handling, I think.

I'm happy to develop and submit a PR for this feature if accepted.

[1]: https://flagrant.garden/
[2]: https://github.com/FlagrantGarden/site
[3]: https://github.com/FlagrantGarden/site/tree/main/content/games
[4]: https://github.com/FlagrantGarden/site/tree/main/content/horticulturists
[5]: https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html

**Comment by alex-shpak** [comment]
Hi!
Would applying `BookHidden` to `content/baz` solve your problem? :)

**Comment by michaeltlombardi** [comment]
Hi! So, that definitely works as a work-around for me, but I think clashes with the principle of obvious/minimal configuration elsewhere in the theme.  As a naive user, I think I would expect to be able to set either a comma separated string or a yaml/toml array for `params.BookSection` and have it behave as expected instead of needing to add a parameter to every index/page at the top level I _don't_ want included in the default nav.

**Comment by alex-shpak** [comment]
Was thinking about it for some time,
Perhaps having comma separated list of sectipns could be convenient, but looking at template code it will add quite some comlexity to it, so I don't really feel like adding that :) 
Also wherew will be the line, comma separated list? glob? regex?

I would suggest to stick to hidden sections.

**Comment by michaeltlombardi** [comment]
@alex-shpak no worries! I've got no problem closing this as a won't-do on account of the increased complexity for small return. I'll use hidden sections for my use case (and document the same for my users).

I appreciate you taking the time and consideration on this request!
