### ISSUE TITLE
Mistranslations caused by File-Tree menu

### ISSUE THREAD

**Issue by rishubn** [alex-shpak/hugo-book#424]
Hi,

We're using this theme to create a multilingual site. We noticed that the menu adds an additional latin "s" at the end of menu headings. Here's an example:
The correct word is "країни" (countries), but the theme generates "країниs"
![image](https://user-images.githubusercontent.com/6591138/155881846-e76d311d-0817-40ec-a745-e2a339c0da01.png)

The code and website is available at https://github.com/rishubn/helpua / https://helpua.at/ to take a look at
The folder structure is:
```
content
│   ├── _index.ua.md
│   └── країни
│       ├── hungary.md
│       ├── moldova.md
│       ├── poland.md
│       ├── romania.md
│       └── slovakia.md
├── content.en
│   ├── countries
│   │   ├── hungary.md
│   │   ├── moldova.md
│   │   ├── poland.md
│   │   ├── romania.md
│   │   └── slovakia.md
│   └── _index.en.md
```

How can we fix this?

config.toml
```
baseURL = 'https://helpua.at'
languageCode = 'uk'
title = ''
theme = "hugo-book"
defaultContentLanguage = 'ua'
[languages]
    [languages.en]
        languageName = "🇺🇸 English"
        title = ""
        weight = 2
        contentDir = 'content.en'
    [languages.ua]
        languageName = "🇺🇦 yкраїнська"
        title = ""
        weight = 1

[params]
    BookTheme = 'auto'
    BookToC = false
    BookSection = '*'
    BookLogo = 'logo.jpeg'

[markup.goldmark.renderer]
unsafe= true
```

**Comment by alex-shpak** [comment]
Hi!
Most likely you need to disable `pluralizelisttitles` in site config.

See:
https://gohugo.io/templates/lists/#:~:text=The%20default%20behavior%20of%20Hugo,directive%20in%20your%20site%20configuration.

🇺🇦

**Comment by rishubn** [comment]
Thanks this fixed it!
