### ISSUE TITLE
Feature Request: A highlight line showing on TableOfContents

### ISSUE THREAD

**Issue by tcitry** [alex-shpak/hugo-book#425]
Hey, first I want thanks for this project, this works very good on my blog.

Recent days I discover some blog site has a highlight line showing on TableOfContents, I think it is very useful to reverse navigate. when you scroll the page, the right sidebar will also change highlight line.

Maybe my English description is not accurate, here has an example to understand: https://demo.stack.jimmycai.com/p/markdown-syntax-guide/

**Comment by alex-shpak** [comment]
Hi!
It is not part of theme, as I try to keep JS minimal, but you can add it yourself,
Please check https://github.com/alex-shpak/hugo-book/issues/235

**Comment by tcitry** [comment]
Get it! Thanks again.
