### ISSUE TITLE
Katex in Heading and table of content (TOC)

### ISSUE THREAD

**Issue by dukenmarga** [alex-shpak/hugo-book#427]
Hi,
I just want to include symbol in heading using Katex, for example below I tried to use \lambda.
The content is OK, but in the table of content (right side) shows additional random string. I think this string has replaced the symbol \lambda. Is there any way to prevent this? Or is it possible the TOC use exactly shown with the symbol?

![combine](https://user-images.githubusercontent.com/743869/156921584-ca0c5d9c-002a-41bc-b170-b90df51d5353.png)

Thank you

**Comment by alex-shpak** [comment]
Hi!
From quick glanc, this is a limitation of rendering, I don't think there is way to render shortcode into TOC, unfortunatelly.

Maybe you can use lambda symbol from UTF `λ`

**Comment by dukenmarga** [comment]
Thank you Alex.
I ended up using symbol from UTF characters.
