### ISSUE TITLE
location issues in demo site

### ISSUE THREAD

**Issue by AmenLemon** [alex-shpak/hugo-book#428]
for example
Columns and Details 
https://imgur.com/cgZ5pXj
Is this a bug?
It feels particularly obvious when you click to switch articles

**Comment by alex-shpak** [comment]
Hi!
It is due to how windows handles scrollbars.
Page is centered, and on first picture scrollbar pushes viewpoint.

**Comment by AmenLemon** [comment]
Thank you for answering
