### ISSUE TITLE
[question] versioned documentation

### ISSUE THREAD

**Issue by ChewingBever** [alex-shpak/hugo-book#434]
Hi!

I gotta say I'm really loving this theme for my documentation. I do however wonder whether it's possible to have multiple versions of the documentation, e.g. using git branches.
The way I currently use this theme is by having a subdirectory in `content` for each project, and in that directory sit the docs for that specific project. However, if possible, I'd like to be able to do e.g. `/project/0.2.0`, with the versioned subsection being created by using git branches of some kind.

Is this something that would be possible or do you know of any resources that I could use for this?

Thanks in advance!

**Comment by alex-shpak** [comment]
Hi!
At the moment there is no easy way to do multiple versions of site.
I know some people use multi-lang supprot for that, or deploy multiple sites in parallel, but not something we have in theme right now, and this one is hard to crack 🤔
