### ISSUE TITLE
[question] what is the difference between tags and categories?

### ISSUE THREAD

**Issue by TheChymera** [alex-shpak/hugo-book#435]
Seems like it is a redundant distinction, no?

**Comment by chrillek** [comment]
>  I'm thinking maybe it would be better for the default to make it bold?

It's not, and it is not related to Hugo themes at all. Also, you can turn it off. Check out the Hugo doc for more information on tags, categories and taxonomies in general.

**Comment by TheChymera** [comment]
> check out the Hugo doc

Best I could find is:

> categories
    currently auto-populated with ‘functions` for future-proofing and portability reasons only; ignore this field.
tags
    only if you think it will help end users find other related functions
    
Dunno what to make of it, sounds like neither is defined as meaning anything really.
Do you how they're fulfilling different purposes in this theme?

**Comment by alex-shpak** [comment]
Hi!
So, `tags` and `categories` are just default taxonomies from hugo, there is no specific support for them in theme, just generic support for taxonomies: https://gohugo.io/content-management/taxonomies/

You cab disable either or both tags and categories in hugo config.
https://gohugo.io/content-management/taxonomies/#example-removing-default-taxonomies
