### ISSUE TITLE
activating KaTeX per-page inserts `\(\)` at the beginnign of the page summary.

### ISSUE THREAD

**Issue by TheChymera** [alex-shpak/hugo-book#437]
Going by this suggestion: https://github.com/alex-shpak/hugo-book/issues/164#issuecomment-593593487
A weird string gets prepended to the page listing, as seen in the picture below:
![decohost_2022-04-15T01:47:09](https://user-images.githubusercontent.com/950524/163526936-3e701080-e894-4b59-8e1d-5b8891027333.png)

Interestingly enough, this does not appear on the actual page. Any idea what can be done about it?

**Comment by TheChymera** [comment]
Hmmm.... interestingly enough putting `{{< katex />}}` at *the end* of the file rather the beginning, both enables KaTeX on the page and inserts no string I could find. All-round pretty strange, though it would kind-of fix or at least obscure the issue.

**Comment by alex-shpak** [comment]
Hi!
having standalone empty `{{< katex />}}` tag is okay, as more-less `{{< katex />}}` shortcode tag just enables KaTeX library for page.
There is an issue with how hugo renders markdown under shortcodes making it escape `\)\)` sequence and causing KaTeX library to not pick up formulas. Wasn't able to fix it so far.

**Comment by alex-shpak** [comment]
Do you have your webiste published? so I can take a look.

**Comment by TheChymera** [comment]
@alex-shpak http://www.opinions.chymera.eu/ code being here https://github.com/TheChymera/chymeric-hugo

The issue is not present right now, but I can break a blog post on purpose and link you to it if would help you help me :)

**Comment by alex-shpak** [comment]
Issue got lost unfortunately, tell me to reopen if you still need help.
