### ISSUE TITLE
figures are no longer displayed online

### ISSUE THREAD

**Issue by MalteHueckstaedt** [alex-shpak/hugo-book#443]
Hi, 

since yesterday, figures are no longer displayed online after creating a website with netlify. Offline everything works without any problems. Do you have any idea what the problem could be?

example here:
https://exquisite-cascaron-d6489f.netlify.app/posts/2022-04-18-test-blog/

repro here:
https://github.com/MalteHueckstaedt/blogdown_chernoff_faces

**Comment by alex-shpak** [comment]
Hi!
Looking into generated URL: https://example.com/posts/2022-04-18-test-blog/index_files/figure-html/unnamed-chunk-1-1.png

Looks like your site context is set to `example.com`

**Comment by MalteHueckstaedt** [comment]
Hi @alex-shpak , 

thanks for the quick help, that's the solution!

regards,
malte
