### ISSUE TITLE
Upgrade to Mermaid 9.x

### ISSUE THREAD

**Issue by austince** [alex-shpak/hugo-book#445]
9.x was released recently: https://github.com/mermaid-js/mermaid/releases/

Any idea what it would take to upgrade?

**Comment by alex-shpak** [comment]
Hi!
Will need to take a look if there were breaking changes.

**Comment by austince** [comment]
From the release notes, it looks like no breaking changes: https://github.com/mermaid-js/mermaid/releases/tag/9.0.0
But, not sure if there's a good way to double check that.

**Comment by alex-shpak** [comment]
Upgraded
