### ISSUE TITLE
Why is the leaf bundle menu option being removed?

### ISSUE THREAD

**Issue by kovasap** [alex-shpak/hugo-book#446]
I really like the new automatically generating menu system.  However, before that was added, i built my own solution that makes a custom menu I like a lot now.  Why is the option to do this being removed as per the README?  Code cleanliness?

I just want to make sure that you know the feature is still being used!

**Comment by alex-shpak** [comment]
Hi!
Leaf menu was introduces from the beginning, when file-tree generated menu was very limited in features.
Now it is reverse, all the collapse, flat-out, etc functions are present in file-tree menu, but there is not technical possibility to implement it in leaf menu. And also there is support for native hugo menus now.

It can stay for some more time, tho without adding new features to it.

**Comment by MaximilianKohler** [comment]
So if I'm using `content\menu\index.md` to customize the left-side nav bar, it's not possible to have sections be collapsible?

>And also there is support for native hugo menus now.

Is it possible by using this? _(I have no idea what this is)_

**Eg**:

On https://hugo-book-demo.netlify.app/ the collapsed menus' URL is: 
`https://hugo-book-demo.netlify.app/docs/example/collapsed/3rd-level/` 
but I want a collapsable menu with links like:
`https://hugo-book-demo.netlify.app/3rd-level/`. 

It's not possible?
