### ISSUE TITLE
List all matching results while searching

### ISSUE THREAD

**Issue by z-8-d** [alex-shpak/hugo-book#449]
Hi all! Currently I'm using hugo with hugo-book for my site. I found that there are at most 10 results listed while typing filtering strings. I'm wondering is there a way to list all the matching results? This could be in a new page, some post or any other forms.

Thanks for your work on this great theme!

**Comment by alex-shpak** [comment]
Hi!
Here in code where search is limited 
https://github.com/alex-shpak/hugo-book/blob/master/assets/search.js#L82

In theory you can write a new page of any layout you want and make it print all found results, tho beware of possible rendering performance issues in browser.
