### ISSUE TITLE
insert an image via RStudio using the R package blogdown

### ISSUE THREAD

**Issue by lennyleadership** [alex-shpak/hugo-book#451]
I have no problem inserting images on posts and docs at my blog with the hugo-eureka template.  I just copy and paste the following code: 
`<img width ="360" height= "200" src = "/docs/images/image.png"/>`

I don't have to modify CSS file(s).

I am not successful in doing so with the hugo-book template.

Could you please walk me through the process?  particularly, do I have to change CSS file(s)? if so, which one?

**Comment by alex-shpak** [comment]
Hi!
I don't have experience with RStudio, can you please elaborate on what you are expecting and getting? any error?
