### ISSUE TITLE
Add prefix to Categories and Tags

### ISSUE THREAD

**Issue by PhilipMay** [alex-shpak/hugo-book#458]
When I open a single blog page with tags and categories they are displayed as a list of links on top of the page.

See here: https://hugo-book-demo.netlify.app/posts/goisforlovers/

The problem is: IMO there should be a prefix in front of them saying `Categories:` and `Tags:`.

Could you add that?

What do you think?

**Comment by PhilipMay** [comment]
Hey @alex-shpak - thanks for the quick answer and the tip.
I would suggest something like this:

```html
{{ range $taxonomy, $_ := .Site.Taxonomies }}
  {{ with $terms := $.GetTerms $taxonomy }}
  <div class="{{ $taxonomy }}"> {{ $taxonomy }}:
    {{ range $n, $term := $terms }}{{ if $n }}, {{ end }}
      <a href="{{ $term.RelPermalink }}">{{ $term.Title }}</a>
    {{- end }}
  </div>
  {{ end }}
{{ end }}
```

**Comment by PhilipMay** [comment]
And then maybe:

```
div.categories,
div.tags {
    font-size: .75rem;
}
```

**Comment by alex-shpak** [comment]
Looks ok if it works for you :)
You can also try `<div> {{ ($.Site.GetPage $taxonomy).Title }}:` to get hugo title for taxonomy page
