### ISSUE TITLE
Edit link return a 404 error

### ISSUE THREAD

**Issue by slashformotion** [alex-shpak/hugo-book#459]
![image](https://user-images.githubusercontent.com/45801817/178349876-5c259136-cb42-4902-90f8-01ec1530bdc1.png)

the link `https://github.com/alex-shpak/hugo-book/edit/main/exampleSite/content/docs/example/_index.md` should be `https://github.com/alex-shpak/hugo-book/edit/master/exampleSite/content/posts/_index.md`

**Comment by alex-shpak** [comment]
Well, maybe it is time to rename default branch.
