### ISSUE TITLE
noob errors shortcode at first installation (as a submodule)

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#460]
Hi,
I found this theme to be exactly what I wanted minus a few stylistic details, but I'm completely helpless in web management. I wanted to dowload your demo and figure out with the exemple where goes what, so I did the procedure to install from scratch (hugo new site mydocs; cd mydocs; git init; git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book; cp -R themes/hugo-book/exampleSite/content .), but I got errors I don't understand, with shortcodes or whatnot. I suppose I just miss a few libraries, as usual.

Thanks for your wonderful theme.

<details> <summary> Details </summary>~/D/A/M/Y/my_blog_en (master)> git submodule add https://github.co
m/alex-shpak/hugo-book themes/hugo-book

Clonage dans '/home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/my_blog_en/themes/hugo-book'...
remote: Enumerating objects: 4070, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 4070 (delta 2), reused 13 (delta 1), pack-reused 4047
Réception d'objets: 100% (4070/4070), 6.24 Mio | 921.00 Kio/s, fait.
Résolution des deltas: 100% (2086/2086), fait.

~/D/A/M/Y/my_blog_en (master)> hugo server --minify --theme hugo-b
ook

Start building sites … 
hugo v0.101.0+extended linux/amd64 BuildDate=unknown

                   | EN  
-------------------+-----
  Pages            |  7  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 78  
  Processed images |  0  
  Aliases          |  2  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 291 ms
Watching for changes in /home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/my_blog_en/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/my_blog_en/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

~/D/A/M/Y/my_blog_en (master)> cp -R themes/hugo-book/exampleSite/
content .

~/D/A/M/Y/my_blog_en (master)> hugo server --minify --theme hugo-b
ook

Start building sites … 
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
WARN 2022/07/14 10:55:12 Expand shortcode is deprecated. Use 'details' instead.
Error: Error building site: "/home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/my_blog_en/content/docs/shortcodes/mermaid.md:14:1": failed to render shortcode "columns": failed to process shortcode: "/home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/my_blog_en/themes/hugo-book/layouts/shortcodes/columns.html:4:12": execute of template failed: template: shortcodes/columns.html:4:12: executing "shortcodes/columns.html" at <$.Page.RenderString>: error calling RenderString: "/home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/my_blog_en/content/docs/shortcodes/mermaid.md:3:13": unrecognized character in shortcode action: U+005B '['. Note: Parameters with non-alphanumeric args must be quoted
Built in 790 ms [/details]

**Comment by alex-shpak** [comment]
Hi!
There is and unsolved nesting issues in shortcodes at the moment.
https://github.com/alex-shpak/hugo-book/issues/452

It happens when shortcode is nested in another shortcode. Before fix either:
1. install pre 0.100 version of hugo
2. delete nested shortcode in mermaid/katex pages

It turned to be not easy to fix :)

**Comment by evanescente-ondine** [comment]
> delete nested shortcode in mermaid/katex pages
Sure ? How do I do ?
What would it change ?

**Comment by alex-shpak** [comment]
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/docs/shortcodes/mermaid.md?plain=1#L14
In this file delete lines `14`, `28`, `41`

And in
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/content/docs/shortcodes/katex.md?plain=1
lines `6`, `14`, `20`

**Comment by evanescente-ondine** [comment]
ok I did that (only the lines, not what was between), and erase the the column line in content/_index.md because it complained.
Now it's: 

> drm@DasReich ~/D/A/M/Y/myblog_en (master)> hugo server
Start building sites … 
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
Error: Error building site: "/home/drm/Documents/Autres_recherches_historiques_ou_genetique/Mes_propres_textes/Youtube/myblog_en/content/docs/shortcodes/section/_index.md:15:1": failed to extract shortcode: template for shortcode "section" not found
Built in 19 ms

**Comment by alex-shpak** [comment]
hm, well, it works for me, do you have your code pushed to git somewhere? Perhaps not all templates were copied

**Comment by evanescente-ondine** [comment]
I don't. Perhaps the simplest is to give instructions to repeat the process since it seemingly has been rather straightforward for you.

So I begin with:
``` hugo new site mydocs; cd mydocs; git init; git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book; cp -R themes/hugo-book/exampleSite/content```
Then I delete exampleSite/content/docs/shortcodes/mermaid.md lines `14`, `28`, `41`
then exampleSite/content/docs/shortcodes/katex.md?plain=1 lines 6, 14, 20
Then ?
I run "hugo server --minify --theme hugo-book" and the exemple site's supposed to work out of the box ?

**Comment by alex-shpak** [comment]
yep, problem is with shortcodes inside of other shortcodes in versions 100+
