### ISSUE TITLE
change dark mode for a wallpaper

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#461]
Hi,
The css is completely out of my league, a simple tuto clearly wasn't enough to do s**it with that kind of thing.
Is there a simple (relatively speaking) way to get a wallpaper instead of the uniform background color ? A rather black image, so the font colors might have to change (though if changing is simple, I wouldn't mind knowing where to do so).

thanks

**Comment by alex-shpak** [comment]
Hi!
You can customize css in file `assets/_custom.scss` in your repo
There is `--body-background` css variable you can change: https://github.com/alex-shpak/hugo-book/blob/master/assets/_main.scss#L10

You can probably do
```
--body-background: url("img/url");
```
And then play with background property untill you get result you want

**Comment by evanescente-ondine** [comment]
I think something like
> background-color: rgba(0, 0, 0, 0.4);
> background: url("Images/wallpaper_matthiew_prefere.jpg");
would do. I'll have to deactivate the bright mode though.

**Comment by evanescente-ondine** [comment]
Sorry, I got it now ;-)
