### ISSUE TITLE
various issues, probably trivial

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#462]
Hi, I have some issues, some to do with hugo-book some I'm not certain.
- From the explanation and testing, I can't understand what "bookFlatSection: true" does nor see that it does anything.
- Talking about links I just don't get it, I don't expect hugo-book to mess with it but this place is as good as any to ask and the answer's probably trivial to you. But since my config.toml includes:
> disablePathToLower = true
BookPortableLinks = true

maybe it is indeed related. Adding "canonifyURLs = true" doesn't change anything.
Here's a sample of my tree:
/home/drm/Blog_en
 ├──􀀂  content 
 │  ├──􀇱  _index.md 
 │  ├──􀀂  docs 
 │  │  └──􀀂  The most important discovery of all 
 │  │     ├──􀇱  _index.md 
 │  │     ├──􀇱  cooking_origin_EN MASTER.md 
 │  │     └──􀇱  ENmaster.md 
 │	└──􀅣  seax1.jpg
 ├──􀀂  static 
 │  ├──􀀂  biology 
 │  │  ├──􀇱  _index.md 
 │  │  ├──􀅣  chimp_eats_monkey.jpg 
From content/_index.md, I can access anything but only below static/ so ![](biology/chimp_eats_monkey.jpg) and [](_index) work fine.
Nothing else does. I tried a bunch of combination with ref/href shortcodes, https://gohugo.io/content-management/cross-references/ didn't help at all either.
```![](../content/seax1.jpg)```
shows a broken link. ALL attempts at ref or relref invariably crash the whole site crashes with
> \[en] REF_NOT_FOUND: Ref "../content/seax1.jpg": "PATH/PAGE_WHERE_THE_REFERENCE_IS_MADE.md": page not found  logged 1 error(s)"

I would like a simple means to access any file, md or otherwise, present below "Blog_en".

**Comment by alex-shpak** [comment]
Tried it locally and it worked for me 🤔

**Comment by evanescente-ondine** [comment]
Look, my need is simple. I need a consistent way to refer to anything in static/, from anywhere down content/. How do I do ? Isn't there a "root" to the website, an absolute reference from which to access both texts in content/ and pictures in static/ ?

**Comment by alex-shpak** [comment]
well, it all works under rules, but you just need to get used to how hugo places files in output filetree
