### ISSUE TITLE
"warnings" about picture in local links

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#463]
Hi,
Now when I run the server I have a bunch of warnings,
<details><summary>which go like this:</summary>
drm@DasReich ~/WEBSITE_EN (master)> hugo server --gc --minify
Start building sites … 
hugo v0.101.0+extended linux/amd64 BuildDate=unknown
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/catching_fire_wrangham_book.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'image_article_conf_hladik_chimie_cadrée_originale.png' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'biology/image_tous_les_cerveaux.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/grenier.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'image_article_grenier-grain-paléolithique-mozambic.png' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/wrangham_quote.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/wrangham_book_goodness_paradox+demonic_male.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/image_article_microstrati.png' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'biology/tapetum_lucidum_bandeau.webp' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/iceman-petit.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'spirituality/gtummo-gtummo_personne_recadre.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/fire_bandeau.jpg' not found in 'docs/Alimentation/cooking_origin_EN_MASTER.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/michel-de-montaigne-011.jpg' not found in 'docs/Alimentation/maturation_faisandage_en_master.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/savarin_médaillon_recadré.jpg' not found in 'docs/Alimentation/maturation_faisandage_en_master.md'
WARN 2022/07/17 17:48:17 Image 'biology/inuit_complet.jpg' not found in 'docs/Alimentation/maturation_faisandage_en_master.md'
WARN 2022/07/17 17:48:17 Image 'biology/chimp_eats_monkey.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/singe_rat.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/Megascolides_vers_géant.png' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/essai_html_7e3b1bebc5c59090.png' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/essai_html_222eaedd5b113da1.png' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/bonobo_diet.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/bwindi_mountain_gorilla_diet.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/ngogo_eastern_chimp_diet.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/rio_muni_central_chimp_diet.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/chimp_eats_monkey.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/canard_batterie_1.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/chicks-are-pictured-in340-million-.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/monkey-enjoy-eat-egg-eating-260nw-1686911809.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/cephalope.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/termites_singe_sur_la_longueur.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/primate_mushrooms_eating_panneau.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/vomis.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/konrad-lorenz-1.jpg' not found in 'docs/Alimentation/_index.md'
WARN 2022/07/17 17:48:17 Image 'spirituality/mythology/Lilith.jpg' not found in '_index.md'
WARN 2022/07/17 17:48:17 Image 'Essai_méta_couv.jpg' not found in '_index.md'
WARN 2022/07/17 17:48:17 Image 'images_article_instincto/illustration_instincto.jpg' not found in '_index.md'
WARN 2022/07/17 17:48:17 Image 'spirituality/mythology/adam_eve_fall_eden.jpg' not found in '_index.md'
WARN 2022/07/17 17:48:17 Image 'History/Byron.jpg' not found in '_index.md'
WARN 2022/07/17 17:48:17 Image 'History/Sappho.jpg' not found in '_index.md'
</details>

As of now I can't show pictures in any file but the first _index.md, so for all of these references I understand why it might raise warnings... though I had the issue two days ago but there was no warning. Anyway;
But as you see the pictures (like Sappho.jpg) in this first _index ALSO raise warnings, eventhough they show up fine !
So I don't know how to interpret this...

**Comment by hitzhangjie** [comment]
This maybe relevant with this template render-image.html.

If the image URL isn't remote URL (a valid http/https url), then the template will try to locate the image to test it existed or not. If it cannot find the image by filesystem path, it reports an warning message.

This is how it works. I was disturbed by this kind of images problem. Maybe the 'Page Bundle' mode is easier. But I still prefer 'global mode'. If you prefer 'global mode' too, please see the render-image.html and do some changing to it.

You'll be quick to fix this :)

**Comment by evanescente-ondine** [comment]
I still don't understand. For some of these pictures (in content/_index.md) they ARE found, or they wouldn't be displayed in the browser. So why are there warnings ?
I wonder I'm being stupid here, or things are as annoyingly confusing as they seem.

**Comment by cjauvin** [comment]
@alex-shpak I'm writing in this issue, instead of creating a new one, because I'm quite certain that it's related. I am trying to switch my project to `BookPortableLinks = "warning"`, but I have a really hard time understanding how it's supposed to work. To be clear, I am _not_ using [leaf bundles](https://gohugo.io/content-management/page-bundles/#leaf-bundles) for my pages, so my images are all in the `/static/images/` folder. With that setup, I get a bunch of warnings:

```
WARN  Image reference '/images/ai-venn.png' not found in '/docs/pr%!C(MISSING)3%!A(MISSING)9sentation/'
WARN  Image reference '/images/hal_and_clippy.png' not found in '/'
WARN  Image reference '/images/livre_la_plus_belle_histoire_de_lintelligence.jpg' not found in '/docs/livres/'
WARN  Image reference '/docs/module2/travail-noté-2' not found in '/docs/travaux-not%!C(MISSING)3%!A(MISSING)9s/'
WARN  Image reference '/images/livre_quand_la_machine_apprend.jpg' not found in '/docs/livres/'
WARN  Image reference '/docs/module3/travail-noté-3' not found in '/docs/travaux-not%!C(MISSING)3%!A(MISSING)9s/'
WARN  Image reference '/docs/module4/travail-noté-4' not found in '/docs/travaux-not%!C(MISSING)3%!A(MISSING)9s/'
WARN  Image reference '/docs/module5/travail-noté-5' not found in '/docs/travaux-not%!C(MISSING)3%!A(MISSING)9s/'
WARN  Image reference '/images/sheets_params_menu.png' not found in '/docs/google-sheets/'
WARN  Image reference '/images/sheets_params_langue.png' not found in '/docs/google-sheets/'
WARN  Image reference '/images/sheets_visu_barre_formule.png' not found in '/docs/google-sheets/'
WARN  Image reference '/images/sheets_paste_special.png' not found in '/docs/google-sheets/'
```

To be clear, this is not useful to me, because it mixes warnings that I care about (wrong links to internal sections of my book) with false positive warnings about images, which I don't care about. What am I doing wrong, and is there a way to fix it?
