### ISSUE TITLE
Question: cannot search anything by i18n zh.yaml

### ISSUE THREAD

**Issue by hitzhangjie** [alex-shpak/hugo-book#465]
Could you help sovling the searching problem?
I write a ebook here: https://hitzhangjie.pro/go-internals/, it uses hugo-book theme. I don't know why the searching not working.
I use Chrome to debug the problem, and I see the document is indexed. 

Maybe the problem is relevant with i18n zh booksearchConfig, I change the tokenize function:
  from `str.replace(/[\x00-\x7F]/g, '').split('');`
  to `str.split(/\W+/).concat(str.replace(/[\x00-\x7F]/g, '').split('')).filter(e => !!e);`

And it worked.

**Comment by alex-shpak** [comment]
Hi!
Nice to see theme used :) that's a lot of content.
It is possible that search config tokenization needs update, as I don't have any idea how to search in chineese properly, and relied on google-help.

Although, when I naively put chineese 'Lorem ipsum' to page and search fractions of it, it works for me in `zh` locale.
Can you send what content you have and what are you trying to search as example?

**Comment by hitzhangjie** [comment]
For example, I want to search both Chinese and English words, like '码农' or 'AST' which appears in markdown file.

Let me show an example here to reproduce the problem.

## Case: tokenize function uses 'str.replace(/[\x00-\x7F]/g, '').split('');'

Let's search '码农', then we see the search result seems OK, it returns a document:
![image](https://user-images.githubusercontent.com/3725760/180005378-de00f9e7-6950-47f7-8efb-680e4cf9a039.png)

Then I search 'AST', then we see the search result is empty, it should returns 2 documents:
![image](https://user-images.githubusercontent.com/3725760/180007340-2a84f0df-50b2-4e2a-b77c-3eaa3e7ceccb.png)

## Case: tokenize function uses 'str.split(/\W+/).concat(str.replace(/[\x00-\x7F]/g, '').split('')).filter(e => !!e);'

Let's search both words again, it works.

search '码农':
![image](https://user-images.githubusercontent.com/3725760/180007723-b292be18-a0a5-4b63-b235-1d790f24039b.png)

search 'ast':
![image](https://user-images.githubusercontent.com/3725760/180007909-e8674c14-c440-4727-8527-c5b86315a9f8.png)

---

ps: Actually I don't know the internals about tokenize function, I came across this problem before and searched Google. I just  copy & paste the settings in my another hugo project.

**Comment by alex-shpak** [comment]
I hope this solves it finally 
https://github.com/alex-shpak/hugo-book/pull/600
