### ISSUE TITLE
Upgrade Mermaid.

### ISSUE THREAD

**Issue by salzig** [alex-shpak/hugo-book#469]
Based on the last commit, it looks like mermaid [8.12.0](https://github.com/mermaid-js/mermaid/releases/tag/8.12.0) is used, current would be [9.1.3](https://github.com/mermaid-js/mermaid/releases/tag/9.1.3)

**Comment by alex-shpak** [comment]
https://github.com/alex-shpak/hugo-book/issues/445
Upgraded
