### ISSUE TITLE
Flickering fonts

### ISSUE THREAD

**Issue by FuadEfendi** [alex-shpak/hugo-book#474]
Few very basic plain text webpages deployed at Netlify have very obvious flickering (changing size) of fonts when browsing (moving from page to page, refreshing). And I have super 900Mbps Internet access.

The same happens on MBP M1 during local tests, but very very little because Mac is super fast; but still visible (to those picky testers)

Enabling "cach-control" headers on Netlify helps, but "flickering" is still visible. 

Why to use "Roboto" fonts instead of default Verdana, sans-serif and monospace?

**Comment by alex-shpak** [comment]
Hi! it probably happens becuase of accesibility font switching.
You can try removing that (and similar) lines
https://github.com/alex-shpak/hugo-book/blob/master/assets/_fonts.scss#L6
