### ISSUE TITLE
hugo's own menu

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#477]
I just noticed there was a native hugo menu, and this theme ignored the parameters.
Did I do something wrong ? I literally copied and pasted the gohugo example code (decommented, obviously).

**Comment by alex-shpak** [comment]
Hi!
Which parameters were ignored?

**Comment by evanescente-ondine** [comment]
huh, well, you just solved the issue. one caveat I hadn't paid attention
to... Now that I learnt to read the code like a chad, I see not only how
you wrote things, but I can add new menus and put them anywhere.
Thanks for your great work !

**Comment by evanescente-ondine** [comment]
However I have another problem with menus, which seems to be a theme issue.
I want menu entries to be numbered, like chapters or sections in a book.
I tried to change ul for ol in partials/docs/menu-filetree.html but while it does number them, it also flats out all entries.

**Comment by alex-shpak** [comment]
Hi!
You can check how it is done in https://github.com/alex-shpak/hugo-book/blob/master/assets/plugins/_numbered.scss
Kinda overcomplicated, but it works for multilevel `ul` nubering.
