### ISSUE TITLE
more native KaTeX equations

### ISSUE THREAD

**Issue by lieskjur** [alex-shpak/hugo-book#482]
Averaging multiple equations per paragraph I would like to insert equations with a syntax more similar to that of LaTeX (especially those inline). There are multiple guides ([1](https://mertbakir.gitlab.io/hugo/math-typesetting-in-hugo/),[2](https://dzhg.dev/posts/2020/08/how-to-add-latex-support-in-hugo/#hook-to-existing-theme),[3](https://www.simonspavound.com/posts/2020/09/equations-with-katex-in-hugo/)) which describe how using "partials". I tried modifying hugo-book in the same manner ([my fork](https://github.com/lieskjur/hugo-book/tree/partial-katex)) but I have run into some rendering issues (an example [here](https://lieskjur.github.io/Notes-native/docs/bellman/) with [repo](https://github.com/lieskjur/Notes-native)). Does anyone know what the solution might be?

**Comment by alex-shpak** [comment]
Hi!
Sorry for delay. If i understand you correct
> with a cost (objective function) \[ J(\bm{x}0,t_0) = ∫{t_0}^{t_1} L(\bm{x},\bm{u},τ) , dτ \]
this output is a problem? it looks like issue with whitespaces somewhere.
