### ISSUE TITLE
how is the page type parameter processed ?

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#484]
Hi,
I can't understand how page types are used. The only mention of .Page.type is in taxonomy.. How does hugo or the theme knows how to render this or that page ? Where can it be overwritten, if for instance I want to remove the menu for the homepage ? I can remove the menu... but for ALL pages.

Thanks

**Comment by alex-shpak** [comment]
Hi!
Taxonomies and page types are quite cryptic in hugo :) 
`Kind`, `Type`, and `Layout` are used in template lookups: https://gohugo.io/templates/lookup-order/
So they are evaluated in order mentioned on documentation page do decide which template to use.
