### ISSUE TITLE
menu index.html in public folder not working properly

### ISSUE THREAD

**Issue by Ethan-Harris0n** [alex-shpak/hugo-book#486]
Hello,

I'm trying to use this theme for my hugo site.

The site builds locally just fine.

However when I check the output in the public folder -- the selecting an item on the menu is navigating to the site index (e.g. listing items in the folder) rather than the index.html. Does anyone have any ideas on how to fix this?

Let me know if I should attach more details! Thanks!

**Comment by alex-shpak** [comment]
Hi!
Do you have deployed example I can look at?

**Comment by alexatadi** [comment]
in my practice, you should start up a web server under `/public` but not just run (double click) the `index.html`

**Comment by adehad** [comment]
I can confirm the same behaviour. But it is worth noting, that if the `baseURL` is configured correctly the website will correctly render.

In my case I was having the same issue as below:

https://github.com/alex-shpak/hugo-book/issues/381
