### ISSUE TITLE
use cursor:pointer style for clickable menu icons

### ISSUE THREAD

**Issue by milahu** [alex-shpak/hugo-book#488]
`layouts/partials/docs/header.html`

```html
  <label for="menu-control">
    <img src="{{ "svg/menu.svg" | relURL }}" class="book-icon" alt="Menu" />
  </label>
```

etc

**Comment by alex-shpak** [comment]
Hi! Not sure, this button is only supposed to be visible on mobile width, where there is no cursor visible, what is your usecase?

**Comment by milahu** [comment]
on desktop, the buttons have `cursor:default` but should have `cursor:pointer`

**Comment by alex-shpak** [comment]
hello!
But menu control icon is not visible on desktop side of site
