### ISSUE TITLE
Support for a custom css (from outside the theme folder)

### ISSUE THREAD

**Issue by assayire** [alex-shpak/hugo-book#491]
Is there a way to provide a custom css/scss file from a path outside `<my-site-folder>/themes/hugo-book`? I like to add a couple of customizations to my site.

I see there is a `themes/hugo-book/assets/_custom.scss` but changing it is more like changing the theme itself (which I have added as a submodule in my project/site).

Thanks.

**Comment by assayire** [comment]
Just checking if this is possible today? If not, will it be supported anytime soon? Thanks.

**Comment by alex-shpak** [comment]
Hello,
Using inject template `layouts/partials/docs/inject/head.html` you can add reference to external CSS. With `link` tag

**Comment by alex-shpak** [comment]
Tho, you can create file `assets/_custom.scss` in your site sources, that will overwrite file from theme. You can overwrite most files like that.

**Comment by assayire** [comment]
The `assets/_custom.scss` turned out to be the perfect solution for the lazy ones like me. Thanks.
