### ISSUE TITLE
Katex or Mermaid work not.

### ISSUE THREAD

**Issue by soydivision** [alex-shpak/hugo-book#495]
I've built site from scratch, but above mentioned libs seem not to display. Am I missing something obvious?
![Katex-My-New-Hugo-Site](https://user-images.githubusercontent.com/48078889/198842480-c681ea6e-76ca-4c49-814a-a141800a19b5.png)

**Comment by alex-shpak** [comment]
Hi!
Screenshot looks like an outdated version of theme, perhaps try to upgrade it.

**Comment by soydivision** [comment]
> Hi! Screenshot looks like an outdated version of theme, perhaps try to upgrade it.

![Katex My New Hugo Site](https://user-images.githubusercontent.com/48078889/199700764-fe8bcccb-1299-44f7-b77b-2a45cfb40b90.png)
I've got the last version. Neither FF, no Chrome works. Are you sure those lib imported correctly?

**Comment by alexatadi** [comment]
Hi, below code works fine on my page.
----------------------------------------------------
{{< katex display >}}
\begin{alignedat}{2}\tag{2}
10&x+3y &= 2\\
3&x+13y &= 4
\end{alignedat}
{{< /katex >}}

**Comment by soydivision** [comment]
> Also works at https://hugo-book-demo.netlify.app/ do you have any errors in browser console?

No, I don't. Did you built it from your latest code in this rep?

**Comment by alex-shpak** [comment]
yes, https://hugo-book-demo.netlify.app/ is automatically built from latest code

**Comment by bjonnh** [comment]
I have the same issue:
https://bjonnh.github.io/dinoctopus/docs/shortcodes/mermaid/

The whole source of the webpage is in the **web** directory of:
https://github.com/bjonnh/dinoctopus

I tried with the git submodule or the hugo module but I don't have katex or mermaid either.

The hugo build is made by:
https://github.com/bjonnh/dinoctopus/blob/main/.github/workflows/doc.yml

But I don't have mermaid either when I do a "hugo server" locally

**Comment by bjonnh** [comment]
./themes/hugo-book/static/mermaid.min.js

Is there and gets copied properly to the public directory

However it is never loaded in the html page like it is in your demo website.

**Comment by bjonnh** [comment]
It looks like the `.Page.Scratch.Get "mermaid"` is true even if the page doesn't contain mermaid yet. 
So something may be evaluating that block but not using the output?

**Comment by bjonnh** [comment]
Mermaid works if you take it out of the columns. So something in the columns is hiding the generated html.

**Comment by bjonnh** [comment]
I made a new issue that has a solution:
https://github.com/alex-shpak/hugo-book/issues/530

**Comment by soydivision** [comment]
> I made a new issue that has a solution: #530

God bless you.
