### ISSUE TITLE
readme section on "Creating site from scratch" needs an update

### ISSUE THREAD

**Issue by chrishavlin** [alex-shpak/hugo-book#496]
In "Creating site from scratch" , `cp -R themes/hugo-book/exampleSite/content .` fails because the `content` folder is now `content.en`. Would be helpful to new users to update that section. Wasn't sure if you'd just want to replace `content` with `content.en` or add a note on the other `content.*` folders, so opening an issue instead of a PR... 

Thanks for the theme! Looking forward to using it.

**Comment by alex-shpak** [comment]
Fxd)
