### ISSUE TITLE
Roboto font looks pixelated in Firefox and Chromium on Ubuntu 20.04

### ISSUE THREAD

**Issue by omarkohl** [alex-shpak/hugo-book#498]
I have no idea if it's appropriate to post this issue here of if it's outside of the scope of the hugo-book (which I love by the way :heart:).

It looks good on my Android phone.

Attached two screenshots taken in Firefox 106.0.2 on Ubuntu 20.04 .

![Screenshot from 2022-11-11 08-56-32](https://user-images.githubusercontent.com/1420656/201293436-ca48b43f-34ad-4169-8290-36812f01b3b4.png)
![Screenshot from 2022-11-11 08-55-33](https://user-images.githubusercontent.com/1420656/201293440-63eec6f2-6e5d-46a5-b56a-1838b72ce65f.png)

You can check the affected website at https://cleodora.org

Notably I have no problem with the official Google Fonts Roboto examples. They look fantastic! https://fonts.google.com/specimen/Roboto

Some other people are complaining about the same thing (concerning Roboto and Firefox/Chrome, not hugo-book) and are suggesting that updating the font or providing different formats, not just woff resolves the issue:

* https://stackoverflow.com/questions/31011278/roboto-from-materializecss-weird-font-rendering-in-chrome-firefox-ok-with-ie
* https://stackoverflow.com/questions/34751547/display-issues-with-roboto-font-from-materialize-in-firefox/36803177

Maybe updating the font or providing different formats would help?

I'm also tracking this issue internally and would try to fix it for my own website even if it can't be fixed for the entire theme. https://github.com/cleodora-forecasting/cleodora/issues/33

**Comment by alex-shpak** [comment]
Hi!
I will try to look into it, as browsing from mac m1 fonts look pretty crisp for me, so maybe I'm not affected by this issue

**Comment by zoe-moment** [comment]
Checked this out on my system. I was able to repeat issue in firefox v102.7 on Debian 12 (bookworm - not a stable release)

I did find something interesting. 

At 100% zoom I see the pixelation issue
![hugo-book_issue498](https://user-images.githubusercontent.com/70442338/219901102-4436bee0-0005-44c2-bbe5-297242f035c0.png)

at 400% zoom it becomes crystal clear 
![hugo-book_issue498_firefox v102 7--zoom1](https://user-images.githubusercontent.com/70442338/219901103-1d113d94-80df-4ec2-b78f-ddb7c528b65c.png)
![hugo-book_issue498_firefox v102 7--zoom2](https://user-images.githubusercontent.com/70442338/219901104-cc746f74-a032-49b9-ac5f-e4c780c9de8c.png)

**Comment by alex-shpak** [comment]
Hi! well, I'm not sure how to help you, I tried on all my devices can't reproduce, I will close for now, please write if you still have an issue. or you can try to switch to another font
