### ISSUE TITLE
images (figure element) doesn't resize 

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#499]
Hi, I have a weird problem.
My css are heavily customized, but I know where I put min-width or min-anything. My issue is that $mobile-breakpoint works very well, but below a certain width, the frame/container/whatever won't resize anymore, so it overflows. Strangely enough, ABOVE $mobile-breakpoint (when at least the menu is present), images always resize, usually up to 50% of the container, whatever the container's size. This is how it looks below and beyond the threshold: below and the issue arises. Especially troublesome for mobile phones.
I put about everything of use here:
https://drive.google.com/drive/folders/1ObyNl6bCboq8M3OTEmYSMjsfUb9GWL0Y?usp=share_link
Please take a look. it's been a while since I had this but never considered how much it mattered for mobile phones. But I noticed one more weirdity: turning chromium's inpspection actuallly set the real borders straight again:
.

![image](https://user-images.githubusercontent.com/33675148/201985650-51605381-14e2-4133-a2e8-07de371e40d4.png)

**Comment by alex-shpak** [comment]
Well, hard to tell, it is likely due to set minimal width of page. I will close issue, please write if it is still and issue.
