### ISSUE TITLE
Support Google Analytics?

### ISSUE THREAD

**Issue by shaform** [alex-shpak/hugo-book#5]
Hi,

Hugo has built-in Google Analytics support: https://gohugo.io/templates/internal/.
Is it possible to enable it for `hugo-book`?

Thanks.

**Comment by alex-shpak** [comment]
Added google analytics template

**Comment by shaform** [comment]
Thanks!

Just for reference, it seems that Google suggests to put the code in `<head>`:

- https://stackoverflow.com/questions/3173571/should-i-put-the-google-analytics-js-in-the-head-or-at-the-end-of-body
- https://stackoverflow.com/questions/42024272/why-google-analytics-code-put-in-head-tag

But, putting it in `<body>` works as well.
