### ISSUE TITLE
Configuration documentation is incorrect by BookMenuBundle

### ISSUE THREAD

**Issue by netcmcc** [alex-shpak/hugo-book#50]
in README.md Written:

> And Enable it by settings BookMenuBundle: /docs/menu in Site configuration

BookMenuBundle: /docs/menu # not working
BookMenuBundle: /menu # is ok

In addition, it is recommended that the configuration file be written in TOML syntax uniformly, otherwise the newcomer directly copies the configuration file and does not work.

**Comment by alex-shpak** [comment]
Ah, thank you, that line is outdated.
About `yaml` vs `toml` I will consider change, I don't have strong opinion in that regard, just usually use yaml config for my sites.

**Comment by alex-shpak** [comment]
Fixed,
I find `yaml` config much easier to read, tho 🤔

**Comment by netcmcc** [comment]
ok,change installation guide

`hugo new site mydocs; cd mydocs`

to

`hugo new site mydocs -f yaml`

This installation step is smooth

**Comment by alex-shpak** [comment]
I the end I added both `yaml` and `toml` for reference in `exampleSite`. I think this should be sufficient.  
`README.md` file then has `toml` examples to copy from.

**Comment by netcmcc** [comment]
very good!
