### ISSUE TITLE
markup rendering in search results

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#500]
I noticed the variables .title, used to display the pages in search results, do not have their markdown nor html processed, in the sense that writing <br> (or `**`) in the .Title is correctly displayed as a linebreak in the menu, but only as "<br>" in the search result. I do not know how to correct json/js whatever, could you ? Like, add the equivalent of "| markdownify" to the results ?

Thanks

**Comment by alex-shpak** [comment]
Hi!
Unfortunately this content that hugo provides for `.Title` :(
