### ISSUE TITLE
flaw in the layout regards to window resizing: bad responsivity

### ISSUE THREAD

**Issue by evanescente-ondine** [alex-shpak/hugo-book#501]
Hi,
I noticed a fundamental flaw in your css layout, that I am not skilled enough to correct. I'm a beginner.
When in mobile mode the layout doesn't resize well, below a certain threshold the central frame ("book-page" I think but developper tools don't help there) doesn't resize but its right-hand border is eaten by the window.
**Sometimes**. Sometimes not. Very erratic, from one build to another, with NO code change whatsoever. But more often than not the problems shows up.
I do not understand anything to the flex layout, beyond display:flex for pictures. Could there be a simpler model for the menu and toc frame with width or max-width set on a percentage or viewport unit, something intrinsically responsive to window properties, unlike rem.
Here are exemples of what it looks like. I tried the same with the original css files, so I'm not to blame.

![image_overlfow](https://user-images.githubusercontent.com/33675148/203088014-d6abf450-5489-4df7-880d-0af93551ea22.jpg)
![image_without_overflow](https://user-images.githubusercontent.com/33675148/203088028-3439731a-7b60-4c66-8c70-161be22fbacd.jpg)

**Comment by alex-shpak** [comment]
Hi!
There is a minimal size of page set here
https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L16

Perhaps try to decrease it, if screen is smalelr than that value you will start seeing content outside of viewbox.
