### ISSUE TITLE
exampleSite code

### ISSUE THREAD

**Issue by auwsom** [alex-shpak/hugo-book#503]
Hi @alex-shpak is the code for the example site accessible somewhere?

I'm just starting and trying to see how partials work and want to add a header to the hugo-book theme. 

I see the content and assests are there under exampleSite dir. So I cloned the whole repo and tried using the command I found at the top of the config.toml: `hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/` but got a page with only the search box.

**Comment by auwsom** [comment]
I think I found it: I'm following this: https://www.ii.com/easy-way-play-with-hugo-theme-examplesite/

I'll leave this here for others.

**Comment by auwsom** [comment]
It appears I needed to run `hugo server --minify --themesDir ..\.. --baseURL=http://0.0.0.0:1313/theme/hugo-book/`. Notice the themesDir is `..\..` instead of `...`, and it works. Probably needs correction in the two config files.

**Comment by alex-shpak** [comment]
Hi!
Yes, I left `...` just for myself, as I use `zsh`
