### ISSUE TITLE
Can you show my an example for gitalk ? Thank you

### ISSUE THREAD

**Issue by pp-tt** [alex-shpak/hugo-book#504]
Hi!
There was not much though process in choosing commenting platform, it is added just becuase it is supported by hugo itself.
But, it is very easy to set alternative comment integration by overwriting `layouts/partials/docs/comments.html` template.

Maybe I can show you an example for alternative solution, if you pick one.

_Originally posted by @alex-shpak in https://github.com/alex-shpak/hugo-book/issues/494#issuecomment-1301393125_

**Comment by alex-shpak** [comment]
Hi!
Sorry for the delay

So, you need to create a file `layouts/partials/docs/inject/head.html` in your website
with content
```
 <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
```
This will add `gitalk` to your pages

Then you need `layouts/partials/docs/comments.html` with
```
<div id="gitalk-container"></div>
<script>
const gitalk = new Gitalk({
  clientID: 'GitHub Application Client ID',
  clientSecret: 'GitHub Application Client Secret',
  repo: 'GitHub repo',      // The repository of store comments,
  owner: 'GitHub repo owner',
  admin: ['GitHub repo owner and collaborators, only these guys can initialize github issues'],
  id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: false  // Facebook-like distraction free mode
})

gitalk.render('gitalk-container')
</script>
```
