### ISSUE TITLE
Can I collapse the left menu at the second or third level?

### ISSUE THREAD

**Issue by kchen0x** [alex-shpak/hugo-book#51]

**Comment by alex-shpak** [comment]
Hi!
There was previous discussion on foldable menu (#32)
I didn't find nice solution yet, since I try to keep theme as JS-free as possible, but I have it in mind.

**Comment by kchen0x** [comment]
Wait your enhancement~~

**Comment by alex-shpak** [comment]
I added some 'experimental' `bookCollapseSection` parameter per page, settings it in section will cause file-tree menu to not render nested section unless visited.

![image](https://user-images.githubusercontent.com/5515443/66439567-5bbdb580-ea30-11e9-974b-48bbae7ca26a.png)

![image](https://user-images.githubusercontent.com/5515443/66439588-64ae8700-ea30-11e9-8068-15f8b689232c.png)

Would be nice if you can test it

**Comment by kchen0x** [comment]
what if I use `menu/index.md` to organize my sidebar menu?

**Comment by alex-shpak** [comment]
Hi!
That one would work only for file-tree menu, unfortunately.
Bundle menu will need something more complex 🤔

**Comment by alex-shpak** [comment]
Hi again!
I tried to find nice solution for a while, unfortunately it seems like I didn't find one. So I mark as wontfix.
I think these days filetree menu is much more powerful and we also got hugo native menus now.

I would recommend to switch to filetree menu or make JS script to fold menu and inject it via one of `inject` partials.

**Comment by nianjiang** [comment]
As alex-shpak suggested, I used js in inject partials to un-collapse the menu.

-------------------------------------------------
The related code:
Find the id from html:
`
<li>
    <input type="checkbox" id="section-2d21464784c99358edd6d2b29e92ed6f" class="toggle" checked="">
    <label for="section-.." class="flex justify-between">
      <a href=".." class="active">..</a>
    </label>
`
**Add js** in themes/hugo-book/layouts/partials/docs/inject/**footer.html**
`
<script type="text/javascript">
    // alert("Script loaded!");
    document.getElementById("section-2d21464784c99358edd6d2b29e92ed6f").click();
</script>
`
