### ISSUE TITLE
V9:"Collapsed menus can be navigated without changing page!"

### ISSUE THREAD

**Issue by longlu** [alex-shpak/hugo-book#510]
V9:"Collapsed menus can be navigated without changing page!"

If i don't want this feature, and prefer the old way, which part of theme should  I change?

Maybe i can switch back to V8,  but it is better if I use V9 and change some part of the code to achieve that.

**Comment by longlu** [comment]
I prefer the old way, because for me I think otherwise there will be  too much content being loaded on the menu, when any webpage is openned.

**Comment by alex-shpak** [comment]
hello!
Logic for collapsing sections is here
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu-filetree.html#L31
