### ISSUE TITLE
Screen flicker on page load due to TOC loading

### ISSUE THREAD

**Issue by danburd** [alex-shpak/hugo-book#512]
Hello,

Thank you for the Book theme - it's wonderful. I've been using it for months.

I did notice a small issue with the screen flickering when the page loads due to the table of contents not loading immediately. This may impact the Cumulative Layout Shift (CLS) score on Lighthouse, as well as being not as visually attractive as possible.

This is visible on the ExampleSite: https://hugo-book-demo.netlify.app/docs/example/table-of-contents/with-toc/ When doing a full refresh, there is a moment when the TOC is not yet loaded and the body text extends into where the TOC will load. Then, the TOC loads and the body text reflows back into its final location. This is visible if you run a Lighthouse score locally on your Chrome browser and under Performance click "View Original Trace" - there is a screenshot without the TOC and with the body text loaded in its place.

I tried tweaking the CSS to prevent this but I am not knowledgeable enough to resolve this. I wanted to see if there was a simple solution that would prevent this. Other Hugo themes with a right sidebar - for example, https://neonmirrors.net/ - do not appear to have this issue so I believe it is possible to fix.

Thank you very much.

**Comment by alex-shpak** [comment]
Hi! Thanks!
Does it happen for you on mobile run on Lighthouse?
Desktop showed me pretty result
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5515443/218580205-8e57de99-782f-43c1-9541-213df3d795b8.png">
