### ISSUE TITLE
Post list cannot sort by date

### ISSUE THREAD

**Issue by RabbyteNi** [alex-shpak/hugo-book#513]
Hi, thank you for your work on this project. It really helps me a lot on building my blog.

I want to let the list of Blogs to display entries by date reversely(newest to oldest).
Where should I configure?

Thanks.

**Comment by Welsh44** [comment]
Hi

In my opinion, you can have a look at `layouts/posts/list.html`, line 2 : ` {{ range sort .Paginator.Pages }}`

**Comment by dirk2011** [comment]
I wanted the same too. This is what I made. 
Make a shortcode file, store it here: /layouts/shortcodes/top10_recently_changed.html.
It lists the last 10 changed pages, you can change the number. Edit or remove the .Lastmode.Format also if you want it different.

Content:
```html
<ul>
  {{- range first 10 .Site.RegularPages.ByLastmod.Reverse }}
    {{- if and .Title (or (ne (.Scratch.Get "relearnIsHiddenStem") true) (ne .Site.Params.disableTagHiddenPages true) ) }}
      <li><a href="{{ .RelPermalink }}">{{ .Lastmod.Format "2006-01-02" }} {{ .Title }}, ({{ .Date.Format "2006-01-02" }})</a></li>
    {{- end }}
  {{- end }}
</ul>
```

Add this to the pages where you want to use the shortcode:
```html
{{< top10_recently_changed >}}
```
