### ISSUE TITLE
[File Tree menu] : index file of docs

### ISSUE THREAD

**Issue by Welsh44** [alex-shpak/hugo-book#514]
Hi

First of all, thanks for this vry useful clear theme.

I build a site with this strcuture :
```
/content
   /docs
      _index.md
      /sect1
         _index.md
         file.md
   /posts
```

The file tree menu renders 
```
sect1
   file
```
but I don't understand how to customize (title...) `/docs/_index.md`.

I'm sure I miss something but what ?

Thanks in advance.

**Comment by Welsh44** [comment]
Thanks.
My question was not as good as I thought.
Whatever I put in `docs/_index.md`, it maybe in the frontmatter or in the content of the file, ther's nothing displayed.

**Comment by pekindenis** [comment]
> Thanks. My question was not as good as I thought. Whatever I put in `docs/_index.md`, it maybe in the frontmatter or in the content of the file, ther's nothing displayed.

Rename index.md fix this problem

**Comment by hvhaugwitz** [comment]
If you want to add `docs/_index.md` to the file tree menu, you can set `BookSection = '*'` in config.toml (to avoid the `Blog` section added twice to the menu add `bookHidden = true` to the front matter of `posts/_index.md`).
