### ISSUE TITLE
Params in order to shrink Menu

### ISSUE THREAD

**Issue by 0x62646f727465** [alex-shpak/hugo-book#516]
Hello,

Thank you very much for this tremendous Hugo theme. I would like to ask your community to develop the following feature.

Exactly as I can set BookToc = false or BookSearch = false in Hugo config.toml, I would like to set BookMenuShrink = true

By the way, what is a shrinked menu? Well, that's what you see when you reduce the size of the browser window so that the menu becomes this cool little icon at the top left of the page. Clicking on this little icon brings up the full menu.

BookMenuShrink = true (or BookFullMenu = false :) would instruct the page to have this "shrink menu" permanently.

The goal of all this is to have a very clean page, especially when using the columns of your theme...

Cheers...

**Comment by alex-shpak** [comment]
Hi!
Well, there is a simple option to hide left menu with CSS globally.
If you put `aside.book-menu { display: none; }` in `_custom.scss`
