### ISSUE TITLE
Ability to search markdown headers?

### ISSUE THREAD

**Issue by fubark** [alex-shpak/hugo-book#519]
This is a great theme for docs. I was wondering if there is or any plans to add search results for the headers in the pages themselves. This feels like it would be really useful since a page result can often be too broad. Instead it, it would show page header results and clicking on them goes to the right page with the header label. eg: `/docs/toc/recipes/#pasta` instead of `/docs/toc/recipes`.

**Comment by alex-shpak** [comment]
Hi! Thanks!
Unfortunatelly it will probably sould not be easy to achieve, the page will need to be broken into sections somehow before indexing. I'm not sure complexity worth it, tho, it will be a nice touch.

**Comment by alex-shpak** [comment]
Hi! I looked around I came to conclusion that I don't want to add such large feature to a simple theme.
