### ISSUE TITLE
'expand' shortcode is deprecated. Use 'details' instead. 

### ISSUE THREAD

**Issue by zothsu** [alex-shpak/hugo-book#522]
Found this on a recent build 

replace 'expand' shortcode with 'details' 

![WARN 2023/02/18 12:17:36 Expand shortcode is deprecated. Use 'details' instead](https://user-images.githubusercontent.com/70442338/219900115-735c9dbb-8741-4102-b9ba-5d29b1f9a738.png)

Running:
hugo v0.110.0+extended
npm v9.2.0

**Comment by zoe-moment** [comment]
I'm not sure what I did but I fixed it..? Is this something worth trying to recreate to see what changed? Or was this issue a silly use of my time?

![hugo-book_issue522--resolved](https://user-images.githubusercontent.com/70442338/219904367-6004217c-ab3d-42d2-b178-a76ecb42aebe.png)

**Comment by alex-shpak** [comment]
Hi!
Example Site contains a call do deprecated shortcode just for documentation purposes. it was replaces with newer `details` shortcode

**Comment by bryndin** [comment]
Still happening with the example site
```
Start building sites …
hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended linux/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=snap:0.127.0

WARN  Expand shortcode is deprecated. Use 'details' instead.
```

**Comment by eskopp** [comment]
> Still happening with the example site
> ```
> Start building sites …
> hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended linux/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=snap:0.127.0
> 
> WARN  Expand shortcode is deprecated. Use 'details' instead.
> ```


Yes, that's the case with all sites. This is a warning that appears because "shortcodes" will soon be removed.
