### ISSUE TITLE
Support for Google Analytics 4 for v9

### ISSUE THREAD

**Issue by wzshiming** [alex-shpak/hugo-book#523]
> Note: The async template is not suitable for Google Analytics 4.

https://gohugo.io/templates/internal/#configure-google-analytics

Maybe we should add a judgement

``` tpl
{{ if hasPrefix .Site.GoogleAnalytics "G-" -}}
  {{ template "_internal/google_analytics.html" . -}}
{{ else -}}
  {{ template "_internal/google_analytics_async.html" . -}}
{{ end -}}
```

**Comment by alex-shpak** [comment]
hello, I think it was already solved on hugo side
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html

**Comment by wzshiming** [comment]
Great, Thanks
