### ISSUE TITLE
[Question] Why a Content is nil in search-data.json?

### ISSUE THREAD

**Issue by gabor-meszaros** [alex-shpak/hugo-book#525]
Hi, Thank you for creating the theme, I chose it for its simplicity and clean look. I really like it so far. I started to build a blog with it, but I could not make the search working. I did modified the `html-head.html` slightly (I moved it to my `layouts` folder), but not really more.

I started to debug the issue:

- All `.js` files (including the search related) are preperly loaded on page load
- The search data is downloaded when I click into the search field
- The search data is always empty.

After a bit more debugging I found that [here](https://github.com/alex-shpak/hugo-book/blob/master/assets/search-data.json#L4) the `Content` is always `nil`. If I remove that line, the search data is generated, although it will contain [an empty section](https://www.earlyoften.com/en.search-data.min.51038799ad5256e2bf768f3178e3fc95d13d63d194e383930f271ef6f81ecd4e.json).

I removed it temporary because it still works for me, but I am wondering why that happens. I get the same result even if I test `Plain` instead of `Content`. I thought that it can because we miss the `.` context in the caller, but it doesn't seem to be the case, and again: the field are there, it is just the test that fails.

I am using Hugo `0.111.1`. Thank you!

**Comment by ai-smalleryu** [comment]
I ran into the same issue in a cento s environment, but my local Mac does not have this situation

**Comment by pradyungn** [comment]
Also having search issues (search-data in the public folder is just an empty array, no resulst showing up), but i didn't modify the html-head at all. Sending my config.toml below:

```
# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = '{SITE URL}'
title = '{SITENAME}'
theme = 'hugo-book'
language-code="en-US"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = '{REPO URL}'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false

  BookPortableLinks = false
  BookServiceWorker = false
  BookTranslatedOnly = false
```

**Comment by ai-smalleryu** [comment]
> Hi, Thank you for creating the theme, I chose it for its simplicity and clean look. I really like it so far. I started to build a blog with it, but I could not make the search working. I did modified the `html-head.html` slightly (I moved it to my `layouts` folder), but not really more.
> 
> I started to debug the issue:
> 
> * All `.js` files (including the search related) are preperly loaded on page load
> * The search data is downloaded when I click into the search field
> * The search data is always empty.
> 
> After a bit more debugging I found that [here](https://github.com/alex-shpak/hugo-book/blob/master/assets/search-data.json#L4) the `Content` is always `nil`. If I remove that line, the search data is generated, although it will contain [an empty section](https://www.earlyoften.com/en.search-data.min.51038799ad5256e2bf768f3178e3fc95d13d63d194e383930f271ef6f81ecd4e.json).
> 
> I removed it temporary because it still works for me, but I am wondering why that happens. I get the same result even if I test `Plain` instead of `Content`. I thought that it can because we miss the `.` context in the caller, but it doesn't seem to be the case, and again: the field are there, it is just the test that fails.
> 
> I am using Hugo `0.111.1`. Thank you!

Can you screenshot your catalog and cofig.toml and assets/search-data.json content? Mine solved, I modified these

**Comment by alex-shpak** [comment]
Hi!
is it still an issue?

**Comment by alex-shpak** [comment]
Moved to https://github.com/alex-shpak/hugo-book/pull/505
