### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by pradyungn** [alex-shpak/hugo-book#528]
Both locally and on deployment, when I try to search I'lll sometimes see the loading wheel pop up for an instant then go away, but no results ever actually show up. When looking at search-data.---.json in my public directory, it's only generating an empty array.  My config.toml is below - I haven't really customised any of the other partials, so not too sure where the error's popping up from?

```
# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = '{URL}'
title = 'Docs'
theme = 'hugo-book'
language-code="en-US"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/pradyungn/ECE385-systemverilog-docs'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false

  BookPortableLinks = false
  BookServiceWorker = false
  BookTranslatedOnly = false

```

**Comment by MakeJames** [comment]
I was also seeing this issue, I think it directly relates to the issue raised in #525

I managed to fix this by createing a `assets/search-data.json` file with the [problematic line](https://github.com/alex-shpak/hugo-book/blob/036e037a63ba06ca366adb1a0c3a005d1a0b15b8/assets/search-data.json#L4) removed.

**Comment by pradyungn** [comment]
That fixed it, thanks! Gonna keep the issue open for now since the root issue is still valid

**Comment by ai-smalleryu** [comment]
> 修好了，谢谢！由于根本问题仍然有效，因此暂时保留该问题
How did you do it? I still haven’t solved it. I think it’s because of the template scanning problem in search-data.json, because when I modify this template, there will be replacements in the generated json file, and the function remains the same. No effect

**Comment by dirk2011** [comment]
Great the solution works for me also, using Hugo version 0.111.3, thanks very much.

**Comment by alex-shpak** [comment]
Hi!
Seems like there was a change in hugo that broke that logic, I will take a look.

**Comment by alex-shpak** [comment]
Could be related: https://github.com/gohugoio/hugo/issues/6015

**Comment by HazardPassado** [comment]
So, this comment is to help someone googling in the future with this behavior. If you are running Hugo as an AWS Amplify site, it will pin an old version of Hugo (0.75.2.) Manually updating the version to 0.118.2 cured this for me after pulling a lot of my hair out trying to track it down. 

More an amplify bug than a Hugo bug, and certainly not a fault with the theme.
