### ISSUE TITLE
changing theme with an icon

### ISSUE THREAD

**Issue by nakednous** [alex-shpak/hugo-book#529]
Hello,

As the title states it: is it possible to change the theme with an icon?
I'd also want to implement [solarized](https://ethanschoonover.com/solarized/) themes for the template. How should I proceed?

**Comment by alex-shpak** [comment]
Hi!
So, top change Icon there is parameter: 
```
  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'logo.png'
  ```
  
For theme coloring, everything is extracted in SCSS files:
https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L32
