### ISSUE TITLE
add images

### ISSUE THREAD

**Issue by omartek** [alex-shpak/hugo-book#53]
Hi,
is it possibile to add images inside pages? Markdown syntax seems not working.
I'm using netlify-github.

thanks for the good job.

**Comment by alex-shpak** [comment]
Hi!

Unfortunately hugo don't have easy solution at the moment.

Options
1. `having page docs/about.md`, create `docs/about/image.png` and then reference relatively `![img](image.png)`, ugly but should work
2. Use absolute path e.g. `![img](/website-path/docs/image.png)`
3. Shortcode I guess, that will use resources to find image url.

**Comment by omartek** [comment]
i've made several combination but none works.
first solution should be good.
i'll try again later.

thanks

**Comment by omartek** [comment]
sorry, you're right.
folder name had spaces (12 - informatica) and this was the cause of little bug.
hugo creates two different folder (12 - informatica and 12-informatica) with and without spaces, the first with the index.html and the second with the image file.

thanks
omar
