### ISSUE TITLE
Configuration change needed to display raw html (mermaid, katex...) inside columns

### ISSUE THREAD

**Issue by bjonnh** [alex-shpak/hugo-book#530]
On recent versions of hugo, raw html cannot be displayed in columns and gets hidden.

One has to add
```
[markup.goldmark.renderer]
unsafe= true
```
to its config.toml to make Mermaid and Katex work.

**Comment by alex-shpak** [comment]
yes, it is true, see config in exampleSite
https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L11-L14

**Comment by alex-shpak** [comment]
Added to readme :)
