### ISSUE TITLE
Assume I want to parametrize footer using partials. How do I pass an argument?

### ISSUE THREAD

**Issue by soydivision** [alex-shpak/hugo-book#531]

**Comment by alex-shpak** [comment]
Hi!
There are few templates you can overwrite in your site, you can create these files in your source folder, they will overwrite default templates.

- `layouts/partials/docs/inject/footer.html`
- `layouts/partials/docs/inject/content-after.html`
- `layouts/partials/docs/footer.html` (this one will overwrite entire footer
