### ISSUE TITLE
Next/Previous page at the end of a page

### ISSUE THREAD

**Issue by yunhaixiang** [alex-shpak/hugo-book#532]
Hello,

Is it possible to have a next/previous page button at the end of a page, like the one they have on the Mermaid documentation?

<img width="702" alt="Screenshot 2023-04-01 at 16 24 30" src="https://user-images.githubusercontent.com/10103526/229312507-b36e839f-2975-49fe-885c-c3474184c7b4.png">

Thanks!

**Comment by gido** [comment]
I would love this feature too

**Comment by alex-shpak** [comment]
Hi!
At the time of trying to implement it I didn't find solution with reasonable performance, unfortunately. So it was left for '
future'

**Comment by yunhaixiang** [comment]
> Hi!
> At the time of trying to implement it I didn't find solution with reasonable performance, unfortunately. So it was left for '
> future', I will need to look into it again

Thank you! I think this would be a really cool and useful feature, please do consider it in the future :)

**Comment by whalekeykeeper** [comment]
I feel I had it in the past somehow, at least two buttons that one can click to jump into the previous/next page. But when I am building a new site with this Hugo theme again, I don't have the buttons anymore. Does anyone encounter this?

**Comment by chinacomx** [comment]
> I feel I had it in the past somehow, at least two buttons that one can click to jump into the previous/next page. But when I am building a new site with this Hugo theme again, I don't have the buttons anymore. Does anyone encounter this?

I figure it out.
For the new site I am building, I should use the feature/prev-next branch.

**Comment by whalekeykeeper** [comment]
> I feel I had it in the past somehow, at least two buttons that one can click to jump into the previous/next page. But when I am building a new site with this Hugo theme again, I don't have the buttons anymore. Does anyone encounter this?

I solved it by using the staled branch but that solution is no longer working now anymore after I updated this theme to the latest version.

**Comment by cjauvin** [comment]
This would be indeed a very nice and useful feature, I searched for it.
