### ISSUE TITLE
Text layout shift on page load

### ISSUE THREAD

**Issue by a-h** [alex-shpak/hugo-book#533]
In Chrome, on a Mac, after loading, the site layout shifts. Perhaps an issue with font loading?

https://user-images.githubusercontent.com/1029947/231832943-2af649dc-fce7-45ac-b908-f588744278b2.mov

**Comment by alex-shpak** [comment]
Hi!
It happens because of swap option here
https://github.com/alex-shpak/hugo-book/blob/master/assets/_fonts.scss#L6

It is recommended for faster render of pages, but has side effect.
You can remove it with custom css if you wish.
