### ISSUE TITLE
Adding a shortcode rawhtml

### ISSUE THREAD

**Issue by wehrend** [alex-shpak/hugo-book#536]
Suggestion to add a shortcode "rawhtml" to allow embedding of html pages or sections,
like done here: https://anaulin.org/blog/hugo-raw-html-shortcode/

**Comment by alex-shpak** [comment]
Hi!
Perhaps you don't need a shortcode for this, be default theme used `markup.goldmark.renderer.unsafe= true` to render some other shortcodes, so you can put HTML straight into markdown file.

**Comment by wehrend** [comment]
Not sure if that will work, since I am using Asciidoc(tor) instead of markdown. 
It would be nice if this small little change got in - then I could use the latest version without any further changes.

**Comment by alex-shpak** [comment]
Hi! there is `html` shortcode now
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/html.html
