### ISSUE TITLE
No easy way to display homepage in sidebar menu with activation state

### ISSUE THREAD

**Issue by melinath** [alex-shpak/hugo-book#541]
The "filetree" sidebar menu doesn't seem to have an easy way to include a link to the homepage. Although users can click on the "brand" logo, it's nice to also provide an explicit link that behaves the same way as all other links. Adding the homepage to the `before` menu does get it to display (using the `menu-hugo` template) but that template doesn't support "active" states for links, even if there's an attached Page.

The simplest workaround I could find is adding a `partials/docs/inject/menu-before.html` override that adds the link explicitly. It works exactly the same, it just took me a while to figure out that was the best option. It seems like this is potentially a common use case and could be worth making part of the main filetree template.

**Comment by alex-shpak** [comment]
Hello!
I prefer to have less options hardcoded in theme and do things with template customisation, suggestion by @baltpeter looks good
