### ISSUE TITLE
Is there a way to prevent tables from wrapping? 

### ISSUE THREAD

**Issue by aCuria** [alex-shpak/hugo-book#542]
On the mobile site there’s not enough page width, so my markdown tables are doing a word wrap.

Is there a way to prevent the word wrap from happening?

**Comment by alex-shpak** [comment]
Hi!
You probably can do that wit ha bit of custom css in `assets/_custom.scss` in you sites source

**Comment by aCuria** [comment]
Changing _defaults.scss with
$container-max-width: 100rem !default;

seems to work on desktop
