### ISSUE TITLE
Remove section description 

### ISSUE THREAD

**Issue by aCuria** [alex-shpak/hugo-book#543]
{{</* section */>}}

The section command renders title and description, but I am getting a garbage description 

Is there a way to render the title only with no description 

or control what comes out in the description

**Comment by alex-shpak** [comment]
Hi! you can modify the shortcode in your site.
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/section.html

and remove lines 6 to 8
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/section.html

**Comment by alex-shpak** [comment]
I added `summary` param for shortcode
`{{< section [summary] >}}`
