### ISSUE TITLE
Multiple Books On One Site

### ISSUE THREAD

**Issue by knightebsuku** [alex-shpak/hugo-book#546]
Hi There.

Is it possible to create multiple books for a single hugo site?

So something like
```
____content
        ____docs
            ____Book_1
                ____page_one.md
            ____Book_2
                ____page_one.md            
```

**Comment by knightebsuku** [comment]
Something like the following

example.com/blog/

example.com/projects/book1
example.com/projects/book2

**Comment by alex-shpak** [comment]
Well, I will think about how this could be implemented, apart from reusing multi-language support

**Comment by taxilian** [comment]
This is closed as completed, but I'm not finding instructions anywhere on how to do it – is it possible?
