### ISSUE TITLE
Clicking one of the search result resets the result list

### ISSUE THREAD

**Issue by nyurik** [alex-shpak/hugo-book#548]
The [rust lang release site](https://releases.rs/) uses this theme, and if I search for any word in the index, the result list in the side bar shows just the pages with the found text. Yet, if I click any of the result items, the whole sidebar result is reset to the full list, and the search box is now empty.

It would be far more convenient if the search result stayed unaffected after showing a search box. Is this something that can be done via the URL modification?

**Comment by alex-shpak** [comment]
Hello!
It happens due to static nature of site generated by hugo, It is perhaps possible to solve with some metadata in URL and scripts. Tho I would prefer not to.
I understand that it is nice to jump thought search results, but it will add significant complexity to site.
