### ISSUE TITLE
Documentation to Change Syntax Highlighting Colorscheme

### ISSUE THREAD

**Issue by saurabh-mish** [alex-shpak/hugo-book#551]
Hi Alex,

Can you let me know how can change the syntax highlighting theme ?

From [this Hugo documentation](https://gohugo.io/content-management/syntax-highlighting/), it looks like `syntax.css` file is used for syntax highlighting, but I cant find this file.

Can you let me know how to change the syntax highlighting colorscheme for this theme ?

**Comment by alex-shpak** [comment]
Hi!
First you can generate styles
```
hugo gen chromastyles --style=monokai > assets/_syntax.scss
```
Then you can import it into `assets/_custom.scss`

```scss
/* You can add custom styles here. */

// @import "plugins/numbered";
// @import "plugins/scrollbars";
@import "syntax";

```
