### ISSUE TITLE
Asciidoc code blocks not highlighted

### ISSUE THREAD

**Issue by stauvel** [alex-shpak/hugo-book#556]
The following Asciidoc block is not highlighted while it's ok with "learn" theme. 

    [source, java]
    .MyClass.java
    ----
    import java.util.List;

    public class MyClass implements MyInterface {
        @Override
        public List<Hello> getHelloes() {
            return List.of("hello");
        }
    }
    ----

Did I missed something ?

**Comment by alex-shpak** [comment]
Hi! Never tried it in hugo.
What result do you expect? do you try to embed ascii block into markdown file?
