### ISSUE TITLE
How to wrap long lines inside of markdown ``` code ``` in hugo-book?

### ISSUE THREAD

**Issue by BrentHuang** [alex-shpak/hugo-book#558]
eg.
```
some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; some very long line; 
```

Horizontal scroll bars are not required, but text is expected to wrap automatically (e.g., a line of up to 80 characters), which is very important for paper printing.

**Comment by alex-shpak** [comment]
Hi!
By default code block do not wrap text as it uses `<pre>` tag, you can adjust that with css
```
.markdown  pre {
  whitespace: auto
}
```

in `assets/_custom.scss`
