### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by kchen0x** [alex-shpak/hugo-book#56]
When the doc site grows bigger and bigger, it's hard for user to find wanted pages/docs/posts even in a hierarchy structured documentation. Therefore, a useful full text search bar is indeed needed.

**Comment by alex-shpak** [comment]
Hi!
Yes, it would be nice to have, so far I didn't develop vision on best way implementing this, so It's in TODO state.

**Comment by alex-shpak** [comment]
Work is started at `feature/search` branch

**Comment by alex-shpak** [comment]
![image](https://user-images.githubusercontent.com/5515443/61294782-e0ed5180-a7d6-11e9-8b04-9f191ef2745d.png)

**Comment by alex-shpak** [comment]
Now I consider two options:
- Keep search bar under site title, and load index on first focus
- Create separate page `/docs/search` to keep all search functionality, to not load lunr and index on each page.

🤔

**Comment by alex-shpak** [comment]
Changes are now pushed to master
https://raw.githubusercontent.com/alex-shpak/hugo-book/master/images/screenshot.png

Though, there is still room for improvement in future.

**Comment by Spejbl123** [comment]
I'm getting these errors when typing into search bar. Happening in Firefox and Chrome.

![image](https://user-images.githubusercontent.com/50444710/62626201-6937c000-b959-11e9-90b7-300a4d86ae09.png)
Do you know what could be wrong? Thanks.

**Comment by alex-shpak** [comment]
Hi!
I suppose it's due to title not being jsonified as well here: https://github.com/alex-shpak/hugo-book/blob/master/assets/search-data.js#L8

Can you please check place where error given and post it here? Or if your website is public to share a link so I can check it.

**Comment by Spejbl123** [comment]
Works flawlessly now! Thanks you for a quick fix :)

**Comment by mistermantas** [comment]
Funnily enough, I ended up setting this up myself from the Hugo Search doc: https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

Also, the search on the live demo here doesn’t seem to work? It’s got a `readonly` attribute.

https://themes.gohugo.io/theme/hugo-book/

**Comment by jog968** [comment]
Hi Alex, 
first of all thank you very much for your excellent work.

I am using tags and categories for my documents and find in the search results links to list pages for categories and tags. So far this is fine. Unfortunately I find after creation of the site in the category and tag folders only xml files but no html files for the category/tag pages. Would it be possible to enhance the theme with the ability to create those pages too?

Furthermore if I could have some more wishes: It would be great if the single pages could append a footer with a table or an unordered list with two bullets. One for categories and one for tags showing the assigened terms as a comma separated and linked list? Finally it would be a great improvement to the search results, when links to category/tag pages could be distinguished from content pages by a marker or label.

**Comment by alex-shpak** [comment]
@jog968 Hi! Thanks,
I think It would be reasonable to create these feature requests as separate issues in github.

In general, main goal of theme is documentation so I added minimal blogging features, but I can adding tags and categories is ok. Not top priority tho. PRs are welcome :)

On lists with tags and categories, I think it's too specific feature for generic website, I think better is to customize your footer partial and add what you want.

**Comment by alex-shpak** [comment]
@mistermantas Regarding search on themes.gohugo.io, this is `absURL` issue, I try to avoid `absURL` in theme, but they are required there because each theme is subfolder.

Not sure that I want to introduce absolute link to fix that 🤔

**Comment by jog968** [comment]
@alex-shpak: Hi and Thanks,
I'm glad to hear that tags and categories can be added. Priority is not so important. I will wait.

Regarding lists I will try to do this by myself. It is time for me to learn some basics.

**Comment by alex-shpak** [comment]
Closing this issue.
