### ISSUE TITLE
How to add a theme switching button?

### ISSUE THREAD

**Issue by Leroy-X** [alex-shpak/hugo-book#561]
How to add theme switching button, I mean, have a button to switch between dark mode and light mode, or auto mode.
I discovered that I can use `BookTheme = 'dark'` to change to dark mode. But how to add a toggle button on the web page?
Thank you so much!

**Comment by Non-NeutralZero** [comment]
The theme author said he doesn't think he will add one.

Please refer to this https://github.com/alex-shpak/hugo-book/issues/420#issuecomment-1039165736

**Comment by Leroy-X** [comment]
Ok, thanks for the reply.
