### ISSUE TITLE
Automatically list pages when using menu bundle

### ISSUE THREAD

**Issue by gpanders** [alex-shpak/hugo-book#57]
I would like to have the side menu automatically list all pages under `docs/` when using `BookMenuBundle = "/menu"`. Right now it looks like I have to manually add each new page to `content/menu/index.md`. Is this possible?

I tried something like this but it doesn't work (I'm still a Hugo noob and learned that templates don't work in Markdown):
```markdown
- [**Home**]({{< relref "/" >}})
- **Docs**
  {{ range where .Site.Pages "Dir" "docs" }}
  - [{{ .Title }}]({{< relref .File.Path >}})
  {{ end }}
- [**Blog**]({{< relref "/posts" >}})
```

**Comment by alex-shpak** [comment]
Hi!

I think easiest option is to switch to file-tree menu in config and override `layouts/partials/docs/inject/menu-before` and `partials/docs/inject/menu-after`.

For example in `menu-after` you can have
```html
<ul>
  <li>
    <a href="{{ relref . "/posts" }}">Blog</a>
  </li>
</ul>
```

**Comment by gpanders** [comment]
Thanks! Using those injected partials does the trick.
