### ISSUE TITLE
add feature to toggle menu to allow more width for content

### ISSUE THREAD

**Issue by jpritikin** [alex-shpak/hugo-book#570]
It's not too much code. Check it out, https://github.com/jpritikin/coach/commit/79fafd26846bfb593e633f7fc8a5ebe2e7efe350 and the parent commit

**Comment by alex-shpak** [comment]
Hi!
I'm not sure I want to add that to base theme, just to keep it simple, but we can keep it in the issues so people can find this solution.

Ref: https://github.com/jpritikin/coach/commit/6537531c739d51dd5fa22f6d17ddd8f5bb0ab2cf

**Comment by jpritikin** [comment]
Okay!
