### ISSUE TITLE
Add support to center docs

### ISSUE THREAD

**Issue by Nrosa01** [alex-shpak/hugo-book#573]
Current implementation works from left to right.

Custom shortcodes like tabs, details and so don't work well with <center>, it also fails for tables. Using custom shortcodes makes the ToC dissapear. It would be a nice feature to have this out of the box as a simple config in the .toml

**Comment by Nrosa01** [comment]
To put an easy example, if you use <center> </center> in vscode markdown and you put a table there, the whole table gets centered. In this Hugo template it doesn't (using any of those also breaks ToC for some reason). I also tried custom shortcodes like these ones: https://discourse.gohugo.io/t/how-to-center-text/22070

If it's not clear I can attach images of what I get versus what I expect/want. It could also be that I'm using this template in a way it was not intended 😅

**Comment by alex-shpak** [comment]
There is no much control over centering in markdown renderer, tho you can try few things:
1. Use `<div>` and classes if you have html enabled
```
<div class="flex align-center">

| A  | B  |
| -- | -- |
| A  | B  |

</div>
```

2. add `css` in `_custom.scss`
```
.markdown table {
  display: grid;
  justify-content: center;
}
```
