### ISSUE TITLE
Site title is prefixed with |

### ISSUE THREAD

**Issue by mmatczuk** [alex-shpak/hugo-book#581]
The code `{{ partial "docs/title" . }} | {{ .Site.Title -}}` renders | to the title.

**Comment by alex-shpak** [comment]
Hi!
At the moment it is by design, `Page title | Site title` output

**Comment by mmatczuk** [comment]
This causes google to refer to your page as `| Title`

**Comment by alex-shpak** [comment]
Is title of your page empty?
