### ISSUE TITLE
use time.Format in date partial to allow localized formatting

### ISSUE THREAD

**Issue by hedzards** [alex-shpak/hugo-book#582]
Hi,

I am completely new to Hugo and just barely got to know your theme that fits nicely for my needs. I tried to set

`BookDateFormat: ":date_long"`

to get localized values for the date in posts. Unfortunately that does not work. I changed partials/date.html to

`{{- return (time.Format $format .Date) -}}`

which does what I expect. Is this the right way to do it? And would that be an adjustment that makes sense in general?

Regards
Hendrik

**Comment by alex-shpak** [comment]
Hi!
Yes, that partial there specifically for that purpose, as that date formatting is old, I'm afraid to change it to not break someone's site.

**Comment by alex-shpak** [comment]
Your suggestion is applied
