### ISSUE TITLE
Is there a way to show an image or text on mouseover?

### ISSUE THREAD

**Issue by keithtangtw** [alex-shpak/hugo-book#584]
When displaying an image like this:

`![](/Styles/image.png)`

I would like to show another image (image2.png) or text on mouseover of the first image.png

How would I go about doing this?

**Comment by alex-shpak** [comment]
Hello! Unfortunately not out of the box, or not very fancy out of the box, you can set a attribute`title` for an image in markdown
`![Alt text can be put here](/Styles/image.png "Put title here")` this will show `Put title here` after hovering over image for a bit of time.
Optionally you can look for JS lib to turn title into popups
