### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gavox** [alex-shpak/hugo-book#588]
Hello, thanks for the work. 

I've installed the theme on a repository I'm working on. Then used it on my laptop, worked flawlessly. 

Then I moved to my desktop and the theme wouldnt work. 

I am ran into a Warning: 

`WARN  found no layout file for "html" for kind "`

And then hugo does not generate a webpage (Page Not Found). 

So, questions, 

* I'm not mistaken the theme is installed on the git repository itself, so it shouldnt need to be installed on each PC. 
* Even if I'm mistaken in the previous point, I also ran the installation instructions on the desktop without errors and it didn't solve the issue. What could be wrong?

I'm at a loss here. Any help is greatly appreciated.

**Comment by alex-shpak** [comment]
Hello!
depending on how you set it up, but in general you should have your git repository with site, where theme is either subfolder or submodule in that repository

so
```
your-repo
   content
   themes
      hugo-book (submodule or folder)
```

when moving between computers you need to clone it from your git together with theme files
