### ISSUE TITLE
Only show search when JS is enabled

### ISSUE THREAD

**Issue by leoheitmannruiz** [alex-shpak/hugo-book#591]
Hey, thanks for the lovely theme!!

What do you think about only showing the search bar when JS is enabled? I feel like this would be a caring touch :)

I know very little about this type of development, but can't you have an empty div, which is filled with the search, in case JS is enabled? Is it that simple?

**Comment by alex-shpak** [comment]
Hi!
I thought about it, option could be to have search box hidden by default and unhide it with JS, not sure if it worth an extra JS script tho
