### ISSUE TITLE
Headless branch bundles not rendering in menu in Hugo >0.123.5

### ISSUE THREAD

**Issue by danburd** [alex-shpak/hugo-book#601]
Nested links on the left side menu in the Book theme are not showing in Hugo 0.123.6, 0.123.7, and 0.123.8. It worked in 0.123.5 and earlier. I don't know if this is a bug with the Book theme or with Hugo, but I wanted to flag it here because I'm not savvy enough to file a bug with Hugo defining the underlying problem. Thank you.

**Comment by jmooring** [comment]
I was unable to reproduce this with the example site. Details:
<https://github.com/gohugoio/hugo/issues/12218>

**Comment by danburd** [comment]
**Update**: the issue is only with **headless** page bundles not showing up on the menu. (All of my page bundles were headless, which is why the issue seemed more broad at the time.) That's why the exampleSite worked and mine did not. I don't know if this is an issue with the theme or an issue with Hugo.

**Comment by danburd** [comment]
I suppose the correct way to do this is to replace ```headless: true``` with:

```
build:
  render: never
```
Thanks. Closing.
