### ISSUE TITLE
Is there a way to have the homepage (/landing page) in left menu (/book ToC) with subsections?

### ISSUE THREAD

**Issue by smillas-snow** [alex-shpak/hugo-book#603]
Hi,
Is it possible to have the homepage (/landing page) appear in the left menu (/book ToC) with subsections?

For the explicit example in the picture:
Ideally, I would like to define the main/home/landing page to be in the folder structure: '../content/handbook/_index.md' instead of '../content/_index.md', for it to be in the left hand menu (/book ToC) with subsection, like other main sections.

Is there a way to define that, or to redirect the main page? The aim is to not having to remember to copy-paste '../content/_index.md' to 
'../content/handbook/_index.md' when somebody makes a change.

Thanks for the help.

![Handbook_homepage_file_location](https://github.com/alex-shpak/hugo-book/assets/52196971/d5ccf859-31d8-40c2-b8ea-2a324a737426)

**Comment by alex-shpak** [comment]
well, it is could be possible with some compromise,
As far as I remember you can change `.Site.Home.`/`content/_index.md` page in hugo, but you can make `content/handbook/_index.md` page to point to home page in the menu

```
---
bookHref: {your home url here}
---
```

tho, there is a catch, right now `bookHref` param always opens a new tab
I will need to think about for solutions

**Comment by smillas-snow** [comment]
Hi,
That's the hint I needed :), thank you so much.
after playing around a bit, I ended up putting 'bookHref' in my home page:
content/_index.md:
---
bookHref: /handbook/
---
That simple redirect to the handbook index.md upon entering. It does not open any additional tabs and the menu incl. substructure is how I want it.
