### ISSUE TITLE
links in shortcodes 'columns' do not work

### ISSUE THREAD

**Issue by smillas-snow** [alex-shpak/hugo-book#605]
Hi,
In one part of my document I want to use your 'columns' shortcodes, as it is very handy, but links to another page are not shown as links but it shows the code snipped as plain text, while on normal text paragraphs it works.
I am not sure if this is a bug or some form of limitation. In case of the second, is there a way around it?

Thanks for your help.

**Comment by alex-shpak** [comment]
Hi!
Can you please post your markdown example here?

**Comment by smillas-snow** [comment]
```
# text normal
bla bla bla [link][handbook_contribution] bla bla bla

# text in columns
bla bla bla
{{< columns >}} <!-- begin columns block -->
#### left
bla bla bla
<---> <!-- column separator -->
#### right
bla bla bla [link][handbook_contribution] bla bla bla
{{< /columns >}} <!-- end columns block -->

<!--PAGE REFERENCE DEFINITIONS-->
[handbook_contribution]: {{< ref "handbook/contributing-handbook.md" >}}
```

This is how it ends up for me:
![image](https://github.com/alex-shpak/hugo-book/assets/52196971/a61e4867-fe5f-4f49-b564-06b74a4a6ad9)

**Comment by alex-shpak** [comment]
Okay, I see, unfortunately that would not work,
as shortcode for columns renders inner markdown it renders it in separate context, so reference is not visible for the renderer inside of the shortcode.
You can simulate columns with html (just check what output shortcode creates) and that should work.

**Comment by smillas-snow** [comment]
Thank you
