### ISSUE TITLE
Math formula support

### ISSUE THREAD

**Issue by invinddv** [alex-shpak/hugo-book#61]
I really love your work and try to build a note site based on this theme for my learning record. Have you planed to add math formula support into your great theme? 
Or if you could give me some suggestions, I am glad to do it myself but cant find a way yet...
Sincere thanks.

**Comment by alex-shpak** [comment]
Hi!
You mean something like https://github.com/KaTeX/KaTeX ?

**Comment by alex-shpak** [comment]
KaTeX support is here

https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/katex.html

![image](https://user-images.githubusercontent.com/5515443/63552998-7946c680-c539-11e9-882c-60582789af7a.png)

**Comment by matteodelucchi** [comment]
Doesn't work in .Rmd files.
