### ISSUE TITLE
Any experience about using Giscus comment in the hugo-book theme?

### ISSUE THREAD

**Issue by Huilin-Li** [alex-shpak/hugo-book#615]
I have tried different articles about adding Giscus comment in hugo. However, they are all based on other themes. Although I tried to mock their steps, I failed again and again.

May I ask for any experience on using Giscus comment system in the Hugo-book theme? Thanks in advance!

**Comment by Huilin-Li** [comment]
Hi, thanks all. I have figured it out~

**Comment by alex-shpak** [comment]
Hi! Good, I haven't tried Giscus :)
