### ISSUE TITLE
Pager for post collections and archives

### ISSUE THREAD

**Issue by djsamperi** [alex-shpak/hugo-book#617]
I see that the latest version of hugo-book supports breaking out posts by category and tag, but there is no paging when a category has many associated posts. Also, there is no archive feature that groups posts by date. Perhaps some or all of these features are already in hugo-book?

**Comment by alex-shpak** [comment]
Hi!
This theme is more focused in documentation pages, so blog features are limited, but paginations can be added I think, if there is a demand

**Comment by alex-shpak** [comment]
Pagination for posts under tag/category was added some time ago
