### ISSUE TITLE
numbered plugin ignores chapters

### ISSUE THREAD

**Issue by djsamperi** [alex-shpak/hugo-book#619]
The numbered plugin is interesting, but there is a small glitch. Chapters are completely ignored, so if there are sections
1.2.1 and 2.2.1, both will be rendered with the number 2.1.

**Comment by alex-shpak** [comment]
Hi!
yes, it is a bit fiddly, can you please provide markdown example, I will take a look

**Comment by alex-shpak** [comment]
Perhaps it got fixed with 
https://github.com/alex-shpak/hugo-book/pull/555
