### ISSUE TITLE
Strange issues on build...

### ISSUE THREAD

**Issue by wehrend** [alex-shpak/hugo-book#627]
I've having some issues with hugo related to the book theme currently. Working on my laptop, so I cannot verify what the issue here... So cant lookup what I could simply check on my workstation...

Error: Error building site: "/src/content/themes/hugo-book/layouts/_default/_markup/render-image.html:1:1": unmarshal failed: invalid character '{' looking for beginning of object key string
Built in 2398 ms

the mentioned file looks like the following: 

{{- if .Page.Site.Params.BookPortableLinks -}}
  {{- template "portable-image" . -}}
{{- else -}}
  <img src="{{ .Destination | safeURL }}" alt="{{ .Text }}" {{ with .Title }}title="{{ . }}"{{ end }}/>
{{- end -}}

{{- define "portable-image" -}}
  {{- $isRemote := or (in .Destination "://") (strings.HasPrefix .Destination "//") }}
  {{- if not $isRemote }}
    {{- $path := print .Page.File.Dir .Destination }}
    {{- if strings.HasPrefix .Destination "/" }}
      {{- $path = print "/static" .Destination }}
    {{- end }}
    {{- if not (fileExists $path) }}
      {{- warnf "Image '%s' not found in '%s'" .Destination .Page.File }}
    {{- end }}
  {{- end }}
  <img src="{{ .Destination | safeURL }}" alt="{{ .Text }}" {{ with .Title }}title="{{ . }}"{{ end }}/>
{{- end -}}

**Comment by alex-shpak** [comment]
Hi! Which URL you supplied to image tag in markdown?

**Comment by wehrend** [comment]
I am not sure what was the culprit, it is solved for now. But I have other issues related to i18n. 
Opening another ticket for it.
