### ISSUE TITLE
The table of contents in the Hugo book theme use to much space

### ISSUE THREAD

**Issue by jonasstein** [alex-shpak/hugo-book#635]
Users reported, that the TOC of my website cuts the content off.
By scaling the browser window, I can reproduce this: The burger menu appears too late and the TOC menu cuts the main window.

How can I fix this? Is there a useful parameter to set? Do I have to adjust the .css?

The website: https://trolug.de/de/docs/termine/
The source: https://github.com/TroLUG/trolug-hugo
Formerly asked in https://discourse.gohugo.io/t/the-table-of-contents-in-the-hugo-book-theme-use-to-much-space/50802/1

**Comment by alex-shpak** [comment]
Hi!
for that that specific page I would suggest to disable ToC in page params: `bookToC = false`
alternatively you can adjust media queries here: 
https://github.com/alex-shpak/hugo-book/blob/master/assets/_variables.scss

using this value:
https://github.com/alex-shpak/hugo-book/blob/master/assets/_defaults.scss#L23

**Comment by alex-shpak** [comment]
Hi!
These are checkboxes that are used to keep open/closed state of side menu, likely something is wrong with CSS styles
