### ISSUE TITLE
Remove persistent "#" symbol on Headers

### ISSUE THREAD

**Issue by stockphrase** [alex-shpak/hugo-book#638]
When I build my site, each header has a persistent # symbol next to it. In the model site these only appear when hovering over the heading. How can you toggle these off? I don't see a setting for this.

**Comment by alex-shpak** [comment]
Hi!
There is no setting in config for this, but you can overwrite this template
https://github.com/alex-shpak/hugo-book/blob/master/layouts/_default/_markup/render-heading.html

**Comment by stockphrase** [comment]
Thank you, Alex.
