### ISSUE TITLE
Code block line numbers are misaligned

### ISSUE THREAD

**Issue by jmooring** [alex-shpak/hugo-book#640]
Using the exampleSite without modification...

mardkown

````text
```text {linenos=table}
aaaa
bbbb
cccc
dddd
eeee
ffff
gggg
hhhh
```
````

rendered

![image](https://github.com/user-attachments/assets/5227a525-1564-4b0b-a054-81cb2f18208f)

But this renders as expected:

````text
```text {linenos=inline}
aaaa
bbbb
cccc
dddd
eeee
ffff
gggg
hhhh
```
````

**Comment by alex-shpak** [comment]
Hi! Thanks, I will take a look

**Comment by alex-shpak** [comment]
Fix has been pushed, took some time to figure out
Problem is that code block numbers generated as `inline` spans, but lines with code are `flex` leading to difference in height.
