### ISSUE TITLE
failed to extract shortcode: template for shortcode "hint" not found

### ISSUE THREAD

**Issue by xiaobinqt** [alex-shpak/hugo-book#644]
Start building sites …
hugo v0.132.1+extended darwin/arm64 BuildDate=2024-08-13T10:10:10Z VendorInfo=brew

Built in 121 ms
Error: error building site: process: readAndProcessContent: "/Users/weibin/go/src/xiaobinqt.github.io/book.leetcode/docs/easy/_index.md:15:1": failed to extract shortcode: template for shortcode "hint" not found

<img width="995" alt="image" src="https://github.com/user-attachments/assets/ca845c21-1f46-45f6-8093-577b78b9e04d">

**Comment by Yichabod** [comment]
May I ask: How did you end up resolving this?
