### ISSUE TITLE
link to local file with absolute path

### ISSUE THREAD

**Issue by juneleung** [alex-shpak/hugo-book#647]
Thanks for your work and I faced an issue when using the code.
I wanna to link to a local file path with an absolute file, like `/User/Apple/xxx.md`, I tried `[MD](/User/Apple/xxx.md)` but seems the final result generated is `http://localhost:1313/Users/Apple/xxx.md`, is obvious not a right path.
How can I add a hyperlink to local file with an abs path? cause some files hard to use a relative path when on another stroage disk. Thanks

**Comment by juneleung** [comment]
and also how to link to another .md file? I tried to use `[>> doc](../20240129.md)` but not work.

**Comment by alex-shpak** [comment]
Hi!
The path starting with `/` will be automatically treated as root of site
Try `[Link](file:///{path})` instead

**Comment by juneleung** [comment]
Hello,
I tried the following: 
```
[pdf](file:///{/Users/Apple/Desktop/motion_retargeting.pdf}) 
[pdf](file:////Users/Apple/Desktop/motion_retargeting.pdf) 
```
but it seems not to work, though it looks like a link, but can't be clicked.
<img width="189" alt="Screenshot 2024-09-03 at 01 20 30" src="https://github.com/user-attachments/assets/0b9f78d8-1a27-40a0-b61e-a342dbd60a99">

**Comment by juneleung** [comment]
seems the local file link is blocked because of safety. For someone uses Hugo as the local library, may can try an extension on Chrome called ```Enable local file links```, it works for me.
