### ISSUE TITLE
Syntax highlighting for (most common) programming languages

### ISSUE THREAD

**Issue by areee** [alex-shpak/hugo-book#65]
Hi!

Could it be possible to add syntax highlighting for presenting the code blocks nicer (e.g. Java programming language)? This could be implemented quite easily by using e.g. [Prism](https://prismjs.com/)... :)

Thanks for a great theme!

**Comment by alex-shpak** [comment]
HI!
Hugo out of the box has quite some syntaxes highlighted, see https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages

And with [code fences](https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.toml#L15) you can just write \```java ...```

Is there some feature you missing from it?

**Comment by areee** [comment]
Aah, I haven't found those pages before. 😅Thanks for these excellent  tips! 👍
