### ISSUE TITLE
can not work in hugo v0.134.1

### ISSUE THREAD

**Issue by WangShaoyu1** [alex-shpak/hugo-book#652]
hugo server -D                  
Watching for changes in D:\gitlab\hugo\myBlog\{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in D:\gitlab\hugo\myBlog\hugo.toml
Start building sites … 
hugo v0.134.1-2f89169baa87a9db47e288b60705f4e99e21a945+extended windows/amd64 BuildDate=2024-09-05T10:17:50Z VendorInfo=gohugoio

WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
ERROR "D:\gitlab\hugo\myBlog\themes\hugo-book\layouts\_default\baseof.html:2:1": parse failed: template: _default/list.html:2: unterminated quoted string
ERROR "D:\gitlab\hugo\myBlog\themes\hugo-book\layouts\_default\baseof.html:2:1": parse failed: template: taxonomy/taxonomy.html:2: unterminated quoted string
ERROR EXECUTE-AS-TEMPLATE: failed to transform "/manifest.json" (application/json): failed to parse Resource "/manifest.json" as Template:: template: /manifest.json:4: unterminated quoted string
ERROR EXECUTE-AS-TEMPLATE: failed to transform "/book.scss" (text/x-scss): failed to parse Resource "/book.scss" as Template:: template: /book.scss:3: unterminated quoted string
Built in 37 ms
Error: error building site: "D:\gitlab\hugo\myBlog\themes\hugo-book\layouts\_default\baseof.html:2:1": parse failed: template: taxonomy/taxonomy.html:2: unterminated quoted string

**Comment by alex-shpak** [comment]
Hi! PR #653 was just merged updating deprecated field to hugo `0.134`
