### ISSUE TITLE
I18n is broken for me / my web page

### ISSUE THREAD

**Issue by wehrend** [alex-shpak/hugo-book#657]
Hi there,
today I was confronted with some hiccups regarding i18n. I've taken the blueprint from  exampleSite and tryed to adapt it, but had no luck so far. Tried it with: 

git clone https://github.com/alex-shpak/hugo-book
cd hugo-book/exampleSite
hugo server --themesDir ../.. 
(see also https://discourse.gohugo.io/t/missing-dropdown-menu-button-for-multiple-languages-language-switch-i18n/51881/7 )

Hope that opening this ticket / issue is fine for you...
My project can be found here (blog - https://github.com/wehrend/hugo_blog ) and contentt https://github.com/wehrend/hugo_content )

**Comment by alex-shpak** [comment]
Hi!
Please describe what issue do you have :)

**Comment by wehrend** [comment]
The language switcher button / menu is not visible in my site, although it is configured... 
I couldnt figure out what is missing... 
Instead of the button I get something like the following (see last line in the menu, it is switching between de:Agenda and en:Agenda): 
![Screenshot_de:agenda](https://github.com/user-attachments/assets/67693e31-d01b-4314-8911-446ebd956a3a)

**Comment by alex-shpak** [comment]
For starters
https://github.com/wehrend/hugo_blog/blob/main/config.toml#L7C2-L8

`Languages` should be in lower case for hugo, I also don't see translated pages in content repo

**Comment by wehrend** [comment]
I took another approach, by copying files over (namely the config file). But i got no better result, I still fail in showing the language switcher...

If you could do me a favor and clone my repo ( https://github.com/wehrend/hugo_blog), and switch to branch testing?

**Comment by alex-shpak** [comment]
I checked the source 
https://github.com/wehrend/hugo_blog/blob/main/themes/hugo-book/layouts/partials/docs/menu.html

this file doesn't look the same as current theme's file
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/menu.html#L4-L6

**Comment by wehrend** [comment]
Oh boy, I'm not sure how this could have happened... Maybe I should have done a git stash on my repo. 
Iam aware that it needed to be called from somewhere... In every case thank you for looking into this....
