### ISSUE TITLE
Broken link on language switcher 

### ISSUE THREAD

**Issue by wehrend** [alex-shpak/hugo-book#660]
Hi, 
most probably not an issue of the theme instead wrong use from my site.
 If I switch from englisch to german, it redirects me to localhost:1313 instead of the configured baseURL = "http://wehrend.uber.space/"
And I have the same issue on the deployed  website. 
Please let me know how to fix it...

**Comment by alex-shpak** [comment]
Hi!
How do you deploy your site, through github pages?

**Comment by wehrend** [comment]
No, I use rsync onto my own webspace.
Here is the make command:

deployment:
    rsync -rav --progress public/
***@***.***:/var/www/virtual/wehrend/html --delete

Thanks for looking into this...

**Comment by wehrend** [comment]
Hi Alex,
I am not sure if it helps, but I get those differing results for curl -I
<remote server> or locakhost:

***@***.***:~$ curl -I wehrend.uber.space/en
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Wed, 23 Oct 2024 10:52:51 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://wehrend.uber.space/en

***@***.***:~$ curl -I localhost:1313
curl: (7) Failed to connect to localhost port 1313 after 0 ms: Couldn't
connect to server
***@***.***:~$ curl -I localhost:1313
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 24024
Content-Type: text/html; charset=utf-8
Last-Modified: Wed, 23 Oct 2024 10:53:47 GMT
Date: Wed, 23 Oct 2024 10:53:54 GMT


All the best,
Sven Wehrend

**Comment by wehrend** [comment]
I am still experiencing issues with that: When I implement the language switcher it points to localhost:1313/de instead of wehrend.uber.space/de . For the english version all is fine - but not for the german one, that points to localhost:1313/de which, does not exist. My configured baseURL is https://wehrend.uber.space ...
Any help appreciated
