### ISSUE TITLE
`ul a { display: block; }` causes strange layout for links in a list

### ISSUE THREAD

**Issue by shaform** [alex-shpak/hugo-book#7]
If we have something like this in our content:

```
Here are some solutions:

*   You could go to [this site](https://example.org).
*   You could ....

```

The rendered content would become:

Here are some solutions:

*   You could go to <div>[this site](https://example.org)</div>.
*   You could ....

I think this might not be desirable?

In addition, the bullet points have disappeared.

**Comment by alex-shpak** [comment]
Mistake during refactoring, should be fixed now in `master`

**Comment by shaform** [comment]
Thanks!
