### ISSUE TITLE
TOC for posts?

### ISSUE THREAD

**Issue by peilingjiang** [alex-shpak/hugo-book#73]
I'm not sure if I did something wrong, but there's no way to have TOC in posts; and when I set `type: docs`, the title and time is missing. Is this how it's designed to be? Can you add TOC for posts?

**Comment by alex-shpak** [comment]
HI!

Right now ToC is not in template for blog post. I can add it, if there is a demand.

**Comment by peilingjiang** [comment]
Hi, I think it would be pretty nice if you could add it, since ToC is really helpful to navigate through the article whether it's a post or doc. Thanks.

**Comment by alex-shpak** [comment]
Added ToC to posts, `bookToc` front-matter parameter will work as well.
