### ISSUE TITLE
Search not working on mobile

### ISSUE THREAD

**Issue by peilingjiang** [alex-shpak/hugo-book#74]
The keyboard will not bump up when using the searching feature, making it unusable on smartphones.

**Comment by twohey** [comment]
I have seen this behavior as well.

**Comment by alex-shpak** [comment]
Hi.
I can reproduce this.

Mobile phone is not popping keyboard because on tap search field is still loading search index and it is in `readonly` state.
Will think about solution.

**Comment by alex-shpak** [comment]
I removed `readonly` from search field, should be fixed by that.

**Comment by peilingjiang** [comment]
It works. Thank you!
