### ISSUE TITLE
checkbox in upper left corner

### ISSUE THREAD

**Issue by turgeonmaxime** [alex-shpak/hugo-book#76]
I recently updated to the most current version of `hugo-book`, and since then there is a checkbox appearing in the upper-left corner of my website:
  - Website is here: https://www.maxturgeon.ca/f19-stat4690/
  - Github repo is here: https://github.com/turgeonmaxime/f19-stat4690

By poking around a bit, I can see that the source code that generates the particular checkbox was added with this commit: https://github.com/alex-shpak/hugo-book/blob/964968be39f7d70c12c41eb77c51e94e1c2ccd6a/layouts/docs/baseof.html

I'm looking at this on Chrome (Version 77.0.3865.75). I also see the checkbox if I use Firefox Quantum (v 69.0).

**Comment by alex-shpak** [comment]
Hi, I can see checkbox in other browsers as well.

I checked generated source 
https://www.maxturgeon.ca/f19-stat4690/book.min.f4161f5e2de53a2e927f51df1611323a2a12cccb2681f23cb6fc3517852e8643.css

And I can't see `.hidden` class in it. I will need to try reproducing such behaviour.

On my sites it worked as expected with checkbox.

**Comment by turgeonmaxime** [comment]
For reference, here's my version of `hugo`
```
hugo version
Hugo Static Site Generator v0.58.2 linux/amd64 BuildDate: 2019-09-13T09:53:38Z
```

**Comment by turgeonmaxime** [comment]
I realized that, even though I was sure I had `hugo-extended`, the version above show that in fact I didn't have it. So I updated `hugo` and made sure it was the extended version:
```
hugo version
Hugo Static Site Generator v0.58.3-4AAC02D4/extended linux/amd64 BuildDate: 2019-09-19T15:34:54Z
```
and now the checkbox is gone.
