### ISSUE TITLE
Feature request: plain text highlighting short code?

### ISSUE THREAD

**Issue by pRot0ta1p** [alex-shpak/hugo-book#77]
It will be great to have short code to change the color of text or the background of text,  for writing those "alert" or "tips" section, which I haven't figured out how to do with just vanilla hugo.

**Comment by alex-shpak** [comment]
Hi!
Vanilla way would be to just insert HTML snipped into markdown file.

```html
<blockquote style="border-left-color: #F00">
Your text
</blockquote>
```

I think for shortcode `blockquote` can be used as well, to keep it minimalistic.

**Comment by alex-shpak** [comment]
WIP

![image](https://user-images.githubusercontent.com/5515443/66144243-c1610a80-e608-11e9-9dad-51f2d74cc8c7.png)

**Comment by pRot0ta1p** [comment]
Thanks for the info and the new short code, you are awsome!
