### ISSUE TITLE
using HTML files with the theme

### ISSUE THREAD

**Issue by mrchristian** [alex-shpak/hugo-book#82]
Is is possible that I can use HTMl files for my book content rather than MD files? Thank you.

**Comment by alex-shpak** [comment]
Hi!

Well, you can write `html` snippets in markdown file, they supposed to be rendered well.
But there might be some caveats.

Try this:
1. Create content file in `content/docs/somefile.html`
2. Put this as content
```
---
---

<div>
    <b>
       My content
    </b>
</div>
```

**Comment by alex-shpak** [comment]
I will close this issue as answered, if you have further questions I can re-open it.
