### ISSUE TITLE
Turn Off Scroll Bar for Menu?

### ISSUE THREAD

**Issue by peilingjiang** [alex-shpak/hugo-book#83]
Hi,

I'm trying to turn off the sidebar of the menu. When the menu is too long for the screen there'll be a sidebar appear - quite prominent and ugly especially when I use windows. I tried to add `overflow-y: hidden;` in `html { }` in book.css, or add `#sidenav { display: none; }` in the file, but none of them works.

Are there a way to do that? Thank you.

**Comment by alex-shpak** [comment]
Hi!

I don't think it's possible to do by conventional means. On windows scrollbar is always visible when there is content outside of screen, unfortunately.

https://stackoverflow.com/questions/3296644/hiding-the-scroll-bar-on-an-html-page
This might help you. Basically browser specific CSS hacks.

**Comment by peilingjiang** [comment]
Thank you!
