### ISSUE TITLE
Document Google Analytics in README

### ISSUE THREAD

**Issue by JensRantil** [alex-shpak/hugo-book#86]
According to https://github.com/alex-shpak/hugo-book/issues/5, support is there, but doesn't seem to be documented in README.

**Comment by JensRantil** [comment]
Actually, maybe not necessary? https://gohugo.io/templates/internal/#google-analytics

**Comment by alex-shpak** [comment]
I can drop few lines in readme that google analytics template is included.

**Comment by JensRantil** [comment]
Nice!
