### ISSUE TITLE
Multilang

### ISSUE THREAD

**Issue by contributorpw** [alex-shpak/hugo-book#87]
Hi Alex! It's a very cool theme! Your approach of manipulate of data impresses me.

Did you try multilang solutions? Any plans?

**Comment by alex-shpak** [comment]
Hi! Thank you!
I think the only thing is missing now for multilang website is switch (or dropdown).
Other things should work out of the box.

Can be useful feature.

**Comment by contributorpw** [comment]
I'd like to try it.

**Comment by alex-shpak** [comment]
Here is documentation on hugo side.
https://gohugo.io/content-management/multilingual/

I guess it can be a CSS-implemented dropdown under left menu 🤔 
I don't have strong vision of it yet.

**Comment by contributorpw** [comment]
OK. I've published a variant https://github.com/contributorpw/google-apps-script-snippets-hugo-site of Multilingual Mode (content, not sites) It seems to work just fine as it is.

I added the switcher as a part of the menu but it is not meaningful

**Comment by contributorpw** [comment]
The current targets

- [ ] Switch on the current page, not return to the main page
- [ ] Get a component to switch. Is this a select box?
- [ ] Upgrade the hugo-book theme

**Comment by alex-shpak** [comment]
Cool 👍 Good that it indeed work out of the box.
I think best way is to implement CSS based select where each item is a link to same page but in other lang.
And fine nice spot for it. I guess it's either at the bottom of menu or in footer of the page.

**Comment by contributorpw** [comment]
I see the content.

I'm going translate this soon.

**Comment by confususs** [comment]
The search function doesn't work out of the box with multilang. I've been working on a site using hugo-book, enabled multilang support, but when accessing `.Site.Pages` in `search-data.js` it iterates over the pages for the default language instead of the selected language.

Add the following snippet in `search-data.js` to see what I'm talking about:
```     
let x;    
{{ range $index, $page := .Site.Pages }}       
console.log('{{ printf "%s" $page}}');    
{{- end -}}
```

This might be somewhat related to https://github.com/gohugoio/hugo/issues/6331. To have it work in multilang I just moved search-related js to a script tag in `html-head.html`.

**Comment by contributorpw** [comment]
@confususs thank you! You're right. At now I'm truing to adapt search to Russian.

**Comment by alex-shpak** [comment]
Hi! 
Multilang support is still WIP, I'm sure that to start with language id needs to added to file name for `search-data.js`. I will need to test it first to be more sure. And yes, linked issue if probably related

**Comment by alex-shpak** [comment]
This is what I came up with so far, needs some polishing.
![image](https://user-images.githubusercontent.com/5515443/68535169-3e854b00-033e-11ea-96b5-64da9deaa7a4.png)

**Comment by alex-shpak** [comment]
Changes has been merged to `master`
