### ISSUE TITLE
[Feature Request] Footnotes as sidenotes

### ISSUE THREAD

**Issue by huangziwei** [alex-shpak/hugo-book#89]
example: https://ps.w.org/side-matter/assets/screenshot-1.png?rev=835324

maybe useful: https://hartshorne.ca/sidenotes-with-css-3f28f1628518

Ideally collapsable.

**Comment by alex-shpak** [comment]
Hi!
Default `blackfriday` footnotes should work out of the box.
https://gohugo.io/content-management/formats/#blackfriday-extensions

```md
This is a footnote.[^1]

[^1]: the footnote text.
```

But I don't think there is enough place for footnotes on side (either in ToC or menu)
