### ISSUE TITLE
scss not supported

### ISSUE THREAD

**Issue by janikvonrotz** [alex-shpak/hugo-book#9]
Hi,

I just tried to setup your theme. I followed the get started instructions from gohugo page, added your theme as a git submodule and ended up with the following error message:

```
PS C:\Users\janik\Documents\knowledge_adnovum> hugo serve
...
ERROR 2018/11/30 14:40:21 error: failed to transform resource: TOCSS: failed to transform "book.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 19 ms
Error: Error building site: logged 1 error(s)
PS C:\Users\janik\Documents\knowledge_adnovum> hugo version
Hugo Static Site Generator v0.52 windows/amd64 BuildDate: 2018-11-28T14:07:10Z
```

Do I need to configure something to make scss conversion possible?

**Comment by rdagumampan** [comment]
It's really nice them but couldn't get this to work out of the box. Would you be able to guide us how to enable base hugo build with extensions so the theme would work? TIA

**Comment by alex-shpak** [comment]
I will close this issue, feel free to reopen if you need some more help.
