### ISSUE TITLE
Javascript and rendering quotes

### ISSUE THREAD

**Issue by jamesb93** [alex-shpak/hugo-book#91]
Hi Alex,

Thanks for your simple theme - it works really well and suits my needs while being light and clear how to use it.

I am having some issues with quotations and javascript. I'm not a web developer so I assume the issue is with me. I have a site setup where I am pushing some chart.js graphics but have experienced this with other content that exists between <script> tags.

## The problem

https://jamesbradburythesis.xyz/docs/data_bending/

On this page you can see two tabs where the charts are. For the chart that works I have included the necessary javascript libraries (which are locally minified and stored). On the other chart however where I have not included the javascript library again all the quotation marks have become `&lsquo` and `&rsquo` which as you imagine breaks the code.

This is what my markdown looks like -> https://github.com/jamesb93/phd-site-hugo/blob/master/content/docs/data_bending/_index.md

If this is not related to theme let me know and you can close immediately, however, if this is something pertaining to the theme that would be useful to fix as I can't seem to get around it!

**Comment by alex-shpak** [comment]
Hi! Thanks!

Hugo will automatically escape html output when rendering,
You can overcome this by creating custom [shortcode](https://gohugo.io/content-management/shortcodes/) which will insert `<script>`

Here is example for [`mermaid`](https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/mermaid.html)

**Comment by alex-shpak** [comment]
`.Inner` will be still escaped, you need something like this

`$PROJ/layouts/shortcodes/script.html`

```tpl
<script>
  {{ .Inner | safeJS }}
</script>
```

And then in markdown
```md
# Content
{{< script >}}
  /* JS Code */
{{< /script >}}
```

Didn't test it, tho :)

**Comment by jamesb93** [comment]
Beautiful, I'll give this a shot.

**Comment by jamesb93** [comment]
Okay, I have something that works quite well now without having to use safeJS. I'm not sure why its rendering properly now to be honest but it seems to do just fine.

https://jamesbradburythesis.xyz/docs/data_bending/

And the shortcode which templates out the chart.js.

```
{{ if not (.Page.Scratch.Get "chartjs") }}
<script src="{{ "/js/Chart.min.js" | relURL }}"></script>
{{ .Page.Scratch.Set "chartjs" true }}
{{ end }}

{{ if not (.Page.Scratch.Get "jquery") }}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{{ .Page.Scratch.Set "jquery" true }}
{{ end }}

{{ $id := substr (md5 .Inner) 0 16 }}

<canvas id='{{$id}}' width="400" height="400"></canvas>
<script type="text/javascript">
$.getJSON("/plots/{{ index .Params 0 }}", function(json) {
    var ctx = document.getElementById('{{$id}}').getContext('2d');
    var scatterChart = new Chart(ctx, {
        type: 'scatter',
        data: {
            datasets: [{
                pointRadius: 0.5,
                data: json.data,
                pointBackgroundColor: "#000000"
            }]
        },
        options: {
            title: {
                display: true,
                text: "{{ .Inner }}"
            },
            tooltip: {
                enabled:false
            },
            legend: {
                display: false
            },
            animation: false,
            scales: {
                xAxes: [{
                    type: 'linear',
                    position: 'bottom'
                }]
            }
        }
    });
});
</script>
```

and in usage:

```
{{< reduc-chart "umap7-1.json" >}}
UMAP Dimensionality Reduction with Neighbours=7 and Mindist=0.1
{{< /reduc-chart >}}
```

**Comment by alex-shpak** [comment]
👍 Cool.

**Comment by alex-shpak** [comment]
I will close then, feel free to open if you need some more assistance.
