### ISSUE TITLE
Code block formatting surprise

### ISSUE THREAD

**Issue by jcw** [alex-shpak/hugo-book#92]
Hello - while trying out this theme, I ran into some unexpected behaviour: line formatting jumps around considerably when using different ways to delimit code blocks:

1. using `'''sh` (backticks, that is, but I'm having trouble escaping them here)
2. using `{{< highlight sh "hl_lines=8 15-17" >}}`
3. using `{{< highlight sh "linenos=table,hl_lines=8 15-17" >}}`

I don't mean the line numbering or highlights, but the fact that the layout / line spacing varies considerably between these different methods. It should be possible to reproduce this, by editing `creating-a-new-theme.md` in the example site.

I'm using Hugo v0.59.0.

**Comment by alex-shpak** [comment]
Hi!
Thank you for report, I think most things can be aligned there. Mostly `line-height` and paddings fixes. I will dedicate some time after search and language changes. PR is welcome.

**Comment by contributorpw** [comment]
I've created samples and codes

    ```sh
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    ```

![1572118798909](https://user-images.githubusercontent.com/5027939/67625080-f5170500-f841-11e9-8e48-ea86166e4304.png)

    {{< highlight sh "hl_lines=8 15-17" >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}

![1572118887830](https://user-images.githubusercontent.com/5027939/67625086-03652100-f842-11e9-8fc6-d968f7a8dafc.png)

    {{< highlight sh "linenos=table,hl_lines=8 15-17" >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}

![1572118926515](https://user-images.githubusercontent.com/5027939/67625091-0a8c2f00-f842-11e9-9052-43e6d3f7e12c.png)

All pictures have discrepancies.

**Comment by alex-shpak** [comment]
I pushed some changes, it's not pixel-perfect but near
![image](https://user-images.githubusercontent.com/5515443/67634358-08b28200-f8bb-11e9-8747-795aecbe4ba3.png)

**Comment by contributorpw** [comment]
OK. It seems there is a small adjusting yet

<details><summary>No shortcode. Height of the block is 307px. <i>OK</i></summary>

    ```sh
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    ```
</details>

<details><summary>Shortcode. Height of the block is 307px. <i>OK</i></summary>

    {{< highlight sh >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}
</details>

<details><summary>Shortcode with <b>FOUR</b> highlight lines. Height of the block is 295px. <b>12 px reduction!</b></summary>

    {{< highlight sh "hl_lines=3 8-10" >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}
</details>

<details><summary>Shortcode with <b>FOUR</b> highlight numbers lines. Height of the block is 295px. <b>12 px reduction!</b></summary>

    {{< highlight sh "linenos=table,hl_lines=3 8-10" >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}
</details>

<details><summary>Shortcode with <b>ONE</b> highlight line. Height of the block is 304px. <b> 3px reduction!</b></summary>

    {{< highlight sh "hl_lines=3" >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}
</details>

<details><summary>Shortcode with <b>TWO</b> highlight lines in order. Height of the block is 301px. <b> 6px reduction!</b></summary>

    {{< highlight sh "hl_lines=3-4" >}}
    #!/bin/bash

    echo "Enter directory name"
    read ndir
    if [ -d "$ndir" ]
    then
      echo "Directory exist"
    else
      `mkdir $ndir`
      echo "Directory created"
    fi
    {{< / highlight >}}
</details>

@alex-shpak   It looks like each highlighted line eats up 3px.

**Comment by alex-shpak** [comment]
Yes, it's due to highlighted lines having `display:block` style which is affecting `line-height`.
I can set `line-height` to `em` units. Though, there will be still +- pixel gap per highlighted block because of subpixel calculation.

**Comment by jcw** [comment]
Great progress! Minor pixel differences should be of no concern - nobody is going to toggle quickly between the two. It was just the large jumps which surprised me, and the fact that nobody seemed to have noticed / looked into this until now.

Many thanks for the fixes, I think this issue can be closed now.
