### ISSUE TITLE
[Feature Request] Support for printing

### ISSUE THREAD

**Issue by cf-sewe** [alex-shpak/hugo-book#94]
When I print a Hugo page with docs template, this will include the Nav Bar on the left and ToC on the right and leave the main part rather unreadable. 

Could you imagine to include some printing support which would hide the mentioned sidebars when printing?

This could be done for example either with:

```html
<link rel="stylesheet" type="text/css" href="print.css" media="print"/>
```
or

```css
@media print {
 /* print related stuff */
}
```

**Comment by alex-shpak** [comment]
Would not be hard to add.
Question is what average use expects to print? Only page content? Table of Contents as well?

**Comment by cf-sewe** [comment]
> Question is what average use expects to print? Only page content? Table of Contents as well?

Personally, I would like the ToC also to be printed - if its not disabled by `bookToc: false` option.
The print location for the ToC  ideally would be on top of the document before the content.

By the way I came up with this to avoid the need for a proper PDF export, and as you say its a low hanging fruit.

**Comment by contributorpw** [comment]
@alex-shpak I agree with @cf-sewe. 

That would be a very nice bonus.

**Comment by alex-shpak** [comment]
I added low hanging fruit part, by hiding everything except content page.

**Comment by alex-shpak** [comment]
Well, it went easier that expected. ToC will show at the top of the page. Consider that printing style might migrate to [plugins](https://github.com/alex-shpak/hugo-book/tree/master/assets/plugins) because css is getting too heavy.
![image](https://user-images.githubusercontent.com/5515443/68515528-a6c22700-0281-11ea-84ce-8ea85afebb07.png)

**Comment by cf-sewe** [comment]
Thank you, that was quick! I
And thank you for such great minimalistic and lightweight theme!
