### ISSUE TITLE
[feature request] can you please create gitlab repo

### ISSUE THREAD

**Issue by leela52452** [alex-shpak/hugo-book#95]
interested persons like me would help a lot.

first of all, thank you. i have gone through few things and it seems great at the moment.

i have accessibility wcag 2.1 level aaa in mind. your theme so far little errors.

validators
- [css validators](http://jigsaw.w3.org/css-validator/)
- [achecker](https://achecker.ca/checker/index.php)
- [w3 validator](http://validator.w3.org/) 

thank you

**Comment by contributorpw** [comment]
What is the point of another repository?

**Comment by leela52452** [comment]
@contributorpw 

> What is the point of another repository?

my limitations 👍 
dont have access to desktop or laptop
expertise to create or configure gitlab repo

uses 👍 
person like me can fork and create simple blog
learn something while tinkering with theme code

**Comment by alex-shpak** [comment]
Hi!
Well, technically it's possible to create mirror at gitlab, but you would not be able to contribute there, because there might be only one source of truth.

Maybe you can elaborate your case and we can find how you can use github?

**Comment by leela52452** [comment]
i have simple goal im mind:
to create blog using your theme.

i have already created blog using one of the example from https://gitlab.com/pages.

if you create repo on gitlab similar to example sites given in above link,  i can fork and modify settings and use it.

i hope it is clear

**Comment by alex-shpak** [comment]
Well, I created mirror repo: https://gitlab.com/alex-shpak/hugo-book
It will be automatically updated from github, but it would not accept pull requests/issues.

You can follow instructions in README to create your site: https://gitlab.com/alex-shpak/hugo-book#creating-site-from-scratch

Keep in mind that theme is documentation oriented, and blog has very limited implementation. Though I will add few more features in future.
