### ISSUE TITLE
Could we add navigation on top of the page like the website of gohugo.io?

### ISSUE THREAD

**Issue by excitedbrent** [alex-shpak/hugo-book#96]
dear, Could we add navigation on top of  the page like the website of hugo? when mouse move over the menu let it show its submenu.
I like this theme's style  , it's like the official website of gohugo.io.
thanks for your great job!

**Comment by alex-shpak** [comment]
Hi!
I will need to think about it. My intention was to create layout specifically without top menu, to make it more unique.

I can add `inject` partial on top of page at least, so you can implement your own menu.

**Comment by alex-shpak** [comment]
Hi!
There is now `layouts/partials/docs/inject/content-before.html` partial to inject custom html before page and `assets/_custom.scss` for styles. As for theme I want to keep layout without top bar.

Feel free to re-open if you still need assistance.
